### ISSUE TITLE
Página Principal de la Wiki: Añadir AIR: Artificial Intelligence in Robotics

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#10]
Se ha recibido una solicitud de **AIR: Artificial Intelligence in Robotics** de convertirse en Grupo Activo de ASROB. Dado que cumplen las condiciones requeridas en los [estatutos](https://asrob-uc3m.gitbooks.io/estatutos/content/chapter1.html), se ha procedido a la creación de una [página para el grupo](http://asrob.uc3m.es/index.php/AIR) en la wiki.

Quedamos pendientes de que **AIR: Artificial Intelligence in Robotics** rellene su página de la wiki para enlazarla desde la página principal.

cc @KFRodicio

**Comment by asrobuc3m** [comment]
Cerrado por inactividad (> 1 mes).
