### ISSUE TITLE
Ha desaparecido la pizarra de ASROB

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#100]
Cuando hemos llegado a la reunión de GAME hoy, nos hemos dado cuenta de que la pizarra de ASROB ha desaparecido. 

Adjunto foto de prueba:
![img_20171003_170346](https://user-images.githubusercontent.com/1451819/31134761-559d0342-a863-11e7-9bd8-9c490eac9fa4.jpg)

**Comment by jgvictores** [comment]
Sorry la tengo en préstamoooo pero ya una pedida a dpto. En RD utilizamos la pizarra grande.  ¿Están en clase hoy?

**Comment by David-Estevez** [comment]
Ok! Era simplemente para tenerla localizada, teniendo en cuenta antecedentes como #51. Dejamos esto abierto hasta que se proceda a su devolución.

**Comment by jgvictores** [comment]
Perfecto!

**Comment by jgvictores** [comment]
Pregunté al secretario del Dpto, aun no estaba pedido. Aproveché el evento para que la pizarra fuese más grande (1x1.5m, creo), que en teoría pedirá hoy.
Nota mental: Cuando llegue, también estaría bien poner una incidencia para que lo coloquen (salvo que alguien considere que es mejor "flotante").

**Comment by David-Estevez** [comment]
Genial!

A mi lo de "flotante" me parece una buena idea, siempre es útil poder moverla (y no tenemos demasiado espacio en la pared para dejarla fija).

**Comment by David-Estevez** [comment]
Ya tenemos nueva pizarra!

![image](https://user-images.githubusercontent.com/1451819/32441079-2a8ce200-c2f6-11e7-805a-c2cfa2cefa44.png)
