### ISSUE TITLE
Falta el netbook de Robot Devastation

### ISSUE THREAD

**Issue by Ruben-MR** [asrob-uc3m/actas#101]
Falta el netbook de Robot Devastation (El que era del ecro)

**Comment by David-Estevez** [comment]
No falta, está atado con cinta aislante al ECRO.

Como no cabía en los armarios, y ante el peligro de que pudiese ~ser sustraído~ desaparecer como otros objetos que había en la nave, yo guardé el ECRO en mi armario. Si vais a trabajar con él (ECRO, portátil o ambos), el próximo día cuando hagamos limpieza le buscamos un sitio en el espacio de ASROB y lo dejamos ahí.

**Comment by Ruben-MR** [comment]
OK gracias, lo vamos viendo

**Comment by David-Estevez** [comment]
Tras la limpieza del otro día hemos hecho espacio en los armarios, así que el NECRO ha vuelto al armario de la derecha. 

Se encuentra en una caja que se puede reconocer porque sobresale de ella la protuberancia blancha que tiene pegada al netbook. Es recomendable mantener la caja, ya que su estructura actual es propensa a las roturas si se el robot no se manipula con cuidado.

Como ya está localizado y podéis acceder a él, procedo a cerrar la issue.
