### ISSUE TITLE
La batería del calibre digital se ha agotado

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/actas#102]
Y es necesario reponerla

**Comment by David-Estevez** [comment]
Tipo de batería?

**Comment by David-Estevez** [comment]
Me contesto a mi mismo: LR44

**Comment by jgvictores** [comment]
Posible que tenga Fernando (técnico).

**Comment by jgvictores** [comment]
Conseguidos dos V357 vía Departamento, que es compatible en cuanto a dimensiones y tensión [1](http://www.lr44batteryequivalent.org/), [2](http://www.truetex.com/buttons.htm).

En armario, en instrumentos de medida. Lo que no encontré fue el calibre. :scream: 

![batteries-v357](https://user-images.githubusercontent.com/4448588/35921403-c8908836-0c1a-11e8-8f25-f7d9c5829f80.jpg)

**Comment by David-Estevez** [comment]
El calibre estaba en el armario, pero no donde debería. He procedido al cambio de pila y ya está en su su sitio. Adjunto foto del calibre funcionando.

![image](https://user-images.githubusercontent.com/1451819/36035342-db6ff930-0db6-11e8-9f79-6711faf23e1c.png)

Gracias a @jgvictores por haber conseguido las pilas!! 😊

**Comment by jgvictores** [comment]
Yuju!
