### ISSUE TITLE
Participación de ASROB en Madrid MiniMakerFaire 2017

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#103]
Buenos días
César García nos ha invitado a participar a este evento maker en Madrid.
El año pasado estuvimos @David-Estevez @JavierIH y yo y nos lo pasamos genial.
A estas citas acuden los mejores makers de España. Sólo me queda una cosa más que decir, ya os he convencido a venir, sólo digo que SAAAAAAAAV.

Y para participar hay que rellenar el siguiente [Call4Makers](https://madrid.makerfaire.com/call-for-makers/)

**Comment by David-Estevez** [comment]
Me apunto!!

PD: quién ha creado la etiqueta "Y después cervezas!"? :joy::joy::joy::joy:

**Comment by David-Estevez** [comment]
Cerrando esto porque estoy en la Maker Faire y los viajes en el tiempo no existen.
