### ISSUE TITLE
Soportar Markdown en la wiki de ASROB

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/actas#105]
Soportar Markdown en la wiki de ASROB.

**Comment by Siotma** [comment]
Es eso posible?

**Comment by jgvictores** [comment]
Hay extensiones que lo implementan. Pasos:
1. Recuerdo que había un montón. Optar por una de las muchas extensiones.
1. Hacer backups de bases de datos de wikis. Hace tiempo que no lo hago. 
1. Meter y configurar la extensión.

**Comment by jgvictores** [comment]
Relacionado con esto, para migrar de `mediawiki` a `markdown` se puede utilizar `pandoc`. A tener en cuenta:
- La versión web http://pandoc.org/try está limitado en cuanto a número de caracteres.
- La versión de Ubuntu Xenial (16.04) no soporta `pandoc --from mediawiki --to gfm` (para Github Flavored Markdown).

Por tanto, recomiendo instalar https://github.com/jgm/pandoc/releases/latest y utilizar:
```
pandoc --from mediawiki --to gfm`
```

**Comment by jgvictores** [comment]
Dado que hay un parón eléctrico mañana a nivel UC3M, acabo de hacer un backup de wikis.

**Comment by jgvictores** [comment]
- Ref: https://www.mediawiki.org/wiki/Requests_for_comment/Markdown#Existing_Markdown_support

**Comment by jgvictores** [comment]
Pese a que el listado de [conflictos](https://www.mediawiki.org/wiki/Extension:MarkdownExtraParser#Conflicts) parece escaso... La idea es que está hecho para que convivan, pero como tenemos la wiki bastante tuneada, ocurre lo del siguiente pantallazo.

![screenshot from 2017-11-10 22-02-11](https://user-images.githubusercontent.com/4448588/32678627-691a91fa-c663-11e7-8cd6-fb3c0d49598c.png)

Procedo a desactivar (que no desinstalar del todo, dejo el `require_once("extensions/MediaWiki-MarkdownExtraParser/MarkdownExtraParser.php");` comentado) la extensión.

**Comment by jgvictores** [comment]
Como conclusión recomiendo más bien la transición hacia GitHub, siguiendo un proceso como el descrito en https://github.com/asrob-uc3m/tutoriales/issues/2 (y todavía mejor si se automatiza más).

@jorgercobo Ok marcar issue como inválida/rechazada y cerrar?

**Comment by jorgercobo** [comment]
👍

**Comment by jgvictores** [comment]
Thanks!
