### ISSUE TITLE
Buenas prácticas en grupos de Telegram

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/actas#106]
- El título de los grupos de Telegram de grupos de trabajo activo podría comenzar con "ASROB:" para unificar las busquedas de grupos de ASROB
- Usar los hashtags #doodle y #reunion para organizar las fechas de reunión y evitar tener que anclar dichos mensajes semanalmente (para aquellos que usen Doodle para decidir el horario de sus reuniones)

**Comment by David-Estevez** [comment]
> El título de los grupos de Telegram de grupos de trabajo activo podría comenzar con "ASROB:" para unificar las busquedas de grupos de ASROB

Hecho

> Usar los hashtags #doodle y #reunion para organizar las fechas de reunión y evitar tener que anclar dichos mensajes semanalmente (para aquellos que usen Doodle para decidir el horario de sus reuniones)

Actualmente ASROBot está roto debido al cambio de la interfaz de Doodle (ya no se puede usar la antigua). No obstante, me parece una buena idea para localizar estos mensajes clave. El progreso en esta tarea podrá seguirse en [la issue correspodiente a esta feature](https://github.com/asrob-uc3m/asrobot/issues/10).

**Comment by Siotma** [comment]
Hecho en Printer One.
