### ISSUE TITLE
Memoria de Asociaciones

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#107]
# TL:DR
* **Qué hay que hacer**:  Rellenar y entregar la Memoria de Asociaciones, que incluye todo lo que hemos hecho este año.
* **Cuándo es el plazo de entrega**: el plazo acaba el **1 de Noviembre de 2017**.
* **Quién se debería encargar de este marrón**: los responsables de cada Grupo de Trabajo Activo, organizadores de actividades de ASROB y miembros de la Junta.
* **Por qué hay que hacer esto**: es un trámite obligatorio para todas las asociaciones de la universidad. No cumplirlo supone la baja en el registro de asociaciones.

# Contenido del email de África

¡¡¡Buenos días!!! hoy toca hablaros de la entrega anual de las memorias y Juntas directivas de vuestras asociaciones... 

Resumo: 

1.- La memoria debe hacer referencia a las actividades y vida de la asociación del curso 2016/17. En este enlace podéis ver qué es lo que se solicita (más o menos) en la memoria: 
https://www.uc3m.es/ss/Satellite/UC3MInstitucional/es/TextoMixta/1371234099705/#memoria

2.- Por favor, NO CONFUNDIR este trámite con el de las memorias que se os solicitan para los proyectos de la Convocatoria de Ayudas (la Convocatoria de Ayudas es una cosa y la presentación anual de la memoria de actividades y Junta Directiva es otra...)
 
3.- Recordad que es MUY IMPORTANTE cumplir con este requisito porque el no hacerlo, puede conllevar la baja en el registro de asociaciones y la no concesión de ayudas de la Universidad. ES DE OBLIGADO CUMPLIMIENTO.

4.- Aquellas Asociaciones nuevas (registradas durante el curso 2017/18) sólo tendrán que subir la junta directiva. Por favor, aprovechar para subir también una pequeña descripción de vuestra asociación para poderla poner en la web... 
Todas las demás, tienen que realizar tanto la memoria como la junta Directiva. 

5.- La entrega se realiza a través de Aula Global: https://aulaglobal.uc3m.es/course/view.php?id=57506

En esta página web también tenéis el enlace: https://www.uc3m.es/ss/Satellite/UC3MInstitucional/es/TextoMixta/1371234099705/#memoria

6.- Aquellas Asociaciones que me habéis estado enviando ya las memorias o las Juntas por correo electrónico, por favor, subirlas a la plataforma (Aula Global) en el plazo estipulado. 

MUY IMPORTANTE: EL PLAZO DE ENTREGA FINALIZA EL 1 DE NOVIEMBRE DE 2017. SIN EXCEPCIONES

Por favor, tomaros muy en serio lo del plazo de entrega porque este año no hay vuelta atrás... 😰

Hala, ya os he dejado deberes... por favor, poneros en serio con esto para no tener disgustos innecesarios después (que ya os he dicho que este año no hay vuelta atrás...  🙏🙏

Un beso grande y feliz  juernes!!!!!!!!!😉

África

**Comment by Siotma** [comment]
Yo puedo encargarme de Printer One y del Taller de Zowimanoides.

¿Está disponible la memoria del curso pasado para tomarla como referencia?

**Comment by jgvictores** [comment]
> ¿Está disponible la memoria del curso pasado para tomarla como referencia?

Sí, en el Google Drive que pertenece a asrobuc3m, carpeta `Papeleo`, encontrarás `Memorias` (además de `Subvenciones`). He estado organizando, ahora tenemos de varios años de historia.

**Comment by David-Estevez** [comment]
Más info:

```
Modelo de memoria y entrega

    Nombre de la actividad
    Asociación responsable general del desarrollo de la actividad
    - Nombre y apellidos
    - Titulación y curso
    - NIE
    - Correo electrónico de contacto
    - Teléfono
    Fecha de realización
    Lugar
    Programa de las actividades realizadas 
    Informe de las actividades realizadas
    - Objetivos previstos y grado de consecución
    - Estructura y organización de las actividades realizadas (programa, calendario de ejecución, cómo se llevó a cabo la gestión, dificultades encontradas)
    - Desarrollo de la actividad (número de asistentes, desarrollo de las sesiones, difusión realizada, análisis de problemas surgidos, resolución de los mismos, colaboraciones con otras entidades o grupos, evaluación de las actividades por los participantes)
    - Conclusiones y valoración personal
    - Sugerencias de mejora (tanto desde el punto de vista del contenido como de la gestión y desarrollo de las actividades)
```

**Comment by David-Estevez** [comment]
Añadido a @JorFru para la parte de UAVs

**Comment by JorFru** [comment]
correcto

**Comment by Siotma** [comment]
> Sí, en el Google Drive que pertenece a asrobuc3m, carpeta Papeleo, encontrarás Memorias (además de Subvenciones). He estado organizando, ahora tenemos de varios años de historia.

No tengo acceso a ese Drive. Las credenciales no están en la Wiki. 😕

**Comment by Siotma** [comment]
Miento, sí que lo están 😰

**Comment by Siotma** [comment]
Pero no funcionan 😆

**Comment by JorFru** [comment]
Por favor, que alguien comparta conmigo la memoria para editarla en Drive
directamente.
A mi correo JorFru.94(en)gooooooooogle.coooom
O en el 100317402

Gracias!

**Comment by jgvictores** [comment]
Oks te acabo de compartir la carpeta de Papeleos al gmail (creo!).

**Comment by JorFru** [comment]
Lo he recibido! gracias!

**Comment by jgvictores** [comment]
Guai! 

@Siotma Dame un gmail o algo y te agrego!

**Comment by Siotma** [comment]
He creado el documento de la memoria y he añadido ya Printer One.

Para el taller de Zowimanoides, desconozco si debo seguir una estructura distinta o sirve la misma para la memoria de actividades y la de subvenciones. Voy a ir haciéndola conforme a la estructura dada por @David-Estevez que me parece muy aplicable.

**Comment by jgvictores** [comment]
Oks, metí una mini-intro similar a la del año pasado, y un apartado de Robot Devastation.

**Comment by David-Estevez** [comment]
He metido unas cuantas cosillas en el documento:
* GAME
* RoboFactory
* Global Robot Expo
* Otros proyectos y actividades
* Fotos surtidas

Al documento le faltaría lo siguiente:
* UAVs
* Taller de Zowimanoides
* Semana de Asociaciones

**Comment by David-Estevez** [comment]
También he creado un documento para la Junta directiva en el que sólo falta que @jgvictores ponga sus datos personales (Este año piden más datos, no sé por qué).

**Comment by jgvictores** [comment]
Updated!

**Comment by Siotma** [comment]
Añadido: taller de Zowimanoides

Puedo escribir algunas líneas sobre el Taller de Arduino de la Semana de Asociaciones.

**Comment by Siotma** [comment]
Añadido: taller de Arduino

También he añadido nuevas fotos de la Feria de Asociaciones.

**Comment by JorFru** [comment]
El lunes 30 cumpliré mi parte de UAVs

Saludos

**Comment by David-Estevez** [comment]
Cómo está esto? Se puede subir ya?

**Comment by Siotma** [comment]
Falta escribir algunas líneas sobre la semana de Asociaciones:

- Breve introducción
- Charla ramas activas
- Feria de asociaciones

Todas estas cosas no deberían ocupar más de media página en total, y se pueden prácticamente reutilizar de la memoria del año pasado.

**Comment by Siotma** [comment]
Me he venido arriba y ya lo he hecho 🤣 . He reutilizado bastante texto, aunque he intentado complementarlo con algunos párrafos de mi cosecha.

A no ser que se nos olvide algún apartado, ya está todo redactado. Se pueden admitir algunas mejoras en cuanto a maquetación, pero creo que eso no es muy importante. 

Echadle un ojo.

**Comment by David-Estevez** [comment]
Está perfecto!!! :clap: :clap: :clap: :clap: 

Por mi parte yo doy mi visto bueno para subirlo. Si confirmáis todos que está ok, la subo yo mismo.

**Comment by Siotma** [comment]
Ok por mi

**Comment by jgvictores** [comment]
Ok por mi parte!

**Comment by David-Estevez** [comment]
Entregado!!
