### ISSUE TITLE
Acceso a los historicos de la wiki

### ISSUE THREAD

**Issue by IceflowCW** [asrob-uc3m/actas#11]
Hola muchahuel@s, desde la lista de correo de Clone Wars hemos detectado que en la migración que se hizo de la wiki vieja, alojada en la asrob, a la wiki nueva de reprap, se dejaron algunos elementos enlazados con la wiki de la asrob, con la ultima limpieza que habéis echo, estos elementos son inaccesibles y nos gustaría migrar por completo todo lo que falte a la wiki nueva y así no molestar ni depender de la asrob en el futuro :D 

Si podéis darnos un acceso temporal para poder hacer un control de revisión de lo que quede sin migrar y zanjamos esto, seria muy de agradecer.

Saludos!!

**Comment by David-Estevez** [comment]
Hola Iceflow! Ahora mismo os creamos una cuenta CloneWars para que podáis hacer la migración.

**Comment by IceflowCW** [comment]
Muchos tanqius!! ;)
