### ISSUE TITLE
El bote de laca se ha terminado

### ISSUE THREAD

**Issue by javii9** [asrob-uc3m/actas#111]
Hoy hemos intentado usar el bote de laca y no quedaba.
¿Quien se encarga de ella?
Alguna idea.

**Comment by Siotma** [comment]
La última vez que pasó esto ( https://github.com/asrob-uc3m/impresoras-asrob/issues/14 ), @jgvictores donó un bote que él tenía. Sin embargo, yo creo que lo ideal sería comprar uno. Hay fondos en ASROB disponibles?

**Comment by jgvictores** [comment]
Hay presupuesto, se ve en la wiki. Monta votación y después lo puedo mover en calidad de ex-tesorero (#98 :smile:).

**Comment by Siotma** [comment]
Dicho y hecho.

Este es el enlace del formulario: https://docs.google.com/forms/d/e/1FAIpQLScihEFr7SU8BFt5FIvXsX5N1LCG8PHDtSp0Fnza69D2F825fg/viewform?usp=sf_link

Votación hasta el domingo por la noche.

**Comment by Siotma** [comment]
Fe de errores: publiqué el formulario sin solicitar registro en UC3M con varias respuestas disponibles por persona.

He eliminado las respuestas recibidas hasta este momento. Por favor, realizarlas de nuevo.

**Comment by Siotma** [comment]
No puedo cerrar la votación porque la Wiki está caída y no puedo acceder a la página de medios sociales para coger la contraseña de asrob at uc3m .

No obstante, se puede comprobar que los resultados a esta hora son 3 votos a favor y 0  en contra.

![imagen](https://user-images.githubusercontent.com/6171234/32717090-b412f714-c858-11e7-83f5-da294444df28.png)

Dado que la reunión de Printer One se está produciendo ahora mismo, y un bote de laca nos vendría muy bien, voy a ir al Hiber a comprarlo.

**Comment by Siotma** [comment]
He comprado el bote de laca en el Hiber, por un precio de 1,89€. Es de 400ml, mientras que el anterior era de 300ml, por lo que debería durar bastante. Adjunto Ticket:

![ticket_laca_13_nov_2017](https://user-images.githubusercontent.com/6171234/32722250-9c742d60-c869-11e7-87a2-4cd98fa0b034.jpg)

@jgvictores me ha devuelto el dinero, luego la issue está lista para sentencia. Gracias por votar!

**Comment by jgvictores** [comment]
Hecho pago en efectivo de 1.89€ a favor de @Siotma y wiki actualizada: http://asrob.uc3m.es/index.php/Cuentas_ASROB
