### ISSUE TITLE
Participación de ASROB en T3chFest 2018 

### ISSUE THREAD

**Issue by daavm** [asrob-uc3m/actas#113]
Buenas chicos,

Escribo esta issue para informaros de que desde T3chFest hemos abierto el Call 4 Talks pata la próxima edición (1 y 2 de Marzo de 2018).

Nos encantaría que desde ASROB se propusiese alguna charla o taller,siempre dentro de la temática de T3chFest, la informática y las nuevas tecnologías. Para ello sólo tenéis que rellenar el formulario en la web, hasta el 4 de diciembre: https://t3chfest.uc3m.es/2018/call-for-talks/

Si tenéis alguna duda o queréis informaros de algo sobre T3chFest comentad en la issue o habladme por Telegram,  y animaos a proponer!

**Comment by Siotma** [comment]
Suena interesante! Ya que conoces un poco ambas asociaciones, qué temáticas crees que serían bienvenidas @daavm ?

**Comment by daavm** [comment]
Buenas,

Pues estamos abiertos a cualquier temática que tenga que ver con las nuevas tecnologías. Con respecto a los talleres, lo que buscamos es que realmente sean talleres, que los asistentes salgan habiendo hecho algo por ellos mismos y a ser posible con conocimientos nuevos entre sus manos. Si es novedoso más que mejor. El cacharreo a la gente le gusta mucho, pero necesitamos que sea algo, como digo, novedoso, no habitual.
Sobre las charlas, cualquier cosa que se os ocurra tiene cabida en el evento. Desde programas de diseño 3D, hasta historia de la impresión 3D, cómo montar tu máquina recreativa desde cero, etc etc...

**Comment by Siotma** [comment]
Voy a poner cosas que se me ocurren que pueden ser interesantes, y gente asociada que creo que podrían ser los más indicados para dar su opinión al respecto.

Charlas:
- Cómo montar tu máquina recreativa desde cero (GAME) @David-Estevez 
- Un shooter de nueva generación con realidad aumentada y robots reales (Robot Devastation) @jgvictores 

Talleres:
- Programa un Bot de Telegram para hacerte la vida más fácil (ASROBot) @David-Estevez 
- Arduino desde cero @Siotma
- FreeCAD @David-Estevez 

Opiniones? Más ideas?

**Comment by jgvictores** [comment]
> Un shooter de nueva generación con realidad aumentada y robots reales (Robot Devastation) 

Personalmente y mientras que no sea capaz de gestionar un equipo grande de manera eficiente, prefiero invertir más tiempo en desarrollo y menos en divulgación. ;-)

**Comment by David-Estevez** [comment]
Qué manera de enmarronar, ¿eh @Siotma ? :stuck_out_tongue_winking_eye: 

Me lo pienso y os digo, aunque el único de los que dice @Siotma que creo que puede tener gancho es el de Telegram, y nuestro bot actualmente es un ñapa-bot.

**Comment by Siotma** [comment]
Estaba haciendo un ejercicio mental sobre las cosas que hacemos en ASROB que podrían tener cabida en el evento. Os he mencionado para que cada cual de su opinión. Personalmente lo más difícil me parece lo de:

> necesitamos que sea algo, como digo, novedoso, no habitual.

**Comment by daavm** [comment]
>  Personalmente lo más difícil me parece lo de:

    necesitamos que sea algo, como digo, novedoso, no habitual.

Con eso me refiero mayormente a los talleres, porque durante el evento hay muchos menos talleres que charlas, y hay que hacer buen uso de ellos. Sobre las charlas... Cualquier cosa puede salir adelante

**Comment by daavm** [comment]
Hoy se lo he comentado a @Siotma. Desde T3chFest probablemente ya sabréis que dias antes del propio evento se organiza una jornada de institutos, donde chavales de institutos (de Madrid casi siempre), vienen y asisten a alguna charla y talleres. 
Estamos buscando gente a la que le interese hacer algún taller, y pienso que ASROB podría hacer algo interesante. Si se os ocurre algo y os animáis decidlo por aquí y nos ponemos en contacto!

**Comment by JorFru** [comment]
Yo organicé un taller con UC3Music para chavales de instituto en el
T3chFest y más contento con el resultado no se puede estar!
Todo salió muy bien.
Estoy disponible para responder preguntas.

On Nov 29, 2017 00:05, "daavm" <notifications@github.com> wrote:

Hoy se lo he comentado a @Siotma <https://github.com/siotma>. Desde
T3chFest probablemente ya sabréis que dias antes del propio evento se
organiza una jornada de institutos, donde chavales de institutos (de Madrid
casi siempre), vienen y asisten a alguna charla y talleres.
Estamos buscando gente a la que le interese hacer algún taller, y pienso
que ASROB podría hacer algo interesante. Si se os ocurre algo y os animáis
decidlo por aquí y nos ponemos en contacto!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/actas/issues/113#issuecomment-347694280>,
or mute
the thread

**Comment by Siotma** [comment]
Quizá el taller de Arduino podría encajar en la jornada de institutos.

**Comment by daavm** [comment]
Si, el taller de arduino sería una muy buena opción. La jornada de institutos este año será el 23 de febrero, el viernes anterior al evento.
Si finalmente os decidís a hacer el taller simplemente confirmadmelo y os metemos en la lista :)

**Comment by daavm** [comment]
Holi. Nos interesaría confirmación para esta semana la siguiente a mucho tardar. Si finalmente creéis que a ASROB no le interesa, no os preocupéis, que no hay compromiso alguno, y T3chFest os quiere igualmente :) 

Lo que sea, comentad, si no, como he dicho, en 1 semana o 2 cerraré la issue 👍
