### ISSUE TITLE
Prestamo de resistencia para extrusor por parte de Printer One

### ISSUE THREAD

**Issue by JuanFdelArco** [asrob-uc3m/actas#115]
Pido a Printer One la resistencia para extrusor que tienen en la caja de recambios para impresoras como préstamo para el laboratorio. Ya hemos pedido una nueva, pero necesitamos una con urgencia. Se devolveria cuando llegase ésta (o la prestada o la nueva, como se prefiera).

Lo he hablado con @Siotma y me ha dicho que en principio no hay problema, pero aquí está la issue.

Puede que no la lleguemos a utilizar si llega la nueva a tiempo, solo necesito saber si podemos hacer uso de la resistencia en caso de que no fuera así.

![78366be4-a999-4402-8444-83cea3c21098](https://user-images.githubusercontent.com/17598605/33139453-a0773d4e-cfad-11e7-995f-33011ff2a3a4.jpeg)

**Comment by Siotma** [comment]
Por mi parte, como te dije, no hay ningún problema.

El origen de esa resistencia es [esta issue](https://github.com/asrob-uc3m/actas/issues/62#issuecomment-284474891). Se compró para resolver unos problemas de calentamiento de Hija Resurrection que finalmente pudimos resolver reparando un cable. Desconozco la tienda donde se compró así como precio o supuesta calidad. En [este comentario](https://github.com/asrob-uc3m/actas/issues/62#issuecomment-281193544) se menciona que @David-Estevez la pilló con cargo al DISA por 3,5€. Le invoco para más detalles.

Indica por aquí si finalmente te la llevas.

**Comment by David-Estevez** [comment]
Efectivamente, de la compra de ese cartucho calefactor se encargó el DISA. La tienda dónde se compró fue [makergal](https://www.makergal.es/).

**Comment by JuanFdelArco** [comment]
Al final nos ha llegado la nuestra a tiempo. No he llegado a coger la de Printer, sigueen su sitio.

Muchas gracias chicos!
