### ISSUE TITLE
Baja como responsable de impresoras 3D

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/actas#116]
Con esta issue presento mi baja como responsable de impresoras 3D. Quedo a disposicion para colaborar en el traspaso de responsabilidad y para resolver todas las dudas que el nuevo responsable tenga.

A la mayor brevedad entregaré la llave de las impresoras al nuevo responsable o en su defecto al grupo de Printer One.

Agradecería que se actualizara la información en la página web y en el nuevo apartado de operadores.

MAGA

**Comment by Siotma** [comment]
Como hablamos ayer, yo estaría interesado en ocupar el puesto de responsable de impresoras ya que actualmente tengo tiempo para ello y la disponibilidad de la llave sería de gran utilidad para las próximas reuniones de Printer One.

Desconozco si con mi ofrecimiento es suficiente o esto hay que votarlo.

En el momento en que recibamos confirmación, nos pondremos en contacto para realizar el traspaso.

**Comment by David-Estevez** [comment]
Pues yo diría que si nadie más presenta candidatura, el puesto sería tuyo... Esperemos a ver si aparecen más opiniones a favor / en contra de esto.

**Comment by jgvictores** [comment]
Totalmente de acuerdo con @David-Estevez :-)

**Comment by Siotma** [comment]
Iniciadas conversaciones para el traspaso.

**Comment by Siotma** [comment]
El traspaso se produjo ayer a las 18:30 horas.

ACK

**Comment by Siotma** [comment]
Voy a intentar actualizar las distintas alusiones al cargo con mis datos pero no sé si me acordaré de todos.

**Comment by Siotma** [comment]
Wiki actualizada: 
http://asrob.uc3m.es/index.php/Operadores
http://asrob.uc3m.es/index.php/Lista_de_socios (no me he dado cuenta de que ya tiene el disclaimer de que está sin soporte)

Web actualizada:
_config.yml via c213bcc4904694576507a6da143ba135087c4b0d

Seguro que me he dejado algo

**Comment by jgvictores** [comment]
> http://asrob.uc3m.es/index.php/Lista_de_socios (no me he dado cuenta de que ya tiene el disclaimer de que está sin soporte)

He actualizado http://asrob.uc3m.es/index.php/Lista_de_socios y http://asrob.uc3m.es :-)

**Comment by David-Estevez** [comment]
Esa lista estaba ahí porque contiene enlaces a páginas que no están migradas todavía, como la página de antiguos miembros o el hall of fame. Para que no haya páginas huérfanas (¿Por qué nadie nunca piensa en los niños?), por favor lleva a cabo alguna de las siguientes opciones (o todas):

* Revertir la wiki a su estado anterior hasta la completa migración de la misma.
* Migrar a la web las páginas que han quedado huérfanas.

**Comment by jgvictores** [comment]
Revertidos cambios a http://asrob.uc3m.es/index.php/Lista_de_socios mediante mecanismo rollback de la wiki. Sorry!

**Comment by David-Estevez** [comment]
No problem, realmente es culpa mía por no documentarlo en ningún sitio :sweat_smile: :sweat_smile:

**Comment by jorgercobo** [comment]
Cosas que tenía pendientes:

* ACK de la entrega de llaves: ACK
* Issues y menciones pendientes como responsable de impresoras 3D: Hay algunas issues pendientes con telarañas ya, que heredé del anterior responsable, en el repo de impresoras y en actas. Podríamos investigar si hay alguna forma de hacer menciones a un rol en vez de a un usuario.
* Lista de operadores: Al quitarme como responsable, no me habéis incluido en la lista de operadores. Voy a abrir una petición de operador, así que no hay problema.

Como nadie se ha presentado al puesto aparte de @Siotma creo que podemos dar por finiquitada esta issue.

**Comment by Siotma** [comment]
> Al quitarme como responsable, no me habéis incluido en la lista de operadores.

Dado que aún no es oficial la migración, creo que tienes derecho a estar ahí. Te he re-añadido: asrob.uc3m.es/index.php?title=Operadores&oldid=12852

> Hay algunas issues pendientes con telarañas ya

¿Podrías indicar por aquí los enlaces? Las iré mirando conforme pueda, pero así no se pierde la información.
