### ISSUE TITLE
Crónica de un corte de electricidad programado, que afectará a wiki y servicios

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#118]
Fwd:

> El miércoles 27 de diciembre la Oficina de Energía, Desarrollo y Entorno (OEDE) va a proceder a la instalación de dos nuevos SAIs (Sistema de Alimentación Ininterrumpida) en la red eléctrica del CPD del edificio Betancourt, modernizando esta parte crítica de la instalación.
Esta intervención conlleva el corte del suministro eléctrico en el CPD de Leganés. De cara a evitar averías por el apagado brusco y el encendido descontrolado de los equipos, recomendamos se apaguen todos los equipos instalados en el CPD Departamental de Leganés antes del miércoles 27 a las 07:30. Los trabajos podrían prolongarse durante la tarde del miércoles 27.
Una vez realizadas las mejoras en la instalación eléctrica, el Servicio de Informática y Comunicaciones (SDIC) sustituirá el equipamiento de red utilizado en el campus de Leganés como nodo central de comunicaciones, con objeto de aumentar la capacidad y dotar de comunicación 10Gbps a elementos críticos. Por ello el servicio de red de datos y la conectividad con Internet permanecerá interrumpida hasta el jueves 28 a las 15:00.
No se recomienda el encendido de los equipos hasta el jueves 28 a las 15:00 una vez se hayan restablecido tanto el suministro eléctrico, como el servicio de comunicaciones.

Esto cual afectará a robots.uc3m.es desde Dic 27 hasta mínimo Dic 28. Sería interesante activar el wake-on-power (si no el wake-on-lan) para no tener que estar físicamente para encender el server.

Somewhat related: #87, #88.

**Comment by David-Estevez** [comment]
¿Puedes encargarte tú de activar esas cosas? A @Siotma y a mi nos interesaría poder trabajar en el sistema nuevo de gestión de impresoras estas vacaciones. 

Si no te puedes encargar con que me pases un tutorial o guía de lo que habría que hacer me vale para intentar activarlo yo.

**Comment by jgvictores** [comment]
Wake-on-LAN lo he hecho, necesita:
1. Activarlo en la BIOS. Esto es, acceso físico. De nuesto dpto, son acastro y scasa los que tienen tarjeta acceso a servers físicos.
2. Cierta conexión cableada interna de tarjeta red a placa. En portátiles existe casi siempre, en servers también. Más bien, a comprobar si anterior punto no funciona.
3. Para probarlo, otro equipo, que envíe broadcast de los paquetes mágicos (si mi memoria no falla, no me lo estoy inventando) con su MAC.

Wake-on-Power:
1. Imagino que sólo necesita el apartado (1) de lo anterior, pero nunca lo he probado.

**Comment by jgvictores** [comment]
FYI: [sdic.uc3m.es > Servicios > Estado](http://www.uc3m.es/ss/Satellite/Informatica/es/TextoDosColumnas/1371216018072/Estado) además de via [twitter @sdic_uc3m](https://twitter.com/sdic_uc3m).

**Comment by smcdiaz** [comment]
Yo me encargaré de encender los equipos

**Comment by jgvictores** [comment]
@smcdiaz Muchas gracias!

**Comment by jgvictores** [comment]
El server estaba encendido, pero las bases de datos estaban mal, tal que las wikis estaban caidas.
Apliqué el proceso descito [aquí](https://github.com/asrob-uc3m/actas/issues/110#issuecomment-342006838) y se ha reestablecido. Cierro, todo en orden. :+1:
