### ISSUE TITLE
Obtener un lector de tarjetas de memoria

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/actas#119]
Estos días, estamos instalando pantallas LCD en las impresoras 3D de la nave para dotarlas de impresión autónoma desde tarjetas SD (https://github.com/asrob-uc3m/impresoras-asrob/issues/40). Para que este nuevo método pueda ser totalmente funcional, es necesario **disponer en la asociación de al menos un lector de tarjetas**, con el que cargar los archivos de impresión.

Creo que lo óptimo sería poner un lector de tarjetas integrado en alguno de los PCs de la nave, para que cualquiera pueda utilizarlo. Estos PCs, desde hace poco tiempo ya tienen internet, y por tanto se podría completar el workflow de impresión con ellos si se dispusiera de un lector de tarjetas.
1. Descargar el archivo de la pieza.
2. Generar el G-code con el software disponible en el PC.
3. Meter el archivo en la tarjeta SD

Los PCs de la nave tienen una bahía de 3,5pulgadas libre, tal como se ve en el PC negro de la siguiente imagen:

<img align="center" width="300" src="https://user-images.githubusercontent.com/6171234/31217246-9470d9aa-a9b6-11e7-9e23-c72fb23ad947.jpg"></img>

Creo que una solución como [esta](https://es.aliexpress.com/item/3-5-inch-USB-Internal-MS-CF-MD-SD-MMC-XD-TF-Card-Reader-L059-New/32819650995.html?src=google&albslr=230262062&isdl=y&aff_short_key=UneMJZVf&source=%7Bifdyn:dyn%7D%7Bifpla:pla%7D%7Bifdbm:DBM&albch=DID%7D&src=google&albch=shopping&acnt=494-037-6276&isdl=y&albcp=652736826&albag=32471627666&slnk=&trgt=75384829977&plac=&crea=es32819650995&netw=g&device=c&mtctp=&gclid=EAIaIQobChMIk6a8vL6i2AIVSCjTCh2FiApVEAkYBCABEgLVovD_BwE) podría ser muy interesante, ya que tiene un coste muy bajo. 

No obstante, me consta que muchos de los PCs de la Universidad tienen lectores de este tipo y por tanto me pregunto si sería posible localizar unidades usadas que estén almacenadas en desuso y nos puedan servir (intuyo que muchas de ellas estarán como nuevas porque nadie las utiliza). No lo digo tanto con el ánimo de ahorrar dinero, que también, sino por reutilizar material electrónico en vez de alimentar la tendencia de comprar, tirar, comprar.

**Comment by jgvictores** [comment]
Hi. Me comentó Ángela que los PCs de la Universidad que tienen lectores de este tipo son sólo los más nuevos. Estamos viendo lo que se puede hacer al respecto.

**Comment by Siotma** [comment]
Muchas gracias Juan!

Nos vas contando.

**Comment by jgvictores** [comment]
Una propuesta temporal y económica:
- En PC: adaptador microSD-USB (sumamente barato, debo tener alguno de aliexpress de 1 eur)
- En Impresora: adaptador microSD-SD (he de tener alguno, viene con la compra de muchas mircoSD)

**Comment by Siotma** [comment]
Es una buena propuesta, lo malo es que no tenemos MicroSDs, solo SDs.

Yo para la reunión de hoy he traído un lector de SD a USB, y de momento estamos funcionando con él, aunque no lo podré dejar en la nave puesto que lo uso con frecuencia en mi casa.

**Comment by jgvictores** [comment]
Ok, era una idea para salir del paso de momento. Lo dicho, en paralelo voy tramitando con Ángela.

**Comment by Siotma** [comment]
De acuerdo, te lo agradezco mucho!

En caso de que acabes viéndolo complicado, ten en cuenta que hay [opciones a 4€](https://es.aliexpress.com/item/3-5-inch-USB-Internal-MS-CF-MD-SD-MMC-XD-TF-Card-Reader-L059-New/32819650995.html?src=google&albslr=230262062&isdl=y&aff_short_key=UneMJZVf&source=%7Bifdyn:dyn%7D%7Bifpla:pla%7D%7Bifdbm:DBM&albch=DID%7D&src=google&albch=shopping&acnt=494-037-6276&isdl=y&albcp=652736826&albag=32471627666&slnk=&trgt=75384829977&plac=&crea=es32819650995&netw=g&device=c&mtctp=&gclid=EAIaIQobChMIk6a8vL6i2AIVSCjTCh2FiApVEAkYBCABEgLVovD_BwE) que con una votación pueden salir adelante fácilmente.

**Comment by jgvictores** [comment]
> En caso de que acabes viéndolo complicado, ten en cuenta que hay opciones a 4€ que con una votación pueden salir adelante fácilmente.

Pues... secundo esa alternativa.

**Comment by jgvictores** [comment]
He vuelto a hablar con Ángela. De Aliexpress no podemos comprar, pero de Amazon sí.
He estado viendo modelos, hay algunos que no me convencen. ¿ Qué tal os parece [este](https://www.amazon.es/Connectland-LECT-MUL-CAR-C109-Lector-interno-tarjetas/dp/B0045O3Y1Y/ref=sr_1_144?ie=UTF8&qid=1515583982&sr=8-144)?

**Comment by jgvictores** [comment]
PD: También está [este](https://www.amazon.es/TooQ-TQR-208B-tarjetas-microSDXC-X-Memory/dp/B005E0EJDK/ref=sr_1_3?ie=UTF8&qid=1515584210&sr=8-3) pero no se ve el conector.

**Comment by GioSunrider** [comment]
El del segundo comentario fue el que le comente a @Siotma que vio por Amazon. Ademas de ser económico nos llega pronto. Desde mi punto de vista es el que elegiria. Que no se vea el conector tampoco es problema, ¿son todos universales no?.

**Comment by jgvictores** [comment]
En el peor escenario, creo que la política de devoluciones de Amazon está bien. Dadme el OK y lo pido.

**Comment by GioSunrider** [comment]
Yo daría el Ok, pero que hable @Siotma que es el responsable ;) Por otro lado no se si te has fijado que es producto Amazon PLUS lo que significaría que necesitamos un pedido de mas de 19 € para poder comprarlo.

**Comment by Siotma** [comment]
Por mi, OK a cualquiera de las dos opciones. Como dice @GioSunrider el tema de Amazon PLUS es un problema para ese artículo en concreto pero seguro que hay gran variedad de ellos y todos son muy similares.

@jgvictores tienes mi OK para hacer el pedido de cualquiera de los que has pasado, o cualquier otro similar en caso de encontrar una alternativa mejor.

**Comment by jgvictores** [comment]
La vía oficial no siempre es la más económica (véase dificultad en justificar compras en Aliexpress, etc).
En principio pido la [segunda opción](https://www.amazon.es/TooQ-TQR-208B-tarjetas-microSDXC-X-Memory/dp/B005E0EJDK/ref=sr_1_3?ie=UTF8&qid=1515584210&sr=8-3). Es posible que aun tarde 1-3 semanas por juntar con otros pedidos, etc. Pediré 2, porque tenemos 2 equipos.

**Comment by Siotma** [comment]
De acuerdo! Muchas gracias ^.^

**Comment by jgvictores** [comment]
Ya pedido! Ahora ya, en principio, pues lo que tarde.

**Comment by Siotma** [comment]
Gracias!

**Comment by jgvictores** [comment]
En armario! (creo que son la primera opción, algo se gestionó para Amazon Prime)

![lectores](https://user-images.githubusercontent.com/4448588/35685701-b68b4bf8-076a-11e8-8dd8-a1a12fe5fd43.jpg)

**Comment by GioSunrider** [comment]
Lectores intalados, y actualmente funcionan perfectamente en ambos equipos sin necesidad de permisos en las cuentas de invitado. Adjunto las fotos del resultado final.

![photo6023629347480513852](https://user-images.githubusercontent.com/10605193/35695049-a3e207c6-0783-11e8-962c-a69e315a3a48.jpg)

![photo6023629347480513853](https://user-images.githubusercontent.com/10605193/35695050-a4019e74-0783-11e8-80d8-2c116eb02f50.jpg)

Las cajas las hemos mantenido en el armario, por si en algun momento fallaran.
