### ISSUE TITLE
URGENTE: DEAD LINE PARA PEDIDO EN BRICOGEEK

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#12]
Cada rama activa cuenta con 50 euros (sin iva) para gastar en bricogeek. Cada rama activa tiene que enviar una lista con lo que necesita antes del 24/04/2016. Cada rama activa que no hayan hecho ningun pedido, perderan el derecho a dichos 50 euros que se gastaran segun la volutad de piggy.

**Comment by jorgerc21** [comment]
VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD VOLUTAD

**Comment by jorgerc21** [comment]
"Cada rama activa cuenta con 50 euros (sin _IVA_) para gastar en _Bricogeek_. Cada rama activa tiene que enviar una lista con lo que necesita antes del 24/04/2016. Cada rama activa que no _haya_ hecho ningun pedido, _perdera_ el derecho a dichos 50 euros que se gastaran segun la _voluntad_ de  _Piggy_."

**Comment by jgvictores** [comment]
"Cada rama activa cuenta con 50 euros (sin IVA) para gastar en Bricogeek. Cada rama activa tiene que enviar una lista con lo que necesita antes del 24/04/2016. Cada rama activa que no haya hecho _ningún_ pedido, _perderá_ el derecho a dichos 50 euros, que se _gastarán_ _según_ la voluntad de Piggy."

**Comment by jgvictores** [comment]
http://tienda.bricogeek.com/placas-raspberry-pi/811-raspberry-pi-3.html para RD please.

**Comment by Rodriwp** [comment]
Falta por mandar la lista de cosas uavs y myod

**Comment by David-Estevez** [comment]
cc @andrespy @JavierIH @Siotma

**Comment by Siotma** [comment]
Tras varios intentos, no he encontrado nada que MYOD "necesite". Como no soy partidario de pedir por pedir porque me parecería un derroche, no voy a poner nada a nuestro nombre.

Sin embargo, sí creo que merecería la pena comprar algunas protoboard/sensores/placas arduino para que la Asociación tuviera de uso común para todas las ramas. Son cosas que dentro de MYOD hemos echado en ocasiones de menos, pero que no sería justificable atribuirnoslas.

Sé que una parte del pedido se va a gastar en objetos de interés común y que probablemente las cosas que comento ya estuvieran planeadas. Sugiero que, de ser inminente el pedido, la parte correspondiente a MYOD se destine a los mismos fines.

**Comment by Rodriwp** [comment]
Puesto que ya contamos con un segundo armario esta previsto en ese segundo armario tener una zona con "kits basicos de arduino" y "kits de componentes avanzados" para uso en las horas de reunion. La idea es que estos sirvan para formación de la gente que entre nueva y a la vez sirvan para poder hacer prototipado rapido de ideas. Estos deberian dejarse perfectamente desmontados y ordenados al terminar de usarlos. 

Podemos pedir parte de ellos con ese dienero a bricogeek

**Comment by Siotma** [comment]
Desconocía la parte de "un segundo armario", pero me encanta jajajaja

Propongo valorar la adquisición de:
- Placas arduino
- Placas protoboard
- Cables de prototipado
- Sensores variados
- Otras cosas necesarias que se me estén olvidando
De forma que, junto a los que ya tenemos, den como resultado una cantidad equilibrada de cada uno de ellos, para conseguir que haya varios kit completos. Adelante con ello.

Además, dado que tendremos más espacio ahora, y que desconozco si la fuente vieja aquella que teníamos sigue por la nave... propongo valorar la adquisición, presente o futura, de una fuente de alimentación regulable para la asociación.

**Comment by Rodriwp** [comment]
Hya que tener en cuenta que tenemos dinero en efectivo para comprar en aliexpress donde cosas como las arduino,cables orptoboards salen muy rentables.

En cuanto a la fuente de alimentación esta operativa y funciona. Aunque probablemente nos vendria bien tener algo mas portatil para las arduinos como esto:
http://tienda.bricogeek.com/fuentes-de-alimentacion/467-fuente-de-alimentacion-12v-5v-2a.html
Probablemente deberiamos hacer otra issue para discutir el tema de los kits, que yo haria 5 kits. Que te da para hacer un curso de 10 personas, a dos personas por kit.

**Comment by David-Estevez** [comment]
Me parece bien disponer de cosillas para prototipar. Pero como ha dicho @Rodriwp todas esas cosas se pueden comprar a mejor precio a china (en BricoGeek nos daría para poco, la verdad) con el dinero suelto de otros patrocinadores. 

Por otra parte, comprar ahí tampoco es ningún despilfarro, porque no se puede gastar ese patrocinio en ninguna otra tienda, así que si vemos algo curioso para la asociación podríamos pillarlo. Por ejemplo, el sensor de monedas y algún joystick para convertir el armario en una máquina de arcade xD

**Comment by Rodriwp** [comment]
Yo aprovecharia para comprar fuentes de alimentación y cosas tipo arcade, hay joysticks, palancas de arcade que estaria guay tenerlas para todo tipo de proyectos.

**Comment by David-Estevez** [comment]
También hay por ahí un chasis de robot con orugas que no tiene mala pinta [(link)](http://tienda.bricogeek.com/robots/533-chasis-robot-zumo.html). (Si lo encontráis en aliexpress me pillo uno para jugar :joy: )

**Comment by Rodriwp** [comment]
Terminado el periodo de peticiones se propone la siguiente lista de pedido. 
![sin titulo](https://cloud.githubusercontent.com/assets/9463837/14770724/afe7694e-0a78-11e6-990f-a8174a06fc75.png)

Que opinais sobre esta lista ?

**Comment by andrespy** [comment]
Me parece que está bastante bien

**Comment by David-Estevez** [comment]
:+1:

**Comment by jgvictores** [comment]
:+1:

**Comment by Rodriwp** [comment]
Faltaria que MYOD diera su opinion sobre la compra

**Comment by Rodriwp** [comment]
Al ir a hacer el pedido tenemos un problema y una buena noticia. Al meter le codigo nos cobra 7,20 euros de envio que nos taca pagar a nosotros. La nuena noticia es que en total tenemos 44 euros mas para gastar ya que el patrocinio no paga iva.

Alguna sugerencia para añadir ?

**Comment by Rodriwp** [comment]
El pedido ya esta hecho se adjuntara la factura en #13

**Comment by David-Estevez** [comment]
@Rodriwp  Cómo va el pedido? cuándo dispondremos de las cosas pedidas?

**Comment by Rodriwp** [comment]
Las cosas pedidas ya estan en el armario 2 de la asociacion. Faltaria hacer el inventario.

**Comment by David-Estevez** [comment]
Jugueteeeeees!!!
