### ISSUE TITLE
Nuevo juego de llaves para Printer One

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/actas#121]
**Aviso:** Como les comenté a los compañeros de Printer One en la última reunión, mi situación personal ha cambiado drásticamente al haber empezado en un trabajo a tiempo completo, por lo que la disponibilidad para asistir a las sesiones se ha visto comprometida.

**Duda:** Esta issue es una consulta acerca de si se podría **disponer de un juego de llaves adicional** para que algún otro miembro del grupo pudiera acceder a la nave y abrir el armario durante las reuniones en caso de que yo no pueda ir, o llegue más tarde. Actualmente, tanto @daavm como @GioSunrider son miembros muy activos y con experiencia en el [Grupo de Trabajo Printer One](https://github.com/asrob-uc3m/impresoras-asrob/wiki/Printer-One-A-Clone-Wars-Story) y han aprendido completamente nuestros métodos de organización, por lo que les propongo para custodiar el nuevo juego de llaves que solicito.

Con el tiempo, evaluaré mis posibilidades reales de seguir asistiendo a las reuniones, e iré transfiriendo algunas de mis obligaciones como responsable en caso necesario, pero eso es algo que quiero hacer de forma progresiva. 

En caso de nos ser viable mi propuesta, estoy abierto a alternativas.

**Comment by jgvictores** [comment]
A nivel departamento estamos un pelín limitados de llaves de la nave en estos días.

@andrespy UAVs se está reuniendo? Podéis ceder vuestro juego de llaves a esta gente?

**Comment by Rodriwp** [comment]
Yo aun conservo el juego de llaves que usaba como antiguo reponsable de HackLab. No tengo inconveniente mediante el procedimiento correspondiente a ceder mi llave. 

@jgvictores ¿puedes confirmar si cuando me dieron la llave estaba a mi nombre? si es asi, ¿ se puede cambiar el propietario de dicha copia a unode los miembros que @Siotma comenta ?

**Comment by Siotma** [comment]
Gracias @Rodriwp !

**Comment by jgvictores** [comment]
> Yo aun conservo el juego de llaves que usaba como antiguo reponsable de HackLab. No tengo inconveniente mediante el procedimiento correspondiente a ceder mi llave.

@Rodriwp Agradezco muchísimo este gesto por tu parte!!

> @jgvictores ¿puedes confirmar si cuando me dieron la llave estaba a mi nombre? si es asi, ¿ se puede cambiar el propietario de dicha copia a unode los miembros que @Siotma comenta ?

En la wiki la única referencia es a https://github.com/asrob-uc3m/actas/issues/15...

**Comment by jgvictores** [comment]
@Siotma ¿Podrías porfa coordinar para que @Rodriwp le pase las llaves a @daavm o @GioSunrider a través de tí o de alguna manera?

**Comment by Rodriwp** [comment]
@jgvictores mi duda tienes más que ver con la llave de la nave, que con la llave de los armarios. La llave de los armarios entiendo que con que quede reflejado en un issue es suficiente. 
¿La llave de la nave se puede ceder con solo reflejarlo en la issue?

**Comment by jgvictores** [comment]
> ¿La llave de la nave se puede ceder con solo reflejarlo en la issue?

Sí, de hecho, el recurso más escaso es la llave del armario. En este caso particular, entendemos que hablamos del conjunto "llave nave + llave armario", ¿no?

**Comment by Rodriwp** [comment]
> Sí, de hecho, el recurso más escaso es la llave del armario. En este caso particular, entendemos que hablamos del conjunto "llave nave + llave armario", ¿no?
Si, es el conjuto llave de la nave + llave armario

**Comment by jgvictores** [comment]
Perfecto "conjuto llave de la nave + llave armario", basta con comentarlo por aquí, gracias.
@Siotma ¡Manifiéstate! :smile:

**Comment by Siotma** [comment]
Lamento la tardanza, mi tiempo libre se ha visto muy reducido y aún no me he acostumbrado a gestionarlo para abarcarlo todo.

@Rodriwp . Podría quedar contigo en la Universidad cualquier día de lunes a viernes a partir de las 18:30 para que me entregues el juego de llaves. La idea es que una vez que las tenga yo, se las entregue a @GioSunrider en la siguiente reunión de Printer One.

Qué os parece? :)

**Comment by Siotma** [comment]
Llaves recibidas hoy a las 18:30 de @Rodriwp ! ACK

Mañana se las entregaré a @GioSunrider y daremos otro ACK.

**Comment by GioSunrider** [comment]
Llaves recibidas hoy a las 18:30 por parte de @Siotma ACK!
