### ISSUE TITLE
Reunión Makerspace UC3M-ASROB (Doodle)

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#122]
La Universidad está preparando un Maker Space, y se está haciendo una ronda de consultas entre las asociaciones de estudiantes, ya que se cree que pueden tener un especial interés en el espacio. Desde el punto de vista académico, Nando (Departamento de Automática) será el encargado de gestionarlo.

Nos ha comunicado que quería saber si estabamos interesados en reunirnos con él para tratar nuestras inquietudes y posibles intereses en el proyecto. Ha contactado directamente conmigo (su email a ASROB se quedó entre nuestros diversos filtros), así que directamente le pedí Doodle reunión para esta issue.

Os animo a todos los interesados que participéis. Aquí enlace a Doodle para concretar fecha/hora reunión para comentar esto del Makerspace con Nando! https://doodle.com/poll/tr29pe6ga4txn6z5

**Comment by Siotma** [comment]
Yo esto no me lo pierdo. Ya he votado!

**Comment by jgvictores** [comment]
Yo votado tb. Nando creo que no puede el lunes, yo prefiero que el miércoles mejor no. Con esos datos, de momento apunta al martes a las 19:00.

**Comment by Siotma** [comment]
Apuntado!

**Comment by jgvictores** [comment]
Asignados los asistentes, cerrando!
