### ISSUE TITLE
Candado Blacky puesto dejando cadena abierta

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#123]
Esta mañana @GioSunrider encontró el candado de Blacky puesto, pero dejando cadena abierta.

Que sepamos, sólo @Siotma tiene llave. Yo en el juego de llaves que en su día me pasó @Rodriwp, no tengo.

Como solución temporal, hablado con @David-Estevez, puse otro candado que tenía yo a mano (con 2 llaves). Me quedé con una llave, y la otra la coloqué dentro del armario convenientemente etiquetado en su lugar correspondiente.

**Comment by Siotma** [comment]
Es posible que esa cadena se quedase abierta por error en la primera reunión de este año. Lamento el fallo.

> Que sepamos, sólo @Siotma tiene llave. Yo en el juego de llaves que en su día me pasó @Rodriwp, no tengo.

Que yo sepa, en [el manojo para gobernalos a todos](https://github.com/asrob-uc3m/actas/issues/65#issuecomment-285311688), hay una copia de la llave de ambos candados (ambos usan la misma llave).

**Comment by jgvictores** [comment]
Encontrado el manojo, cerrado candado original, quitado el provisional.
