### ISSUE TITLE
Uso del espacio "La Nave" por los asociados de UC3Music 21 Febrero.

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#124]
Este miércoles 21/02/2018 UC3Music ha organizado una quedada-taller para montar los kits de MiDispositivoMIDI. El horario planteado  es de 13 a 15h.
Solicitamos permiso para usar el espacio de La Nave porque el despacho de UC3Music no es suficientemente grande ni tiene mesas suficientes. Usaremos dos de las cuatro mesas como máximo, seremos siete personas.

A continuación invacaré una votación, cuando encuentre el enlace a forms.

**Comment by JorFru** [comment]
Dale!
https://goo.gl/forms/1hQFKCIeo2PDMhJF3

**Comment by JorFru** [comment]
Todo está saliendo a pedir de Milhouse
Cerrando...
![photo_2018-02-21_13-37-30](https://user-images.githubusercontent.com/11017088/36480396-6dc24a6e-170c-11e8-8287-e6e17752cb7d.jpg)

**Comment by Siotma** [comment]
Deja por aquí alguna fotillo del resultado ;)

**Comment by JorFru** [comment]
Aquí se pueden ver las fotos del proceso de construcción y de todas las piezas. Por @serjsanchez
https://www.instagram.com/p/BfdsDfdFjNc/
