### ISSUE TITLE
Solicitud de reembolso dinero Dohyō

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#125]
Una de las competiciones para las que estamos preparándonos en RoboFactory es la de sumo. Para poder entrenar, necesitamos un [Dohyō](https://en.wikipedia.org/wiki/Dohy%C5%8D) en el que combatan los robots. Para este fin,  @Ruben-MR compró unas maderas a partir de las cuales cortar el . El precio de dichas maderas fue de 18€ (ver [issue #4](https://github.com/asrob-uc3m/ASROB-sumo/issues/4)). 

Dejo por aquí la votación para el rechazo/aprobación de dicho reembolso por parte de la Asociación: https://goo.gl/forms/MHdmRLj58YNWEqhf2

Fecha límite: 23/02/2018

**Comment by David-Estevez** [comment]
Aprobado, 4 votos a favor, 0 en contra. 

Para el pago, es posible que haga falta resolver #98

**Comment by jgvictores** [comment]
Porfa di cuándo es la siguiente reunión donde nos podamos cruzar, no tengo problema con reembolsártelo en calidad de tesorero en funciones. ((Si alguien detecta algo que no vaya acorde con los Estatutos, que diga sin problema. Actúo tratando de facilitar las cosas dentro de una situación que creo que no está contemplado)).

**Comment by Ruben-MR** [comment]
Hola, buenas noches. Yo voy a estar en la asociación este martes de 15:00 a 17:00 para la reunión de RoboFactory, si hay algún inconveniente, no tengo problema en acercarme a la universidad en un momento cuando sea. Muchas gracias.

**Comment by jgvictores** [comment]
Ok, me pasaré.

**Comment by jgvictores** [comment]
Entrega realizada, [wiki](http://asrob.uc3m.es/index.php?title=Cuentas_ASROB&type=revision&diff=12893&oldid=12803) actualizada. @Ruben-MR Creo que puedes ACK y cerrar sin problema.

**Comment by Ruben-MR** [comment]
Vale, procedo entonces a cerrar la issue, gracias.
