### ISSUE TITLE
Uso del espacio "La Nave" por T3chFest para taller Drawdios institutos 23 Febrero 2018

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#126]
T3chFest organiza en la EPS un taller para alumnos de institutos. El taller consiste en en montaje de Drawdios. El taller lo imparto yo, representando a UC3Music.

La cuestión es que T3chFest tiene más actividades que aulas disponibles en la universidad, y @daavm ha pensado que podría usarse nuestro espacio de "La Nave". Por eso organizo esta votación.

El taller será el 23/02/2018 en horario de 9 a 14h (todo recogido a esa hora). 15 alumnos por sesión, dos sesiones de dos horas cada una.

El material que usaremos es sólo el mobiliario de mesas y sillas. El material de soldadura nos lo prestará el Dpto. de laboratorios de electrónica.

El plazo de voltación termina antes del viernes.

https://docs.google.com/forms/d/e/1FAIpQLSfply6M3IxzXE794JigAbZk9Ga2gPgTrdObwinPhksIEyIM-g/viewform?usp=sf_link

**Comment by Siotma** [comment]
Teniendo en cuenta que no necesitáis más que el mobiliario, yo creo que estaríais más cómodos en un aula que tuviera posibilidad de mover las mesas. En un aula dispones de pizarra para explicar y también de proyector y pantalla para poner vídeos explicativos. Si os hacen falta enchufes, yo creo que podeis contar con los alargadores y regletas de la nave.

No creo que sea operativo estar 16 personas en el hueco de la nave, se me hacen muchas. Cuando hemos sido tantos es complicado moverse. Además, los chavales querrán dejar sus cosas (mochilas, abrigos y merchandising que les de la Uni) en algún sitio y me temo que lo pongan encima de las impresoras, y eso no me mola.

Desde mi punto de vista, no es una buena solución.

**Comment by daavm** [comment]
¡Hola!

Como bien dices @siotma, no es el mejor espacio para un taller así. El motivo por el que pedimos el espacio de la nave es porque el día 23 (el día de la jornada de institutos) no hay más aulas disponibles que la universidad pueda darnos. Realmente les ha costado darnos aula para los otros 5 talleres que tenemos, hasta tal punto que se van a usar las aulas de la tercera planta de la biblioteca.

Por otra parte, estoy de acuerdo en que el tema de los bultos que lleven los chavales puede suponer un problema, pero tanto Jorge como yo vamos a estar allí, y eso estaría más que vigilado.

Repito que pienso igual que tú, no es el mejor sitio, pero si la mejor opción que tendríamos ahora mismo.

Saludos :)

**Comment by JorFru** [comment]
Sugiere a Oficina Logística reservar un pasillo, ya verás como se ponen las pilas...

**Comment by Siotma** [comment]
En caso de que no encontreis alternativa, se puede aceptar bajo las condiciones de vigilancia que mencionas.

**Comment by JorFru** [comment]
En las siguientes imágenes podréis ver la granja de soldadura a pleno rendimiento.
![photo_2018-02-24_16-31-38](https://user-images.githubusercontent.com/11017088/36631983-b24ae116-1980-11e8-92fc-d8bc9f909c1e.jpg)
![photo_2018-02-24_16-31-38](https://user-images.githubusercontent.com/11017088/36632035-2113c93c-1981-11e8-99e4-2140e4d0f724.jpg)


Esto es el estado en el que acabó nuestro espacio después del taller,
![photo_2018-02-24_16-31-40](https://user-images.githubusercontent.com/11017088/36631987-b9fb55e4-1980-11e8-9a55-12e21b0fc417.jpg)
Así es como quedó cuando lo recogimos @daavm y yo.
![photo_2018-02-24_16-31-40 2](https://user-images.githubusercontent.com/11017088/36631988-ba415666-1980-11e8-8139-fa02775427d0.jpg)

Desde aquí agradecer la enorme ayuda y el apoyo emocional de @daavm  ¡Eres un grande!
