### ISSUE TITLE
Tornillo asesino

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#127]
Ayer @daavm casi se nos mata por culpa de este tornillo.

Sugiero hacer sufrir doblemente al tornillo. Primero por atentar contra la seguridad de nuestro compañero, y segundo por su desgracia de ser avellanado.

Este tornillo no merece compasión y sugiero que sea el premio al peor robot en el próximo Hackatón.

![photo_2018-02-24_16-41-44](https://user-images.githubusercontent.com/11017088/36632061-9e8a8e46-1981-11e8-8190-21ab50c8abc9.jpg)

**Comment by daavm** [comment]
No es broma, ¡casi me comí el suelo! Si solo hubiese levantado el pie 1cm más... Jajaja

**Comment by GioSunrider** [comment]
😂😂😂😂😂 últimamente estamos que nos gusta demasiado el suelo de la nave, si no que se lo digan a @Siotma 🤣 y lo que es la propuesta del premio me parece perfecta ajajajaja

**Comment by daavm** [comment]
Hoy tras casi caerme otra vez (no lo ha visto nadie JA), he apretado el tornillo y ya no supondría un problema. Que también podría haberlo quitado, pero bueno :D 
Se puede cerrar la issue supongo

**Comment by JorFru** [comment]
Te concedo el honor de cerrarla tú mismo. Ya que has arreglado el problema

**Comment by JorFru** [comment]
Está bien que lo atornilles. Así queda almacenado hasta la organización de #92
