### ISSUE TITLE
Reunión de Convocatoria de Ayudas a Proyectos

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#128]
Estoy llorando de risa. Mañana hay una reunión de Asociaciones para la convocatoria. Dicen que si no vas a la reunión, no cae un chavo, pero no es vdd.

Datos:
Martes 27 de febrero
12.00 horas
Campus de Getafe. Aula 10.2.7

Me tocará ir a mí, así asisto también representando a UC3Music y matamos dos pájaros de un tiro.

Además me asigno, con extra de puntos por "Tarea tediosa que nadie quiere hacer"

**Comment by JorFru** [comment]
Vale! Ya he ido y está todo bien por parte de ASROB.

Como somos buenos redactando, entendieron nuestro proyecto a la primera y les hemos convencido para que nos subvencionen las actividades.

El punto que más han destacado en la reunión es hacerlo todo a tiempo e ir mandando las facturas según se generen, para no acumular el trabajo al final de la convocatoria.

Apuntado el tanto que vale por cinco. 


Cualquier pregunta, estarán disponibles para contestarla en la dirección espacioabierto(alojado en)uc3m(puntico)es

**Comment by jgvictores** [comment]
Gracias @JorFru !!!
