### ISSUE TITLE
Reunión con África Semana de Asociaciones

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#129]
Ha llegado un correo de África convocando reunión para organizar la Semana de las Asociaciones.
Ya sabéis que esta semana está formada por varios días de talleres, charlas, etc. Y también por la famosa feria donde expondremos todos nuestros cacharritos.
Siempre mola enseñar nuestros juguetes, publicitarnos, y además es buena oportunidad para hacer combates robóticos, incluso para probar nuestros robots acuáticos en la fuente.

Lo marco como tarea tediosa que nadie quiere hacer y quien resuelva esta issue podrá sumarse ASROBCoins y puede que hasta se lleve un gomet verde por portarse bien :-)

```
Buenas tardes! os escribo para confirmaros la reunión del martes 6 de marzo a las 12 horas en el campus de Leganés (no puedo indicaros todavía el aula...).

Será una reunión preparatoria para la próxima Semana de Asociaciones, ya que aunque pueda parecer que queda mucho, lo cierto es que junio (que es cuando yo tengo que tener el "esqueleto" de la semana...) está a la vuelta de la esquina...  

¡¡¡Espero veros a todos!!!! 😊

Un beso y feliz fin de semana!!!!!!!! ⛄❄☔☔

África
```

**Comment by David-Estevez** [comment]
Yo el martes a esa hora tengo compromisos docentes que atender, así que no podré ir :cry:

**Comment by jgvictores** [comment]
Apuntado, voy!

**Comment by JorFru** [comment]
Juan asignado para ganar ASROBCoins!

Gracias!

**Comment by jgvictores** [comment]
Acta 2018/03/06 a las 12h en 4.0.E02. Asistentes: África + 12 contándome.

A destacar de todo lo de debajo, los DEBERES para la Semana, y la posibilidad de ir a Getafe para la feria.
# Repaso feedback de la última Semana
- Pos: Africa muy orgullosa de todo lo que dicen.
- Neg: cosas como cancel a última hora, alguna charla puntual poco preparada. Todo esperable. 
- Petición: Cosas más prácticas. Cacharreo.
# Semana (para curso que viene, que es el quinto)
- Fechas: Oct 1-5 (que dé tiempo y aun haya buen clima).
- Aulas Getafe ya reservadas hall 14.0.11 y hall 15.
- Pancartas (hay 2): las asociaciones se tienen que juntar para pedir colocarlas, por ej después de bienvenida septiembre. se puede hacer 1/2 más (más sábana que lona). 
- Ordenadores para Actividades? (pedir con tiempo, revisar sw/permisos).
- Aviso: Están cambiando cosas de reconocimiento de créditos, estar atentos.
- **Semana previa y manteniéndose durante**: tratar de tener cosas visuales fuera (expos fotos, etc). **Se habla de vitrina con expo ASROB (y que Fórmula tiene vitrinas).**
- **Se contabilizan los inscritos (en general se inscriben los que van por créditos), por lo cual es bueno que se inscriban ((via enlace oficial en aula global)): para mostrar necesidad capacidad aulas, etc.**
- **Camisetas = cosa importante. Como la de ASROB mola, podemos ir 50/50 (ASROB/uni roja)((lo que se busca es bulto rojo)).**
- **DEBERES (deadline 4 junio [email con asunto "Semana Asociaciones: Actividad(es) ASROB"])(charlas/talleres): Actividades: nombres y descripciones. Duración 1.5h (1 sello)  o 3h (2 sellos). Aunque podría tocar a solo 1 por Asociación, el año pasado hubo alguna con 3,, no se sabe hasta tener todas.**
# Feria Asociaciones
- Es en cojunto con Delegación. Getafe(campus humanidades,jueves)<->Leganés(viernes). **Nos comunican que nunca hemos ido a Getafe, y que deberíamos** @@
# Encuentro Asociaciones
- Posible Abril, posible pizzas, posible sábado.

**Comment by David-Estevez** [comment]
Muy bien documentado, muchas gracias por el curro!!
