### ISSUE TITLE
Cuentas Asrob

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#13]
En esta issue se irán publicando las cuentas de asrob.
Actualmente tenemos:

- 250 euros para gastar en bricogeek #12

- 327,24 euros en efectivo (127,24 tienen que llegar todavía)

- 18 euros piggy en cuenta bancaria

- Lo que haya ahora en piggy (calderilla fundamentalmente)

Se ha gastado dinero de piggy en materiales fungibles que hay en el armario, un calibre y un nivel.

**Comment by David-Estevez** [comment]
No sé si esto va aquí, pero hay que mandar los datos de la cuenta a los señores del IEEE para que nos hagan la transferencia (hay un correo en la lista de ASROB). Fecha límite: 15 Mayo

**Comment by Rodriwp** [comment]
La información ya ha sido enviada @David-Estevez

**Comment by David-Estevez** [comment]
Hecho y cerrada. Borro los comentarios en esta issue?

**Comment by David-Estevez** [comment]
He estado pensando que realmente las cuentas de ASROB no son un "issue", sino algo que debería estar publicado siempre (no se cerraría nunca este "issue"). Así

**Comment by David-Estevez** [comment]
Es un hack (como todo esto que hemos montado en github), pero tiene más sentido (y posiblemente visibilidad) si se integra como sección de la wiki de ASROB. Se puede gestionar también mejor los permisos de edición y lectura (para limitarlo a miembros activos, por ejemplo). También está el hecho de que todas las modificaciones de la wiki quedan registradas en un histórico, y en github las ediciones de los comentarios no quedan registradas ni se notifican. En la wiki también se pueden adjuntar facturas, etc, que se consideren necesarias (echad un ojo a cómo tienen montado los del CRM el tema de la transparencia en [su web](https://github.com/CRM-UAM/CRM-UAM.github.io).

De la misma forma, yo entiendo que sería más intuitivo que cada enmienda o consulta que se haga se haga en el contexto de una issue nueva o independiente, de forma que quede registro de las cosas que ya se han decido y consultado antes de hacer una consulta nueva (dentro de un mismo hilo quedarían más ocultas).

**Comment by Rodriwp** [comment]
Se hna gastado 8,40 euros de piggy en adecuacion de la seguridad del material

**Comment by David-Estevez** [comment]
Mi propuesta es esta: http://asrob.uc3m.es/index.php/Cuentas_ASROB (Restringido el acceso a miembros de la Junta, de momento)

Si os mola el formato, podemos crear permisos de miembro activo para que la gente de la aso pueda acceder y verlo.

**Comment by David-Estevez** [comment]
Y al año se podrían migrar las tablas a otra página para que no acabase petada esa.

**Comment by Rodriwp** [comment]
-7,20 gastos de envio pedido bricogeek
Total efectivo 320,04
Se adjuntara la factura en cuanto este disponible

**Comment by Rodriwp** [comment]
Hemos recibido el dinero del IEEE, ya esta disponible para su uso

**Comment by David-Estevez** [comment]
Entonces, ¿Os gusta el [formato wiki](http://asrob.uc3m.es/index.php/Cuentas_ASROB)? ¿Lo adoptamos?

**Comment by jgvictores** [comment]
Ok por mí el formato wiki. Si a 20 JUN 2016 nadie se opone, cerramos issue.

**Comment by David-Estevez** [comment]
Dado que nadie ha dicho nada en contra, a partir de ahora todos las cuentas de ASROB se llevarán en la wiki, en la [siguiente página](http://asrob.uc3m.es/index.php/Cuentas_ASROB).

@Rodriwp habría que actualizar la página de la wiki con lo gastado en la compra a Bricogeek, para tener las cuentas al día.
