### ISSUE TITLE
Semana de Asociaciones 2018: Envío de descripciones de actividades

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#130]
Email a Africa con asunto `Semana Asociaciones: Actividad(es) ASROB`. Charlas/talleres: Actividades: nombres y descripciones. Duración 1.5h (1 sello)  o 3h (2 sellos). Aunque podría tocar a solo 1 por Asociación, el año pasado hubo alguna con 3,, no se sabe hasta tener todas. (TLDR: #129)

Deadline 4 junio.

**Comment by David-Estevez** [comment]
Esto ya se completó con éxito por @wenflehecanario  y @madelgj Nos coordinaremos para subir el formulario al drive que esté disponible junto con los de otros años.

La charla propuesta tendrá lugar el Lunes 1 de Octubre de 15:00h a 16:30h. en el aula 3.1.S08.

Si creéis que sería adecuado crear otra issue para gestionar esa charla, adelante.
