### ISSUE TITLE
Semana de Asociaciones 2018: Exposición previa/durante

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#131]
Semana previa y manteniéndose durante: tratar de tener cosas visuales fuera (expos fotos, etc). Se habla de vitrina con expo ASROB (y que Fórmula tiene vitrinas). (TLDR: #129)

**Comment by Siotma** [comment]
Una locura muy molona: Una impresora 3D imprimiendo durante días la misma pieza. 

Lo dejo escrito por aquí que si no la inspiración se me va, y se me olvida.

**Comment by jorgercobo** [comment]
Podemos dar por concluida la Semana de Asociaciones 2018 al no haber más actividades en las que participemos. Antes de cerrar la issue podríamos usarla para hablar el tema de las vitrinas, que puede entrar en el apartado decoración de la nave, o mover la discusión a una de las issues relacionadas.

**Comment by David-Estevez** [comment]
Como dice @siotma, mejor mantener las issues monotemáticas para poder cerrarlas y que no se queden ahí de forma indefinida.

Al final lo de la exposición no se hizo, así que esta issue se puede cerrar. Para todo lo demás, nueva issue, o issue correspondiente.
