### ISSUE TITLE
Llevarme Zowi a casa

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#133]
Issue original: https://github.com/asrob-uc3m/zowi/issues/6
Autor: @VentressAsajj
Contenido:
> Hola a todos:
> He pensado aprovechar esta semana santa para intentar terminar uno de los zowis que tenemos en la asociación. Os importa que me lleve uno a casa? hay uno que necesita calibrase y cargarle el programa.

**Comment by Siotma** [comment]
Hola.
Yo creo que es factible. Para oficializarlo te pediría:
1. Foto y breve descripción del estado del robot en el momento en que te lo llevas.
2. Lista de modificaciones que planeas realizar sobre el robot. Debes demostrar que tras realizar este proceso, el robot pasará a estar en un mejor estado del que se encuentra actualmente.
3. El día que lo devuelvas. Otra foto y otra descripción de las diferencias de estado del robot con respecto al día que te lo llevaste.

Que lo disfrutes :)

**Comment by David-Estevez** [comment]
En otros préstamos ha habido votación de por medio (https://github.com/asrob-uc3m/actas/issues/99), pero era un caso distinto porque el solicitante no era miembro activo.

En este caso con hacer lo que ha sugerido @Siotma yo creo que sería suficiente. Otros miembros de RoboFactory también se han llevado sus robots para trabajar en ellos esta Semana Santa.

**Comment by VentressAsajj** [comment]
ok.@David-Estevez cuándo me puedo pasar a por el. 
La lista de tareas a realizar ¿las dejo escritas aquí o en otro sitio? y la foto igual, ¿la subo aquí? ¿la pongo en el grupo?

**Comment by David-Estevez** [comment]
Ahora tengo clase hasta las 13h, luego estaré por la uni brevemente porque hoy como en casa. Así que por mi parte las opciones son:

* No mucho más tarde de las 13h
* 15-20 min antes de las 19h

¿Cuál te viene mejor?

**Comment by VentressAsajj** [comment]
Tengo la foto. ¿Dónde la pongo?

**Comment by David-Estevez** [comment]
Puedes ponerlo todo por aquí

**Comment by VentressAsajj** [comment]
![img_1865](https://user-images.githubusercontent.com/27798557/37933806-a338049a-314c-11e8-8ac1-76ff7c427843.jpg)
El robot está sin calibrar, está sin terminar, le faltan los brazos, la cabeza, etc.
Le objetivo es calibrarlo e instalar el programa.

**Comment by VentressAsajj** [comment]
Hola. El robot lo sigo teniendo. He visto que tiene un servo mal, así que si no os importa lo cambio.

**Comment by VentressAsajj** [comment]
devuelto. cierro issue

**Comment by jorgercobo** [comment]
Cerrando
