### ISSUE TITLE
Donación de circuitos de siguelíneas

### ISSUE THREAD

**Issue by JavierIH** [asrob-uc3m/actas#134]
En la LNRC sobran algunas pistas de siguelíneas que pueden ser donadas a la asociación. El único requisito es ir a buscarlas entre hoy y mañana (martes 3 de abril). Están en un local de Madrid, comparto la dirección por privado.

Conseguir los circuitos soluciona asrob-uc3m/ASROB-racing#1

Adjunto foto:
![whatsapp image 2018-04-02 at 12 05 59](https://user-images.githubusercontent.com/5154251/38196784-377f56a2-3685-11e8-9b46-59bbd5c21f9a.jpeg)

**Comment by David-Estevez** [comment]
Se ha organizado una excursión formada por @wenflehecanario, @madelgj y un servidor para recuperar esos circuitos mañana.

**Comment by David-Estevez** [comment]
Los circuitos se recuperaron con éxito, junto con 2 tatamis de sumo, y se encuentran actualmente en La Nave. 

Cuando los usemos haremos fotos y le daremos visibilidad en redes sociales.
