### ISSUE TITLE
Uso del espacio "La Nave" por los asociados de UC3Music 19 Abril. 

### ISSUE THREAD

**Issue by BreakingTheExpectations0** [asrob-uc3m/actas#135]
UC3Music ha organizado una quedada-taller para arreglar cascos y demás audio gadgets. El horario planteado es de 13 a 15h. Solicitamos permiso para usar el espacio de La Nave porque el despacho de UC3Music no es suficientemente grande ni tiene mesas suficientes. Usaremos dos de las cuatro mesas como máximo, seremos alrededor de 10 personas.
A continuación invacaré una votación:
https://docs.google.com/forms/d/e/1FAIpQLSdeD7uuTbbvv1roICYJSkrC0OzgLQvDCeq2PymaLI3C90MTMQ/viewform?usp=sf_link

**Comment by David-Estevez** [comment]
Hola @BreakingTheExpectations0, gracias por seguir los procedimientos de ASROB correctamente para tu petición :smile: 

"La Nave" es un espacio del DISA que está cedido indefinidamente a ASROB para realizar sus actividades. Por ello, pese a que ha habido antecedentes (#126, #124) de la cesión a terceros del espacio para actividades puntuales, creo que se deberían considerar los siguientes puntos:

1. La prioridad del uso del espacio debería ser siempre para los asociados y las reuniones en sus respectivos grupos de trabajo. La cesión a un tercero siempre debería estar condicionada a que el espacio esté libre.
2. Esta cesión no se debe ver como algo habitual, sino algo puntual. Es decir, que hay que procurar dentro de lo posible que esta cesión sea el último recurso, habiendo intentado previamente obtener un espacio mediante los métodos habituales de la universidad (p. ej. reserva de aulas). Si la universidad no dispone de un espacio adecuado para las necesidades de UC3Music (y de cualquier otra asociación), se debería hacer llegar esta petición / queja a la universidad para que la tenga en cuenta.

El horario de la mayoría de reuniones de ASROB se elige el Domingo de la semana anterior / Lunes de la misma semana, por lo que hasta el día 19 no se sabrá si el espacio estará ocupado o no. De estar libre, no habría inconveniente en que llevases a cabo la actividad si la votación es positiva. Si no quieres arriesgarte, te recomendaría que intentases reservar un aula para la quedada-taller.

**Comment by David-Estevez** [comment]
Los correspondientes doodles se han cerrado, y las reuniones de esta semana ya están fijadas. El hueco solicitado, jueves 19 de 13 a 15h está libre.

Quedamos pendientes del resultado de la votación.

**Comment by David-Estevez** [comment]
Los resultados de la votación han sido los siguientes:

![image](https://user-images.githubusercontent.com/1451819/38942459-18323f10-432f-11e8-8adc-9ee076f56be5.png)

A favor: 1
En contra: 0
Ni fu ni fá: 3

Por tanto, podéis hacer uso del espacio el próximo Jueves 19 de 13 a 15h.

**Comment by Siotma** [comment]
Fotos! Fotos!

**Comment by BreakingTheExpectations0** [comment]
https://www.facebook.com/UC3Music/photos/pcb.827249600809002/827248937475735/?type=3&theater

**Comment by JorFru** [comment]
Muchas gracias, gente de ASROB, por cedernos vuestro espacio.
Muchas gracias, Mark, por hostearnos las fotos.
