### ISSUE TITLE
Pegatinas de ASROB para portátil 

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#136]
@wenflehecanario propone en https://github.com/asrob-uc3m/ASROB-racing/issues/9 hacer pegatinas de ASROB, idea que me parece genial.

De momento necesitamos:

* [x] Saber cuántas personas querrían pegatinas (para saber cuántas pedir).
* [ ] Saber cuánto nos costarían esas pegatinas.
* [ ] Diseñar las pegatinas (se puede usar el logo que está [aquí]() directamente).
* [ ] Fabricar las pegatinas.

¿quién se ofrece voluntario para encargarse de esto? ¿@wenflehecanario?

**Comment by David-Estevez** [comment]
@madelgj ha creado un doodle para que nos apuntemos si queremos pegatinas:

https://doodle.com/poll/3c4kqt9z5tzdsp89

Lo dejamos abierto hasta el domingo 15 de Abril.

**Comment by wenflehecanario** [comment]
Me ofrezco voluntario como tributo!!

**Comment by VentressAsajj** [comment]
y yo ayudo @wenflehecanario

**Comment by David-Estevez** [comment]
Cerramos el doodle. Los resultados han sido:

* 11 personas quieren pegatinas.
* Algunas personas quieren más de una.

La siguiente fase sería ver dónde pedir las pegatinas y cuántos nos costarían.

**Comment by daavm** [comment]
En stickermule son relativamente baratas, podemos pedir 200 de 5"x5" (redondas) por unos 70 euros. 

![screenshot from 2018-04-16 00-32-20](https://user-images.githubusercontent.com/14359236/38784132-c19e431a-410d-11e8-913f-0daa9e95095a.png)

**Comment by GioSunrider** [comment]
Yo no especifiqué que quería varias, pero las quiero 😂😂😂😂

**Comment by David-Estevez** [comment]
@wenflehecanario a cuánto salen 200 pegatinas en la web que miraste?

**Comment by wenflehecanario** [comment]
Buenas, después de días de búsqueda y comparación de precios, he llegado a la conclusión de que nuestra mejor opción es esta página web: https://www.moo.com
![pegatinas](https://user-images.githubusercontent.com/33062755/39602581-da6f9670-4f25-11e8-8935-d822c00dc911.jpg)
 Si no, a precios más inviables para el bolsillo español tenemos:
-https://www.reprotel.com/product/pegatinavinilo#
![imagen](https://user-images.githubusercontent.com/33062755/39602631-0598b4b2-4f26-11e8-910a-0f5e44291d43.png)
-https://camaloon.es/pegatinas-personalizadas/pegatinas-vinilo/pegatinas-vinilo-forma-estandar?placement=interior&shape=oval
![imagen](https://user-images.githubusercontent.com/33062755/39602666-2315adc4-4f26-11e8-90b6-ebdb7b59b0b1.png)
-https://www.lagranimprenta.es/pegatinas-personalizadas/pegatinas-redondas-95.html?___SID=U
250 pegatinas a 72€

Dejo esta información para que se tomen las decisiones pertinentes.

**Comment by Siotma** [comment]
Gracias por la info! @wenflehecanario

**Comment by David-Estevez** [comment]
@wenflehecanario  ¿Y temas de envíos / aduanas? ¿Cuál sale mejor de precio contando con envío+aduana(si las hay)+ IVA (importante)?

**Comment by wenflehecanario** [comment]
@David-Estevez Como se había acordado, mirare en una imprenta en Canarias que nos va a salir mucho más barato sin contar que nos ahorramos el IVA.

**Comment by wenflehecanario** [comment]
Hoy procederé a la ruta de precios para camisetas y pegatinas en Canarias, cuando tenga una lista la subiré 😉

**Comment by JorFru** [comment]
@diegogarciax2 se va a encargar de ello

**Comment by wenflehecanario** [comment]
Me encanta esta respuesta 1 año depués jajaja

**Comment by DiegoGarciaX2** [comment]
He encontrado un presupuesto de 30 euros aprox para 100 pegatinas de 38mm en la pagina que a pasado wen. Son muy pequeñas o os parece bien?

**Comment by David-Estevez** [comment]
Yo creo que están bien, pero que opinen los que llevan el portátil empapelado de pegatinas :smile:

**Comment by JorFru** [comment]
Yo las pediría de 50 o 55mm

**Comment by JorFru** [comment]
![photo_2019-09-16_15-22-27](https://user-images.githubusercontent.com/11017088/64961465-dd894b80-d895-11e9-9080-67b03ccc4fef.jpg)
50mm es el tamaño que me parece óptimo

**Comment by DiegoGarciaX2** [comment]
![image](https://user-images.githubusercontent.com/26299768/64962697-29d58b00-d898-11e9-9a03-0306c497606b.png)

**Comment by DiegoGarciaX2** [comment]
Ya estan pedidas

**Comment by David-Estevez** [comment]
qué eficiciencia! :clap: :clap: :clap:

**Comment by JorFru** [comment]
Votación en curso para decidir quién paga las pegatinas.
Propongo dos opciones.
1. La asociación las regala. ASROB pierde 45.46€
2. La asociación las vende para no perder dinero. Habilito la posibilidad de venderlas un poco más caro de lo que costaron no sólo para ganar dinero, que no es el objetivo, si no para recuperar la inversión más rápido. Ya que si las ponemos a 0.50€ posiblemente tardemos un año o más en vender las 100 y recuperar el dinero. Si las ponemos a 1€ tardaremos poco tiempo en recuperar el dinero, y luego vendrá bien ese extra que se puede ganar.


https://forms.gle/waRzE7fBiqZACWyV9

**Comment by GioSunrider** [comment]
Corrígeme, las pegatinas, ¿sí o sí las paga ASROB correcto? Y en función de eso las opciones anteriores, ¿correcto?

**Comment by JorFru** [comment]
ASROB haría el colchón para que nadie se quede sin su dinero.
Ya que es posible que no se liquiden todas en un periodo razonable.

**Comment by DiegoGarciaX2** [comment]
Yo las pondria a 50 cent. Que a nadie le va a costar nada pagarlo y creo que tambien es mas justo, para que nadie se lleve pegatinas de mas

**Comment by GioSunrider** [comment]
Guay, pues añadiría la tercera opción de Diego aunque la opción 2 me parece justa! Así tenemos dinerito para necesidades (a.k.a. una estantería 🙄)

**Comment by JorFru** [comment]
La votación se ha cerrado
La conclusión ha sido:
Piggy compra la totalidad de las pegatinas por 45.46€
Y las vende cada una a 1€. Dejándose el dinero en metálico en la hucha.

![imagen](https://user-images.githubusercontent.com/11017088/66841439-fefb5700-ef69-11e9-936f-ad83f5473c40.png)

**Comment by JorFru** [comment]
Por ahora el dinero de las pegatinas lo he adelantado yo.
Mi idea es esperar a que Piggy se llene con 45.46€ y una vez estén reunidos, cogerlo.
A partir de ese momento las pegatinas estarán pagadas y yo conforme.

**Comment by JorFru** [comment]
Que no se os olvide meter el eurillo en Piggy por cada pegatina.
