### ISSUE TITLE
Redistribución del espacio de trabajo

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/actas#139]
Debido a que necesitamos  montar en Printer One una estanteria como se menciona en [#50](https://github.com/asrob-uc3m/impresoras-asrob/issues/50) se propone una reorganizacion del espacio de tabajo de la nave.
En el proceso se propone retirar de su lugar el escenario verde de manera que tambien exista la posibilidad de modificarlo para que sea montable y desmontable para usos puntuales. En caso que no se demuestre su utilidad se propone su eliminacion.
Para la colocacion de la estanteria se propone el siguiente esquema de uso.

![photo5944836815225728222](https://user-images.githubusercontent.com/10605193/38695041-7b5d1478-3e8b-11e8-924a-10b17f528d26.jpg)

En el dibujo de muestra el espacio designado para todo pegado a la pared. Con la aclaración de que el PC de RPi propuesta de @David-Estevez que seria conectar una RPi a una de las pantallas. Le invoco para los casos de uso de esta idea.

Para la reorganización de la nave, se propone mover los armarios pegados a la lona, y seguidamente colocar la mesa grande de 1'60 m como puesto de soldadura permanente.

Donde actualmente se encuentra el armario 2, colgar en horizontal la pizarra grande, y debajo situar la vitrina para su uso. 

Donde actualmente se encuentra la vitrina y la "Ñapa-cade" colgar en vertical la pizarra pequeña y debajo guardar la mesa de air hockey.

Donde actualmente se encuentra el armario 1, colocar todos los tatamis y circuitos siguelineas que Robofactory usa pegados a la pared.

Propongo que para esta issue el siguiente procedimiento:

- [x] Discusión de opciones y exposición de opiniones.
- [x] Selección de Opciones.
- [x] Votación.
- [x] Establecer un día para realizar los cambios de ser favorable.

**Comment by David-Estevez** [comment]
A mi me parece guay todo lo que se comenta.

> En el dibujo de muestra el espacio designado para todo pegado a la pared. Con la aclaración de que el PC de RPi propuesta de @David-Estevez que seria conectar una RPi a una de las pantallas. Le invoco para los casos de uso de esta idea.

Estos PCs serían RPi3 con programas básicos (arduino ide, platformio, freecad, cosas de impresoras 3D) para que la gente que venga a las reuniones sin PC (que nos ha pasado más de una vez) pueda trabajar. Además, en eventos se podrían sacar junto a los mandos de recreativa como máquinas arcade.

**Comment by JorFru** [comment]
¿Por qué usar una RPi cuando tenemos dos torres de mediana calidad?
Yo diría de poner un monitor a la Pi que gestiona las impresoras.
Pero un ordenador normal al lado, para cualquier tarea de programación, y
además se puede complementar con Mame para videojugar con los nuevos mandos.

Siguiendo mi idea quedaría por determinar (ya por curiosidad) si es más
cómodo slicear en el ordenador normal y mandarlo al servidor de impresión
usando Octoprint, o bien slicear directamente con el servidor de impresión.
Si alguien ha descargado ficheros y slicear modelos en RPi que se
manifieste diciendo si es o no es práctico.

**Comment by jgvictores** [comment]
Todo lo que sea mejorar el espacio, guai tb.

Algunas consideraciones:
- Es bastante obvio que si se desmonta lo verde, acabaremos no usándolo. Pero bueno, por dejarlo un tiempo prudencial tampoco pasa nada.
- Parece una propuesta impresora-céntrica, lo cual no es malo, y se soluciona con el siguiente punto.
- Lo que va a ser siempre de interés general es la distribución de mesas y sillas. :smile: ¿Podríais hacer porfa un diagrama (aunque sea a mano como la anterior) que contemple la redistribución propuesta de todo el espacio, mesas y sillas incluidas?

**Comment by daavm** [comment]
> ¿Por qué usar una RPi cuando tenemos dos torres de mediana calidad?

Sería cuestión de ver si una RPi es mejor o no que las torres y con eso decidir qué usar

> Es bastante obvio que si se desmonta lo verde, acabaremos no usándolo. Pero bueno, por dejarlo un tiempo prudencial tampoco pasa nada.

Creo recordar que lo de hacerlo lo antes posible era por no llegar a juntarnos con exámenes y verano.

**Comment by jgvictores** [comment]
Mini-comentario respecto al uso de RPi(s): Los PCs son fáciles de anclar, o por lo menos no es tan habitual que alguien se los lleve sin querer. ¿Está contemplado esto para RPi(s)?

**Comment by David-Estevez** [comment]
1. **RPi**
* Ventajas frente a  PC (desde mi punto de vista):
  * No estoy seguro de que las torres sean mejor que una RPi3 (habría que mirarlo)
  * Son más pequeñas, nos "quitan" menos espacio que las torres.
  * Es más fácil crear una imagen del SO y mantenerla / clonarla / quemarla porque (las imágenes) suelen ser pequeñas y las SDs más manejables que discos duros.

* Evitar "descuidos": es imposible evitar que alguien se las lleve si le pone suficiente empeño (igual que es imposible evitar que alguien desguace una impresora 3D y se lleve la placa, por ejemplo), pero la idea era fijarlas a la parte trasera del monitor para que ocupasen el menor espacio posible y no estuviesen muy a la vista.

2. **Cosa verde**
* Aclaración:
La  idea detrás de deshacernos de la cosa verde es que actualmente (y desde que se hacían entrenamientos para competiciones de humanoides) no se ha usado apenas y ocupa mucho espacio. Esto hasta ahora ha estado bien, porque "marcaba el territorio", pero hemos crecido en proyectos y material y ahora mismo nos viene mejor usar ese espacio para cosas útiles. Tanto para impresoras 3D, como para circuitos y entornos de competición para los robots que estamos desarrollando en RoboFactory.

* 
  > Es bastante obvio que si se desmonta lo verde, acabaremos no usándolo. Pero bueno, por dejarlo un tiempo prudencial tampoco pasa nada.

  La idea original era tirarlo (o reciclarlo). La única motivación que tenemos para mantenerlo es que nos habéis transmitido desde Robot Devastation vuestra intención de darle uso, por lo que estamos intentando encontrar una situación que satisfaga a todos (que no ocupe tanto espacio y se pueda recoger, y que vosotros podáis usarlo). En ese sentido estamos abiertos tanto a sugerencias por vuestra parte que mejoren la "portabilidad" y la "usabilidad" como a la posibilidad de que finalmente decidáis que es mucho lío y no queráis mantenerlo. 

Respecto a los tiempos, el circuito ha estado ahí bastantes años, por lo que añadir más tiempo "a ver si alguien lo usa" no tiene, en mi opinión personal, mucho sentido.

**Comment by jgvictores** [comment]
`Re (cosa verde)`: Nah, vamos "back to the primitive". La idea original de RD era que el mundo fuese el escenario.

`Algo que sigo considerando bueno (para que si hay votación, se sepa exactamente qué se está votando)`: ¿Podría alguien hacer porfa un diagrama (aunque sea a mano como la anterior) que contemple la redistribución propuesta de todo el espacio, mesas y sillas incluidas,?

**Comment by David-Estevez** [comment]
@GioSunrider  Puedes hacer un croquis de cómo quedaría todo después del cambio?

**Comment by GioSunrider** [comment]
Si, sin problema.

**Comment by David-Estevez** [comment]
Gracias tío!

**Comment by GioSunrider** [comment]
Esta seria la colocación, si he contado las mesas bien, la mesa 5 que aparece en el dibujo, también se podría colocar en L con la mesa 4.

![37f0b052-d2e6-4ac0-9598-982999303057](https://user-images.githubusercontent.com/10605193/38747727-11abbbe4-3f4c-11e8-847e-19dc5b8d7722.jpg)

**Comment by daavm** [comment]
Yo la mesa 5 la suprimiría, pero en general me parece bien :)

**Comment by jgvictores** [comment]
IMHO, ganar una mesa está genial.

**Comment by daavm** [comment]
La suprimiría porque no me parece que haya espacio para tanta mesa y silla, aunque sé que habéis tomado medidas, pero es cuestión de verlo en la vida real

**Comment by David-Estevez** [comment]
Las mesas son un recurso escaso y yo optaría por mantenerlas siempre que sea viable. Quizá uniría las mesas 4 y 5 o en La o en cuadrado para tener un espacio de trabajo me amplio sin necesidad de tanta silla alrededor.

**Comment by GioSunrider** [comment]
A mi la idea de mesa grande me mola, pero claro hay que ver luego a la hora de montar. Viendo que os ha gustado la idea, propongo dejar hasta el domingo para nuevas propuestas y el domingo abrir la votación, para así esta semana poder empezar a colocar todo ya que nos urge un poco antes de que empiece temporada de exámenes

**Comment by JorFru** [comment]
Añado ideas sueltas:

Reorganizar el espacio de ASROB dará una imagen sobre nosotros de que somos responsables, organizados y limpios.
Tener una piscina que durante un año se ha usado con el único fin de trastero de retales de madera, metal, ordenadores desguazados, periféricos de ordenador en desuso tirados... no da una buena imagen de nosotros.

Yo creo que tener nuestro espacio organizado podrá permitir que en un futuro consigamos concesiones por parte del departamento. Muy posiblemente no nos concedan nada nunca, pero desde luego con una mala imagen no se avanza.

Todas las ideas que se han propuesto me parecen ideales, porque generan espacios que son fáciles de limpiar (y fácil de que parezcan ordenados), las pizarras quedan útiles y lo que más me gusta de todo: una mesa para soldadura y trabajos de electrónica (actualmente es necesario mover el osciloscopio y la fuente para poder utilizarlos).

**Comment by Siotma** [comment]
Creo que este nuevo enfoque para el espacio de trabajo mejorará mucho la experiencia de usuario de los miembros, presentes y futuros, de la asociación. También estoy de acuerdo con @JorFru en que dará mejor imagen. Para mi la clave fundamental es que va a ser una distribución más funcional, que se adapta mejor a las necesidades de la asociación y que genera menos espacios muertos.

Solamente tengo una idea que aportar de cara a la estantería de impresoras:

Lo he estado pensando y la verdad es que no me cabe mucho en la cabeza la idea de meter la TronXY "dentro de la estantería". Esta es una decisión que complica la selección de la estantería porque obliga a unos tamaños (de fondo) difíciles de encontrar de forma comercial. En la [idea original](https://github.com/asrob-uc3m/impresoras-asrob/issues/50) yo planteaba que el ancho de la estantería fuera un metro. Si ponemos la TronXY en una balda, ya no nos cabe otra impresora al lado a no ser que hagamos toda la estantería más ancha (he visto que propones 1,40m). En resumen, por el tamaño y la forma que tiene, la TronXY es una impresora que obliga a modificar toda la estantería. Desde mi punto de vista, puede que no necesite de estantería.

Propongo algunas alternativas de ubicación que simplificarían el montaje de esa zona del espacio de trabajo:

1. Poner la TronXY en el suelo, eliminando la balda inferior de la estantería. De esta formar la TronXY queda integrada en la estantería pero no hace falta buscar baldas de 70 mm de ancho porque el suelo es todo lo ancho que uno quiera. Desventajas: a) sobresale y puede recibir patadas; b) en el suelo se va a llenar de polvo; c) habría que cambiar la posición de la controladora y la pantalla para que fueran más accesibles sin que uno se tenga que agachar.

2. Poner la TronXY sobre la mesa anexa a la estantería. Esta mesa tiene 80cm de fondo por lo que la TronXY cabe perfectamente. Desventaja: perdemos espacio para uno de los PCs que se planteaba colocar ahí.

3. En caso de que se siga prefiriendo ponerla en la estantería, he encontrado [este fabricante](https://www.ractem.es/) que ofrece estanterías a buen precio y con medidas que nos pueden interesar. [Este modelo ](https://www.ractem.es/estanterias-media-carga/81-estanteria-c-max-200.html#/Color-Azul%20y%20gris/Niveles-4/Balda-Melamina/ancho-1000_mm/ancho-1000_mm/capacidad_de_carga-200_kg/fondo-700_mm/fondo-700_mm/alto-2000_mm/alto-2000_mm) concretamente está disponible en medidas válidas para nuestras necesidades. Si cogemos el ancho de 1500 mm incluso podrían caber 3 impresoras de las pequeñas en la misma balda en el futuro.

Desde mi punto de vista la opción 1 no es realmente válida porque se pone en peligro la integridad de la impresora. La 2 es más conservadora, y la 3 es más ambiciosa. Conociéndoos, creo que os va a gustar la opción 3. Además, tiene portes gratis :wink:

**Comment by GioSunrider** [comment]
Yo veo la opción 3 dado que así quedan menos espacios muertos, somos ambiciosos! No, solo me baso por tamaño, pero aún así la veo la mejor.

**Comment by JorFru** [comment]
Hasta ahora la piscina "marcaba territorio", pero ese cacho de nuestro territorio estaba un poco desguazado y con apariencia prescindible.

En cualquier momento podría venir el departamento y plantarnos un puente grúa en esos 8m² porque: "es que sólo los utilizáis para guardar chatarra, es la función que hemos visto que ha tenido el último año y vemos que no lo dais uso".

**Comment by JorFru** [comment]
Sobre la idea 3, @Siotma 
¿Sería comprar una estantería de fondo de 60? 70cm?
Molaría poner tres máquinas en una balda a la altura de los brazos, y la Tronxy en una balda que empiece a la altura de las rodillas. Como la tronxy trabaja principalmente imprimiendo en la parte de arriba, nunca quedará demasiado baja para que sea "serviceable" de forma cómoda.
Y al lado de la Tronxy nuesta próxima impresora (por favor que no sea otra Prusa i3 xD)

Si la estantería va a ser de ese fondo vamos a tener un mostrenco bastante interesante, pero me mola la idea de que estén las impresoras centralizadas y la mesa entera disponible.
Yo voto por 3, creo.

**Comment by daavm** [comment]
Yo el mayor inconveniente que le veo a la estantería "grande" es todo el espacio libre que nos va a quedar en las baldas superior e inferior, a parte de eso no me parece mala idea. Mi voto va para la 2!

**Comment by jgvictores** [comment]
> todo el espacio libre que nos va a quedar en las baldas superior e inferior

IMHO, no hay nada en contra de un futuro con más impresoras, alguna posiblemente con las dimensiones de la Tronxy... no?

**Comment by GioSunrider** [comment]
No, no hay nada en contra, además que esas baldas se pueden poner como "puertas" y utilizarlas de almacen.

**Comment by GioSunrider** [comment]
La votación seguirá abierta hasta mañana a las 15:00.

**Comment by Siotma** [comment]
> ¿Sería comprar una estantería de fondo de 60? 70cm?

En la opción 3, la única medida compatible con la TronXY son 70cm.

La opción 3 ha tomado fuerza por el hecho de poder colocar hasta 3 impresoras por balda, lo que implicaría coger el modelo de 1500mm ancho X 2000mm alto X 700mm fondo. Tal vez se podría valorar coger 2200mm de alto si hiciera falta.

Yo voy a votar por la opción 3 también, aunque pondría la condición de que antes de comprar la estantería definitiva se hagan las comprobaciones necesarias en cuanto a medidas para no cagarla.

**Comment by GioSunrider** [comment]
Estoy de acuerdo con la ultima propuesta, se puede valorar la altura, aunque tener en cuenta a la hora del alcance de los 220cm es limitado para algunos.

**Comment by GioSunrider** [comment]
Se ha cerrado la votacion con resultado faborable a los cambios propuestos como muestra el siguiente grafico.

![captura](https://user-images.githubusercontent.com/10605193/38941615-3a07413c-432d-11e8-8864-1f44a4a5e408.JPG)

En cuanto a la opcion que @Siotma propuso se ha optado por la opcion 3, es decir, la estanteria grande. El resultado se puede ver en el siguiente grafico:

![captura2](https://user-images.githubusercontent.com/10605193/38941680-61217558-432d-11e8-8058-a631047341ea.JPG)

Por ultimo el destino del escenario verde, el resultado final ha sido por una mayoria el tirarlo, como muestra el ultimo grafico:

![captura3](https://user-images.githubusercontent.com/10605193/38941747-83aeb6d0-432d-11e8-8327-cd96fabb5854.JPG)

Por ello doy por completado el proceso de votacion solo queda quedar un dia todos para realizar todas las tareas que ello implica. ¿Que metodo seguimos? ¿Doodle?

**Comment by GioSunrider** [comment]
IMHO, lo primero casi seria desmontarlo y reorganizar todo, la estantería seria lo ultimo en incluir.

**Comment by David-Estevez** [comment]
Yo además añadiría la condición de que no haya clase ese día en la nave, para molestar lo mínimo posible.

**Comment by GioSunrider** [comment]
Creo que eso va a ser prácticamente imposible, aún así mañana es clase hasta las 7, de 7 a 9 son horarios extras para que hagan los proyectos, así que en esas horas podemos sacar la basura sin molestar.

**Comment by David-Estevez** [comment]
Pero entonces esto se va a hacer hoy? 

De todas formas puedo preguntar a ver si hay algún día en el que no tengan clase de auto.

**Comment by David-Estevez** [comment]
Me dicen que clase de auto sólo hay jueves y viernes, así que lunes, martes y miércoles en principio no molestaríamos.

**Comment by JorFru** [comment]
Este es el estado actual de nuestro espacio. Buen trabajo chicos!
![photo_2018-04-21_13-22-23](https://user-images.githubusercontent.com/11017088/39083615-3733cb74-4567-11e8-9165-14dfa3511481.jpg)

Este es el estado actual de la zona de impresoras, donde se va a desarrollar el proyecto [granja de impresoras](https://github.com/asrob-uc3m/impresoras-asrob/issues/50)
En la próxima semana aparecerá el nuevo mobiliario y lo dejaremos todo muy bonico.
![photo_2018-04-21_13-23-03](https://user-images.githubusercontent.com/11017088/39083616-3a27945a-4567-11e8-959b-dfd955abbc2a.jpg)

**Comment by Siotma** [comment]
Después de haberlo pensado un tiempo, creo que sería más seguro arrinconar la granja de impresoras junto a la columna y dejar la mesa de los PCs pegada al armario de docencia: o sea, intercambiar mesa y estantería. 

Digo esto porque los chavales que están en clase tienden a dejar sus cosas donde pillan, y no me gustaría ver abrigos, cajas o cables en las baldas de la estantería simplemente porque "están a mano".

Al arrinconar las impresoras, también se consigue quitarlas del paso por lo que se reduce la posibilidad de que alguien pueda chocarse con la estantería o tocar alguna impresora sin querer y hacerse daño o estropear algo.

Lo planteo para ver qué os parece, creo que de primeras es razonable, aunque luego a la hora de montar la estantería habrá que ver cómo queda.

**Comment by GioSunrider** [comment]
Tambien hay que tener en cuenta la accesibilidad, una de las principales razones de no ponerlo ahi era no tener que "saltar" mesas. Aun asi me parece adecuado mirarlo el dia de montaje.

**Comment by GioSunrider** [comment]
En la pasada reunión se instalo la estantería a la Derecha. Adjunto foto del resultado. 

![photo6026288237179415797](https://user-images.githubusercontent.com/10605193/40054853-7f7b7534-5846-11e8-9f14-b2f15f5f0d2d.jpg)

**Comment by Siotma** [comment]
Queda algo por hacer dentro del contexto de esta Issue?

**Comment by GioSunrider** [comment]
Creo que podemos proceder a cerrarl, la mantenia abierta en caso de un cambio de ultima hora.
