### ISSUE TITLE
Enviar datos de la cuenta a los señores del IEEE

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#14]
Desde el IEEE nos piden datos de la cuenta para ingresar los 127€ que nos corresponden a nuestra Student Branch. Han dado de fecha límite el día 15 de Mayo.

Extraído del email del IEEE (está en la lista de Miembros Activos de ASROB):

> Hola a todos,
> 
> Este año por fin hemos conseguido que la asignación del IEEE a cada rama de estudiantes nos la envíen por transferencia a la cuenta de la sección para que nosotros la repartamos.
> 
> Es una solución que os evitará los problemas de cobrar los cheques y las altas comisiones de los bancos. 
> 
> Esta lista no es el mejor sitio para tratar esto, es mucho más adecuada la comisión de colaboración en la que hay un miembro de cada rama pero tenemos el problema de que algunas ramas no tienen ninguna persona asignada. Por favor, nombrad a alguien para que podáis estar al tanto de todo lo que hacemos. En concreto no hay nadie de las ramas de Cartagena, UNED y Oviedo.
> 
> Os pongo más abajo una lista de la cantidad total que hemos recibido y el detalle de cada rama. Como sabéis, el total depende del número de miembros. Son $2 USD por miembro más $50 USD si la rama tiene menos de 50 miembros ó 100 euros si la rama tiene más de $50 USD.
> 
> Por favor, necesito que me proporcionéis los datos bancarios de vuestras ramas: IBAN y titular de la cuenta. 
> 
> Enviádmelo con copia a José Miguel. No lo enviéis a la lista.
> 
> Cuando tenga todas le pasaré los datos al tesorero de la sección para que haga las transferencias correspondientes.
> 
> Un saludo.

Asigno al tesorero @Rodriwp para que se haga cargo del tema.

**Comment by Rodriwp** [comment]
La información ya ha sido enviada.
