### ISSUE TITLE
Nuevo Responsable de Impresoras

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/actas#140]
Debido a que el grupo ha aumentado de tamaño, y dado que @Siotma no puede asistir al completo a las reuniones de Printer One.
Se propone que haya dos responsables de las impresoras, dada la necesidad de manipular las impresoras y sacarlas de sus cadenas. Por lo que habría que hacer un nuevo juego de llaves de los candados de las impresoras.
¿Que método habría que seguir?

**Comment by David-Estevez** [comment]
Sobre esto no hay nada escrito todavía, así que estamos abiertos a propuestas...

**Comment by GioSunrider** [comment]
La propuesta sería hacer un segundo responsable, por lo que un segundo juego de llaves de Impresoras, para facilitar la liberacion de las impresoras cuando sea necesario.

**Comment by David-Estevez** [comment]
Y qué os parecería hacer que el responsable de impresoras y el responsable de Printer One tuviesen llaves. 

Teniendo en cuenta que os dedicáis a jugar con las impresoras vería lógico que tuviéseis al menos una llave.

**Comment by David-Estevez** [comment]
A mi esa idea me gusta. Vamos a dar unos días para ver si surgen más ideas /  opiniones y si no surge nada creamos la votación para esto.

**Comment by GioSunrider** [comment]
Perfecto 😊

**Comment by Siotma** [comment]
La idea de que el responsable de Printer One tenga llave de las impresoras es muy lógica, y muy útil. 

Actualmente, ostento el cargo de responsable de impresoras, pero responsables de Printer One somos @GioSunrider y yo.

Veo con buenos ojos que se haga una nueva llave de las impresoras, siempre que este hecho quede debidamente documentado y se actualicen en caso necesario los estatutos.

**Comment by GioSunrider** [comment]
Votacion: https://goo.gl/forms/jlWY7pCTRUata22A3

**Comment by GioSunrider** [comment]
La votación seguirá abierta hasta mañana a las 15:00.

**Comment by GioSunrider** [comment]
El resultado de la votación ha sido favorable con el siguiente grafico: 

![sin titulo](https://user-images.githubusercontent.com/10605193/38873628-85dfed5c-4256-11e8-8e8d-16d6765e4f25.jpg)

Por lo que invoco a @jgvictores y a @Siotma para ver como se gestiona la nueva copia de las llaves.

**Comment by David-Estevez** [comment]
Siendo llaves de candado, igual es complicado hacer una copia... alguien sabe si el manojo único (:ring: ) mencionado en #65 contenía más de una llave para el candado?

**Comment by Siotma** [comment]
El manojo único tiene una sola llave de los candados, y yo soy partidario de que se quede ahí.

El pasado jueves fui a una ferretería y me hicieron sin problemas una copia de la llave, que ya entregué a @GioSunrider a fecha 19 de abril.

Para buscar la manera de hacer oficial esto, he abierto una discusión en https://github.com/asrob-uc3m/estatutos/issues/18 .

Documentación gráfica de la llave y la factura:

![19_04_2018_new_printers_key](https://user-images.githubusercontent.com/6171234/39084130-98ac203c-4570-11e8-890d-8ab5b80424cd.jpg)

![19_04_2018_new_printers_key_invoice](https://user-images.githubusercontent.com/6171234/39084131-9a70893a-4570-11e8-9edc-f0f1d54932e0.jpg)

Solicito reembolso con cargo a la Asociación.

**Comment by jgvictores** [comment]
> Solicito reembolso con cargo a la Asociación.

Porfa di cuándo es la siguiente reunión donde nos podamos cruzar, no tengo problema con reembolsártelo en calidad de tesorero en funciones.

**Comment by Siotma** [comment]
Gracias! Estaré el próximo jueves en la nave desde las 18:30 hasta las 21:00.

**Comment by Siotma** [comment]
Pago recibido ayer por la tarde de @jgvictores . ACK

**Comment by jgvictores** [comment]
Actualizadas cuentas en [zona restringida wiki](http://asrob.uc3m.es/index.php?title=Cuentas_ASROB&type=revision&diff=12896&oldid=12893).
