### ISSUE TITLE
La rama ASROB-UAVs ha dejado de ser grupo activo.

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#144]
Hola!
He sido de los últimos usuarios activos de la rama UAVs, y he presenciado su declive.
No soy el responsable de la rama, lo es @andrespy 

Esta rama no cumple con los estatutos: principalmente incumple el punto 1: "Sus miembros se reúnen asiduamente (de forma presencial no remota, mínimo una vez por semana)" y todos trabajan con todos propongo su archivo y mover todo a la sección "antiguos grupos de trabajo"

Se debería de proceder a archivar esta rama y moverla a "grupos inactivos". De esta manera conservamos la información en la web (en un lugar más escondido, como es natural) mientras damos más visibilidad a los proyectos nuevos, que se lo merecen.

Andrés, confirma lo que estoy diciendo para que podamos archivar la rama.

**Comment by David-Estevez** [comment]
Pasos a dar:

* [ ] Dar de baja en la web
* [ ] Dar de baja en la wiki
* [ ] Material de UAVs en el armario: 
     * [ ] Qué material es de UAVs
     * [ ] Qué material es de los miembros
     * [ ] Desalojo del material de los miembros

**Comment by JorFru** [comment]
Bloqueado por:
Exámenes

Necesitaremos un mes largo y entonces realizaremos estas acciones.

**Comment by andrespy** [comment]
Ok, yo vuelvo del erasmus en junio asi que me pasare a ver que cosas son mias y las recogeré

**Comment by JavierIH** [comment]
La reactivamos porfa?

**Comment by JorFru** [comment]
La rama ASROB-UAVs queda reactivada.
[Aquí](https://github.com/asrob-uc3m/FENIX/blob/master/Acta%20Reunion%2004-10-2018%20.txt) se puede consultar el acta de la reunión que reúne los cambios que ha sufrido la rama y los próximos talleres, miembros interesados, **nuevo responsable de grupo**.

Cerro issue.

**Comment by Siotma** [comment]
Fantástico! Bien hecho chavales!

La información quedaría más accesible en la Wiki del repo: https://github.com/asrob-uc3m/FENIX/wiki
