### ISSUE TITLE
Camisetas de ASROB para los nuevos

### ISSUE THREAD

**Issue by madelgj** [asrob-uc3m/actas#149]
Necesitamos camisetas oficiales para poder representar a la asociacion en la semana de asociaciones, la feria y demás (campamento!).
Tenéis la info de donde conseguisteis las vuestras y eso?

**Comment by JorFru** [comment]
Se pidieron a la tienda PiP, en la Calle Butarque 14.
Los archivos necesarios para volverlas a imprimir están subidos en GitHub.

Yo me apunto con una! Que no tengo...

**Comment by JorFru** [comment]
Me asigno para la compra.
Condiciones: dinero por adelantado.

**Comment by David-Estevez** [comment]
No quiero abrir la caja de pandora, pero... ¿no sería mejor que todos tuviésemos las camisetas del mismo color? Así se nos reconocería mejor en eventos....

Yo diría que negro (como la última vez) o rojo, para no tener que llevar las que nos da África :wink:

**Comment by JorFru** [comment]
Hoy he ido al PiP, donde se pidieron el año pasado, he refrescado la memoria a mi amigo de allí, y hemos rescatado el diseño con las mejoras que hicimos para el calado interior y el borde paralelo blanco y todas esas chuminadas que son importantes a nivel diseño. Y en la factura, para 11 camisetas, se nos cobró 93.50€, por lo tanto salieron a 8.50€ cada una.

¿Y para este año? me ha contado que ha subido el precio del textil y que este año son a 9.50€, que no puede hacer nada, ya que él sigue cobrando lo mismo por la estampación. Y me ha dicho que me puede conseguir el precio de 9.50€ si llegamos a 15 unidades. Si pedimos menos el precio subirá lo más posible.
Cambiar colores no sube el precio, elegir talla tampoco.

[Lo que ha dicho David](https://github.com/asrob-uc3m/actas/issues/149#issuecomment-420200292) me parece buena idea pero yo creo que no hace falta ponernos todos de acuerdo en esto. Si no simplemente dejar que cada uno elija el color de su camiseta y si no la elige negra quedará marcado de otro color y por lo tanto fácilmente reconocible como el que traicionó la tradición de las camisetas negras.

Voy a facilitaros las cosas a vosotros y a mí también, ya que necesito saber el número y las tallas para hacer el pedido (y tristemente adelantar el 50%), a si que levanto la mano con el tema "dinero antes de apuntarte en la tabla".
Y recogeré el dinero en el momento de entregar la camiseta.

**Comment by GioSunrider** [comment]
@JorFru no tendrás por ahí la guía de tallas de las camisetas? A día de hoy cada maldita tienda tiene la suya y es un poco lioso a la hora de hacer pedidos.

**Comment by JorFru** [comment]
@GioSunrider te sugiero mirar la sheet donde se pidieron las del año pasado y preguntes a sus propietarios qué tallas dan. Por ejemplo @Kfrodicio, que tiene tu tamaño, aproximadamente.

**Comment by GioSunrider** [comment]
Perfecto, muchas gracias. Os adjunto una guía de tallas para que también os guieis.

![img-20180911-wa0005](https://user-images.githubusercontent.com/10605193/45409262-ff426800-b66e-11e8-9472-9e552614b129.jpg)

**Comment by JorFru** [comment]
Ya hemos llegado a 15 camisetas pedidas!
Vamos a esperar hasta el día 24, que la fecha que puse en su momento.

Gracias

**Comment by JorFru** [comment]
Cerrado el periodo para apuntarse.
Hoy voy a hacer el pedido y se va a pedir esto:
![imagen](https://user-images.githubusercontent.com/11017088/46003475-e4311880-c0b0-11e8-947f-09f048b898ef.png)

**Comment by JorFru** [comment]
Pedidas

**Comment by JorFru** [comment]
Las camisetas llegarán el día 5 de octubre

**Comment by VentressAsajj** [comment]
el pago de las camisetas? creo que no he pagado

**Comment by JorFru** [comment]
Las camisetas se pagan en el momento de la entrega.
Entrega a partir del día 5 de octubre.

**Comment by JorFru** [comment]
Esto está hecho no?
Cerrando.

Gracias por vuestra participación.
Maldición gitana a los que pidieron la camiseta blanca.
