### ISSUE TITLE
Cambio de llaves 

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#15]
Ya tenemos un segundo armario que en estos momentos se encuentra vacio. Este segundo armario sera para el material común, las herramientas etc. 

Junto con este movimiento se ha procedido al cambio del candado del primer armario. Solo se necesita llaves de este primer armario, puesto que la llave del segundo(la del candado y la grande) estarán en el interior de este primer armario.
Se guardara un manojo de llaves con una llave de cada candado (impresoras, armario 1 y armario 2) en un lugar seguro. 

Cada rama activa tiene derecho a tener hasta 2 llaves que se solicitaran al tesorero y tendra el coste de 1,20 euros. No se podran hacer copias adicionales de esas llaves. Se guardara en el inventario una relación con las llaves y los guardianes de las mismas.

El coste de la operación asciende a 8,40 euros

- Candado armario 2: 4,20 euros
- Candado armario 1: 3 euros
- Chapa metalica armario. 1,20 euros

Esta lista de gastos se paga con el dinero de piggy

**Comment by andrespy** [comment]
👍

**Comment by Rodriwp** [comment]
Falta MYOD por recibir su llave

**Comment by Siotma** [comment]
La llave de MYOD la puedo recoger yo desde hoy, en cualquier momento. Decidme cuándo y dónde.

**Comment by David-Estevez** [comment]
¿Están recogidas ya todas las llaves?

**Comment by Rodriwp** [comment]
Todas entregadas
