### ISSUE TITLE
Charla Semana de Asociaciones

### ISSUE THREAD

**Issue by madelgj** [asrob-uc3m/actas#150]
Como nosotros no somos oradores profesionales pensamos que lo mejor es hablar un poco más informal, contar nuestra experiencia y que hablemos varios. También hemos pensado incluir un video (bloopers).
Lo único, yo vuelvo a Madrid el 30 de Septiembre así que estaré para la charla, pero no creo que pueda ayudar mucho a montarla a no ser que se monte ya.

**Comment by David-Estevez** [comment]
Tranquilos, salvo algunas asociaciones que se viene muy arriba, todas las charlas suelen darlas gente de las asociaciones, como vosotros.

Para montarla otros años nos lo hemos preparado lo mínimo, En el drive de ASROB tenéis las diapositivas de charlas anteriores para inspiraros, si no tenéis acceso/no sabéis como acceder a ellas pedidlo.

**Comment by wenflehecanario** [comment]
Solicito acceso legal al drive de ASROB.
Mi gmail es: 100383105 y ya el resto lo sabes ;D

**Comment by madelgj** [comment]
Yo tmb quiero acceso al Drive

**Comment by jgvictores** [comment]
Compartí `Charlas y talleres` y `Multimedia` con `100383105`.

**Comment by David-Estevez** [comment]
La charla la dará una persona de cada rama, y hay que quedar con tiempo.

**Comment by GioSunrider** [comment]
Cierro la issue dado que al final no se realizo ninguna charla en la semana de asociaciones.
