### ISSUE TITLE
Dinero para camisetas y pegatinas ASROB

### ISSUE THREAD

**Issue by wenflehecanario** [asrob-uc3m/actas#151]
Después de que los estudiantes de nuevo ingreso pidieran pegatinas y camisetas de la asociación tan maravillosa en la que estamos, en las Issues #136 y #149 veo pertinente lanzar una propuesta que involucra a los integrantes de la asociación, y a ciertos grupos de la misma.

La idea consiste en hacer piezas impresas en 3D y venderlas un día en el retiro para reunir dinero y comprar que PLA que se habrá gastado.

Lanzo la idea para que penséis que podemos imprimir que los frikis del retiro nos compren sin dudarlo. Principalmente se me ha ocurrido hacer figuras de videojuegos famosos, que eso siempre triunfa.

**Comment by David-Estevez** [comment]
Cerrada como inválida/inactiva (reunión 10/09/2018)
