### ISSUE TITLE
Baja como responsable de Printer One

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/actas#153]
Con esta issue presento mi baja como responsable de Printer One, que se hará efectiva en la próxima reunión del grupo de trabajo, en la que se realizará la votación para elegir al nuevo responsable. Entre las atribuciones de este cargo están:

- Participar en la organización horizontal de la Asociación, sirviendo de medio de contacto con otros grupos y con la junta directiva para tomar decisiones y recibir informaciones que nos afectan a todos los grupos.
- Asistir de forma habitual a las reuniones de Printer One y dar acceso al resto de miembros a las instalaciones de la Asociación durante dichas reuniones.
- Coordinar el Grupo de trabajo, definiendo objetivos y proponiendo tareas para sus miembros; atendiendo también las propuestas de los mismos.
- Fijar una reunión semanal durante el curso, y comunicarla por los canales habituales: Web, Calendar y Grupo de Telegram.
- Promover la solicitud y gestionar el uso de las subvenciones.
- Aparecer en la Web de la Asociación con el rol de responsable de Printer One.
- Custodia de llaves:
  - Candado de las impresoras.
  - Puerta de la nave.
  - Armario de la Asociación.

A partir de este momento se abre el período de presentación de candidaturas.

Quedo a disposición para resolver dudas asociadas con el traspaso de la responsabilidad.

**Comment by GioSunrider** [comment]
Me ofrezco como tributo para la tarea.

**Comment by JorFru** [comment]
Hemos realizado la votación presencialmente en la reunión de Printer One del 24 de Septiembre de 2018.
El resultado ha sido ampliamente favorable para el único presentado al puesto @GioSunrider 
El traspaso de poderes se ha llevado a cabo satisfactoriamente.
![photo_2018-09-24_20-15-28](https://user-images.githubusercontent.com/11017088/45970423-c3c47800-c036-11e8-92c6-7fb1c062e29d.jpg)


### Larga vida @GioSunrider

**Comment by GioSunrider** [comment]
Con esto pido a laguno @David-Estevez @jgvictores que si por favor pueden hacerme editor del google calendar y maintainer de GitHub, para poder gestionar el grupo correctamente.

**Comment by David-Estevez** [comment]
Hecho!

Ya de paso he ascendido también a @dmarcosm, que creo que se lo ha ganado.

**Comment by GioSunrider** [comment]
Perfecto, cierro issue entonces, muchas gracias!
