### ISSUE TITLE
Baja como responsable de Impresoras 3D

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/actas#154]
Con esta issue presento mi baja como responsable de Impresoras 3D. Entre las atribuciones de este cargo están:

- Se encarga de conocer el estado de las impresoras 3D, de repararlas y de gestionar la compra de fungibles o repuestos (via [estatutos](https://asrob-uc3m.gitbooks.io/estatutos/content/puestos_de_responsabilidad.html)).
- Velar por la buena administración, buen estado y buen uso de las impresoras 3D de la Asociación.
- Renovar semanalmente las hojas de reservas de las impresoras, más info aquí: https://github.com/asrob-uc3m/printers-status-webpage/issues/5. Al menos hasta que haya un medio automático para hacer esto, por ejemplo lo propuesto aquí https://github.com/asrob-uc3m/printers-status-webpage/issues/4.
- Aparecer en la Web de la Asociación con el rol de responsable de Impresoras 3D.
- Custodia de llaves:
  - Candado de las impresoras.
  - Puerta de la nave (?).
  - Armario de la Asociación (?).

A partir de este momento se abre el período de presentación de candidaturas, que se cerrará con una votación.

Quedo a disposición para resolver dudas asociadas con el traspaso de la responsabilidad.

**Comment by GioSunrider** [comment]
Me ofrezco como tributo para la tarea.

**Comment by GioSunrider** [comment]
Visto que no hay mas candidatos, habilito hasta el domingo una votación al cargo. https://goo.gl/forms/59vGJGr8rCCEfBIj1

**Comment by GioSunrider** [comment]
La votación ha sido cerrada con el siguiente resultado:

![votacion1](https://user-images.githubusercontent.com/10605193/46263631-e57b9e80-c511-11e8-942c-4411fbfa5bf9.png)

Luego el nuevo responsable de impresoras 3D se ha cambiado. Muchas gracias @Siotma por tu dedicación, y por todo lo que me has enseñado sobre ellas.

**Comment by JorFru** [comment]
Enhorabuena @GioSunrider 
Pero veo aquí un claro caso Juan Romo.
Eso o a la gente le hace demasiada gracia el botón: "haced lo que queráis, pesados"
