### ISSUE TITLE
El soldador JBC prestado por UC3Music ha desaparecido

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#155]
Es un modelo ST30, de 25W
Su correspondiente base está localizada, en el armario.

**Comment by CeciliaVa** [comment]
¿Desde cuando crees que falta?  
Últimamente no andamos muy bien de soldadores, la semana pasada solo había dos en el armario, eran iguales, de color verde tirando a turquesa.

**Comment by JorFru** [comment]
@CeciliaVa este soldador se llevó al Campamento ASROB?
Se identifica porque es negro entero y tiene una pegatina que pone UC3Music.
La última vez que recuerdo haberlo utilizado es antes de vacaciones.

**Comment by MrTommyGuns** [comment]
Encontradoo!!! Estaba en el taller de Uc3Music en la caja que correspondía a otro.
![img_20180921_001837_117](https://user-images.githubusercontent.com/36898802/45849842-f2d7a280-bd33-11e8-9b81-b7417a07f054.jpg)
