### ISSUE TITLE
Habilitar un casillero para recibir correspondencia en ASROB

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#156]
Actualmente los paquetes de ASROB se reciben en los casilleros de JuanGV, DEF o en casa de Gio: esto no es sostenible, ya que hay que molestarles a la hora de recoger el paquete.

Creo esta issue para informar del estado de este proceso, que en principio me encargaré yo de llevar a cabo.

Para recibir la correspondencia, la dirección de envío será

> 
> Calle Butarque, 15 28911 Leganés Madrid
> Asociación ASROB

a partir de la fecha que informe el cierre de esta issue.

**Comment by JorFru** [comment]
Actualmente tenemos un casillero en el Sabatini. La dirección postal para recibir correspondencia aquí es:
> Av. de la Universidad, 30 28911 Leganés Madrid
> Asociación ASROB

¿Seguimos con este casillero y lo usamos?
¿Pedimos el cambio a la conserjería del Betancourt?

Debate aquí. Si se necesita, abro votación.
Debate

**Comment by GioSunrider** [comment]
Yo creo de cambiarlo a Betancourt por ser el propio edificio donde se encuentra la asociación.

**Comment by JorFru** [comment]
Te informo de que la asociación se encuentra oficialmente establecida en el edificio Sabatini.
Sobre los papeles somos de ese edificio, La Nave es una ventaja adquirida a través del departamento de robótica, que son muy majos.

**Comment by David-Estevez** [comment]
Nope, tras la mudanza de asociaciones nuestro despacho oficial está en el Betancourt (3ª planta).

**Comment by GioSunrider** [comment]
Exacto, tenia en cuenta la mundanza. (Porque decir 'zasca' queda muy feo 🤣)

**Comment by JorFru** [comment]
Zasca recibido, gracias

**Comment by jgvictores** [comment]
Bloqueado por #114

**Comment by JorFru** [comment]
Confirmo que el casillero de ASROB se ha movido al Betancourt.
ya podemos enviar mercancía a nuestro casillero y recogerla cómodamente.


Para el cartero:
Dirección: C. Butarque, 15 / Asociación ASROB
CP: 28911
Municipio: Leganés
