### ISSUE TITLE
Automatizar publicaciones en Fb usando las de Twitter

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#159]
(viene de #141 )

Se quiere automatizar las publicaciones en Fb usando las de Twitter como base.

Estado actual: esperando que @dmarcosm nos cuente qué averiguó investigando APIs para saber si esto se puede hacer o no.

**Comment by dmarcosm** [comment]
La verdad es que todavía no he tenido tiempo de hacerlo, pero por poderse se puede hacer de una forma u otra

**Comment by jgvictores** [comment]
Cierro issue como inválida (no necesaria) puesto que en la actualidad contamos con responsable de Facebook: http://asrob-uc3m.github.io/members.html (src: https://github.com/asrob-uc3m/asrob-uc3m.github.io/blob/a57d62bd028354e498c13553f2a53658b05eef99/_config.yml#L96-L98 )
