### ISSUE TITLE
Bote Armario para Material Fungible

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#16]
Desde el grupo de uavs han propuesto, aprovechando que ya hay espacio en el segundo armario, hacer un bote para la comprar de material y reformar el actual sistema de deistribución "piggy". 

La idea seria poner 10 euros cada uno y hacer un pedido a chicna con material fungible variado. Todos los que hayan puesto lso 10 euros en el bote tendera derecho a disponer de el cuando lo necesiten. 

En caso de que alguien no haya pagado esos 10 euros y necesite algo de material, podra poner dinero a piggy y coger ese material. El pago por esta via sera superior.

Tambien hace falta cierto material no fungible, este se pagara con el dinero que hay en cuenta y se debatira en #17.

**Comment by David-Estevez** [comment]
Y usar los fondos reservados de ASROB para la compra de materiales? Si son materiales comunes a todas las ramas procedería usar estos fondos en lugar de crear otro fondo.

Haced propuestas (presupuestos) de los materiales que creéis necesarios y los vamos discutiendo y votando.

**Comment by jgvictores** [comment]
Existiendo la propuesta específica https://github.com/asrob-uc3m/actas/issues/17, ¿ok con cerrar esta issue?

**Comment by Rodriwp** [comment]
Este hilo es diferente al #17 . Aqui se debate la idea de hacer una derrama para la compra ee material fungible que propone uavs. Este material es para uso personal en proyectos individuañes auqnue tambien se puede usar en proyectos colectivos. La idea es evitar tener que pedir a chicana constantemente teniendo un stock comun. @David-Estevez  yo dejaria el dinero de la asociacion para las cosas inventariables, ya que tenemos poco.

**Comment by David-Estevez** [comment]
@Rodriwp Estoy viendo las cuentas en la wiki y el saldo actual es >300€... 

Dejando eso a un lado, creo que todo lo que sean proyectos personales de cada uno deberían ir financiados por cada persona a título personal. El bote tendría sentido para material común de uso colectivo en proyectos de la asociación. Como se ha estado haciendo hasta la fecha, vamos.

**Comment by jgvictores** [comment]
@Rodriwp Estoy de acuerdo con @David-Estevez 
La idea es que si alguien coge material común, que sea para un proyecto de un [grupo de trabajo activo](https://asrob-uc3m.gitbooks.io/estatutos/content/chapter1.html), porque así nos aseguramos que ese material sigue pudiéndose utilizar de forma semanal por quien se apunte al proyecto.
