### ISSUE TITLE
Representar a ASROB en la Bilbao Maker Faire

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#160]
Eché el Call4Makers y nos han aceptado.

![imagen](https://user-images.githubusercontent.com/11017088/45961994-26f6e000-c020-11e8-8768-20fae780ce39.png)

Ofrecen una plaza, con viaje, comida y alojamiento pagado.

Sugerí que ASROB llevaría las hordas de Zowis y Zowimanoides. Se pidió permiso de préstamo de manera informal a @Siotma pero hay que formalizarlo.

### Necesitamos a una persona que nos represente en la feria.
Es necesario listar las personas interesadas en ir y debatir un método de elegir al afortunado. Buen momento sería #157

**Comment by GioSunrider** [comment]
Yo creo/me gustaría ir. Es una experiencia que hay que vivir jajajajajaa

**Comment by JorFru** [comment]
Cancelada la participación en la feria.
Una pena, la verdad.
