### ISSUE TITLE
Los correos que llegan a nuestro email no se están contestando

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#163]
_From @JorFru on September 12, 2018 22:6_

Ahora mismo hay cinco personas que han contactado con nosotros para intentar unirse a nuestra asociación y no pueden.
Es el momento más importante del curso para la captación, no podemos dejarlos pasar.

_Copied from original issue: asrob-uc3m/estatutos#19_

**Comment by jgvictores** [comment]
_From @David-Estevez on September 13, 2018 8:20_

@KFRodicio me comentó que les mandaría un mensaje genérico dirigiéndoles al Telegram.

PD: ¿esto no iría en actas?

**Comment by jgvictores** [comment]
Movido a actas.

Se propone que un bot re-envíe los emails de Africa a Telegram. Esto no es excluyente de tener un responsable, sino que agilice este caso particular.

**Comment by JorFru** [comment]
Tenemos un nuevo candidato a responsable de respuestas a correos: @dag00dag33
Hay que seguir los estatutos.

**Comment by JorFru** [comment]
https://github.com/asrob-uc3m/estatutos/issues/24

**Comment by JorFru** [comment]
Ahora mismo hay personas que han contactado con nosotros por correo para intentar unirse a nuestra asociación y no pueden.
También hemos recibido invitaciones a eventos y convocatorias de reunión, entre otras.

El responsable actual de correos @DAG00DAG33 no se está haciendo cargo de responder ni informar al resto de asociados.

**Comment by JorFru** [comment]
Hay personas esperando que nos han escrito y no tienen respuesta @dag00dag33

**Comment by DAG00DAG33** [comment]
Si, pero que no salten las alarmas. 

Lo que sí que se me ha pasado es asti challenge. Que ahora lo he leído e informo a todo el mundo.

También es relevante decir que la convocatoria de reunión era consciente de ella, pero cuando me puse como el encargado de correo esa conversación ya estaban un poco antiguas las fechas que habían propuesto ellos y Photofolks habían pasado. La deje como no leída, para que no cayese en el olvido, por  si volvían a contactar.

Lo mas importante, es cierto que han pasado algunos días en los que no lo he mirado y alguna respuesta ha tardado en salir. No como excusa, pq lo debería haber solucionado hace tiempo, si no para arreglarlo decir que no tengo acceso al correo desde el móvil. Me pongo ahora a conseguirlo.
No vi tu anterior mensaje, si no me habría puesto las pilas antes. 👍

**Comment by DAG00DAG33** [comment]
Buahh acabo de ver que lo de la reuinon fue hace no tanto. Cuando lo vi pensaba que era mas antiguo. 🤦‍♂

**Comment by JorFru** [comment]
Gracias Diego

perdona por no haberte avisado antes
creía que estabas suscrito a las notificaciones de las issues.

**Comment by DAG00DAG33** [comment]
Lo estoy pero con un correo que no uso. 
Pero ya he redirigido el correo de gitHub al de la uni.
