### ISSUE TITLE
Revisar la composición de la Junta Directiva de forma anual: Presidente

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#164]
Revisar la composición de la Junta Directiva de forma anual: Presidente

Related: #157

**Comment by JorFru** [comment]
Me presento candidato para el puesto de responsabilidad: Presidente.

Prometo horizontalidad y transparencia en toda la extensión y dominio de ASROB.

**Comment by David-Estevez** [comment]
Me presento candidato para el puesto de responsabilidad: Presidente.

Mi principal objetivo es evitar que JorFru no nos queme la nave. También tengo locuras varias que aportar a la asociación.

**Comment by jgvictores** [comment]
Votación abierta hasta Oct 14 2018: https://goo.gl/forms/GAVAlGOpoMXXqCs33

**Comment by jgvictores** [comment]
Votación cerrada:
- @jgvictores: 13 (37,1%)
- @JorFru: 2 (5,7%)
- @David-Estevez: 17 (48,6%)

![presi](https://user-images.githubusercontent.com/4448588/46922731-b71bba00-d00d-11e8-996b-7c7bcb52a670.png)

**Comment by jgvictores** [comment]
Cierro issue. Quedarían pendientes issues que se pueden tratar de forma independiente:
- https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/30
- https://github.com/asrob-uc3m/estatutos/issues/18

¡Muchas gracias por la participación!

**Comment by David-Estevez** [comment]
En primer lugar me gustaría agradeceros a todos la confianza depositada en mi.  Soy consciente de que era una decisión difícil, pues todos los candidatos son gente muy capaz de desempeñar este cargo, y así lo han reflejado los resultados.  Sólo puedo decir que lo haré lo mejor que pueda durante este año,  y trabajaré junto a vosotros para hacer que ASROB se mantenga como una de las Asociaciones de cacharreo de referencia en la UC3M.

También me gustaría agraceder a Juan todo el tiempo que ha dedicado a la Asociación durante su presidencia. Yo entré en la Asociación gracias a él y le debo mucho no solo en lo profesional y en el cacharreo, sino también a nivel personal. Juan es un crack, y por muy liado que esté (y Juan suele estar siempre hasta arriba de curro) siempre que ha hecho falta echar una mano en ASROB ha estado ahí. Por eso  es para mi todo un honor recibir de él el testigo, y le aliento a que no se desanime y continúe participando activamente en la Asociación cerrando issues con nosotros, pues sin duda necesitamos entre nuestra filas miembros tan experimentados como él. 

Por último, recordaros que los puestos de la junta son puestos meramente simbólicos, y que los realmente importantes en la Asociación sois vosotros, los miembros activos. Lo realmente bonito de esta Asociación es que todos, tanto nuevos como veteranos tenemos la capacidad de proponer ideas, mejoras, actividades y locuras en general, y que la gente las apoye o no según el criterio individual de cada uno. Nos juntamos sin importar  el nivel de cada uno y creamos robots, construimos cacharros y compartimos nuestro conocimiento.  Cada miembro aporta lo que puede y todos salimos ganando. Esto es lo que nos hace grandes, y es algo que no siempre pasa en todas las asociaciones, y por ello tenemos que valorarlo y que mantenerlo en la forma de ser de ASROB.

Larga vida a ASROB!!
