### ISSUE TITLE
Crear cuenta de Instagram

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/actas#165]
Como se comento en la primera reunión organizativa del curso, se proponía la creación de la cuenta de Instagram, ya que actualmente es la red social mas "de moda" del momento. @JorFru como responsable de redes estaba en contra de llevarla. 
En la reunión de hoy se ha propuesto a @VentressAsajj para que lleve a cabo la labor, la invoco para que acepte o no la propuesta.
Independientemente, creo que la cuenta se podría llevar entre mas personas, por ejemplo:
uno de nosotros se va a la OSHdem o la Mini Makerfaire, pues que ese alguien lleve la cuenta de instragram de la asociación, para promocionar y compartir in situ la actividad.

**Comment by VentressAsajj** [comment]
Tu poder de invocar ha funcionado. 
No hay problema en crearla, pasar clave y gestionarla en conjunto o individual o como queráis.  Solo una cuestión, ¿qué nombre? asrob? he visto que está libre asrobUc3m?

**Comment by GioSunrider** [comment]
No se que tal lo ven el resto. yo de nombre pondría el mismo del @ de Twitter para facilidad de búsqueda. Mi idea es que la lleves tu, colgando las locuras que hacemos, y luego ademas en eventos alguno de los integrantes lleve también la cuenta así es mas fácil para todos.

**Comment by GioSunrider** [comment]
Tienes el honor de cerrarla @VentressAsajj

**Comment by VentressAsajj** [comment]
Pues no, no la cierro. Dado que has comentado el vincular la cuenta de IG con la de Twitter y FB, Yo, desde mi punto de vista perfil seguridad, no lo haría pero como queráis. :D

**Comment by GioSunrider** [comment]
También es para que en Facebook haya fotos y cosas así de momento, entre que se hace la unión y no.

**Comment by LuRuz** [comment]
Si nadie se anima yo me comprometo a actualizar la cuenta de Facebook

**Comment by JorFru** [comment]
Como responsable de RRSS me parece bien tu propuesta

> Si nadie se anima yo me comprometo a actualizar la cuenta de Facebook

Por mi parte queda aceptada.

Queda pendiente determinar la manera por la cual entre nosotros compartimos las imágenes y textos a publicar. ¿Os parece bien un grupo de Telegram para las RRSS? @VentressAsajj @LuRuz

**Comment by LuRuz** [comment]
Por mi perfecto

**Comment by VentressAsajj** [comment]
perfecto.

**Comment by VentressAsajj** [comment]
Cerramos issue?

**Comment by David-Estevez** [comment]
Yo creo que sí, lo del Facebook mejor tratarlo en otro sitio para que no se mezclen temas.

**Comment by VentressAsajj** [comment]
state:closed

**Comment by VentressAsajj** [comment]
@GioSunrider no puedo cerrarla no tengo el botón de cerrar, solo el de comentar.
