### ISSUE TITLE
Limpieza anual de Armarios

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#167]
En #157 hablamos de la necesidad de volver a ordenar y redistribuir los armarios e intentar que, esta vez, duren ordenados algo más de un par de meses.

Para ello, en la misma reunión se aprobó la creación de una Comisión de Limpieza para pensar en la mejor forma de llevar a cabo ese objetivo y ejecutarlo. Esta comisión tiene plenos poderes en el armario (limitados por el respeto y el sentido común), y cualquiera es bienvenido a unirse a ella.

Para reunir a la comisión físicamente y llevar a cabo nuestro trabajo, @CeciliaVa ha creado el siguiente doodle, con las fechas en las que ambos podemos reunirnos (ya que ambos hemos convocado a la comisión): https://doodle.com/poll/ai69f3asenrewf4v

El doodle se cerrará el próximo domingo.

**Comment by David-Estevez** [comment]
Primera reunión de la Comisión de Limpieza: Miércoles 10/10/2018 a las 19h.
Convocada por @CeciliaVa y @David-Estevez

**Comment by David-Estevez** [comment]
Tengo la impresión de que añadir más espacio de almacenaje no va a solucionar el problema, sino que sólo nos va a dar un sitio más donde acumular trastos...

**Comment by David-Estevez** [comment]
Crónica de una reunión anunciada (día 10/10/2018 a las 19h):

* F.E.N.I.X solicitó un espacio para almacenar su material / proyectos. Tras inspeccionar el armario, se llegó a la conclusión de que hay espacio suficiente para que cada grupo actualmente en activo disponga de 1 balda para uso propio. Para ello, el espacio ocupado por el material de la difunta G.A.M.E fue movido al segundo armario.
* Se debatió sobre si colgar las herramientas para hacerlas más accesibles o no. Tras acalorados debates se abandonó la idea de colgarlas pues no hay espacio para almacenarlas todas colgadas. La solución propuesta en su lugar es mantener las gavetas azules actuales, pero especificar de forma clara qué va en cada una. Se sugirieron varias formas de especificar esta información, desde varias listas hasta una fotografía de los contenidos de la gaveta, pasando por algún tipo de esquema con siluetas. Queda pendiente de concretar qué información mostrar y cómo.
* Dado que el único grupo activo que usa el router actualmente es Robot Devastation, se propuso que se almacenase en el espacio de Robot Devastation para liberar algo de espacio en la zona común del armario.

Todas estas discursiones acabaron quemándonos bastante, así que optamos por no recurrir a la violencia física e irnos al bar a calmarnos.

**Comment by JorFru** [comment]
Al final del año pasado se realizó la limpieza.
