### ISSUE TITLE
Definir estado LinkedIn

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#168]
Definir estado LinkedIn: quién lo lleva, cuál es su URL, etc.

- URLs:
   - Org con admin desconocido: https://www.linkedin.com/company/asociaci-n-de-rob-tica-de-la-universidad-carlos-iii/
   - User con credenciales habituales: https://www.linkedin.com/in/asrobuc3m/

Derivado de https://github.com/asrob-uc3m/actas/issues/157 parece que estamos poniendo un responsable por RRSS. ¿Cómo lo veis?

**Comment by jgvictores** [comment]
No sé si es casualidad, pero desde que Miguel dio su charla, de repente tengo permisos para editar https://www.linkedin.com/company/asociaci-n-de-rob-tica-de-la-universidad-carlos-iii :tada:

Mini-votación informal por un par de días:
- :+1: para solicitar https://www.linkedin.com/company/asob-uc3m
- :tada: para solicitar https://www.linkedin.com/company/asob
- :-1: para solicitar https://www.linkedin.com/company/asociaci-n-de-rob-tica-de-la-universidad-carlos-iii
- :confused: para solicitar dar de baja
- :heart: para solicitar https://www.linkedin.com/company/<3

**Comment by David-Estevez** [comment]
asob -> asrob?

**Comment by jgvictores** [comment]
> asob -> asrob?

Corregido, gracias!!

**Comment by jgvictores** [comment]
Ya funciona: https://www.linkedin.com/company/asrob-uc3m/
He uniformizado logo y banner tb en: https://www.linkedin.com/in/asrobuc3m/

Pantallazo resultado mini-votación:
![screenshot from 2018-12-15 18-48-25](https://user-images.githubusercontent.com/4448588/50046371-1b084080-009a-11e9-9c45-38c220300b68.png)

**Comment by jgvictores** [comment]
1. ¿Dejamos abiertas las dos cuentas?
2. ¿Alguien que se quiera hacer responsable de esto?

**Comment by JorFru** [comment]
> ¿Dejamos abiertas las dos cuentas?

En UC3Music tenemos dos abiertas (y desactualizadas) y es un rollo. Yo no lo recomiendo.

>    ¿Alguien que se quiera hacer responsable de esto?

Lo siento pero no podréis contar conmigo

**Comment by JorFru** [comment]
Hacemos lo mismo que con G+?
Posteamos úna despedida indicando las redes que sí actualizamos y el link a nuestra bonita web=

**Comment by David-Estevez** [comment]
> Hacemos lo mismo que con G+?

G+ muere el 2 de Abril, creo que no merece ni la pena

**Comment by JorFru** [comment]
Nos parece bien.
Mensaje de despedida diciendo que no vamos a actualizar más pero no la borramos para dejar el enlace de la web y tener visibilidad en Hintern3rd.
