### ISSUE TITLE
ASROB en la OSHWDem 2018

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#169]
Tenemos a ASROB y a UC3Music apuntados a la OSHWDem 2018, lo cual implica 2 plazas por cada asociación + 1 (?) plaza de un taller de UC3Music (esto lo tiene que confirmar @JorFru ).

Como ya hemos ido otros años y nos conocen, @JorFru y yo estamos llevando a cabo las gestiones con ellos. @JorFru y yo podemos estar en cualquiera de las 3 cosas (stand ASROB, stand UC3Music o taller), así que quedarían otras 3 plazas a repartir entre ASROB y UC3Music. Los que quieran ir que se manifiesten por aquí.

Tengo entendido que también va gente de RoboFactory a las competiciones, pero no estoy 100% seguro de quiénes son. Por lo que he visto en Twitter, @DiegoGarciaX2 es uno de ellos, pero que nos confirmen ellos.

# EDIT Fechas y horarios

1. Opción 1:

    - Salida el jueves (ya que el viernes es fiesta en Madrid (Aunque no fiesta en la uni))
    - Fiesta el jueves: los madrileños con los gallegos que se atrevan a salir el jueves aunque el viernes tengan que trabajar.
    - Fiesta el viernes
    - OSHWDem sábado
    - Fiesta sábado.
    - Volver el domingo a mediodía, llegar sobre las 20h.

2. Opción 2:

    - Salida el viernes
    - Fiesta el viernes
    - OSHWDem sábado
    - Fiesta sábado
    - Volver el domingo a mediodía, llegar sobre las 20h.

**Comment by GioSunrider** [comment]
Yo me apunto!!!

**Comment by dmarcosm** [comment]
A mi me gustaría ir también!

**Comment by JorFru** [comment]
Por lo visto los competidores son @diegogarciax2 y @madelgj

**Comment by JavierIH** [comment]
Nope, los competidores no están subvencionados.

**Comment by David-Estevez** [comment]
> Nope, los competidores no están subvencionados. 

Eso lo saben ellos? :sweat_smile:

**Comment by DiegoGarciaX2** [comment]
Puedo asumir el coste no hay  fallo. Conmigo tambien vendria Pau Castaño, que esta trabajando en el siguelineas conmigo.

**Comment by JorFru** [comment]
> Puedo asumir el coste no hay fallo. Conmigo tambien vendria Pau Castaño, que esta trabajando en el siguelineas conmigo.

¿Tu compañero Pau Castaño pertenece a ASROB?


@madelgj faltas tú por pronunciarte.

EDITO el primer mensaje de David con las fechas de salida/llegada que se están planteando.

**Comment by David-Estevez** [comment]
Pau es @pau19993

**Comment by madelgj** [comment]
Hola, sí yo voy 👋

**Comment by DiegoGarciaX2** [comment]
¿Como va la situación de desplazamiento? Lo digo por ir viendo buses o trenes si no hay hueco en ningún coche

**Comment by DiegoGarciaX2** [comment]
Por mi parte yo solo podría la segunda opción porque tengo examen

**Comment by David-Estevez** [comment]
La organización me está pidiendo nombres de asistentes, así que debemos cerrar esto cuadr cuánto antes, ya sea aquí o por Telegram.

**Comment by GioSunrider** [comment]
Por dónde queráis pero me parece correcto!

**Comment by GioSunrider** [comment]
Visto que es evento pasado y cuento como asistentes a @madelgj @David-Estevez @DiegoGarciaX2 @JorFru @L4g0 @pau19993 y @GioSunrider
