### ISSUE TITLE
Adquisición de Material Inventariable

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#17]
Como bien sabeis se ha estado hablando de la necesidad de adquirir material extra para nuestras reuniones de trabajo. 

Ahora mismo estan propuestos los siguientes gastos:
- 5 Kits de Arduino Basico 
- 5  Kits de Sensores y Actuadores basicos 
- 2 Kits de Sensores y Actuadores Avanzados
- 1 Kit IoT ESP8266 / Shield Ethernet Arduino ??
-  1 Kit ARM CORTEX M3 ??
- Un crimpadora.

Todo esto estara guardado en el armario en cajas individuales y servira tanto para la formación de la gente que entre en la asociación como para prototipado rapido. Aqui podeis opinar sobre la comprar proponer materiales basico y actuadores basicos.

**Comment by Rodriwp** [comment]
Ejemplo de posible kit basico de sensores y actuadores:

http://es.aliexpress.com/store/product/Free-Shipping-Helpful-37-in-1-For-Starters-Compatible-Sensor-Module-Kit-for-arduino-Vibration-switch/1383618_32371326711.html?spm=2114.30011108.3.2.4uIKGI&ws_ab_test=searchweb201556_8,searchweb201602_3_10037_10033_507_10032_10020_10017_10021_10022_10009_10008_10018_101_10019,searchweb201603_6&btsid=eaf2454c-c9a6-4989-8bb4-52a06d7926c5

**Comment by Rodriwp** [comment]
El posible kit basico de arduino seria:
Arduino + Protobard + Cables + Alimentador protoboard. 

Componentes basicos hay en las cajas sueltos.

**Comment by David-Estevez** [comment]
@Rodriwp Podrías adjuntar un ejemplo de presupuesto?

**Comment by Rodriwp** [comment]
kit basicos de arduino 5 x 5 € ( Lo hay mas barato 5 kits 14 euros ) 
Kit sensores basicos 5 x 10 € el enlace que he enviado 
Kit sensores, shield y actuadores avanzados arduino 2x 15
kit IoT 4 x 5 euros ( esp8266, breadoboard, cables cada kit )
Kit Arm cortex M3 2 x 5 euros 

Total  135 euros 

El kit avanzado seria para meter sensores chulos que se nos ocurran ( de movimiento, de acohol, etc )
Crimpadora 5 euros

**Comment by Rodriwp** [comment]
Dejo aqui diversos enlaces para no perderlos.
http://es.aliexpress.com/store/product/Smart-Electronics-ESP8266-serial-WIFI-Witty-cloud-Development-Board-ESP-12F-module-MINI-nodemcu/1383618_32597903151.html?storeId=1383618&spm=2114.12010408.1000013.34.y87G5R

http://es.aliexpress.com/store/product/5pcs-lot-Uno-R3-Kit-for-arduino-400-points-Breadboard-65-Flexible-jumper-wires-USB-Cable/1240331_1875960971.html?spm=2114.30011108.3.398.ugN6oq&ws_ab_test=searchweb201556_8,searchweb201602_3_10037_10017_10021_507_10022_10032_10009_10020_10008_10018_10019_101,searchweb201603_6&btsid=5992c64d-0de7-466b-9a9e-f7a0f6ffe6e0

**Comment by jgvictores** [comment]
@Rodriwp Respecto al título de la issue: Normalmente los materiales entran en una de dos categorías, o "inventariable" o "fungible". ¿Ok cambiar el título de la issue por "Adquisición de material inventariable", o no representa el contenido?

**Comment by asrobuc3m** [comment]
Cerrado por inactividad (> 1 mes)
