### ISSUE TITLE
Eliminar subteams RoboFactory

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/actas#170]
[WIP] Sustituir por etiquetas en repos, hacerlo más vistoso.

**Comment by David-Estevez** [comment]
Puede que esté un poco amodorrado todavía después de comer, y no lo entienda bien, pero:

1. ¿Esto no es un duplicado de https://github.com/asrob-uc3m/RoboFactory-issues-e-ideas/issues/1 ?
2. ¿Esto no es un tema exclusivo de RoboFactory (y por tanto no procede tenerlo aquí en actas)?
3. En caso de que la respuesta a 1) y 2) sea "no", ¿no podrías encargarte tú? :sweat_smile:

**Comment by jorgercobo** [comment]
Efectivamente, es un duplicado, cerrando :sweat_smile:
