### ISSUE TITLE
Reunión con África post-Feria de Asociaciones

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#172]
## Martes, 23 de Octubre a las 13:30 en Getafe, aula 9.1.4

Esta reunión es importante, recordad que en la Semana de Asociaciones no pudimos explicar nuestro proyecto porque se cancelaron las dos actividades donde íbamos a participar: bienvenida de la semana (con una presentación breve) y la charla "conoce ASROB" con spam del duro.

**Comment by David-Estevez** [comment]
Yo el martes a las 14h tengo un partido y siendo en Getafe no me daría tiempo a llegar ni de coña (además de que las reuniones se alargan bastante) :disappointed:

**Comment by GioSunrider** [comment]
Yo tengo clase a esa misma hora, tampoco podría asistir 😅

**Comment by madelgj** [comment]
Yo tampoco, no me da tiempo a ir a clase luego 🙃.

**Comment by MrTommyGuns** [comment]
Resumen:
Aunque no ha sido nuestro caso, no se pueden realizar las cosas por cuenta de cada asociación por separado y tenemos que apoyarnos entre las asociaciones porque los de arriba nos ven como una sola entidad y si cae alguna o pasa algo nos repercute a todos.
Las estadísticas de la semana de Asociaciones, aunque han sido peores que las de años pasados, teniendo en cuenta las dificultades por el tema creditos, "no han sido tan malas".
Se ha comentado que nos hemos relajado y teníamos que poner más spam para la próxima.
Se han sugerido formulas para mejorar la semana del año que viene. Yo mismo he propuesto que se haga de forma más visual y clara la forma de inscripción, así como no enviar mensajes con emoticonos para evitar que el correo acabe en la bandeja de spam.
Se ha propuesto hacer un grupo de manualidades para que la gente ayude a la creación de carteles, pancartas y diversos materiales.
Se propone crear un grupo para gestionar las asociaciones como un gran conjunto, aunque se aclara que se ha intentado y se sigue barajando.
Y creo que nada más.
Doy por cerrada la issue.
