### ISSUE TITLE
The bots are coming (to telegram)

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#173]
## Descripción del problema
The bots are coming, a nuestros grupos de telegram via enlaces públicos.

JorgeRJ recomendó https://github.com/J-Rios/TLG_JoinCaptchaBot

## ToDo (la flecha marca la tarea actual):

* [ ] Búsqueda de posibles soluciones :arrow_backward: 
* [ ] Selección de la solución más adecuada
* [ ] Implentación

## Posibles soluciones:

* [JoinCaptchaBot](https://github.com/J-Rios/TLG_JoinCaptchaBot) (sugerido por @jorgercobo)
* [Combot](https://www.reddit.com/r/Telegram/comments/8dqkma/how_do_i_block_continuous_fake_users_joining_my/e4uawsk/) (sugerido por @PeterBowman)
* Implementar esta función en ASROBot (sugerido por @dmarcosm )
* [Añadir un captcha](https://developers.google.com/recaptcha/docs/display) (sugerido por @David-Estevez , pensado por @jorgercobo en paralelo)

**Comment by jgvictores** [comment]
https://www.reddit.com/r/Telegram/comments/8dqkma/how_do_i_block_continuous_fake_users_joining_my/e4uawsk/

**Comment by David-Estevez** [comment]
Edito el mensaje principal siguiendo las guidelines de @Siotma para la creación de issues más concretas y cerrables.

**Comment by David-Estevez** [comment]
De todas las opciones sugeridas hasta ahora, yo optaría por la que:

1) Ya esté hecha
2) No tengamos que gestionar nosotros (es decir, que si se rompe la API o algo así haya una tercera persona que lo solucione por nosotros)

¿Alguien conoce algún otro bot que banee bots?

**Comment by jgvictores** [comment]
Una solución rápida sería reemplazarlo por algo menos machine-readable?
Mecanismo [dot] con explicación.

**Comment by jgvictores** [comment]
PD: En grupos son texto y se puede, en grupo general algo más complicado pq está formato icono

**Comment by JorFru** [comment]
Como solución temporal, contemplo la posibilidad de ampliar la vigilancia de los grupos de Telegram.
@David-Estevez es el único administrador del grupo de TG ASROB-Horizontal, y las labores de gestión y restricción de bots requieren a más personas administrando para cubrir un horario más amplio en el que se pueda hacer este control.

Me presento voluntario para colaborar en el control de bots mediante el privilegio de la administración del grupo de Telegram ASROB-Horizontal.

Me votáis?

**Comment by JorFru** [comment]
> Una solución rápida sería reemplazarlo por algo menos machine-readable?
> Mecanismo [dot] con explicación.

Yo creo que los bots vienen a través de enlaces publicados en otros grupos de Telegram. Lo que comentáis crea una barrera de entrada a los bots, pero no los erradicaría. En mi opinión.
De hecho, los bots cuando entran a un grupo, suelen descargarse el historial para encontrar enlaces que les resulten interesantes.

**Comment by David-Estevez** [comment]
> Como solución temporal, contemplo la posibilidad de ampliar la vigilancia de los grupos de Telegram.
@David-Estevez es el único administrador del grupo de TG ASROB-Horizontal, y las labores de gestión y restricción de bots requieren a más personas administrando para cubrir un horario más amplio en el que se pueda hacer este control.

Estoy de acuerdo y en desacuerdo con el mensaje. 

De acuerdo: el grupo necesita más de un administrador, principalmente por si me atropella un camión cualquier día, para que no os toque hacer un grupo nuevo. No obstante no es el tema de esta issue y sugiero externalizarlo a otra nueva.

En desacuerdo: como dijo Jesús "dadle al admin lo que es del admin y al bot lo que es del bot". Si la solución, aunque temporal, es banear a los bots, mucho mejor si no es una persona (o varias) la(s) que tiene(n) que luchar contra los bots, sino otro bot. Esto también ayudaría con:

> cubrir un horario más amplio en el que se pueda hacer este control.

ya que los bots trabajan 24h y los admins no. 

Lo que he entendido es lo que ha comentado @PeterBowman ¿te refieres a que dos cuentas distintas han puesto el mismo mensaje?

**Comment by PeterBowman** [comment]
> Lo que he entendido es lo que ha comentado @PeterBowman ¿te refieres a que dos cuentas distintas han puesto el mismo mensaje?

En efecto. Pero una blacklist solo cubriría el caso particular de bloquear un tipo de mensajes, haría falta mantener la lista si mañana llega otro bot y pega un enlace diferente, etc. Me convence mucho más la opción del bot que exige resolver un captcha a quien quiera entrar en el grupo (pero no un captcha a nivel enlace de invitación).

**Comment by dmarcosm** [comment]
A mi también me convence muchísimo más la idea de que el bot haga resolver un captcha/decir algo al bot nada más entrar. Si no lo hace en X segundos, fuera.

**Comment by jorgercobo** [comment]
Creo que antes de entrar a buscar soluciones habría que concretar cual es el problema y analizarlo.

Una puntualización antes de empezar, lo que está entrando en los grupos son **usuarios falsos** (que estarán gestionados por un bot) pero no hay que confundirlos con bots de Telegram, aunque por simplicidad sigamos nombrandolos como bots.

Primero documentar con algo mas de detalle que ha ocurrido:

1. En los últimos días y de forma escalada, han entrado varios bots en el grupo general de ASROB, Robot Devastation y Printer One mediante el link del grupo (Telegram lo especifica en el mensaje de aviso). Destacar que no han entrado en RoboFactory ni F.E.N.I.X, que tambien son grupos públicos accesibles de la misma manera. Todos los bots presentan el mismo perfil, nombre y apellido no españoles sin fotogafía de perfil.
2. Tras unas horas spamean un enlace a una página web (teiegram o algo similar) de contenido erótico.
3. Una vez se elimina el mensaje del grupo y se le expulsa del grupo, al poco tiempo se borra la cuenta (puede ser que la borre el autor o que tras varios reports lo haga Telegram). Podemos suponer que forman parte de la misma campaña aunque no se sabe si funcionan de forma independiente. No parece un ataque dirigido.

Sería interesante ver el historial de actividad de los bots en el grupo, @David-Estevez y demas admins, para saber si hacen algo más.

El **vector de ataque** está claro que es el link público de los grupos ya que los grupos no tienen un alias definido y nadie está invitando a los bots al grupo. El punto de ataque puede ser:
* La página web 
* Los archivos de configuración de la web en GitHub 
* Links compartidos en otros grupos de Telegram como sugiere @JorFru, o en nuestros propios grupos, es decir, entraron en uno de ellos y saltaron a los demas grupos
* Links accesibles de alguna otra forma que no conocemos

Viendo que solo han entrado en tres de los grupos, descartaría la página web y GitHub.

Parece que la única finalidad de estos bots es el **spam** pero tambien pueden dedicarse a **extraer datos del grupo** para continuar extendiendose (links a otros grupos) o para buscar datos sensibles.

Ahora sí, posibles soluciones (tambien amplío las que ya se han mencionado antes):

1.	**Seguir con el control manual**

2. **Blacklist**: Los bots se borran muy rapidamente y no evita nada que no haga un baneo manual a no ser que generemos una red con gran cantidad de grupos.

3.	**Generar nuevos links de grupo**:
	* Sugiero que se haga lo antes posible ya que nos dará información de si entran por crawling de info antigua (links compartidos) o por las fuentes que actualizamos (página web y GitHub).
	* :heavy_check_mark: Evita el acceso al grupo por fuentes comprometidas sin necesidad de realizar muchos cambios y no dificulta el acceso a nuevos miembros.

4.	**Bot con catpcha al entrar** (CaptchaBot/Combot/Executrix/etc):
	* :heavy_check_mark: Evita el spam: Los bots no spamean inmediatamente.
	* :heavy_check_mark: Estas soluciones ya están implementadas, hosteadas externamente y no es necesario ningún mantenimiento.
	* :question: Evita la extracción de datos a largo plazo pero no a corto plazo: Pueden descargar todo el historial de mensajes tras entrar al ser supergrupos, pero al expulsarlos rapidamente no pueden descargar archivos.
	* :x: Software externo no libre en nuestros grupos.

5.  **Captcha para ver el link del grupo en la web** y hacer el link menos machine-readable:
	* :heavy_check_mark: Es algo que el usuario medio entiende y de facil implementación.
	* :question: Añade complejidad al proceso de entrada para nuevos miembros.
	* :x: Hay que monitorizar si funciona correctamente. 

6.	**Timbre bot**: Bot que gestione el acceso a los grupos, que pasan a ser privados. Pide un captcha para solicitar entrar al grupo. Si se responde correctamente, avisa a un admin de que me meta al user al grupo(1)/mete al user en el grupo por si mismo(2)/le da el link para entrar(3). El link/alias de este bot sería la parte pública
	* :heavy_check_mark: Evita la entrada de bots al grupo a cualquier nivel y el grupo sigue siendo igual de alcanzable sin ser público(1)(2).
	* :heavy_check_mark: Podemos usar un mismo bot para todos los grupos y así aprovechamos para generar un directorio de grupos de la asociación.
	* :x: Hay que desarrollar la solución, hostearla y mantenerla.
	* :x: Más complejidad para entrar a los grupos.
	
Personalmente creo que primero habría que cambiar los links y ver si el problema persiste ya que creo que ha sido un ataque puntual y nuestros grupos, al ser de organización, no están expuestos constantemente para que sea necesaria una solución permanente.

Corregidme si he soltado alguna burrada :sweat_smile:

**Comment by jorgercobo** [comment]
Parece que nos han dejado en paz :smile_cat: Cerramos la issue por ahora?

**Comment by jgvictores** [comment]
Esperar a que vuelva a llover para arreglar el tejado? :grin: 

IMHO aquí se plantea un tema difícil y se han propuesto unas soluciones interesantes. Estamos viendo dónde y cómo almacenar información "protected" (como punto entre "public" y "private"). La mantendría abierta. 

Más bien planteo otro dilema: si se añade un captcha a nivel web (no bot el telegram), ¿dónde se almacena la info a donde ir (la URL auténtica, me da q al final tb es o public o privada...)?

**Comment by MrTommyGuns** [comment]
Hasta que encontremos una solución más elegante y efectiva, creo que tendríamos que regenerar el link para evitar que se metan de forma tan frecuente una temporada

**Comment by jgvictores** [comment]
Me llama la atención este mecanismo (aunque es de `Discord`, habría que hacer un bot para `Telegram`), porque no plantea los dilemas anteriormente planteados (dóde se almacena la URL) y parece que se corresponde con el modus operandi de los bots que nos invaden:
- [Invite link/amazingsexdating spam auto-banning](https://github.com/ryry013/Rai#invite-linkamazingsexdating-spam-auto-banning) (`Toggles the banning of all users who join and instantly send an invite link, or those that join and spam a link to amazingsexdating.com. If you use the below welcome messages module too, then the welcome message won't be posted.`)

**Comment by JorFru** [comment]
El problema se ha solucionado o bien podemos convivir con el problema.

**Comment by jgvictores** [comment]
For reference, me crucé con un bot llamado `BH Antibots` (https://botostore.com/c/bhantibots_bot/ maybe?) que obligaba a pasar un captcha antes de permitirte escribir. :smile:

**Comment by jgvictores** [comment]
Otro más que moló: @join_captcha_bot
