### ISSUE TITLE
Administración grupo de Telegram ASROB-Horizontal

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#174]
Sugiero que el grupo de Telegram: ASROB-Horizontal tenga más de un administrador, ya que actualmente tiene sólo uno, que es @David-Estevez 
Ya que a este único administrador le puede atropellar un camión cualquier día, para que no nos toque hacer un grupo nuevo, sugiero añadir un segundo o más administradores.

Como sabéis, los administradores pueden cambiar la información del grupo, anclar mensajes, moderar el contenido (eliminación de mensajes), restringir usuarios (limitar el envío de multimedia, por ejemplo).
Los administradores también pueden ver los cambios que se han realizado en el chat: edición de mensajes, mensajes eliminados.
Todas estas opciones de administración son configurables, puede haber varios grados de administración.

Si esta propuesta sale adelante (requerirá votación), me presento como candidato a ayudar con la administración del grupo de Telegram.

**Comment by VentressAsajj** [comment]
Por mi perfecto

**Comment by jgvictores** [comment]
Me presento como candidato a ayudar con la administración del grupo de Telegram.

Dejo caer otra idea para asegurar siempre un mínimo de admins: que cada responsable de grupo sea admin del grupo de Telegram.

**Comment by JorFru** [comment]
Votación abierta hasta el 26.11.18 a las 18h.


https://docs.google.com/forms/d/e/1FAIpQLSer9OcvPjvd03-E0j4StrJBUcZj6utvJbhaY3yz5OZGYBeBHA/viewform?usp=sf_link

**Comment by JorFru** [comment]
El resultado ha sido favorable con ocho (8) a favor, cero (0) en contra y cero (0) votos en blanco.
Se procederá a incluir a los interesados, por ahora, @JorFru y @jgvictores como adminisradores del grupo de Telegram: ASROB Horizontal.
![imagen](https://user-images.githubusercontent.com/11017088/49023476-92336e80-f197-11e8-9351-6a2e8ab866bd.png)

**Comment by David-Estevez** [comment]
Lista de acciones a tomar:

* [ ] Determinar quiénes son las "otras personas" de las que habla el texto de la votación. ¿Son los responsables de grupo? ¿Son las personas que se han ofrecido voluntarias? ¿Son los voluntarios que se han presentado después de votar? PD: Esto igual debería haberse decidido antes de hacer la votación :man_shrugging:

Y una vez decidido el punto anterior:
* [ ] Añadir a dichos usuarios como adminstradores del grupo principal
* [ ] Documentar en Estatutos el criterio elegido para seleccionar a los administradores / como dar de baja a administradores / como añadir administradores nuevos

**Comment by JorFru** [comment]
> Determinar quiénes son las "otras personas" 

Cuando escribí el texto de la votación me refería a las personas que se mostraron interesadas durante el periodo de recibir opiniones de la votación. Estos somos @jgvictores y yo.
@GioSunrider llegó después de la votación y debería de entrar en la siguiente tanda de votaciones.


Sí, se debería de haber elegido antes de hacer la votación, pero además se debería de haber decidido en estatutos el criterio para determinar quién se puede presentar y cómo se elige.

En todo caso yo considero que es un tema urgente y ya mismo debería ascender alguien más a la administración del grupo de Telegram ya que administrarlo unilateralmente puede comprometer la experiencia horizontal de los asociados. Y a continuación resolver el asunto de estatutos.

**Comment by GioSunrider** [comment]
Pero, yo comente antes de la votacion, al comentario de @jgvictores de que deberian de ser los responsables de grupo y lo hice pensando en que se tendria como consideracion y punto de partida ese comentario. Y lo hice como responsable de Printer, y mostrando interes en el tema.

**Comment by David-Estevez** [comment]
Si de horizontalidad se trata, lo suyo es que la administración no esté atada a personas concretas, sino a puestos, ¿no?

**Comment by JorFru** [comment]
Te lo compro David

**Comment by JorFru** [comment]
Sugiero la siguiente votación:

Añadir como administradores del grupo de Telegram ASROB Horizontal a los puestos de responsabilidad de ASROB:
A saber:

Presidencia
Secretaría
Tesorería
Jefes de cada grupo de trabajo activo.

 



Abro periodo de aprobación/comentarios/rechazo, y en una semana abriré votación con la pregunta decidida.

**Comment by JorFru** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSfOosbym0oBenchv8lZD_UCQc0CrC7ocUKXTtaVYTU0RanZMA/viewform?usp=sf_link

Ya podéis votar

**Comment by JorFru** [comment]
Han pasado ocho días de votación

Los resultados:
![image](https://user-images.githubusercontent.com/11017088/51075104-8a685480-1687-11e9-9d34-631f45909c9b.png)

@David-Estevez el pueblo dice que sueltes prenda.

**Comment by David-Estevez** [comment]
Actualmente tenemos 5 admistradores:

* @David-Estevez en calidad de Responsable de RoboFactory y Presidente
* @madelgj en calidad de Secretaria
* @JorFru  en calidad de Responsable de F.E.N.I.X y Tesorero
* @GioSunrider en calidad de Responsable de Printer One
* @jgvictores en calidad de Responsable de Robot Devastation

@JorFru por favor, realiza la tarea que queda pendiente:

> Documentar en Estatutos el criterio elegido para seleccionar a los administradores / como dar de baja a administradores / como añadir administradores nuevos

**Comment by JorFru** [comment]
Hay una votación pendiente aquí:
https://github.com/asrob-uc3m/estatutos/issues/21
Link form: https://docs.google.com/forms/d/e/1FAIpQLSfmchTzLTtRVPYfI9w6_d90hTROu2DgN46GwQL33lyP__Yebg/viewform?usp=sf_link

**Comment by JorFru** [comment]
Estos son los cambios en los estatutos que contemplan lo decidido.
https://github.com/asrob-uc3m/estatutos/blob/master/admin_telegram.md
