### ISSUE TITLE
Aviso: Retirada de material de miembros no activos

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#175]
Como parte de #167 vamos a proceder a la retirada de material de miembros no activos que se encuentra en la parte superior de los armarios. Este material incluye, entre otras cosas:

* Piezas de una impresora 3D, propiedad de @andrespy
* Calibre digital, propiedad de @andrespy
* Maletín con material surtido, propiedad de @andrespy

Dejamos abierta esta issue hasta el día 06/11/2018 para que los afectados expresen su voluntad de recuperar el material. Si no se expresa esa voluntad o se retira el material antes de dicha fecha, la Comisión de Limpieza tomará las acciones más adecuadas para su retirada.

**Comment by Siotma** [comment]
Estamos seguros de que @andrespy está recibiendo la notificación de esta issue?

**Comment by David-Estevez** [comment]
Las menciones deberían llegar como correos, incluso si no estás metido en el proyecto.

**Comment by JorFru** [comment]
Como no se da por aludido y escribe aquí...
posteo su comentario
![imagen](https://user-images.githubusercontent.com/11017088/48096542-b7c3fc80-e217-11e8-99e7-03a16b8ae2e7.png)

**Comment by GioSunrider** [comment]
Material recogido al encargado designado por @andrespy

**Comment by JorFru** [comment]
Aleluya!


En realidad estoy triste.
Disfrutamos mucho desmontándola.

el calibre también dio mucho juego en nuestra asociación.
