### ISSUE TITLE
Consulta: reserva del espacio ASROB para seminario

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#176]
El otro día Alberto Jardón se puso en contacto conmigo como presidente de ASROB para pedir el espacio de ASROB para un seminario. Los detalles son los siguientes:
*El seminario es algo puntual, ellos tienen asignado un aula, pero va a estar trabajando con los robots industriales y el aula asignada les pilla lejos de los robots (Edificio Torres-Quevedo).
*Los días en los que querrían disponer del espacio son martes 6 y jueves 8 de 15h a 20h.

Yo no tengo potestad para decidir si autorizarles o no, además de que no soy imparcial en este tema por mi afiliación con el departamento, así que abro el debate para conocer la opinión de los miembros.

**Comment by jgvictores** [comment]
En alguna otra ocasión (p.ej. #135 de una búsqueda rápida) montamos votación.

Se le puede proponer que lo monte él para acelerar el proceso. : )

**Comment by David-Estevez** [comment]
Si hay que votar que monte la votación alguien con un PC, que estoy sólo con el móvily esto es un infierno...

**Comment by jgvictores** [comment]
Consulta abierta hasta Nov 1, 11:59 am Madrid: https://goo.gl/forms/pkDfStpnXmgTYkuH2

**Comment by jgvictores** [comment]
Se registraron 3 votos, manifestándose todos a favor.

![asd](https://user-images.githubusercontent.com/4448588/47968891-e7cc9d80-e067-11e8-8ec9-75718888254b.png)

**Comment by JorFru** [comment]
Hoy he cotilleado, lo siento.
![imagen](https://user-images.githubusercontent.com/11017088/48099269-5738bd80-e21f-11e8-95b6-f3c01d3fb37c.png)
