### ISSUE TITLE
Se debe realizar el traspaso del manojo único

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#177]
https://github.com/asrob-uc3m/estatutos/issues/18 resultó en https://github.com/asrob-uc3m/estatutos/blob/master/llaves.md ([perma](https://github.com/asrob-uc3m/estatutos/blob/4fc20c22f2da512036d724a37c2b3327f09fd759/llaves.md)), cito:
> el presidente (...) salvaguarda el "[manojo único](https://github.com/asrob-uc3m/actas/issues/65) (:ring:)"

Como resultado de https://github.com/asrob-uc3m/actas/issues/164, se deberá proceder al traspaso de llaves de @jgvictores a @David-Estevez. Por cuestiones logísticas, esto en principio se realizará la semana del 17 de diciembre de 2018.

**Comment by David-Estevez** [comment]
Manojo único (:ring:) recibido!
