### ISSUE TITLE
Solicitud espacio de trabajo (fuente de alimentación y osciloscopio)

### ISSUE THREAD

**Issue by L4g0** [asrob-uc3m/actas#178]
Hola,

Quería saber si este miércoles de 7 a 9 habría problema en usar la fuente regulada y el osciloscopio. Nos íbamos a acercar @MrTommyGuns y yo.

Solo ocuparemos esa mesa. si hay alguna reunión y creéis que molestaremos hacedlo saber plzz.

Peace!

**Comment by JorFru** [comment]
Será excelente oportunidad para estrenar la estación de trabajo de electrónica.
Sin embargo, el osciloscopio siempre nos ha parecido que funciona mal, o no lo hemos sabido poner a funionar.
Yo creo que como ambos son miembros activos de justificable trayectoria dentro de la asociación, se les puede abrir la nave tranquilamente.
No hay reuniones programadas, el espacio ASROB estará libre en el horario solicitado.

**Comment by GioSunrider** [comment]
Por mi parte tampoco hay ningún problema. @JorFru ha razonado a la perfección lo que también pienso.

**Comment by L4g0** [comment]
![image](https://user-images.githubusercontent.com/23212123/48569369-c4281380-e901-11e8-8fa7-54ca72efc450.png)
Pues al final parece que funcionaba el osciloscopio.
