### ISSUE TITLE
It's raining euros, hallelujah!!

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#179]
Abierto el plazo para presentar proyectos y pedir subvenciones, hasta el **25 de Noviembre**.

![image](https://user-images.githubusercontent.com/1451819/48451764-3090fe80-e7ac-11e8-8504-04030f9f3158.png)

Link a la convocatoria: https://www.uc3m.es/ss/Satellite/Cultura/es/TextoDosColumnas/1371240285442/

Plan de actuación propuesto:
1. Hacer desglose de lo que queremos pedir cada grupo, con precio (rollo presupuesto)
2. Reunión para puesta en común
3. Hacer dos macroroyectos que incluyan el mayor número de cosas posibles de la lista

Yo daría esta semana para sacar los presupuestos y quedaría la semana que viene, para que haya margen para redactar las propuestas.

**Comment by David-Estevez** [comment]
## Informe de la situación

*(el que no esté sentado en este punto que tome asiento y luego siga leyendo, por favor)*

.

.

.

Al parecer el plazo de entrega era el 25 de Noviembre... a las 14h.

Cuando comencé  a redactar las memorias ya había pasado ese plazo, pero además me llevó más tiempo del esperado terminarlas, así que por desgracia cuando acabé ya estábamos fuera de plazo y el enlace de Aula Global para la entrega había cerrado. 

He mandado un correo excusándonos y adjuntando las memorias, pero no sé si finalmente aceptarán tenerlas en consideración o si las rechazarán por haberlas entregado fuera de plazo.

Crucemos los dedos... :crossed_fingers:

**Comment by CeciliaVa** [comment]
Pero, ¿lo entregaste el 25 después de las 14 o no lo entregaste el 25?

**Comment by David-Estevez** [comment]
Oficialmente se entregó fuera de plazo, porque no quedó registro de lo de aula global
