### ISSUE TITLE
Semana de Asociaciones: "ASROB: Ramas Activas ASROB"

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#18]
Como todos sabréis (y si no sabéis, pues os podéis unir al [grupo de Telegram](https://telegram.me/joinchat/ADT1EAgigvgsuobGUHMl_w)) nos hemos comprometido a dar dos charlas en la Semana de Asociaciones (3-6 Octubre 2016):
 * Charla sobre Arduino + ESP8266 (propuesta por @Rodriwp)
 * ASROB: Ramas Activas ASROB

Esta issue gestiona las acciones a seguir para la correcta organización y realización de la actividad.

Las acciones a realizar son las siguientes:

*  [x] Rellenar la [ficha correspondiente](https://docs.google.com/document/d/1V32T8_5rIKHX31t0-ouFcFNOClYSaqWV3_rqhBcSo2o) *lo antes posible* para entregársela a África.

**Comment by David-Estevez** [comment]
Enviado!

**Comment by jgvictores** [comment]
Info extraida del [horario oficial de la Semana de Asociaciones](http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/eventos/semana_asociaciones/Campus%20de%20Legan%E9s1)
> Martes, 4 de octubre
> 17.00 a 18.30 h.
> Edificio y Aula por determinar
> Código 46. Conferencia “ASROB: Ramas activas”
> Contaremos a la gente los proyectos que tenemos activos en la actualidad.
> ASROB

¿Cómo proceder?

**Comment by jgvictores** [comment]
BTW, actualizado el horario, que el copy+paste me la jugó.
