### ISSUE TITLE
Necesitamos una espatula

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/actas#181]
A la vuelta de vaaciones de verano nos percatamos que no habia espatula, pensabamos que estaba perdida por el propio armario. Despues de incansables busquedas la damos por perdida, por lo que solicitamos una nueva, ya que es necesaria para sacar las piezas de las impresoras.

**Comment by GioSunrider** [comment]
Invoco a @JorFru como tesorero para ver si puede conseguirnos una para esta semana.

**Comment by GioSunrider** [comment]
No, no venia nada que facilitara el sacar la pieza del cristal.

**Comment by GioSunrider** [comment]
Gracias a @JorFru ya tenemos espatulas, asi que puedes proceder a cerrar la issue.

**Comment by JorFru** [comment]
Compré un kit de tres espátulas, que costaron como dos euros.
Tengo el ticket y soy el tesorero, pero me da pereza hacer el papeleo para cobrarlas. Prefiero donarlas.

Disfrutad y cuidad el nuevo material.
