### ISSUE TITLE
Se debe entregar llave a FENIX

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#182]
Se debe entregar llave/llaves a FENIX. Related:
- Enmienda https://github.com/asrob-uc3m/estatutos/issues/18#issuecomment-432177915 que derivó en  https://github.com/asrob-uc3m/estatutos/commit/0228da07ee3a5b549ee08ab8d024566a86555861
- En https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/32#issuecomment-438403808 @JorFru comenta que aun no dispone de llave.

**Comment by JorFru** [comment]
Procedo a realizar la copia. Usaré una que me preste Daeste.
Informaré cuando la tenga y rellenaré la información de llaves como dicen las recientes mejoras en los estatutos.

**Comment by JorFru** [comment]
Por causas del destino me está siendo muy difícil copiar la maldita llave.
Ofrezco 5€ a cambio de que alguien realice la copia por mí y me la entregue en mano.
Llevo dos meses para conseguir la llave, me desespera.

**Comment by JorFru** [comment]
Todavía no tengo llave.
Quiero morirme.
Soy un desastre.

**Comment by jgvictores** [comment]
Calma @JorFru eres un grande y te queremos!
Ahora comentamos cómo solucionar

**Comment by JorFru** [comment]
Hito conseguido después de seis meses intentándolo.
Muchas gracias a  @jgvictores por el padrino de la operación.

**Comment by jgvictores** [comment]
Cerrando!

**Comment by jgvictores** [comment]
Updated at https://github.com/asrob-uc3m/asrob-uc3m.github.io/commit/fe9e3ab879197f2b225c69e39a4c55a93974b92e gracias al recordatorio en https://github.com/asrob-uc3m/actas/issues/201#issuecomment-531502706

**Comment by PeterBowman** [comment]
Mirándolo con perspectiva, @jgvictores ha sido la llave para resolver este problema.

**Comment by jgvictores** [comment]
LOOOOOOOOOOOOOL
