### ISSUE TITLE
Presentación de la asociación y proyectos en MakerSpace EPS-UC3M

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#183]
Nos han invitado a organizar esto:
![imagen](https://user-images.githubusercontent.com/11017088/49594824-f95ed900-f976-11e8-8813-9966787913ca.png)

sería en febrero, después de exámenes.
Como al final no hicimos ninguna actividad en la "Semana de Asociaciones", podríamos aprovechar y hacerlas aquí.
Lo dejo como idea.

**Comment by JorFru** [comment]
Fernando el señor que lleva el tema MakerSpace dice:
`hemos reservado la semana del 4-8 de marzo para eventos de las asociaciones, que tal os viene preparar algo para esa semana`

**Comment by JorFru** [comment]
Qué os parece presentar el proyecto:
Construir un contador de días sin accidentes para el MakerSpace

La idea no es que lo hagamos nosotros. La idea es dar nosotros el taller.
Gente se apuntará al taller, la universidad pondrá los materiales, y lo construyen nuestros Oompa Loompas.

Ganamos visibilidad, no mucho más. Pero la segunda parte del proyecto podría ser hacerlo IoTa o LoRa y comparar nuestros números en tiempo real.

**Comment by GioSunrider** [comment]
Lo del contador está muy guay y lo de LoRa también, yo me apunto también a lo que sea.

**Comment by JorFru** [comment]
Estaría pepo tener un par de nodos LoRa que se hablen entre ellos.

Podríamos mandar zumbidos como en la época del messenger.

**Comment by JorFru** [comment]
Voy a sugerirles dar una charla los de Printer sobre las impresoras open source. Un poco la historia de RepRap y Clone Wars: datos, curiosidades, etc.

Alguien me ayudaría a impartirlo?

**Comment by GioSunrider** [comment]
Yo te ayudo. Y veo también que si lo ves factible proponer el contador de días sin accidentes por LoRa.

**Comment by JorFru** [comment]
Veo bien las dos cosas.
Una es una charla, la otra es un taller.

**Comment by GioSunrider** [comment]
Exacto, por mi organizamos las dos.

**Comment by JorFru** [comment]
Igual me he calentado mucho. Bueno, esto le he propuesto.



> Hola Fernando,
> Tenemos las siguientes ideas:
> 
> 
> 1. Charla Impresoras 3D DIY. El contenido será básicamente la historia de las impresoras libres desde Adrian Bowyer hasta las Anet. La importancia de las comunidades maker, el despegue de los foros como RepRap y su versión nacional, Clone Wars, nacida en la UC3M.
> 
> 2. Taller construir un Nodo LoRa para el MakerSpace: LoRa es una tecnología de comunicación a larga distancia con la que se puede formar una red nodal alternativa al Internet. Más información: https://www.thethingsnetwork.org/community/madrid/ Se suele usar para conectar sensores: los más básicos temperatura y humedad, pero podríamos streamear información sobre el uso del MakerSpace, o cualquier cosa que se nos ocurra que no requiera mucho ancho de banda. Crear un nodo e incluirlo en la red TTN Madrid para que cualquiera pueda usarlo para repetir sus señales y crear una red más consistente y capaz.
> 
> 3. Taller construir un "Contador de días sin accidentes", parecido al instalado en la central nuclear donde trabaja Homer Simpson. En ASROB tenemos uno construido, de más o menos 60x40cm de tamaño, con dos dígitos tipo siete segmentos, y que se ilumina con LEDs direccionables WS2812. Además molaría conectar nuestro contador a vuestro contador, por LoRa, claro.
> 
> 
> Alguna que te parezca interesante?
> Saludos.

**Comment by VentressAsajj** [comment]
Yo tengo un Gateway de un canal de LoRa. Los de The things networks mad creo que tienen subido a github como se hace y un sensor de apertura de puerta.
Si queréis os lo busco.
Yo no me puedo comprometer por problemas laborables, si fuera por la tarde no me importa.

**Comment by JorFru** [comment]
Gracias por el ofrecimiento Asajj, pero estoy prácticamente seguro de que los materiales los va a poner el MakerSpace.

**Comment by JorFru** [comment]
Dice Fernando

> Hola Jorge,
> 
> Perfecto! Los 3 proyectos son muy interesantes, gracias por la iniciativa. Me pongo a moverlo a ver que fechas tenemos disponibles y os contacto a la vuelta,. 
> 
> Un saludo.

**Comment by JorFru** [comment]
Miércoles 20 de marzo, de 13 a 15h. Makerspace EPS UC3M, Leganés.
El contenido se puede consultar aquí:

**Comment by JorFru** [comment]
https://www.youtube.com/watch?v=RSujxnzPGc0
