### ISSUE TITLE
Compras herramientas hackatón

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#184]
Durante el hackatón, los organizadores nos percatamos de que igual nos faltaban herramientas y material:

- Mecanizar los tubos de PVC (había equipos que lo estaban intentando cortar con el soldador)
- Mucho pegamento caliente
- Elementos sorpresa

Estado de la inversión:
- Las herramientas que se compraron están todas en La Nave
- Los consumibles algunos quedan, otros se han gastado.
- Los elementos sorpresa algunos hay, otros perdidos (tampoco tenían mucho valor)

Salimos de compras exprés al chino de la calle peatonal, nuestro amigo el Comercio Zhonghua.
Adjunto el ticket.
![image](https://user-images.githubusercontent.com/11017088/51074975-b4207c00-1685-11e9-822c-7db379d76aad.png)

Está parcialmente impreso, no se puede comprobar el día de la compra, pero @David-Estevez estuvo para corroborar los hechos.

Abro votación para decidir si esto se paga con Piggy (yo pagué en metálico)
https://docs.google.com/forms/d/e/1FAIpQLSehRAwxfXhvxyXwE0dXrdM6xejw_0FRlyRBuLsaxtpEpZPQJw/viewform?usp=sf_link
Una semana de plazo para la votación.
Si resulta que sí, se traspasarían 22.40€ de los fondos de ASROB a Jorge Frutos.

**Comment by David-Estevez** [comment]
> Está parcialmente impreso, no se puede comprobar el día de la compra, pero @David-Estevez estuvo para corroborar los hechos.

Corroboro los hechos.

**Comment by JorFru** [comment]
Todavía no cierro la issue porque me quedan por cobrar ciento y pico de las pizzas y cuarenta y tanto de la bebida. Esto corresponde con el patrocinio de T3chFest.
