### ISSUE TITLE
Material desaparecido en el Hackatón

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#185]
En el último hackatón (noviembre 2018) desapareció material personal mío.
En concreto una caja de cartón que originariamente traía filamento de la marca Fillamentum, marcada con el nombre "maraña de cables", y que contenía cables de varios colores con recubrimiento siliconado de entre 12 y 30AWG cuyo valor monetario es de más de 60€.

Os aviso para que si la véis rodando por nuestras dependencias, me lo hagáis saber.

**Comment by David-Estevez** [comment]
No ha desaparecido, me la prestaste a mí y no la volviste a reclamar 😜. Está en mi casa.

**Comment by JorFru** [comment]
Fa fe fi fo fuuuuck

Devuélvemela
