### ISSUE TITLE
Creación de nueva asociación para la rama eléctrica

### ISSUE THREAD

**Issue by Lucas-LSM** [asrob-uc3m/actas#189]
Hol@:

Soy Lucas, delegado de titulación de ingeniería eléctrica. 
Queremos montar una nuevas asociación que tiene muchas cosas en común con ASROB (la parte de cacharrero de hardware) pero más enfocado al sector eléctrico (motores, cuadros y fuentes de alimentación, etc) y creo que os puede interesar. Aparte, otras tantas actividades que no serían cacharreo, como visitas a centrales eléctricas, apoyo con las prácticas de laboratorio, biblioteca de apuntes (física y online) y libros originales de ejercicios resueltos de circuitos, eso como ideas iniciales, pero abiertos a todas las que vengan.. 

Quería saber opiniones. En principio vamos a crear una asociación nueva, pero hasta que no nos la aprueben, no sabremos si dispondremos de espacio ni cuánto. Por eso planteo que en algún momento se pueda hacer colaboración de espacio con ASROB para talleres u ocasiones puntuales.

Soy todo oídos

**Comment by JorFru** [comment]
Lucas es Delegado el grado de Ing. Eléctrica y tiene muy buenas ideas.
Le conozco desde hace tiempo y hoy me ha contado esto.
Como es habitual, le he mandado a poner una issue.

Mientras me contaba su interés sobre fundar una nueva asociación de eléctrica se me ha ocurrido sugerirle crear una nueva rama de Ing. Eléctrica dentro de ASROB. Aunque la idea le ha gustado, hay razones por las que sigue prefiriendo crear una asociación a parte (tendrían más pasta y cumplirían con el deseo del director de grado (que es la persona que le ha encomendado crear la asociación a @Lucas-LSM ))

Si esto se resuelve por la vía de asociación nueva, posiblemente tengan problemas de espacio para algún taller puntual. Por lo que le he enseñado a @Lucas-LSM el método de issue tipo préstamo en la línea #176  de para proceder al préstamo de espacio en caso de necesitarlo.

**Comment by JorFru** [comment]
Ya se ha montado la asociación TestLAB Electric de forma independiente a ASROB.
Enhorabuena por la nueva asociación.
