### ISSUE TITLE
Semana de Asociaciones: Charla sobre Arduino + ESP8266

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#19]
Como todos sabréis (y si no sabéis, pues os podéis unir al [grupo de Telegram](https://telegram.me/joinchat/ADT1EAgigvgsuobGUHMl_w)) nos hemos comprometido a dar dos charlas en la Semana de Asociaciones (3-6 Octubre 2016):
 * Charla sobre Arduino + ESP8266 (propuesta por @Rodriwp)
 * ASROB: Ramas Activas ASROB

Esta issue gestiona las acciones a seguir para la correcta organización y realización de la actividad.

Las acciones a realizar son las siguientes:

* [x] Especificar si hay algún requisito especial de *aula, aforo, u otra necesidad ténica* (regletas, etc).
* [x] Rellenar la [ficha correspondiente](https://docs.google.com/document/d/1Zl6KjUbG76zPr87PInXLlOaWC8vj2hoXT3CErCTnrgY/) *lo antes posible* para entregársela a África.

**Comment by David-Estevez** [comment]
@Rodriwp esta issue es bastante urgente, ¿estás ya en ello?

**Comment by David-Estevez** [comment]
Jelooooooouuu @Rodriwp , África sigue esperando la respuesta!

**Comment by Rodriwp** [comment]
En cuanto a los requisitos, estan ya puestos en la ficha. 

Necesitaremos 10 kits de arduino +esp8266. Cuento que usaremos los que compremos en aliexpress #17 y los modulos que tegamos por ahi nosotros para tener 10 kits.

**Comment by David-Estevez** [comment]
> Se necesita una sala de ordenadores con el IDE de Arduino y el plugin de ESP8266  instalado

Creo que eso va a ser bastante improbable, @Rodriwp . ¿Pedimos mejor que la gente se traiga un portátil (Con el IDE y plugin instalado)?

> necesitaremos una ip fija para el taller que nos permita conectar el servidor en la sala de ordenadores en al que estemos.

También se puede hacer con un router y una LAN, no hace falta tener una IP fija, ¿no?

**Comment by David-Estevez** [comment]
Voy a hacer esos cambios y a entregarlo, que llevamos más de una semana con esto y la conversación no es muy fluida que se diga :sweat_smile: 

@Rodriwp Los requisitos e instrucciones de instalación de todo lo que necesites para el taller irán en esta página: http://asrob.uc3m.es/index.php/Semana_Asociaciones:_Arduino_%2B_ESP8266 Acuérdate de editarla con tiempo antes de la actividad para que la gente vaya con todo preparado de casa.

**Comment by jgvictores** [comment]
Info extraida del [horario oficial de la Semana de Asociaciones](http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/eventos/semana_asociaciones/Campus%20de%20Legan%E9s1)
> 9.00 a 12.00 h.
> Edificio y Aula por determinar.
> Código 35. Taller “Monta un servidor sencillo con Arduino y ESP8266”. ESTA ACTIVIDAD COMPUTA CON 2 SELLOS
> Construiremos un servidor web sencillo con un Arduino y un módulo ESP8266.
> ASROB

¿Cómo proceder?

**Comment by jgvictores** [comment]
BTW, actualizado el horario, que el copy+paste me la jugó.

**Comment by Rodriwp** [comment]
Hay que comprobar que tenemos los recursos necesarios. Sala de ordenadores con arduino instalado con soporte para esp8266. Si no es asi, tendremos que pedir que la gente venga con portatil y hacer el taller en la nave o en una clase del edificio 1

**Comment by jgvictores** [comment]
No cuentes con que instalen nada, por eso siempre pedimos portátiles. La ventaja de las aulas informáticas es que hay más enchufes para los portátiles.

**Comment by David-Estevez** [comment]
Como comentamos cuando rellenamos la ficha de la propuesta del taller, es casi imposible que los de informática nos dejen instalar ningún software en los ordenadores de la universidad.

Por tanto, deberíamos tener en internet (por ejemplo, en la wiki) una guía para el taller que incluyese:
   * Requisitos del taller: traer portátil con software instalado
   * Guía paso a paso de cómo instalar dicho software

Después sería tan sencillo como poner ese enlace en la web de la semana de asociaciones.

PD: aún así, y por experiencia propia, no esperes que más del 50% de los asistentes traigan el software instalado, así que probablemente debas dedicar 10-15 min del taller a la instalación de todo lo necesario.

**Comment by David-Estevez** [comment]
Y las aulas probablemente ya estén reservadas (aunque no lo sé seguro), porque la solicitud incluía un apartado de requisitos (como el tema de las regletas para los portátiles).
