### ISSUE TITLE
Feria de asociaciones de abril

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#191]
26 de Abril 2019, césped de Leganés.

Asociaciones de la UC3M EPS organizan una segunda feria de asociaciones. Ya hay una anual allá por octubre, esta es otra, con el objetivo de fomentar las actividaes en asociaciones.

Horario de exposición de 11 a 17h (aunque el doodle diga desde las 10). Media hora por delante y por detrás para montar y desmontar. Aproximadamente. Se puede llegar más tarde, pero el que antes llega pilla mejor sitio.

**IMPORTANTE! Se necesitan personas que cubran el evento: estar allí demostrando y vigilando los robots y nuestras creaciones.**
Actividad extra: hackeo en vivo. Se realizarán tareas parecidas a las que se llevan a cabo dentro de la nave, pero puertas abiertas para que el SAV le pique a los visitantes.
Y después cervezas, entre todas las asociaciones.

Se propone Doodle para indicar disponibilidad.
https://doodle.com/poll/n8hxeb8f7c35nx4b
Votad!

**Comment by GioSunrider** [comment]
Yo me comprometo a cubrir la tarde, es decir a partir de las 14:30 que llegó aprox de currar.

**Comment by David-Estevez** [comment]
Yo todavía no puedo asegurar nada, pero de poder sería por la tarde.

**Comment by JorFru** [comment]
¿Qué os parece ponernos al lado de UC3Music y así compartir recursos humanos?
Empalmar las mesas y cuidar nuestros proyectos mutuamente.

**Comment by David-Estevez** [comment]
:+1:

**Comment by MrTommyGuns** [comment]
Hay un grupo de WhatsApp para organizarnos y han recomendado que nos metamos 2 personas por asociación.
Estamos Lago y yo metidos por parte de Uc3music peroo supongo que podemos estar también en representación de Asrob, aunque de todos modos si se metiese alguien más podría estar guay

**Comment by JorFru** [comment]
He colocado los carteles en nombre de ASROB

**Comment by JorFru** [comment]
Gracias a todos los colaboradores que participaron.
Recordad que la próxima vez tenéis que recoger las mesas, que nos han llamado la atención y no es la primera vez.

**Comment by arturfcesped** [comment]
cuando la siguiente feria?

**Comment by JorFru** [comment]
> cuando la siguiente feria?

Por ahora y con motivo de la pandemia no se considera hacer Feria hasta el curso que viene por lo menos.

Te sugiero que nos sigas en redes sociales para enterarte de las próximas fechas. Twitter e Instagram son las únicas que funcionan ahora mismo.
Un saludo
