### ISSUE TITLE
Ha desaparecido el alargador

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/actas#192]
Ayer cuando llegue a la nave a la reunion de Printer One, me percate que habia desaparecido el alargador de 4 conexiones que tenia el cable kilometrico.

**Comment by GioSunrider** [comment]
Alargador/Ladrón encontrado, está en uno de los ABB que usa @daeste, en su defecto hay un ladrón sustituyéndolo aunque no es tan largo hace su función.

**Comment by David-Estevez** [comment]
Sí, ha sido culpa mía. Cogí el alargador blanco para un experimento con los ABB, dejando como repuesto una regleta un poco más corta para sustituirlo. La idea era devolverlo pronto, pero no pude acabar los experimentos porque había prácticas ese día y se me pasó totalmente el avisar. Sorry :sweat_smile:
