### ISSUE TITLE
Semana de Asociaciones 2019

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#193]
Nos ha llegado un correo de Montserrat (la nueva África) sobre la Semana de Asociaciones:

> Queremos informaros de las fechas de la VI Semana de las Asociaciones que se celebrará del 30 de septiembre al 04 de octubre, en los campus de Leganés, Getafe y Colmenarejo.
>
> La VI Semana de Asociaciones quiere reflejar el entusiasmo de las Asociaciones de Estudiantes de la UC3M y de la Delegación de Estudiantes por mostrar el importante trabajo que desarrollan en la universidad. Se realizarán talleres, conferencias, video-forum, mesas redondas…
>
> Como en años anteriores, tenemos que proceder a la reserva de espacios, así como a la publicación en web y Aula Global de las actividades.
> 
> Para conocer el número de asociaciones que participará en estos actos, y las necesidades de las mismas, nos gustaría nos comuniquéis vuestra asistencia, mediante el formulario que os adjunto, antes del 10 de julio. Nos gustaría contar con 11/12 actividades en cada campus. Adjunto los cuadrantes horarios de los diferentes campus para que los tengáis en cuenta.

TL;DR:

* Este año se va a volver a organizar una Semana de Asociaciones, pero no vamos a tener a África para presionarnos a proponer cosas porque ya no lleva el tema.
* Aún asi, es importante organizar alguna charla / taller porque hay que mostrar que las Asociaciones estamos activas para luego poder optar a subvenciones, etc y que no reduzcan / cierren el programa de Asociaciones.
* Nos piden propuestas de actividades **antes del 10 de Julio**

Sé que este año muchos no vamos a estar aquí por esas fechas, pero estaría bien que comentáseis por aquí si vais a estar o no y si se os ocurre alguna charla / taller que dar, a ver si sacamos algo adelante.

**Comment by JorFru** [comment]
Se presentó algo por parte de ASROB?

**Comment by DAG00DAG33** [comment]
Si, una charla y un taller
El taller para montar un theremin

**Comment by JorFru** [comment]
Genial.

Y la charla, alguien tiene información de ella?

**Comment by JorFru** [comment]
Charla: Conoce ASROB


Taller: Theremin



Necesitamos mano de obra para organizar y dar estas actividades

**Comment by jgvictores** [comment]
Copio de Telegram:

> CÓDIGO 09 - 1 de Octubre 16:00-19:15h: ASROB. Monta un Theremin (3h) (Aula 1.0.F02)
> CÓDIGO 18 -  3 de Octubre 17:30-19:45h ASROB. Charla: Conoce ASROB (1,30h) (Aula 7.1.H01)

Por cierto, no cuadran muy bien horario final-inicio vs duración.

**Comment by jgvictores** [comment]
Ok, en cartel oficial pone ese horario inicio a final.

![IMG_20191002_165501_870](https://user-images.githubusercontent.com/4448588/66055274-93f75c80-e535-11e9-8caf-5614e7e240f4.jpg)

**Comment by JorFru** [comment]
Única foto que tengo. Grande Tommy.
allí estuvimos con robots en la calle y una impresora pasando frío y dando thermal runaway todo el rato. Nos vemos en la siguiente.
![imagen](https://user-images.githubusercontent.com/11017088/69811811-30b14000-11ef-11ea-9d42-ca486bc6f454.png)

**Comment by JorFru** [comment]
![imagen](https://user-images.githubusercontent.com/11017088/69811985-98678b00-11ef-11ea-9534-2fea1cceb63b.png)
![imagen](https://user-images.githubusercontent.com/11017088/69811993-9bfb1200-11ef-11ea-8a84-6e2269d68c9a.png)
Fotos del taller de Arduino
