### ISSUE TITLE
La puerta se cierra

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#194]

**Comment by JorFru** [comment]
Resuelto
https://www.thingiverse.com/thing:3728319
![photo_2019-07-04_01-46-00](https://user-images.githubusercontent.com/11017088/60631085-e07bb080-9dfd-11e9-949d-934910964a5f.jpg)
![photo_2019-07-04_01-45-58](https://user-images.githubusercontent.com/11017088/60631087-e1144700-9dfd-11e9-95a6-4535f59e99bd.jpg)

**Comment by PeterBowman** [comment]
Dos cosas:

* Sugerencia: pondría el enganche para la cuerda en el otro lado, no en el del pasillo sino en el que da al interior de la nave.
* He roto la cuerda. Perdón. (Alguien puso este invento en la parte móvil de la puerta, no en la que está fija. Al tirar, se rompió la cuerda. Posiblemente fuese por el punto anterior, alguien pensaría que el enganche debería estar hacia dentro y lo puso así.)

**Comment by JorFru** [comment]
Tienes razón. Es un bug bastante gordo.
Voy a modificar el archivo fuente TopePuertaNave.FCStd con un agujero para la cuerda por el lado de dentro y generar un nuevo .stl para imprimir.


El asunto de poner el tope en la hoja móvil de la puerta parece un problema de usuario. No se me ocurre cómo bloquear la posibilidad de ponerlo en la hoja móvil para que no suceda esto.
Para mí no es intuitivo ponerlo mal, pero ya ves.

**Comment by JorFru** [comment]
https://www.thingiverse.com/thing:3728319/files


TopePuertaNave2.stl ya está disponible para imprimir

**Comment by GioSunrider** [comment]
Ayer imprimimos en PRinter la nueva version y la dejamos instalada. Esperemos ahora sea mas eficaz y nadie se la cargue.
![photo5875072248392561452](https://user-images.githubusercontent.com/10605193/61567631-8840e180-aa80-11e9-8ab2-938e0d08d1b4.jpg)
