### ISSUE TITLE
Limpieza del techo de la Nave

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#195]
Recibido por mail personal:

> Buenos días:
>
>Se informa de que desde el día 2 de Julio hasta el día 12 de Julio de 2019 se van a realizar las tareas de limpieza en el techo acristalado de los despachos de la planta 1ª del edificio Betancourt.
>
> Los operarios realizarán las tareas desde la pasarela, por lo que existe riesgo de caídas de objetos en la planta baja.
>
>La realización de los trabajos en cada uno de los espacios se indicará mediante carteles de advertencia en los accesos a la nave.
>
>Se recomienda que no se acceda a las zonas indicadas, y en caso de que sea necesario, no acercarse a la zonas acotadas.

**Comment by GioSunrider** [comment]
Creo que esto se pujede dar por cerrado, gracias @David-Estevez por el aviso.
