### ISSUE TITLE
Something's coming

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/actas#197]
Algo nuevo se acerca, el dia que llegue a la nave lo anunciare. Pero de momento dejo la issue y asi os genero un poquito de hype.

**Comment by GioSunrider** [comment]
El próximo día de reunión, se desvelará la sorpresa.

**Comment by JorFru** [comment]
Tiene ruedas

**Comment by David-Estevez** [comment]
Desearás que las tenga...

**Comment by GioSunrider** [comment]
Bueno, pues la sorpresa de desveló, una impresora donada por parte de Moebyus Machines. 
Hay que iniciar los procedimientos para darle de alta en nuestro sistema y buscarle hueco. (Pendientes de subvenciones) 
Ya que ahora mismo estamos desbordados.
En adelante subire las fotos que tengo de ella.

**Comment by GioSunrider** [comment]
Aqui fotitos 
![photo6039654909843976343](https://user-images.githubusercontent.com/10605193/66597413-3ac7a280-eb9f-11e9-8656-af57e155f2dc.jpg)

**Comment by jgvictores** [comment]
@GioSunrider Cierras issue? Entiendo q es de tipo `aviso`, que podemos cerrar tras 1 mes. ^^

**Comment by GioSunrider** [comment]
Todo realizado y pasado a donde corresponde cierro la issue.
