### ISSUE TITLE
Reunion inicio de curso.

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/actas#198]
Como todos los años, propongo una reunion de inicio de curso la semana que viene. En ella trataremos de vernos las caras y presentar la situacion del año venidero y propongo ademas los siguientes temas.

- [ ] Cerrar issues pendientes y antiguas.

- [ ] Preparar ideas de subvenciones para el proximo curso y asi no nos pilla el toro como el año pasado.

Dejo el [doodle](https://doodle.com/poll/qyxvpig4u7mv7dwy) para el final de esta semana y la semana que viene. Lo dejo abierto hasta el jueves!

**Comment by GioSunrider** [comment]
Se ha cerrado el doodle, la reunión será el Miércoles 11 de Septiembre de 19:00 a 21:00.

**Comment by GioSunrider** [comment]
A los temas por tratar de añaden la presentación para los nuevos, así como ver si se asistirá a las ferias de tecnología que están al caer.

**Comment by JorFru** [comment]
El acta, señores.
https://github.com/asrob-uc3m/actas/blob/master/reunion-2019-09-11.md
