### ISSUE TITLE
Patrocinios RoboKode 2015

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#2]
En la reunión del 24/02/2016 se propuso revisar los patrocionios del RoboKode 2015.

Tareas a realizar:

* [x] Realizar relación de patrocinios gastados vs patrocinios por gastar
* [x] Seleccionar productos a comprar
* [ ] Gastar dinero

cc Tesorero: @Rodriwp

**Comment by Rodriwp** [comment]
Esta informacion la tiene @raulperula 
En cuanto pueda que mande un correo a la junta con toda la información, para que la tengamos todos.

Tambien hay que hacer el traspaso de poderes en la tesoreria

**Comment by Rodriwp** [comment]
ya se han realizado todas las operaciones correspodientes a esta issue. Datos publicados y operaciones de compra en marcha
