### ISSUE TITLE
Ayudas IEEE: Ayudas a las ramas 2015-2016

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#20]
A la atención del tesorero (@Rodriwp):

> Estimad@s compañer@s;
> 
> Os escribo para informaros de la fecha tope para pedir las ayudas a las ramas que se os asignara en la convocatoria 2015-2016 es el 31 de Julio. Después de esa fecha ya no será posible reclamar el importe adjudicado.
> 
> Recibid un cordial saludo;

https://groups.google.com/d/msg/miembros-activos-asrob/yJjVC0IcLog/PzRkjUP2AQAJ

**Comment by Rodriwp** [comment]
Piggy dice que pidamos la ayuda. Fecha tope para tener todos los papeles preparados 24/06/2016

**Comment by David-Estevez** [comment]
Confiamos en ti, tesorero!

**Comment by Rodriwp** [comment]
Respecto a esta issue es para reclamar las ayudas que nos hubieran asignado. En nuestro caso no me consta que hayamos pedido ninguna ayuda en octubre 2015.

En cualquier caso, el IEEE nos ha dado un dinero para este año que ya tenemos en nuestra cuenta. Lo unico a tener en cuenta es que tenemos que rellenar todo el papeleo IEEE  que antes hacia raul.
Estaria bien que nos asesosrara a ser posible. @David-Estevez y @jgvictores , teneis documentacion del IEEE del año pasado ? Basicamente creo que seria entregar lo mismo modificado.

**Comment by David-Estevez** [comment]
Yo imagino que el antiguo tesorero sí que llegaría a pedir ayudas al IEEE en Octubre, pero no sé nada a nivel oficial, dado que éste no proporcionó información alguna a ASROB de las actividades que se iniciaron cuando él aún estaba en el cargo (y que siguen en vigencia) cuando se llevó a cabo el traspaso de la tesorería.

En resumen, te tocará mirar correos antiguos de la cuenta de ASROB en caso de que el antiguo tesorero llevase los trámites desde el correo oficial y no desde alguno personal. Si no encuentras nada, lo suyo sería ponerse en contacto con la gente del IEEE y explicarle la situación (traspaso de poderes y total desconocimiento por nuestra parte de los trámites a seguir). También habría que ver quién figura como "Student Branch Chair" y actualizar el cargo para que lo ostente algún miembro activo.

**Comment by jgvictores** [comment]
[Aquí enlace](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/miembros-activos-asrob/UsAGLo1RXZg/tMd5_00wBwAJ) al email de la reunión del IEEE del 14 de Julio. En realidad es una teleconferencia, pero yo estaré fuera, en reunión y/o con mala cobertura. Estaría bien que alguien de la Asociación se pudiese conectar.

**Comment by David-Estevez** [comment]
Cierro issue por finalización de plazos.
