### ISSUE TITLE
Viaje a la OSHWDem /A Coruña/ 9-Nov-2019

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#200]
Que se apunten a continuación las personas interesadas en viajar. Y ya veremos la forma de conseguir las ayudas necesarias.

**Comment by JorFru** [comment]
Yo voy

**Comment by MrTommyGuns** [comment]
+1

**Comment by GioSunrider** [comment]
Me too

**Comment by MrTommyGuns** [comment]
@L4g0 también se apunta

**Comment by VentressAsajj** [comment]
yo, yo voy :D

**Comment by GioSunrider** [comment]
Hasta que día damos de margen para algún rezagado?

**Comment by JorFru** [comment]
Las plazas subvencionadas ya están completas.
Por parte de ASROB son dos:
Gio, Asajj.
Por parte de UC3Music son tres (debido a que además del stand llevamos un taller)
Tommy, Lago, JorFru

**Comment by GioSunrider** [comment]
Vale, como lo organizamos?

**Comment by JorFru** [comment]
La organización pide que se optimice lo máximo posible el transporte para abaratar costes.
Fletar un coche particular y llenarlo con cinco personas es lo mejor.
Creo que está claro el plan.

**Comment by GioSunrider** [comment]
Eso lo imaginaba, me refería más a tema de salir jueves o viernes, a quien hace la inscripción, etc

**Comment by JorFru** [comment]
La inscripción está echada
Vamos en mi furgo
Y por mí salimos el jueves después de comer.

**Comment by GioSunrider** [comment]
Vale, la hora la vemos, que yo trabajo el jueves 😅, y me gustaría hacer lo que hizo (hiciste @JorFru) de las tarjetas plastificadas de los proyectos. Me parece la mejor idea de gestion

**Comment by GioSunrider** [comment]
Por cierto propongo llevar, zowis, arcade y a roverto como lo veis?

**Comment by JorFru** [comment]
No sé el estado actual del proyecto Roverto, llevaría además a ProjectX que al menos está terminado.

**Comment by David-Estevez** [comment]
Siento comunicar que el Project X no está ni funcional, ni en la asociación ahora mismo .Al menos el mío, que creo que es el único que llegó a funcionar alguna vez.

**Comment by GioSunrider** [comment]
Roverto está "funcional" osea teleoperado y FPV verdad?

**Comment by David-Estevez** [comment]
Creo que yo no fui la última persona que lo tocó, así que no sé decirte. Es tan sencillo como conectarle el mando y ver si anda...

**Comment by GioSunrider** [comment]
Mañana le pruebo y valoramos, si no me lo llevo y le pongo a punto para al menos moverlo telemáticamente

**Comment by David-Estevez** [comment]
Decidle a Julián que se lleve el Zowi Make, que está acabado y es vistoso :+1:

**Comment by JorFru** [comment]
![imagen](https://user-images.githubusercontent.com/11017088/69812346-45da9e80-11f0-11ea-801b-1f84c8e8ee95.png)
![imagen](https://user-images.githubusercontent.com/11017088/69812356-4a06bc00-11f0-11ea-825f-e7e466b9be29.png)
Lo pasamos pirata!
