### ISSUE TITLE
Nuevo responsable de Printer One

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/actas#201]
Tras presentar mi [baja](https://github.com/asrob-uc3m/actas/issues/153) como responsable el año pasado, aún conservaba un juego de llaves en calidad de segundo responsable "oficioso" de Printer One.

En la [reunión](https://github.com/asrob-uc3m/actas/issues/198) de inicio de curso de la semana pasada, traspasé mi juego de llaves (nave + armario + candados de las impresoras) a @MrTommyGuns , llamado a ser el [próximo responsable del grupo](https://github.com/asrob-uc3m/impresoras-asrob/issues/147). ¡Larga vida @MrTommyGuns !

![photo6039654909843976300](https://user-images.githubusercontent.com/6171234/64912157-8d8e7580-d72b-11e9-838e-e182c005673a.jpg)

A partir de este momento, yo ya no tengo ninguna llave relacionada con ASROB.

Acciones:

- [x] Traspasar las llaves a @MrTommyGuns : hecho.

- [x] Actualizar la información en la [web](https://asrob.uc3m.es/workgroups/2017-05-28-printer-one.html). Invoco a @GioSunrider y/o a @MrTommyGuns para ello.

**Comment by Siotma** [comment]
Web actualizada vía d9d01546c601aa403a0c422ab0e703a991697a11 . No recordaba que fuera tan fácil.

**Duda**: ¿Hay algún otro sitio donde actualizar esto? cc @David-Estevez @jgvictores

**Comment by jgvictores** [comment]
> Hay algún otro sitio donde actualizar esto?

Creo que eso es todo, y que puedes cerrar issue sin problema!

**Comment by Siotma** [comment]
Gracias!
