### ISSUE TITLE
Solicitud espacio Asrob para UC3Music

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/actas#202]
Buenas,

Nos gustaría poder usar el espacio de trabajo de Asrob si no hay ninguna reunión planificada para el día 23/9/19 de 17h a 21h.

Un saludo de parte de UC3Music.

**Comment by MrTommyGuns** [comment]
A mi me parece correcto, estos chicos son muy majetes.

**Comment by GioSunrider** [comment]
Por mi ningún problema, siempre y cuando no haya auto para no llamen la atención.

**Comment by MrTommyGuns** [comment]
Hoy creo que han tenido de 15 a 17

**Comment by MrTommyGuns** [comment]
Se ha concedido la utilización del espacio por medio de una votación via Telegram.

![image](https://user-images.githubusercontent.com/36898802/65185023-00b72500-da67-11e9-9e04-3b81d177298f.png)

Gracias!!! ^^

**Comment by JorFru** [comment]
No tan rápido, vaquero.
Hay que subir aquí una foto que demuestre el buen uso que le hemos dado al espacio de La Nave.

**Comment by David-Estevez** [comment]
Me parece una idea genial lo de crear votaciones en Telegram para cosas rápidas y no muy críticas para la asociación. Reduce la burocracia, es más cómodo y nos da más agilidad. Pero me gustaría también recordar que la forma actual de proceder es esta: https://github.com/asrob-uc3m/estatutos/blob/master/metodo_de_votacion.md, y que si queremos cambiarla o ofrecer formas alternativas de votación para ciertos casos hay que seguir el método tradicional de "issue + votación Google Forms".

Así que ya sabéis... 
![image](https://user-images.githubusercontent.com/1451819/65228108-2de8ef00-daca-11e9-87df-f95e754ae87c.png)

**Comment by JorFru** [comment]
Hicimos el friki correctamente y no rompimos nada

![photo_2019-10-08_12-16-51](https://user-images.githubusercontent.com/11017088/66391756-49129480-e9ce-11e9-8561-19aa9d8f7267.jpg)
![photo_2019-10-08_12-16-50](https://user-images.githubusercontent.com/11017088/66391758-49129480-e9ce-11e9-9abe-9c82ecd0d0f0.jpg)
![photo_2019-10-08_12-16-49](https://user-images.githubusercontent.com/11017088/66391759-49129480-e9ce-11e9-88b3-79cecfea8b41.jpg)
