### ISSUE TITLE
Nos han invitado a la Bilbao MakerFaire

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/actas#203]
El año pasado nos invitaron y no fuimos.

Alguien se anima a ir y representar a ASROB llevando robotillos? Pagan todo el viaje y el alojamiento.

Se pueden llevar los Zowis, por ejemplo.

Será los días 1, 2 y 3 de Noviembre, de viernes a domingo.
Más info: https://bilbao.makerfaire.com/

Hay que rellenar el C4M en caso que alguien se anime.

**Comment by JorFru** [comment]
Yo no puedo, sorry.

**Comment by David-Estevez** [comment]
Yo tampoco :(

**Comment by JorFru** [comment]
Plazo de inscripción hasta el 27 de Septiembre
