### ISSUE TITLE
Solicitud espacio ASROB para UC3Music

### ISSUE THREAD

**Issue by L4g0** [asrob-uc3m/actas#204]
Buenas, Nos gustaría poder usar el espacio de trabajo de ASROB si no hay ninguna reunión planificada para el día 30/09/19 de 17h a 21h.

No hay clase simultáneamente, por lo que no se molestaría.

Como dicen los estatutos dejo aquí el link para la votación: https://forms.gle/mJFPhfiLbvtbPuAeA

Deadline el 27/09/2019 a las 23:59.

**Comment by David-Estevez** [comment]
El día 30 de Septiembre hay clase de: 9.00 - 11.00 y de 13.00 - 17.00

(Que no creo que sea un problema porque sois gente civilizada, pero just for your information)

**Comment by JorFru** [comment]
Vamos a ir a tocar la guitarra y el bajo (just for your information)

**Comment by JorFru** [comment]
El ampli es 5W

**Comment by JorFru** [comment]
He hablado con Ramón Barber, to majete ahí el hombre.
Dice que nos autoriza.

**Comment by David-Estevez** [comment]
Segovia lo sabe?

**Comment by JorFru** [comment]
No, porque según él eso es un evento chusquero

**Comment by L4g0** [comment]
Fotillas del montaje

![image](https://user-images.githubusercontent.com/23212123/66262370-608b2b00-e7de-11e9-85f2-da7f7aad649c.png)
![image](https://user-images.githubusercontent.com/23212123/66262371-64b74880-e7de-11e9-9e96-4270f94a8e21.png)
![image](https://user-images.githubusercontent.com/23212123/66262374-6a149300-e7de-11e9-83af-662bdb56af1b.png)
![image](https://user-images.githubusercontent.com/23212123/66262375-6ed94700-e7de-11e9-8583-6a8e8412ab69.png)
![image](https://user-images.githubusercontent.com/23212123/66262378-78fb4580-e7de-11e9-8a75-6b087e856e5f.png)
![image](https://user-images.githubusercontent.com/23212123/66262380-7c8ecc80-e7de-11e9-943c-79dd2bbf9eae.png)
![image](https://user-images.githubusercontent.com/23212123/66262382-7f89bd00-e7de-11e9-89ac-ec8beedab286.png)
