### ISSUE TITLE
Prestamo soldadores para taller TeslabElectric

### ISSUE THREAD

**Issue by DiegoGarciaX2** [asrob-uc3m/actas#208]
Me ha comentado lucas, el presidente de TesLab, que va a hacer un taller de soladura en el maker y que le gustaria tener un par de soldadores mas a mano para que todo el mundo pueda cacharrear. Seria este miercoles.

**Comment by JorFru** [comment]
Podríais especificar qué soldadores se necesitan en particular? Porque sólo hay una estación Baku y un TS80 operativo, creo que la cesión del JBC ST-30 de UC3Music ya CC voló.
CC @Lucas-LSM

**Comment by jgvictores** [comment]
* Teníamos muchos estilo <https://www.electronicaembajadores.com/es/Productos/Detalle/HRJP005/herramienta/soldadores-electricos/soldador-electrico-lapiz-30w> tb

**Comment by GioSunrider** [comment]
Siguen los verdes por alguna caja, y de hecho en calor creo que había también alguno.

**Comment by JorFru** [comment]
Taller realizado.
No se ejecutaron préstamos.
