### ISSUE TITLE
Memoria de Asociaciones 2019

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#209]
Ha llegado el momento del año que tod@s esperábamos: la entrega de la Memoria de Asociaciones de 2019

# Resumen
* **Qué hay que hacer**:  Rellenar y entregar la Memoria de Asociaciones, que incluye todo lo que hemos hecho este año. Añadir la junta de la asociación actualizada: director, secretario, tesorero.
* **Cuándo es el plazo de entrega**: el plazo acaba el **18 de Diciembre de 2019**.
* **Quién se debería encargar de este ~~marrón~~ trámite**: los responsables de cada Grupo de Trabajo Activo, organizadores de actividades de ASROB y miembros de la Junta. Pero cuantos más seamos para escribir cosas, mejor.
* **Por qué hay que hacer esto**: es un trámite obligatorio para todas las asociaciones de la universidad. No cumplirlo supone la baja en el registro de asociaciones.

**Comment by madelgj** [comment]
18 de diciembre de 2018?

**Comment by David-Estevez** [comment]
Obviamente no :rofl: 

Editado
