### ISSUE TITLE
Petición de financiación desde los fondos de ASROB

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#21]
## Petición de financiación desde los fondos de ASROB

En [Robot Devastation](https://github.com/asrob-uc3m/robotDevastation) estamos desarrollando una plataforma robótica que será la base de la siguente generación de [Robot Devastation](https://github.com/asrob-uc3m/robotDevastation), basándonos en diseños de robots omnidireccionales.

Para el prototipo necesitamos:

| Item | Cantidad | Coste unitario | Coste |
| --- | --- | --- | --- |
| [Conversor DC-DC de dos canales](http://www.hobbyking.com/hobbyking/store/__46630__Dr_Mad_Thrust_series_3A_BEC_with_Inbuilt_Aux_Controlled_On_Off_Switch_for_Accessories_UK_UK_Wareh.html) | 1 | 8.37€ | 8.37€ |
| [Motores 6V 300RPM](http://es.aliexpress.com/store/product/300RPM-25GA-6V-DC-High-Torque-Electric-Gear-Box-Motor/1668679_32289853212.html) | 3 | 7.81€ | 23.43€ |
| [Ruedas omnidireccionales](http://www.robotshop.com/en/58mm-plastic-omni-wheel-lego-nxt-servo.html) | 3 | 6.47€ | 19.41€ |
| [Raspberry Pi Zero (Basic kit)](https://thepihut.com/products/raspberry-pi-zero) | 1 | 20.88€ | 20.88€ |
| Total: | - | - | 72.09€ |
| Con gastos envío: | - | - | ~80€ |

Sabiendo que hay fondos ASROB disponibles para los distintos proyectos de las distintas ramas activas, solicitamos hacer uso de ellos para financiar ese prototipo.

La votación: http://goo.gl/forms/t4PAsDouWCfJthnE2, fecha límite **Julio 6, 23:59h**

**Comment by Rodriwp** [comment]
Creo que faltan algunos datos para la petición del dinero.
-  Enlace al proyecto en la wiki
-  Urgencia en la recepcion de materiales (Pedir en aliexpress y ahorra pasta).

En cuanto al metodo de votación, me aprece adecuado. Puesto que son los miembros activos que revisan wiki y github amenudo los que deben decidir que hacer con los fondos

**Comment by David-Estevez** [comment]
> Creo que faltan algunos datos para la petición del dinero.
> 
>    * Enlace al proyecto en la wiki

En la descripción de la issue hay **dos** enlaces al proyecto en GitHub, que a su vez tiene enlaces a la wiki, además de que creo que es sobradamente conocido entre los miembros activos.

>   * Urgencia en la recepcion de materiales (Pedir en aliexpress y ahorra pasta).

Si revisas la lista, verás que lo que se puede pedir a Aliexpress se ha contemplado ya en los enlaces. El resto de cosas no las hay en Aliexpress, por lo que se han seleccionado proveedores alternativos. Otro elemento a tener en cuenta cuando se eligen componentes es la calidad de los mismos. Si, pongamos un ejemplo, Aliexpress me vende una cámara a 2$, pero de cada 4 que compro me funciona bien una (o la resolución es una :hankey: y acabo teniendo que comprar otra), realmente no me estoy ahorrando tanto. Si es un poco más caro pero nos ahorra tiempo, en mi opinión, merece la pena pagar la diferencia.

**Comment by Rodriwp** [comment]
Si ese estudio ya esta entonces perfecto.

**Comment by David-Estevez** [comment]
El resultado de la votación fue **favorable**. Se prodecerá pues a a la compra de dichos materiales.

**Comment by David-Estevez** [comment]
Cerrada por inactividad (> 1 año)
