### ISSUE TITLE
Revisar la composición de la Junta Directiva de forma anual

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#214]
Siguiendo https://github.com/asrob-uc3m/estatutos/blob/36daef4dc74be6b4002abbd8530f9a56b33bdef3/metodo_de_votacion.md#m%C3%A9todo-de-votaci%C3%B3n -> Revisar la composición de la Junta Directiva de forma anual.

Por agilizar:

- Usemos este hilo para Presi, Secre, Tesor
- 24 h para candidaturas

**Comment by elfantasmadeasrob** [comment]
Cerrado por GOLPE DE ESTADO :fist_left:
