### ISSUE TITLE
Recursos digitales de la asociación

### ISSUE THREAD

**Issue by JavierIH** [asrob-uc3m/actas#22]
Hola chicos,

En la wiki de AsRob tenemos un [maravilloso apartado](http://asrob.uc3m.es/index.php/Redactar) con pautas y consejos para redactar documentos científicos, destacando TFGs y TFMs.

Pienso que podría ser interesante guardar las plantillas, tanto de texto como portadas, en un repositorio aquí en GitHub. Razones:

- Poder hacer revisiones y mejoras.
- Poder forkarlas para escribir cada uno su propio proyecto.
- GitHub es un lugar seguro y será fácil encontrar los archivos en cualquier momento (Hace unos meses la página de AsRob de cayó y me puse muy nervioso).

La motivación de esto es que me gustaría hacer un PR a la portada de TFMs (migración de pptx a svg).

¿Qué opináis?

**Comment by David-Estevez** [comment]
+1

**Comment by JavierIH** [comment]
Entonces que tal si:

1. Abro un repo llamado "recursos-digitales".
2. Hago un primer commit a nombre de "asrob" con los archivos que tenemos.
3. Se acompaña de un README con las atribuciones de los archivos actuales.

**Comment by jgvictores** [comment]
Perfecto. Llevo tiempo queriendo migrar lo de https://svn.code.sf.net/p/asrob/svn/admin/, sobre todo los logos. ¿Puedes tener los ficheros en cuenta para la organización de la nueva repo?
Si directmente los copias como te parezca, puedo encargarme de borrar los de sf.net.

**Comment by JavierIH** [comment]
Podemos intentar migrarlo, pero realmente de ahí creo que solo nos interesan algunos archivos y la mayoría son cosas gráficas que no tienen historial de modificaciones.

Analizando carpeta a carpeta:
Cartel_Asociaciones_old son bastante "old"
Inventario/  ¿Son pegatinas de RD?
Logos/  Material valioso
Memorias/ ¿Queremos que estén en el nuevo repo?
Merchandising/ También parece un poco "old"
Multimedia/ ¿Quizás mejor en un drive/dropbox?
Presentaciones/ Material valioso. Podría juntarse con las presentaciones de eventos pasados y futuros.

Personalmente, no he migrado nunca cosas de svn a git, quizás puede ser un lio al ser un repo muy grande (3,8gb) que incluye tambien los proyectos de la asociación.

También ocurre que un repo con este tipo de archivos se va a saturar enseguida. Quizás es razonable dividir en varios repositorios. De momento podría ser uno de plantillas y logos, luego podemos abrir uno de presentaciones (y meter también las presentaciones de las charlas de los eventos), memorias... Según se vayan necesitando.

**Comment by jgvictores** [comment]
> Cartel_Asociaciones_old son bastante "old"

Pueden ir al Drive existente, a ver si lo podemos organizar mejor.

> Inventario/ ¿Son pegatinas de RD?

Jeje, no, son las pegatinas que se utilizan para el Inventario. Quizás al Drive.

> Logos/ Material valioso

**Sí, éste para mí era lo principal.**

> Memorias/ ¿Queremos que estén en el nuevo repo?

Pueden ir al Drive existente, a ver si lo podemos organizar mejor.

> Merchandising/ También parece un poco "old"

Pueden ir al Drive existente, a ver si lo podemos organizar mejor.

> Multimedia/ ¿Quizás mejor en un drive/dropbox?

Pueden ir al Drive existente, a ver si lo podemos organizar mejor.

> Presentaciones/ Material valioso. Podría juntarse con las presentaciones de eventos pasados y futuros.

Pueden ir al Drive existente, a ver si lo podemos organizar mejor.

**Comment by JavierIH** [comment]
Repositorio creado!

https://github.com/asrob-uc3m/recursos-digitales
