### ISSUE TITLE
Jornadas de Bienvenida estudiantes grado

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#220]
Ya en Calendar: Tuesday, September 10⋅10:00 – 17:00

Enlace al del año pasado: https://www.uc3m.es/ss/Satellite/ApoyoEstudiante/es/TextoDosColumnas/1371234132151/?d=Touch

**Comment by jgvictores** [comment]
Envié form confirmando asistencia ASROB (hoy era el deadline ^^)!

**Comment by PeterBowman** [comment]
El enlace anterior apunta al de este año, pero es diferente, así que lo vuelvo a poner aquí: https://www.uc3m.es/orientacion/bienvenida#leganes.

**Comment by PeterBowman** [comment]
Documentación gráfica en: https://drive.google.com/drive/folders/1tPjF6HtfLxHg--4-13-Bb1Bkeaxa_nNf.

**Comment by PeterBowman** [comment]
Álbum del evento: https://www.flickr.com/photos/centroorientacion/albums/72177720320308079/ (creo que salimos solo en dos fotos, ya las he subido al drive).
