### ISSUE TITLE
Pedir subvencion IEEE Octubre 2016

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#23]
Para que no se nos olvide que son 127 euros en efectivo sin control en facturas(compra a china), muy utiles.

**Comment by David-Estevez** [comment]
Estamos a noviembre.... ¿esto se ha hecho?

**Comment by jgvictores** [comment]
Pregunté ayer (2/Nov/2016) a José Miguel Alfonso Sepulcre si esto era el reporte, y contestó:

> No,  el reporte es un trámite obligatorio que se hace todos los años.
> La convocatoria de ayudas la mandaremos pronto.

Toca esperar, o ir preparando en base a convocatorias de otros años.

**Comment by Rodriwp** [comment]
Esta issue hacia referencia a la convocatoria de subvenciones 2016, que ya recibimos y esta en cuenta.

**Comment by David-Estevez** [comment]
No, @Rodriwp , esta issue hacía referencia a la convocatoria de este año, la cual [**no se ha abierto todavía**](https://github.com/asrob-uc3m/actas/issues/23#issuecomment-257909727)

**Comment by jgvictores** [comment]
Ver email "[Ramashispania] Convocatoria de Ayudas a Ramas de Estudiantes" de Angela Martinez recibido el Apr 24 2017.

**Comment by David-Estevez** [comment]
En este caso, creo que le toca pedirla al actual tesorero :sweat_smile: 

En caso de que haga falta hacer una memoria o algo similar, pide ayuda por el grupo de Telegram para hacerla entre todos.

**Comment by KFRodicio** [comment]
Sigo en esta issue. Me confirman que podemos usar la ayuda para financiar el evento, quereis que lo haga?

**Comment by jgvictores** [comment]
Nos harías un gran favor a todos, Muchas Gracias!

**Comment by KFRodicio** [comment]
Ok, me pongo con eso mañana

**Comment by KFRodicio** [comment]
Echando un vistazo a la convocatoria, podemos pedir 3 ayudas de hasta 100 euros. A parte del Evento, quereis pedir para algo más?

**Comment by David-Estevez** [comment]
Tienen alguna limitación / condición esas ayudas?

Nos vendría bien pasta para comprar / renovar cosas inventariables, como herramientas.

**Comment by KFRodicio** [comment]
Probablemente tendrían que ser cosas específicas para un proyecto o
actividad, porque luego se tiene que justificar todo eso en la petición de
ayuda. Además, es hasta un límite de 100 euros

**Comment by David-Estevez** [comment]
Peores cosas hemos justificado... (Ejem Air Hockey ejem)

**Comment by KFRodicio** [comment]
Pero el air hockey era algo específico para un proyecto, lo que no estoy
seguro es que puedas justificar material genérico

El 4/7/2017 4:50 p. m., "David Estévez Fernández" <notifications@github.com>
escribió:

Peores cosas hemos justificado... (Ejem Air Hockey ejem)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/actas/issues/23#issuecomment-312897042>, or mute
the thread

**Comment by David-Estevez** [comment]
Hombre, si no tienes herramientas no puedes hacer ningún proyecto...

**Comment by David-Estevez** [comment]
Creo que #89 invalida esta issue...
