### ISSUE TITLE
Participación en Bienvenida 2016

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#25]
África nos ha mandado un correo preguntando si vamos a participar en la Bienvenida de Asociaciones. 

La fecha será el **6 de Septiembre de 2016** de **16:00 a 21:00**.

Podéis votar aquí: http://goo.gl/forms/acNrCswXz7IvBYH42 , hasta el día **18 de Julio de 2016** a las **23:59**.

PD: os dejo también el link al doodle donde las asociaciones están confirmando si van o no: http://doodle.com/poll/yfv9md83wsmp248u

**Comment by jgvictores** [comment]
La votación ha salido positiva, con lo que nos deberíamos apuntar en el [Doodle](http://doodle.com/poll/yfv9md83wsmp248u). Yo al final no puedo ir ese día... ¿voluntarios?

**Comment by David-Estevez** [comment]
:hand:
