### ISSUE TITLE
Petición de financiación desde los fondos de ASROB

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#26]
## Petición de financiación desde los fondos de ASROB

Como se propuso en #17 se hablo sobre la adqusicion de diversos materiales tanto para el prototipado rapido en las reuniones, como para hacer talleres en la asociación. Por tanto y siguiendo el sistema de peticion de finaciación que ya fue usado en #21, se propone la siguiente lista de compra:

| Item | Cantidad | Coste unitario | Coste |
| --- | --- | --- | --- |
| [Arduino Uno ](http://www.electronicaestudio.com/i/f/ArduinoUnoR3Front.jpg) | 5 | 2.50€ | 12.50€ |
| Cables Prototipo | 1 | 10€ | 10€ |
| [BreadBoard 400 puntos](https://es.aliexpress.com/store/product/1-Pcs-New-400-Tie-Points-Solderless-PCB-Breadboard-Mini-Universal-Test-Protoboard-DIY-Bread-Board/1948124_32517894271.html?spm=2114.04020208.3.78.6WPVVh&ws_ab_test=searchweb201556_0,searchweb201602_3_10057_10065_10056_10055_10037_10054_10044_10043_301_10059_10032_10058_10017_107_10041_10042_10060_10061_10052_414_10062_10053_10050_10051,searchweb201603_7&btsid=5a46ac59-134e-48bb-9a72-8d52887aeca8) | 10 | 1€ | 10€ |
| [Kit de Sensores 37 en 1](https://es.aliexpress.com/store/product/37-IN-1-BOX-Sensor-Kits-37-SENSOR-KIT-For-Arduino-HIGH-QUALITY-FREE-SHIPPING/1544094_32592140121.html?spm=2114.04020208.3.1.A5lXGV&ws_ab_test=searchweb201556_0,searchweb201602_3_10057_10065_10056_10055_10037_10054_10044_10043_301_10059_10032_10058_10017_107_10041_10042_10060_10061_10052_414_10062_10053_10050_10051,searchweb201603_7&btsid=89eab729-6f02-4c9d-b4fb-523be50dbd8f) | 5 | 11€ | 55€ |
| [ESP8266](https://es.aliexpress.com/store/product/New-Wireless-Module-NodeMcu-Lua-WIFI-Internet-of-Things-Development-Board-Based-ESP8266-with-Pcb-Antenna/1757110_32453467385.html?spm=2114.04020208.3.307.jLtqLa&ws_ab_test=searchweb201556_0,searchweb201602_3_10057_10065_10056_10055_10037_10054_10044_10043_301_10059_10032_10058_10017_107_10041_10042_10060_10061_10052_414_10062_10053_10050_10051,searchweb201603_7&btsid=e8b8a812-f9ad-4bdd-a52d-0fee6fa6ca2f) | 5 | 3€ | 15€ |
| Total: | - | - | 102,50€ |

El gasto total es aproximado, ya que en el momento de la compra teniendo en cuenta cupones y descuentos igual es algo menos.

La votación: https://docs.google.com/forms/d/1ItvdTliLpXYdElU3fqvtyZY_dak8c4wEqGH1RCqEXq8/, fecha límite **Septiembre  7, 23:59h**

**Comment by Rodriwp** [comment]
Puesto que el resultado ha sido negativo por 5 votos a favor y 7 encontra, no se realizara el pedido

**Comment by David-Estevez** [comment]
Vaya... :disappointed: 

De todas formas, me he fijado que el form que habéis usado no tenía verificación de usuario ni restricción de votos por persona (puede que alguien haya votado más de una vez, tanto a favor como en contra). 

Para próximas votaciones usad la cuenta de Asrob que nos dio la uni, que deja limitar los votos a únicamente gente con cuenta de la uni, sólo te deja votar una vez.

La opción de poder ver cómo va la votación después de votar también está guay habilitarla, para que la gente pueda tener un seguimiento de los resultados.

**Comment by jgvictores** [comment]
> Para próximas votaciones usad la cuenta de Asrob que nos dio la uni, que deja limitar los votos a únicamente gente con cuenta de la uni, y limitar los votos (te deja votar sólo una vez, aunque puedes modificar este voto las veces que quieras).

Debería bastar con hacer el Google Form con una cuenta dentro del dominio @uc3m.es (sea @alumnos.uc3m.es, @ing.uc3m.es,...) para activar la verificación que habilite los límites.

**Comment by asrobuc3m** [comment]
Cerrado por inactividad (> 1 mes)
