### ISSUE TITLE
 Reunión LUNES 19 SEPTIEMBRE. SEMANA DE ASOCIACIONES.

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#29]
Citando a África:
"¡Buenos días!!! ya pasada la bienvenida, nos queda dar el último empujón a la Semana de Asociaciones... Por este motivo os convoco a una reunión el próximo lunes 19 de septiembre a las 10.30 en el campus de Getafe en el aula 4.1.07 a las 10.30 horas. Tenemos mucho que hablar y concretar y queda muy poquito tiempo... ¡¡¡¡por favor, os ruego máxima asistencia"
Anyone?

**Comment by David-Estevez** [comment]
Me la asigno a mí, así aprovecho y voy también en representación de UC3Music.

Tras la reunión mandaré los temas tratados a la lista de miembros activos y cerraré esta issue.

**Comment by jgvictores** [comment]
Os recuerdo que tenemos "ASROB: Ramas Activas ASROB (#18)" y "Charla sobre Arduino + ESP8266 (#19)" ya incluidos en el [horario oficial de la Semana de Asociaciones](http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/eventos/semana_asociaciones/Campus%20de%20Legan%E9s1)... esta reunión interesa!!

**Comment by Rodriwp** [comment]
Seria conveninte tener la información cuanto antes puesto que hay que preparar las actividades para el martes.

**Comment by David-Estevez** [comment]
Os dejo por aquí un resumen de los temas tratados en la reunión y cierro issue:

-África nos insta a darle toda la publicidad que podamos a la Semana de Asociaciones
- Habrá "camisetas corporativas" de asociaciones que deberán llevar puestos los que den las charlas de la Semana de Asociaciones. El día de la feria podemos llevar nuestras propias camisetas.
- En la presentación es el único momento en el que el señor director de la escuela tendrá contacto con las asociaciones, así que deberíamos llenar el aula de gente para demostrarle que las asociaciones mueven gente y que el programa de asociaciones merece la pena.
- Se puede optar a crédito por organizar.
- Hay que pedir los espacios ya.
- África nos pide que vayamos a la Feria de Getafe en la medida de lo posible.
- La Feria de Getafe será el jueves, la de Leganés el viernes.
- África va a pintar una sábana para sustituir el cartel de la Semana de Asociación que falleció, y solicita voluntarios que la ayuden a pintar.
