### ISSUE TITLE
Limpieza de primavera en la wiki

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#3]
En la reunión del 24/02/2016 se propuso hacer limpieza de la wiki.

Tareas a realizar:

* [x] Sección antiguos miembros
* [x] Sección antiguos proyectos
* [x] Hall of Fame
* [x] Visibilidad para los tutoriales
* [x] Limitar el acceso a la wiki a los miembros activos

cc: @jgvictores @Rodiwp

**Comment by jgvictores** [comment]
En busca de soluciones equitativas y sostenibles, veré si se puede automatizar una herramienta como:
https://www.mediawiki.org/wiki/Manual:RemoveUnusedAccounts.php

**Comment by David-Estevez** [comment]
+1

**Comment by jgvictores** [comment]
Implemented `crontab -e`:
`0 0 1 * * php removeUnusedAccounts.php --delete`
(Run once a month)

**Comment by David-Estevez** [comment]
All items are now completed. Closing issue...

**Comment by jgvictores** [comment]
I've discovered a glitch: `removeUnusedAccounts.php` only removes accounts that have never been used. We need an alternative for acounts that haven't been active for a long time.

**Comment by David-Estevez** [comment]
@jgvictores Es posible editar el script para tener en cuenta otros factores (como la fecha de la última edición)?

También habría que definir "a long time".

**Comment by jgvictores** [comment]
Primero miraré si hay algo ya hecho.
"a long time" -> Empezaré por revisión mensual de los 12 meses anteriores.

**Comment by David-Estevez** [comment]
¿Cómo va este tema? ¿Qué solución seleccionamos como definitiva?

**Comment by jgvictores** [comment]
La solución elegante es [crear un script de mantenimiento](https://www.mediawiki.org/wiki/Manual:Writing_maintenance_scripts), p.ej. basado en [removeUnusedAccounts.php](https://www.mediawiki.org/wiki/Manual:RemoveUnusedAccounts.php). Decisiones de diseño:
- Bloqueo vs borrar. Propongo por bloquear escritura, puesto que no he encontrado documentación acerca de si borrar puede romper tablas.
- Acción a tener en cuenta: que no han editado vs simplemente logueado. Propongo simplemente loguearse.
- Tiempo. Propongo bloqueo de escritura permanente si han pasado 12 meses desde que no se ha realizado la acción (loguearse).

**Comment by jgvictores** [comment]
> El nuevo script no necesitará que el usuario jamás haya editado la wiki

Implementado en: https://github.com/jgvictores/snippets/commit/659022346af7b4d2f17cf24dbe7684b04236b295
`php ./disableInactiveAccounts.php --ignore-touched 2000`
Ubica 13 usuarios cuyo [user_touched](https://www.mediawiki.org/wiki/Manual:User_table#user_touched) es de hace más de 2000 días. Para 12 meses:
`php ./disableInactiveAccounts.php --ignore-touched 365`
La cifra asciende a 186 usuarios.

> Borrar vs deshabilitar.

Los siguientes commits serán orientados a deshabilitar en lugar de borrar.

**Comment by jgvictores** [comment]
Script terminado en https://github.com/jgvictores/snippets/commit/1831168a3e4c84a6c94528701ec8d28e65163411. Falta automatizar el proceso.

**Comment by jgvictores** [comment]
Implemented crontab -e:
`0 0 1 * * php disableInactiveAccounts.php --ignore-touched 365 --disable`
(Run once a month)

**Comment by David-Estevez** [comment]
Cierro la issue
