### ISSUE TITLE
Semana Asociaciones 2016: Última Reunión

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#31]
África nos convoca (de nuevo)  a una reunión el jueves 29 de septiembre (este jueves) a las 11.00 horas en el Campus de Getafe en el aula 10.2.2, para tratar temas de la semana de asociaciones y darnos material (imagino que las camisetas corporativas).

¿Alguno está disponible en ese horario?

**Comment by David-Estevez** [comment]
Al final asistí yo a la reunión.

En la reunión se nos comunicó el número de alumnos apuntados a cada charla (19 al taller de ESP8622 y 6 a la de Ramas Activas) y se nos entregaron las camisetas y acreditaciones que habrá que llevar puestas para dar la charla.

También se nos reiteró la importancia de que hagamos difusión de la Semana y de la Feria, así como la importacia de estar en la presentación contando lo que hacemos en la asociación. Es muy importante que el director de la escuela sepa que existimos y lo que hacemos.

**Comment by jgvictores** [comment]
@David-Estevez Gracias por asisitir, y por la info!!!
