### ISSUE TITLE
Nuevo proyecto de la rama UAVs

### ISSUE THREAD

**Issue by andrespy** [asrob-uc3m/actas#34]
Este año queremos hacer un circuito automatizado para drones entre otras cosas pero necesitamos algo de material para ello. En el circuito habrá puertas que detecten el paso de los drones y transponders de IR para detectar de quien es el drone y para ello necesitamos una raspi 2, y demas componentes, este proyecto de deteccion ya está hecho y lo podeis ver [aqui](https://github.com/polyvision/EasyRaceLapTimer/blob/master/docs/hardware.md) 

También haremos plataformas para detectar salidas antes de tiempo y un semáforo. Nos gustaría tener un sistema donde controlar todas las puertas y demás sistemas para lo cual igual os pedimos alguna charla de ROS o yarp. La idea se esta gestando desde hace poco y falta mucho por pulir, aun así os adjunto un primer borrador del proyecto para más detalles.
[PROYECTO ASROB.pdf](https://github.com/asrob-uc3m/actas/files/528205/PROYECTO.ASROB.pdf)

**Comment by David-Estevez** [comment]
Un proyecto muy chulo, @andrespy !!

Raspberry Pi 2 tiene que haber en el armario, y la verdad es que no sé de qué rama son (si son de alguna), pero ahora mismo no las está usando nadie. 

Para el resto del material, cuando lo tengáis un poco más claro, haced un presupuesto de cuánto costaría todo (podéis usar #21 como referencia) y se vota entre todos. Para la votación, aseguraos de que el form está hecho con una cuenta uc3m (la aso tiene una) para poder filtrar a que sólo voten miembros de la uc3m y que sólo vote una vez cada persona.

**Comment by jgvictores** [comment]
Eso es: https://github.com/asrob-uc3m/estatutos/blob/master/metodo_de_votacion.md

**Comment by jgvictores** [comment]
...pero en actas, al tratarse de asuntos generales. :smile:

**Comment by andrespy** [comment]
Genial! @jgvictores @David-Estevez muchas gracias por responder y decirnos cómo proceder tan rápido! haremos un presupuesto y un formulario de votación en poco!

**Comment by David-Estevez** [comment]
Si necesitáis ayuda para montar el formulario o algo avisadnos!

**Comment by Rodriwp** [comment]
Las raspi 2 actuales son de robotdevastation. Podeis hablar com los responsables para que os cedan una.

**Comment by asrobuc3m** [comment]
Cerrado por inactividad (> 1 mes).
