### ISSUE TITLE
Reporte IEEE

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#35]
Hay qie hacer el reporte anual IEEE si nos interesa seguir siendo parte de esta organizacion. La fecha tope es para el 1 de noviembre.

Yo creo que interesa hacerlo puesto que es reutilizable para hacer el de la uni.

**Comment by jgvictores** [comment]
Ok, he mirado el asunto, consiste en loguearse en https://sbr.vtools.ieee.org/ y rellenar formularios online. Los campos son:
- School <- UC3M
- Finances <- Esto lo comentamos en persona, es poco
- Activities <- Aquí hay que rellenar una tabla, dar una cifra de cantidad de actividades "Technical / Non-technical / Administrative / Other" por cada mes del 2016 y de lo planificado para el 2017. Se puede hacer en persona.
- Feedback <- **Esto es más lioso. Propongo que se complete a base de comentarios en esta issue.**
 - "What is the primary purpose of your Branch as a student organization?" (450 char)
 - "What are the specific goals of the Branch for the coming year?" (450 char)
 - "What problems do you anticipate needing to overcome to successfully run the Branch? (What were some of last year's problems?) How can we help you to improve your operations?" (450 char)
- Signatures, Save and Submit <- Se puede hacer en persona.

Por tanto, propongo:
- [ ] Rellenar la sección "Feedback" <- **@todos** ¿**Quién puede echar una mano aquí**?
- [ ] En cuanto tengamos eso, juntarnos los que podamos una tarde, rellenar y enviar.

**Comment by jgvictores** [comment]
ping!

**Comment by jgvictores** [comment]
Ok, hecho. Uno se puede loguear en https://sbr.vtools.ieee.org y a través de https://sbr.vtools.ieee.org/report/show_submitted_by_ou buscar los reportes de IEEE. Filtrando por nombre, de la Universidad Carlos III de Madrid aparece el que acabo de rellenar, más los de dos cursos anteriores.
Cierro issue, si alguien necesita algo, siempre se puede reabrir.

**Comment by David-Estevez** [comment]
Thanks @jgvictores
