### ISSUE TITLE
Jornada Robótica HispaRob

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#36]
Fecha: 22 de noviembre de 2016 (martes) - horario aproximado de 9:30 a 18:00
Lugar de celebración: Universidad Carlos III de Madrid (sede de Leganés)

La Jornada, organizada por HispaRob, Plataforma Tecnológica de Robótica, con la colaboración de la Universidad Carlos III de Madrid, se enmarca dentro de la celebración de la Semana Europea de la Robótica (ERW), promovida por euRobotics.

http://jornada.robotica.hisparob.es/wp/

¿Qué material nos haría falta para ir?

**Comment by jgvictores** [comment]
Por cierto, se admiten propuestas de etiqueta políticamente correcta para este tipo de eventos (el anterior está en [otro repo](https://github.com/asrob-uc3m/estatutos/issues/8), pero encajaría bajo la misma etiqueta).

**Comment by jgvictores** [comment]
https://groups.google.com/forum/#!topic/miembros-activos-asrob/jWRyAuX8UqM

**Comment by David-Estevez** [comment]
A mi personalmente me gustaría ir con algún robot funcional para poder enseñarlo y que se vea que en la Asociación tenemos el potencial de hacer cosas muy chulas (y para no aburrirnos allí).

Ya que recientemente tenemos una versión bastante funcional de Robot Devastation, yo intentaría conseguir material para reparar alguno de los RD1/RD2 que tenemos actualmente desguazados.

**Comment by Siotma** [comment]
A mi me interesa mucho y creo que podría asistir por la mañana. Puedo llevar mi Anger Zowi plenamente operativo e incluso permitir a los asistentes que lo controlen con su teléfono móvil.
La posibilidad de montar un ring con dos Zowimanoid para que se peguen y que la gente los controle sería brutal, pero más costosa.

**Comment by David-Estevez** [comment]
Para demo de Robot Devastation, cualquiera de estos elementos incrementaría nuestra capacidad de montar una demo:
- Servomotores (2x robot)
- Webcam
- Pincho WiFi USB

**Comment by jgvictores** [comment]
Necesitaríamos listado con cantidades y URLs compra (que además lleguen a tiempo para montar).

**Comment by David-Estevez** [comment]
En plan wishlist?

**Comment by jgvictores** [comment]
Yes.

**Comment by David-Estevez** [comment]
BOM
--------

Debido a lo precipitado del evento, todos los componentes han sido seleccionados en [Electrónica Embajadores](http://www.electronicaembajadores.com). Este BOM es para construir UN ROBOT, hay que duplicarlo para tener una demo jugable de Robot Devastation. Las Raspberry Pi las pondremos nosotros, tenemos stock de sobra para dos robots.

| Artículo | Cantidad | Precio ud | Total |
|-----------|-------------|--------------|--------|
| [Webcam](http://www.electronicaembajadores.com/Productos/Detalle/8/CM2D016/c-mara-web-usb-2-0-alta-velocidad-con-micr-fono) | 1 | 11.61€ | 11.61€ |
| [Adaptador WIFI](http://www.electronicaembajadores.com/Productos/Detalle/28/PC3A020/adaptador-lan-usb-wifi---300-mbps) | 1 | 9.5€ | 9.5€ |
| [Chasis para robot con motores](http://www.electronicaembajadores.com/Productos/Detalle/31/ROBT010/chasis-2wd-mini-robot-ft-dc-002) | 1 | 22.19€ | 22.19€ |
| [Driver 2 motores](http://www.electronicaembajadores.com/Productos/Detalle/26/LCMM003/driver-2-motores-de-continua---drv8833) | 1 | 6.82€ | 6.82€ |
| [Batería LiPo 7.2V](http://www.electronicaembajadores.com/Productos/Detalle/2/BA1A7410/bateria-de-polimero-litio---7-4v---1000ma) | 1 | 12.19€ | 12.19€ |
| [Convertidor DC-DC](http://www.electronicaembajadores.com/Productos/Detalle/33/SA31353/convertidor-dc-dc--in--3-2--40v--out--1-25--35v---3a) | 2 | 6.53€ | 13.06€ |
| Total |  | | 75.37€ | 

Total (dos robots): 2 * 75.37€ = 150.74€

**Comment by David-Estevez** [comment]
Me comunica Ramón que nos aprueban el BOM para dos robots.

 Hay que organizar una expedición para comprar las cosas lo antes posible.

**Comment by David-Estevez** [comment]
El pedido ya está hecho y pendiente de recogerlo.

**Comment by David-Estevez** [comment]
Ya tenemos los componentes y estamos en proceso de montar los robots.

**Comment by David-Estevez** [comment]
Hemos sobrevivido a la jornada con éxito.

Agradecimientos (Relacionado con https://github.com/asrob-uc3m/estatutos/issues/11):

- A @KFRodicio por su participación activa en el stand.
- A @jgvictores por su participación activa en el stand, y montaje y programación de robots para demo en vivo.
- A @David-Estevez por su participación activa en el stand, y montaje y programación de de robots para demo en vivo.
