### ISSUE TITLE
Decorar la nave

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#37]
El otro día estuvimos hablando @jgvictores y yo sobre colocar pósters en las paredes de nuestro espacio en la nave para dar una imagen más chula y "corporativa". 

Las propuestas son:
  - Pósters stickers "Keep calm and pon una issue" y "Keep calm and has mirado la wiki"
  - Póster sticker "Piggy wants you"
  - Póster ASROBOT (Logo de la aso con nuestra mascota)
  - Pósters de cada uno de los proyectos activos de la aso

Más las propuestas que hagáis vosotros. Dejamos esta issue abierta hasta el **17/11/2016** para debatir qué pósters nos molan más y luego votamos para hacer o no los pósters.

**Comment by David-Estevez** [comment]
Añado el link para la votación sobre si hacemos los pósters o no: https://goo.gl/forms/QGo0L9VwwvkzhCVn2

La votación estará abierta hasta el **01/12/2016**

**Comment by David-Estevez** [comment]
La votación está cerrada. Los resultados son los siguientes:

1. Pósters stickers "Keep calm and pon una issue" y "Keep calm and has mirado la wiki" (100% - 4 votos)
2. Póster ASROBOT (Logo de la aso con nuestra mascota) (100% - 4 votos)
3. Póster sticker "Piggy wants you" (75% - 3 votos)
4. Pósters de cada uno de los proyectos activos de la aso (25% - 1 voto)

Se pocederá a la fabricación e instalación de los mismos en ese orden, parando cuando llenemos el espacio disponible o se nos haya terminado el presupuesto.

**Comment by David-Estevez** [comment]
Retomando el tema, y aprovechando para renovar el material publicitario de ASROB (por ejemplo, el roll-up que se nos cae a cachos), dejo por aquí unos links de referencia a pósters y roll-ups junto con sus precios:

* [Póster A2 ](https://www.vistaprint.es/lonas-y-posteres/posteres), Mate, 10.78€/ud
* [Roll-up](https://www.vistaprint.es/lonas-y-posteres/roll-ups), Economy, 44.99€/ud
* [Lona](https://www.vistaprint.es/lonas-y-posteres/lonas), 76x122cm, 26.98€
* [Cartel de cartón pluma](https://www.vistaprint.es/lonas-y-posteres/carteles-de-carton-pluma), A2, 19.49€

PD: también hacen pegatinas ([24 por 4.49€](https://www.vistaprint.es/materiales-de-marketing/etiquetas-y-adhesivos/etiquetas-adhesivas-personalizadas/plantillas/horizontales-a1)) y tazas ([a 5.99€/ud](https://www.vistaprint.es/regalos-con-foto/tazas-personalizadas))

**Comment by David-Estevez** [comment]
Pedido, al final el coste de esto ha sido:

| Artículo | Precio |
| --------- | ---------|
| Cartel cartón pluma ASROB | 19.49€ |
| Póster Keep calm & pon una issue | 17.99€ |
| Póster Keep calm & has mirado la wiki | 17.99€ |
| Roll-up ASROB | 44.99€ |
| Gastos de envío | 4.98€ |
| **Total** | 105.44€ |

Y la fecha prevista de entrega es el 5 Oct

**Comment by David-Estevez** [comment]
Ya se han recibido y colocado los pósters en la Nave con la ayuda de @jorgercobo 

Adjunto fotos del resultado:
![photo_2017-10-03_22-58-01](https://user-images.githubusercontent.com/1451819/31148946-8f528d34-a88e-11e7-904f-2e88af98d238.jpg)
![photo_2017-10-03_22-58-05](https://user-images.githubusercontent.com/1451819/31148945-8f4e8c16-a88e-11e7-956d-be8c76fb9964.jpg)

**Comment by David-Estevez** [comment]
Tras la colocación de los pósters, y ya que esta issue está aprobada por votación, se solicita el reitegro del importe de los mismos (105.44€ desglosados en comentario previo).

Ya que no hay tesorero nuevo, correspondería al tesorero en funciones @jgvictores hacer dicho pago.

**Comment by jgvictores** [comment]
Hecha transferencia 105.44€ a favor de @David-Estevez y wiki actualizada: http://asrob.uc3m.es/index.php/Cuentas_ASROB

**Comment by David-Estevez** [comment]
Confirmo que he recibido dicha transferencia de @jgvictores

**Comment by jorgercobo** [comment]
Parece oportuno citar esto aquí: #93 

> Decoración del armario. Actualmente en el armario hay mucho cartel anticuado. Evaluar si alguno se puede retirar e instalar magnéticamente el nuevo cartel ASROB.

¿Alguna sugerencia para redecorar el(los) armario(s)?

**Comment by Siotma** [comment]
La información de los armarios debería estar actualizada, propongo:
- Quitar el cartel de MYOD, que ya no es una rama activa.
- Quitar el cartel de mirar la wiki si no puedes abrir el armario, es muy feo y cutre, y además tiene mucho timepo.
- Poner el nuevo y flamante cartel de ASROB.

**Comment by David-Estevez** [comment]
El cartel de la apuesta es un hecho histórico, pero la verdad es que ya nadie pilla la coña, porque no conocen a los que hicieron la apuesta.

Por otro lado, también quitaría el cartel del hisparob, que lo pusimos ahí por no tirarlo y no queda demasiado bien.

**Comment by jorgercobo** [comment]
Ideas: 

- Cartel de normas de uso del espacio de la asociación (recoger todo antes de irse, no dejar la impresora desatendida durante la impresión, etc) - Redactar dichas normas si no lo están ya.

- Cartel con información sobre los recursos de la asociación (pagina web, wiki -si sobrevive-, gestión de impresoras, a quien preguntar por la llave del armario).

- Cartel con el logo de las ramas/grupos de trabajo/talleres/sectas transhumanistas activ@s

**Comment by Siotma** [comment]
A favor!

**Comment by PeterBowman** [comment]
Ironía fina:

![20180321_210635](https://user-images.githubusercontent.com/9977198/37734655-1a9fce96-2d4c-11e8-89ff-5df5b077e33e.jpg)

Lo dejo de momento sobre una de las mesas, por la mañana me puedo pasar con un poco de celo para arreglar el estropicio.

**Comment by David-Estevez** [comment]
Arreglado, el cartel vuelve a lucir en la pared con todo su esplendor original.

**Comment by David-Estevez** [comment]
Como esta issue se nos está desmadrando, he abierto #137 para centrarnos en lo único que quedaba por hacer en esta (Decorar el armario) y pedir la ayuda de los nuevos.

Por lo demás no queda nada por hacer, así que cierro esto.
