### ISSUE TITLE
Colaboración en proyecto europeo STIMEY

### ISSUE THREAD

**Issue by KFRodicio** [asrob-uc3m/actas#38]
Buenas.

Abro esta issue para discutir sobre la oferta que nos llegó para participar (como colaboradores externos, supongo) en el proyecto STIMEY. Creo que lo primero que deberíamos hacer, antes de discutir pros y contras, sería ponernos en contacto con ellos para concretar que es lo que esperan de nosotros (no se por que, pero apostaría que quieren que organicemos talleres). Que os parece?

**Comment by Rodriwp** [comment]
Estoy interesado. Puede proporcionarnos recursos para la formación de los nuevos.Habria que ver en que consiste la colaboracion con ellos, pero si los terminos no son abusisvos, puede ser interesante colaborar. 

A parte del material que nos puedan dejar, puede ser interesante la propuesta formativa para robotica que tengan

**Comment by David-Estevez** [comment]
Totalmente de acuerdo en ver primero qué quieren de ASROB.

¿Podéis escribirles un correo preguntándoles cuál sería el rol que tendría ASROB dentro de ese proyecto europeo, y cuáles serían nuestras obligaciones?

**Comment by KFRodicio** [comment]
En principio no me importa escribir el correo mañana a primera hora, si
quereis. Lo pasaré por telegram para que me deis el visto bueno antes de
mandarlo.

**Comment by KFRodicio** [comment]
Buenas. Este es el correo que les envié pidiendo mas información:

Buenos días.

Ante todo, nos gustaría agradecerles que hayan pensado en nosotros como un posible colaborador para este proyecto. La posibilidad de participar en un proyecto europeo puede suponer un impulso importante para nosotros. Sin embargo, antes de poder tomar una decisión al respecto, nos gustaría saber a que nos estaríamos comprometiendo, y que se espera de nosotros, en caso de aceptar su invitación. Reiteramos nuestro agradecimiento por la invitación, disculpen las molestias.

Un saludo 

A ver que responden.

**Comment by David-Estevez** [comment]
Muchas gracias, @KFRodicio !!

**Comment by jgvictores** [comment]
Antes que nada, @KFRodicio gracias por tu proactividad. 
Respecto a esta posible colaboración, recordad que no sería entrar como socios sino colaboradores externos. Si lo que atrae es la idea de colaboración en un Proyecto Europeo, puedo poner la Asociación

**Comment by jgvictores** [comment]
Editado mi comentario anterior que se había truncado. 😅

**Comment by KFRodicio** [comment]
Estoy 100% de acuerdo contigo, juan, yo creo que el colaborar en un proyecto de este nivel exige una organización y dedicación muy alta durante un largo periodo de tiempo. Evidentemente tendría que ser muy ventajoso el acuerdo para que nos merezca la pena todo ese trabajo. Esto es mas que nada por tener toda la información posible (aunque el hecho de que no hayan contestado aún apunta a que ya encontraron a otros).

**Comment by David-Estevez** [comment]
¿Les preguntamos cómo colaborarían ellos con nosotros o les decimos que no de forma respetuosa y a otra cosa?

**Comment by KFRodicio** [comment]
Yo voto por la B, decirles que no

**Comment by David-Estevez** [comment]
Me parece correcto, pero habría que escribirles en lugar de hacerles el vacío.

**Comment by jgvictores** [comment]
Done.

**Comment by jgvictores** [comment]
Votación abierta hasta dentro de 7 días: https://goo.gl/forms/eLFNGnOrcDh9jFCJ2

**Comment by David-Estevez** [comment]
La votación está cerrada. Se ha decido que **no participaremos en el proyecto europeo STIMEY**.

@jgvictores puedes contestar al correo indicándoles el resultado de la votación?

**Comment by jgvictores** [comment]
Done.
