### ISSUE TITLE
Falta el alargador

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#39]
Falta el alargador de 5 metros, no esta en el armario. @jgvictores @David-Estevez  ¿sabeis que se hizo con el despues del evento?

**Comment by jgvictores** [comment]
Me consta que ha estado en el armario desde el evento. En las reuniones del 9 Nov 2016 aun lo llegamos a utilizar en la nave.

**Comment by David-Estevez** [comment]
Robot Devastation desconoce su paradero. @andrespy sabe UAVs qué ha podido pasar con el alargador?

**Comment by David-Estevez** [comment]
![img_20170125_172652](https://cloud.githubusercontent.com/assets/1451819/22300125/cbedf400-e326-11e6-98e3-f02442cb9b20.jpg)

El alargador ha sido recuperado, estaba vagando por la nave...
