### ISSUE TITLE
Documentar El Evento

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#40]
*  [x] Añadir a la web las presentaciones
*  [x] Subir los vídeos

**Comment by JorFru** [comment]
En UC3Music ya hemos subido los vídeos a YouTube, en [nuestro canal](https://www.youtube.com/user/uc3musice)
Falta poner las miniaturas bonitas, y falta decidir si se pondrá la primera diapositiva de la presentación, una foto de archivo del ponente, o un logo de ElEvento (el cual no existe todavía).
Me ofrezco a resubirlo al canal de ASROB, si así se decide. (y poner las mismas miniaturas para hacerlo más fácil)

Resumen. ¿Se resube al canal de YT de ASROB? ¿con qué miniatura?

**Comment by David-Estevez** [comment]
Yo le pondría una portada que fuese "El Evento 2016", el título de la charla, el ponente y los logos de ASROB, UC3Music (y Bricogeek).

Si os gusta la idea me coordino con @JorFru para hacerlos y ponérselos a los vídeos.

**Comment by JorFru** [comment]
La cuenta de ASROB tiene limitada la longitud de los vídeos a 15 minutos.
Para activar vídeos más largos hay que dar un número de teléfono para que "se compruebe que no eres un robot"
¿qué número de teléfono uso?

**Comment by jgvictores** [comment]
Te envío vía privado.

**Comment by JorFru** [comment]
Ya se pueden subir vídeos grandes

**Comment by David-Estevez** [comment]
Gracias, @JorFru !!

**Comment by JuanFdelArco** [comment]
De los videos del hackaton que sabemos?

**Comment by JorFru** [comment]
Están subidos al canal de YT de UC3Music pero no están editados.
Los marco como públicos para que se puedan ver.

**Comment by David-Estevez** [comment]
WIP en https://github.com/David-Estevez/evento2016/tree/post-event

**Comment by David-Estevez** [comment]
Hecho e integrado en la web: https://github.com/asrob-uc3m/evento2016/pull/33
