### ISSUE TITLE
La lista de socios está desactualizada

### ISSUE THREAD

**Issue by asrobuc3m** [asrob-uc3m/actas#41]
http://asrob.uc3m.es/index.php/Lista_de_socios

**Comment by jorgerc21** [comment]
Ya he añadido mi info a la lista de socios y demás lugares donde figura el responsable. Si me he dejado alguno sin cambiar o hay algún error, avisadme

**Comment by David-Estevez** [comment]
Gracias, @jorgerc21 !!

He quitado a MYOD de la lista, ya que no es una rama activa y he actualizado a los responsables de los grupos activos.

Veo que todo está ya al día, así que cierro la issue. Pero de todas formas echadle un vistazo y si veis algo fuera de lugar cambiadlo / reabrid la issue.
