### ISSUE TITLE
Enviar email a Irene de la Umh de elche

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#44]
Copio texto de telegram (que incluye dirección email) ""Desde esta rama queremos hacer una recopilación de todos los proyectos que se han hecho en la sección España. Por favor podeis pasarme un resumen de vuestros proyectos??""

**Comment by David-Estevez** [comment]
Mail enviado!

**Comment by jgvictores** [comment]
@David-Estevez Thanks!!!!!
