### ISSUE TITLE
Entrega de memorias y junta directiva

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#45]
Nos ha llegado un correo de África, la parte importante es:

>Como sabéis, tanto la presentación de estas memorias como las juntas directivas, es muy importante, ya que si no lo hacéis durante dos años consecutivos, **vuestra asociación será dada de baja en el registro de Asociaciones.**

Y:

> **RECORDAD** que estas memorias no son las que se os solicitan por los proyectos de la Convocatoria de Ayudas. 

La fecha límite es el **domingo 18 de Diciembre**. 

Copio el correo de África íntegro como referencia:

> Buenos días!!! 
> 
> Ya está disponible vuestro acceso en Aula Global para la entrega anual de memorias y directivas, esta vez del curso 2015/2016. Desde ahora este va a ser el nuevo sistema de entrega. Tened en cuenta que el plazo de subida finaliza el domingo 18 de Diciembre. 
> 
> El enlace es el siguiente: https://aulaglobal.uc3m.es/course/view.php?id=54391
> También lo tenéis disponible en la página de recursos y servicios de asociaciones: http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/espacio_abierto/asociaciones/recursos_servicios
> 
> Como sabéis, tanto la presentación de estas memorias como las juntas directivas, es muy importante, ya que si no lo hacéis durante dos años consecutivos, vuestra asociación será dada de baja en el registro de Asociaciones. 
>  
> MUY IMPORTANTE: todos aquellos que ya lo habéis entregado por correo electrónico a Espacio Abierto o a mí, deberéis asimismo subirlo a Aula Global. 
> 
> RECORDAD que estas memorias no son las que se os solicitan por los proyectos de la Convocatoria de Ayudas. 
> 
> Un beso grande y feliz semana!!! :)
> 
> África

**Comment by KFRodicio** [comment]
Tenemos por ahí la memoria del año pasado para ver un ejemplo?

**Comment by jgvictores** [comment]
http://asrob.uc3m.es/index.php/Informe_Actividades

**Comment by KFRodicio** [comment]
Si la información de la wiki está al día, esto no será mucho problema, le puedo echar un vistazo este finde

**Comment by David-Estevez** [comment]
No sé si en la wiki aparecen talleres / eventos (El Evento, concretamente).

**Comment by KFRodicio** [comment]
A parte de el evento, la feria de asociaciones, hisparob, que mas me falta?

**Comment by David-Estevez** [comment]
Participamos en el I Hackatón de UC3Music y se organizaron algunos talleres. Yo dí uno de FreeCAD y uno de Kicad.

Si vemos que nos quedamos cortos podemos poner lo del golpe de estado xD

**Comment by David-Estevez** [comment]
Lo que podemos hacer es repartirnos el curro para que no se coma el marrón uno solo.

**Comment by KFRodicio** [comment]
Si realmente lo que voy a hacer es copiar la mas reciente que haya en la wiki, actualizar los datos y meter los nuevos eventos, yo creo que no se tarda nada

**Comment by Rodriwp** [comment]
Faltaria por añadir nuestra participacion en la semana de asociaciones con los taller arduino + esp8266 y la charla sobre nuestra asociacion.

Por parte de city of robots, nuestra actividad ha sido el diseño y primer desarrollo de la city, y el programa de iniciacion a la robotica y el cachareo

Subire la informacion ya desarrolla siguien el formato del ejemplo

**Comment by Rodriwp** [comment]
Incluyo aqui la informacion referente a los proyectos "city of robots" y "hacklab". Tambien esta explicado el taller "arduino+esp8266" que se hizo en la semana de asociaciones.

2 Proyectos Activos 

2.1 City of Robots 
En este proyecto se tiene como objetivo la construcción de una maqueta de una ciudad adaptada para robots. Esta ciudad permitirá tener un entorno donde los diferentes proyectos robóticos de la asociación puedan interactuar entre ellos. La construcción en si es un proyecto sencillo que engloba pequeños montajes para introducirse en el mundo de la robótica y el movimiento DIY
El coordinador de este grupo de trabajo es Rodrigo Mompo
2.2 Hacklab
Este proyecto surge de la necesidad de habilitar un espacio donde desarrollar de manera colaborativa diferentes proyectos personales para afianzar los conceptos aprendidos en las asignaturas desde un enfoque totalmente práctico. Este espacio también permite explotar el enfoque transversal de esta universidad, ya que conviven en un mismo espacio estudiantes de diferentes titulaciones. Así, convertimos pequeños proyectos personales en proyectos más complejos multidisciplinares 
El coordinador de este grupo de trabajo es Rodrigo Mompo
3 Actividades y reuniones
3 The city 
Este grupo de trabajo se ha reunido semanalmente. Durante sus reuniones semanales se ha procedido a la realización de pequeños taller de iniciación en diferentes aspectos útiles para el desarrollo de robots. Se han dado charlas introductorias sobre arduino, git,  freecad,kidcad,… y desarrollado pequeños montajes con arduino. Además se han construido 10 edificios para “the city” que servirán de base para la continuación del proyecto en el siguiente curso. 
Este grupo también se dedicó a preparar el material para poder acoger a más gente iniciándose el mundo de la robótica y sentó las bases para poder lanzar el proyecto hacklab a finales de año.

3 HackLab

Este proyecto es el más nuevo de todos, actualmente llevamos solo unos meses funcionando. En este espacio ya se han realizado montajes de todo tipo basados en arduino y han salido nuevas ideas que se desarrollaran en el siguiente curso.  El grupo se reúne semanalmente para poner en común el avance de sus proyectos e intercambiar ideas para futuras mejoras de los mismos. Actualmente no hay ningún montaje terminado, ya que se está trabajando activamente en ellos.
4 Otras actividades

En el contexto de la semana de asociaciones, se realizó un taller sobre “Arduino y Esp8266” donde los asistentes pudieron programar un servidor web capaz de controlar unos leds , en solo  3 horas, introduciéndose así de manera muy básica en el mundo del IoT.

**Comment by David-Estevez** [comment]
Has dado un taller de esto: https://www.youtube.com/watch?v=pwU8wJLTxkk ?????

 :confused: :confused: :confused: :confused:

**Comment by Rodriwp** [comment]
kicad

**Comment by David-Estevez** [comment]
:stuck_out_tongue_winking_eye:

**Comment by andrespy** [comment]
Fer y yo hemos hecho lo de UAVs ya. Echadle un ojo y nos decis que tal

https://docs.google.com/a/uc3m.es/document/d/10mYtMrvQFVy6WmsAjxU2nDDUOzzYvhi70du3IKEu5C4/edit?usp=sharing

**Comment by andrespy** [comment]
Bueno mejor lo pongo aqui por el tema del login

PROYECTO CIRCUITO AUTOMATIZADO
Como proyecto general dentro de la rama de UAVs, este año se está llevando a cabo el desarrollo y construcción de un circuito de drones de funcionamiento autónomo.
El proyecto está dividido en diferentes secciones, dedicándose cada una de ellas a una parte de dicho circuito.
Alguno de los grupos de trabajo son:
	
-Sistema de puertas: puntos de control por los que el piloto de dron debe pasar durante una carrera. se controla que pase por ellas con sensores, se detecta qué piloto ha pasado y el tiempo de vuelta.


-SIstema de salida: diseño y construcción de una plataforma de despegue para los drones. Controla que ningún piloto salga antes de tiempo y muestra un semáforo de cuenta atrás para el comienzo de la carrera.




CHARLAS SEMANALES
Para ayudar a los nuevos integrantes de la rama de UAVs, estamos llevando a cabo una serie de charlas acerca de los componentes que constituyen un dron de carreras (motores, baterias, hardware, software….). Elaboramos una pequeña presentación cada semana y damos una charla de una hora del tema correspondiente. Hasta ahora los temas tratados ha  sido:


	-Introducción a la impresión en 3D
	-Estabilización de un dron (PIDs)
	-Componentes de un dron( motores, hélices y variadores)


Futuras charlas:
	-Baterías
	-Antenas
	-Sistema FPV (FIrst Person View)
	-Software de vuelo
	-Modos de vuelo de un dron


DRONES
Gran parte de los integrantes de la rama montan y vuelan drones de carreras. Durante las reuniones mejoran sus diseños, e imprimen en 3D dichos diseños. 
A modo de práctica se utilizan diferentes simuladores de vuelo de drones.
Estos drones transmiten video a tiempo real con unos dispositivos que les hemos instalado, también nos fabricamos nuestras propias antenas.




FUTUROS PROYECTOS
Construcción de un dron de ala fija sobre el que puedan montarse diferentes instrumentos de filmación, topografía…...

**Comment by KFRodicio** [comment]
Me parece bien, creo que solo me falta el de RD y ya están todos

**Comment by David-Estevez** [comment]
Una cosa, ¿MYOD se reunía todavía antes del verano pasado? En caso afirmativo también hay que describir sus actividades, porque la memoria es de todo el año.

**Comment by KFRodicio** [comment]
Tecnicamente si, pero creo que mas allá del taller de mini zowis no se
hicieron mas cosas

**Comment by David-Estevez** [comment]
Pues eso también hay que ponerlo, y a ser posible con fotos. Cuanto más pongamos, más cosas verán que hacemos y más facilidades nos pondrán luego para seguir haciéndolas.

**Comment by David-Estevez** [comment]
Ya he añadido todo lo que he podido a la memoria. Como la estructura principal ya está hecha, sólo faltaría desarrollar las secciones que todavía no se han redactado.

Asigno también a @JavierIH a esta issue, pues comentó que encargaría de redactar un pequeño texto para el apartado de MYOD.

**Comment by KFRodicio** [comment]
En principio, con que javi me pase lo de myod, creo que ya puedo acabar yo
el resto. De UAVs me podeis pasar alguna foto de las charlas o reuniones,
para poner en la memoria?

**Comment by David-Estevez** [comment]
@KFRodicio En Facebook hay fotos de sus excursiones a volar drones, puedes usar esas.

**Comment by KFRodicio** [comment]
Perfecto, gracias David

**Comment by KFRodicio** [comment]
Perfecto, gracias David

El 6/12/2016 7:27 p. m., "David Estévez Fernández" <notifications@github.com>
escribió:

@KFRodicio <https://github.com/KFRodicio> En Facebook hay fotos de sus
excursiones a volar drones, puedes usar esas.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/actas/issues/45#issuecomment-265230712>, or mute
the thread

**Comment by JavierIH** [comment]
Taller de zowimanoides

La rama de investigación de robótica humanoide Myod, con el objetivo de relanzar su actividad y formar a nuevos miembros, organizó un taller de Zowimanoides. El taller fue dirigido hacia un grupo de entre 10 y 16 personas y una duración de 6 semanas.

El Zowimanoide es un robot de bajo coste y pequeño tamaño que basa su geometría en el robot Zowi. La personalización de los robots permite a los miembros experimentar con diferentes tecnologías en el ámbito del diseño 3D y de la programación.

Este taller consistió en seis sesiones, cada una con un objetivo específico que se detalla a continuación:

Semana 1: Introducción al taller.
En esta primera sesión se reunió al equipo completo para hacer una presentación del proyecto y realizar un pequeña exhibición de robots Zowimanoides. Durante la sesión se mostraron los aspectos clave del diseño de un Zowimanoide y se barajaron diferentes configuraciones de sensores y actuadores.

Semana 2: Compra de material y diseño de los robots.
Comenzando con el desarrollo de los robots, se empezaron a diseñar las primeras piezas imprimibles utilizando programas CAD a elección de cada participante. Al mismo tiempo, se realizaron las gestiones necesarias para adquirir el material que posteriormente se montaría en los robots. En este caso, el dinero de cada robot fue provisto por cada participante.

Semana 3: Impresión de piezas en 3D.
Durante la tercera sesión los participantes aprendieron a utilizar las impresoras 3D de las que dispone ASROB para imprimir sus propios diseños. Además, en esta sesión se debatieron las estrategias seguidas por cada participante para la construcción de su robot. Esta sesión fue especialmente crítica, ya que ayudó a que cada integrante del taller verificara su diseño y lo comparase con los diseños del resto.

Semana 4: Montaje de los prototipos.
En la cuarta sesión se desarrolló el montaje de los prototipos. En este momento se integró el hardware y el software que se había creado hasta el momento, siendo la sesión mas motivadora para los participantes del taller.

Semana 5: Publicación de los diseños en GitHub.
Uno de los objetivos más importante del taller fue la publicación de la documentación que se generase durante las sesiones anteriores. Toda la documentación y diseños puede consultarse en la cuenta de GitHub de ASROB, en un fork del repositorio Zowi.

Semana 6: Ajustes y pruebas en escenario real.
En esta sesión se testaron los robots en un escenario montado para la ocasión. Esta sesión fue bastante más tranquila que las anteriores, dejando un poco más de lado los apartados técnicos.

Como conclusión, el taller fomentó que los asistentes que aún no habían tenido un contacto con la robótica pudieran aplicar conocimientos de diferentes materias para construir su propio robot. Por otra parte, la posibilidad de desarrollar un proyecto propio pero común al grupo permitió que los asistentes adquirieran una visión crítica sobre sus ideas iniciales y su desarrollo. Por último, el taller sirvió para colaborar con el proyecto Zowi, el cual se localiza en GitHub y ha sido desarrollado por más de 30 contribuyentes de todo el mundo.

**Comment by jgvictores** [comment]
¿Link al doc más actualizado para poder revisarlo?

**Comment by jgvictores** [comment]
Ok, está en el Drive, revisado. ¡Chicos, habéis hecho un trabajo fenomenal! ¡¡Muchísimas Gracias!!

**Comment by KFRodicio** [comment]
Memoria y junta directiva entregadas, procedo a cerrar la issus

**Comment by David-Estevez** [comment]
Me uno a los agradecimientos a todos los que habéis contribuido a cerrar esta issue a tiempo
:clap: :clap: :clap: :clap: :clap: :clap:  :tada:  :tada:  :tada:
