### ISSUE TITLE
Actualizar la información de ASROB en el listado asociaciones UC3M

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#46]
En la actualidad, en [el listado asociaciones UC3M](http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/espacio_abierto/asociaciones/directorio), ASROB:
1. Está en el apartado de [promocion profesional](http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/espacio_abierto/asociaciones/directorio/promocion_profesional) (vs. [cultura, deporte y tecnologia](http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/espacio_abierto/asociaciones/directorio/cultura_deporte_tecnologia)). 
2. Contiene 2 de 3 enlaces a Robokode2014.
3. Figura en 2.3.A.11, nuestro despacho oficial. **Yo no cambiaría esto.** Comentarios acerca de este punto via telegram, por favor.

Creo que debemos actualizar la información de ASROB en el listado asociaciones UC3M. La vía será un email de petición a África.

Votación abierta hasta el próximo **martes 6 de Diciembre**! https://goo.gl/forms/OJkLSZcapi57ni4Y2

**Comment by David-Estevez** [comment]
La votación ha finalizado. La opción elegida ha sido:

> Eliminar los enlaces aRobokode2014 + movernos acultura_deporte_tecnologia

Con un 100% a favor (4 votos ).

@jgvictores te encargas de solicitar dicha modificación?

**Comment by David-Estevez** [comment]
Como era una cosa rápida ya he enviado el correo yo, @jgvictores :sweat_smile:

**Comment by jgvictores** [comment]
@David-Estevez Muchas gracias!!

Africa ya ha contestado, ahora estamos en [promocion_profesional](http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/espacio_abierto/asociaciones/directorio/promocion_profesional), además de [cultura_deporte_tecnologia](http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/espacio_abierto/asociaciones/directorio/cultura_deporte_tecnologia) donde ya estábamos. Lo del RoboKode2014 también ya lo ha quitado. Le he escrito dándole las gracias, renviado a lista de miembros activos. ¡Cerrando issue!

**Comment by David-Estevez** [comment]
:clap: :clap: :clap: :clap:
