### ISSUE TITLE
El calibre ha desaparecido

### ISSUE THREAD

**Issue by JuanFdelArco** [asrob-uc3m/actas#47]
He ido a echar mano del calibre del armario y no he sido capaz de encontrarlo. @David-Estevez también ha estado mirando y tampoco lo ha encontrado. Alguien lo ha visto?

**Comment by David-Estevez** [comment]
@andrespy UAVs sabe algo?

**Comment by andrespy** [comment]
yo lo he visto en el armario, mañana llevo el mio y si no lo encuentro lo dejo hasta que aparezca @David-Estevez

**Comment by David-Estevez** [comment]
Puede ser que esté, pero no somos capaces de dar con él. 

Si lo encontráis ponedlo por aquí y cerramos la issue.

**Comment by Rodriwp** [comment]
El calibre se lo ha llevado Daniel Navarro pensando que era el suyo que tenia en el armario. Lo devolvera al armario cuanto antes.

**Comment by GotYourCalibre** [comment]
Malas noticias, Daniel Navarro ha sido un daño colateral.
Su calibre ahora es nuestro rehén, si no recibimos respuesta en menos de una hora lo haremos estallar.
![calibresecuestrado](https://cloud.githubusercontent.com/assets/24316900/20835360/7d147f86-b89a-11e6-8eb7-109dd83a2010.jpg)

Alah es Glande

**Comment by jgvictores** [comment]
¿Alguien sabe en qué quedó esto?

**Comment by JuanFdelArco** [comment]
Acabo de ver que está en su sitio. @David-Estevez puede dar fe de ello. Cierro pues la issue.

**Comment by David-Estevez** [comment]
Pero el que había en el armario no es el de la foto del secuestro... seguro que era el nuestro?

**Comment by JuanFdelArco** [comment]
Definitivamente el que está en el armario es el nuestro. "Recierro" esto.
