### ISSUE TITLE
El router siempre se queda fuera

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#48]
Y no mola que eso ocurra.

**Comment by jgvictores** [comment]
Estoy de acuerdo. No mola. Hace pensar en un anti-Asrobcoin que resta Asrobcoins.

**Comment by David-Estevez** [comment]
Gracias al ASROBOT que hemos implementado, al menos ahora hay un aviso de que el router se ha quedado fuera.

Creo que es lo único que podemos hacer al respecto, así que cierro la issue. Si volviese a ser un problema se reabre y listo.

**Comment by jgvictores** [comment]
@David-Estevez Thanks!!!
