### ISSUE TITLE
Cable HDMI para pantalla asrob

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#49]
Acabo de encontra el transformador de la pantalla que tenemos en la nave inventariada con la pegatina asrob. Para que este operativa solo faltaria un cable HDMI

Alguien tiene uno de sobra por ahi, o hacemos una peticion de finanaciacion para comparlo ?

**Comment by David-Estevez** [comment]
Estamos en proceso de conseguirlo, don't worry!

**Comment by jgvictores** [comment]
Me he acercado a la nave. Esa fuente es de máximo 3.3 A. Por favor no alimentéis el monitor de 5 A con esa fuente, que obviamente no es la suya. Cerrando issue como inválida.

![photo_2016-12-02_16-28-53](https://cloud.githubusercontent.com/assets/4448588/20839343/7e45547c-b8ac-11e6-8dd1-f5a1b1d39411.jpg)
