### ISSUE TITLE
Organizar Contactos Externos

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#5]
En la reunión del 24/02/2016 se propuso realizar encuentros con otras asociaciones de otras universidades para fomentar el intercambio de ideas y experiencias y darnos a conocer.

Tareas: 
- [x] Contacto con otras asociaciones
- [x] Organizar encuentro

**Comment by David-Estevez** [comment]
@CarlosGS os apetece estrenar la temporada de visitas?

**Comment by CarlosGS** [comment]
Sí!!! Cómo lo podemos hacer? Nuestros respectivos campus están en Mordor del Norte (UAM) y Mordor del Sur (UC3M) :') así que habría que sincronizarse bien!

**Comment by David-Estevez** [comment]
Pues yo crearía un Doodle con unas propuestas de  fecha para ver cuándo nos viene mejor a todos. @CarlosGS os parece que pongamos en el doodle las dos últimas semanas de Abril? Así hay tiempo de cuadrar agendas

**Comment by CarlosGS** [comment]
OK, voy pensando qué tipo de encuentro puede ser

**Comment by asrobuc3m** [comment]
Cerrado por inactividad (> 1 mes).

**Comment by David-Estevez** [comment]
Voy a reabrir la issue con una propuesta de "Cena de Navidad" interasociacional.

¿Qué os parece, @CarlosGS?

**Comment by CarlosGS** [comment]
Por mí estupendo, ¿cuando os apetece?

**Comment by David-Estevez** [comment]
He creado un Doodle para decidirlo: http://doodle.com/poll/kyhr2hn5s92qgfne

Digamos que damos hasta el final de esta semana de margen para decidirlo.

**Comment by David-Estevez** [comment]
Doodle cerrado!

El ganador, por aplastante mayoría es el **martes 20 de Diciembre**. Por tanto la cena será ese día.

Respecto al sitio, se han propuesto tres sitios:
* ~McAuto~
* ~La cafetería de la universidad~
* Goiko Grill

Habrá que confirmar cuántos seremos finalmente para poder reservar para ese día.

**Comment by CarlosGS** [comment]
Apuntado! Qué ganas!!! Muchas gracias por organizarlo :-)

**Comment by jgvictores** [comment]
@David-Estevez ¿Vía oficial para confirmar (esta issue, telegram...)?

**Comment by David-Estevez** [comment]
@jgvictores Casi nos montamos un doodle, no? Que ~20 personas comentando son muchos comentarios...

**Comment by David-Estevez** [comment]
Doodle para confirmar aquí: http://doodle.com/poll/q4f6a8bitpwdx8bm

Dejamos hasta este domingo (incluido) para que confirméis, el lunes llamamos para reservar (porque si no igual nos quedamos sin sitio).

**Comment by David-Estevez** [comment]
Ya está todo reservado para ese día. El resumen es el siguiente: 

# Información importante sobre la reserva:

 * **Número de personas**: 18
 * **Fecha**: martes 20 diciembre 2016
 * **Hora**: 22:00

# Dirección del restaurante:
GOIKO GRILL - Glorieta de Bilbao: Glorieta de Bilbao, 3 , 28004, Madrid

# Duración de la reserva
Para grupos de más de 12 personas la reserva tiene una duración de 2:00 horas. Si no habéis llegado después de 15 minutos una vez comenzada la reserva, liberaremos la mesa.

@CarlosGS te encargas tú de avisar a la gente del CRM que se apuntó?

**Comment by CarlosGS** [comment]
Avisados están! Gracias!!

2016-12-13 19:17 GMT+01:00 David Estévez Fernández <notifications@github.com

**Comment by David-Estevez** [comment]
Una cena genial de la que tardaremos en recuperarnos... :joy: :joy: :joy: 

Un placer teneros por allí, chicos, y a ver si este es el comienzo de más actividades juntos!

**Comment by CarlosGS** [comment]
Sin duda ha estado genial. Una gran iniciativa por vuestra parte :D
¡¡Gracias por contar con nosotros!! @eduhs @crm-uam
