### ISSUE TITLE
Convocatoria subvenciones 2016-2017

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#50]
Tenemos hasta el 15 de diciembre para pedir hasta 5 subvenciones pertenecientes a ASROB

 http://portal.uc3m.es/portal/page/portal/cultura_y_deporte/espacio_abierto/concursos/convocatoria_ayudas

Podemos pedir hasta 5 subvenciones siendo una de ellas en colaboracion de dos o mas asociación.

Propongo que la subvención de colaboración se realice en conjunto con uc3music, para la realización de 2 o más hackatones durante el curso.

**Comment by Rodriwp** [comment]
Ahora mismo hay 3 subvenciones propuestas en desarrollo: 

1. Hackton (asrob-uc3music) proyecto colaborativo
2. Proyecto Integrado arduino 
3. Proyecto EEG

**Comment by Rodriwp** [comment]
Aqui esta el proyecto integrado: INICIACION A LA ARDUINO
[Anexo II.2 .ProyectoINTEGRADO_Iniciación_a_la_arduino.docx](https://github.com/asrob-uc3m/actas/files/652155/Anexo.II.2.ProyectoINTEGRADO_Iniciacion_a_la_arduino.docx)

@jgvictores @David-Estevez tenemos que rellanar el anexo I con los datos de la asociación correspondientes a cada uno.

**Comment by jgvictores** [comment]
Respecto a las 3 propuestas que mencionas, por favor enumera a qué grupo activo pertenece cada una.

**Comment by jorgerc21** [comment]
Ya está listo el anexo del taller EEG pero no me deja adjuntarlo, donde lo envío? 
Respecto al tema de grupo activo, por ahora podría incluirse en HackLab ya que ha surgido de esa rama y aún está en gestación, y una vez el proyecto avance de manera independiente crearíamos un nuevo grupo.

**Comment by Rodriwp** [comment]
1 Proyecto colaborativo( responsable UC3Music)
2 Iniciacion a la arduino(HackLab- City of Robots)
3 EGG ( HackLab-City of Robots)

Recuerdo que para llegar a pider pedir hasta 5 subvenciones se nos exige almenos una de proyecto colaborativo. 

Propongo que cada uno presente las propuestas a subvencion, adjuntando el anexo II. En caso se tener mas de 5 propuestas, se votara con cuales nos quedamos.

**Comment by jgvictores** [comment]
@Rodriwp

1. Por favor nos subas nada por tu cuenta.
2. Por favor reflexiona sobre si Hacklab ha hecho los deberes en este periodo (documentar cada proyecto, subir sus proyectos a GitHub... esas cosas que haría un grupo activo).
3. Revisa tu(s) memoria(s).  Contiene errores GRAVES.

**Comment by David-Estevez** [comment]
Además de lo que te ha comentado ya @jgvictores, sólo añadir los siguientes puntos:

1. Por favor, lee correctamente las bases de la convocatoria. Tus comentarios acerca de la misma contienen errores.
2. Dado que no ha habido actividad en esta issue hasta el día anterior a la deadline, UC3Music y ASROB, representadas en este caso por @JorFru y @David-Estevez,  tomaron la iniciativa y ya han organizado y redactado las solicitudes de dinero conjuntas ASROB-UC3Music para El Evento 2017 y para Hackatón. Dicha solicitud ya contiene una partida para el material que describes en tu solicitud, por lo que es redundante, además de contener errores graves como ha comentado @jgvictores .
3. Pese a nuestra insistencia en que el grupo de EEG se formase como grupo activo, no ha habido ninguna solicitud por parte del mismo ni aparece en la wiki, por lo tanto no seguiría los [Estatutos](https://github.com/asrob-uc3m/estatutos) que pidiese algún tipo de ayuda bajo el nombre de ASROB. No obstante el proyecto me parece muy interesante, y para que salga adelante os insto a que solicitéis la ayuda a título personal (modalidad permitida por la convocatoria).
4. Robot Devastation, al haber cumplido durante el año con sus obligaciones como rama activa, pedirá ayudas para sus proyectos, los cuales ya han sido planificados y aprobados por los responsables del proyecto durante las reuniones de su grupo activo. Redactaré y subiré dichas solicitudes a lo largo de la mañana, antes que cierre el plazo.

**Comment by Rodriwp** [comment]
1. Considero que HackLab ha cumplido con sus obligaciones como rama activa, y ha cumplido sus obligaciones en cuanto documentación a los proyectos realizados como dicha rama. 
2. En cuanto al tema de EEG esto de acuerdo con @David-Estevez 
3. He estado trabajando usando el material que me paso @JorFru para preparar la convocatoria de proyecto conjunto Hackton. En cualquier caso, si decis que ya lo teneis hecho perfecto.Descarto el documento que tenia
4. Siento que mi inexperiencia con este tipo de solicitudes lleve a que la que he redactado para el proyecto hacklab no tenga la misma calidad que las que pueda hacer gente mas experimentada. Revisare la memoria para encontrar esos defectos que señalais y asi corregirlos.

**Comment by jgvictores** [comment]
@Rodriwp

1. Por favor lee los estatutos acerca de un grupo activo. Por favor contesta desde un punto de vista analítico y sincero si http://asrob.uc3m.es/index.php/HackLab:_Proyectos y la total falta de presencia en GitHub hace de esta idea un grupo activo.

**Comment by Rodriwp** [comment]
@jgvictores 

Entiendo que por tanto consideras que HackLab no es un grupo activo. 
Me parece correcto dar de baja HackLab como grupo activo, puesto que no cumple las especificaciones de nuestros estatutos como grupo activo asrob. 
Por tanto procedo a no pedir la subvencion "Iniciacion a la arduino"

**Comment by David-Estevez** [comment]
Las solicitudes ya fueron enviadas dentro del plazo correspondiente.

Cumpliendo nuestros requisitos de transparencia:

* [Aquí](http://asrob.uc3m.es/index.php/Convocatoria_Proyectos_2017) está documentada la relación de subvenciones pedidas y los correspondientes proyectos.
* Se procede de inmediato al traspaso de la propiedad de los documentos de dichas solicitudes a la cuenta de ASROB.
