### ISSUE TITLE
Prestamo del joystick grande

### ISSUE THREAD

**Issue by JuanFdelArco** [asrob-uc3m/actas#54]
Un compañero del máster que estuvo en el Hackatón (Guillermo) me ha preguntado si ASROB le podía prestar el joystick grande para utilizarlo en su proyecto de teleoperación. Lo devolvería la semana que viene después de presentar el proyecto.

**Comment by David-Estevez** [comment]
Mientras no le haga modificaciones yo no veo objecciones...

**Comment by jgvictores** [comment]
Idem.

**Comment by JuanFdelArco** [comment]
Ok pues se lo prestaré y cuando lo devuelva cerraré la issue.

**Comment by David-Estevez** [comment]
El joystick fue devuelto (incluso con mejoras) y está ya sano y salvo en el armario.
