### ISSUE TITLE
Global Robot Expo

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#55]
Entre el 2 y el 4 de febrero se celebra la segunda edición de Global Robot Expo (http://www.globalrobotexpo.com/en/).

Abro hilo para comentar acerca de esto a medida que me dan detalles acerca de posibilidad de stand, etc.

**Comment by JavierIH** [comment]
Saludos,

Yo tengo pensado ir como mínimo de visitante ¿Qué posibilidad tenemos de exponer cosas? ¿Un hueco en algún stand de la UC3M/RoboticsLab?

**Comment by jgvictores** [comment]
Tenemos una mesa para nosotros, al lado del cual colocaremos el roller.

¡Bienvenidos sean tu [Raider](http://lnrc.es/robots.jsp?id=176), [miniKame](https://github.com/JavierIH/miniKame), y lo que se te ocurra!

**Comment by jgvictores** [comment]
¿Más participaciones?

En la última [Jornada](https://github.com/asrob-uc3m/actas/issues/36) al final casi sólo estuvimos @KFRodicio @David-Estevez y yo...

¡Los ASROB-COIN se consiguen, pero hay que minarlos!

**Comment by JavierIH** [comment]
Guay, yo tengo posibilidad de ir desde el viernes por la tarde en adelante.

**Comment by JavierIH** [comment]
¿Alguna noticia? ¿Si en la puerta digo que soy yo me dejarán pasar?

**Comment by jgvictores** [comment]
A los de la Uni nos han dado códigos por persona. Voy moviendo lo tuyo y te comento vía privado.

**Comment by David-Estevez** [comment]
Un éxito, como siempre. Muchas gracias a todos por vuestra participación!!!

**Comment by jgvictores** [comment]
Para el histórico, estuvimos: @David-Estevez @imontesino @victordiazobregon @jgvictores

**Comment by jgvictores** [comment]
cc: https://github.com/asrob-uc3m/estatutos/issues/11

**Comment by JavierIH** [comment]
Nota para el histórico: Javi llevó sus robots a la mesa del stand y cuando llegó no había mesa en el stand.

**Comment by jgvictores** [comment]
@JavierIH He actualizado mi comentario arriba.

BTW, lo vamos a gestionar vía assigned para evitar NLP. Estás assigned. :smile:

**Comment by David-Estevez** [comment]
Sí, a mi también me pareció curioso que no hubiese espacio en el stand para una Asociación sin ánimo de lucro...
