### ISSUE TITLE
Cambio de tesorero

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#57]
Con motivo de la dimisión por parte del anterior tesorero @Rodriwp (#52), me propongo como candidato a puesto de tesorero.

Votación abierta hasta 3 de Febrero las 23:59, enlace: https://goo.gl/forms/cTnf9Xa9LXt76N9H2
M.A.G.I.A.

**Comment by David-Estevez** [comment]
Se aprueba la propuesta con 3 votos a favor y 0 en contra.

Por tanto, con efecto inmediato se proclama a @jgvictores como nuevo tesorero de ASROB. Procedo a la actualización de la wiki y a la gestión del traspaso de poderes en la issue #59
