### ISSUE TITLE
Traspaso de tesorería

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#59]
Tras la dimisión del antiguo tesorero @Rodriwp ( #52 ) y la posterior elección de @jgvictores como nuevo tesorero ( #57 ) creo esta issue para coordinar el traspaso del cargo de tesorero de manera rápida y eficaz.

Tareas a realizar:

 - [x] Comunicación del estado actual de las cuentas
 - [x] Traspaso de dinero 
 - [x] Resolución de todas las dudas del nuevo tesorero (en caso de tenerlas)

**Comment by Rodriwp** [comment]
En este momento el estado de las cuentas es el siguiente: 

300.54 euros en efectivo (en cuenta)
27 euros efectivo piggy (en cuenta)

Todacia no se ha pagado nada del presupuesto asignado en #21

En cuanto a subvenciones, no hay ningun tramite pendiente, ni ninguna subvencion en proceso para el conjunto de asrob.

**Comment by jgvictores** [comment]
@Rodriwp ¿El titular de `cuenta` eres tú a nivel individual?

**Comment by Rodriwp** [comment]
Si. Para el traspaso de dinero se puede hacer en efectivo o a la cuenta que  indiques.

**Comment by jgvictores** [comment]
Efectivo, ¿reunión mañana miércoles?

**Comment by Rodriwp** [comment]
No estoy disponible en esa fecha, propongo mañana jueves. 

En caso de ser efectivo,Como formalizamos la documentacion del traspaso del dinero ?

**Comment by jgvictores** [comment]
Acabamos de hablar @Rodriwp y yo en persona. Hemos acordado:
- Traspaso de dinero en efectivo en persona Feb 15-16 2017.
- Formalizar la documentación del traspaso mediante triple ACK vía esta issue de GitHub y redundancia en grupo `ASROB: Organización Horizontal (como Valve)` de Telegram.
- Quedamos pendientes de ver lo de los 100 EUR en material de Bricogeek.

**Comment by Rodriwp** [comment]
Se procede a la entrega a @jgvictores nuevo tesorero votado democraticamente en #54 de la cantidad ##300,54##trecientos euros con cincuenta y cuatro centimos ## correspondiente al dinero efectivo de los fondos de asroba fecha de 23-02-2017

Queda por entregar el dinero perteneciente al apartado piggy asi documentado en la wiki. ##27## vientisiete euros##

**Comment by David-Estevez** [comment]
¿La información de la wiki está al día? La última modificación tiene fecha de Noviembre 2016, y parece que hay información confusa y/o incompleta:

![image](https://cloud.githubusercontent.com/assets/1451819/23255810/3865eb5e-f9bd-11e6-9d9d-719c1f3411eb.png)

Esta información debería ser aclarada para el correcto traspaso de tesorería.

**Comment by jgvictores** [comment]
Recibida la cantidad de ##300,54##trecientos euros con cincuenta y cuatro centimos ## correspondiente al dinero efectivo de los fondos de asroba fecha de 23-02-2017.

Queda por entregar el dinero perteneciente al apartado piggy.

**Comment by Rodriwp** [comment]
La información esta actualizada, no ha habido movimientos economicos desde esa fecha. Ultimo gasto fue El evento. 

El apartado mencionado antes @David-Estevez corresponde al contenido del interior de piggy.

Como ya ha sido comunicado a @jgvictores   hay 80 euros asignados a ROBOTDEVASTATION en  #21, no asignados todavia.

**Comment by jgvictores** [comment]
> Como ya ha sido comunicado a @jgvictores hay 80 euros asignados a ROBOTDEVASTATION en #21, no asignados todavia.

Primera noticia.

**Comment by jgvictores** [comment]
> Como ya ha sido comunicado a @jgvictores hay 80 euros asignados a ROBOTDEVASTATION en #21, no asignados todavia.

Ok pero visto ya en #21.

**Comment by Rodriwp** [comment]
> Recibidala cantidad de ##300,54##trecientos euros con cincuenta y cuatro centimos ## correspondiente al dinero efectivo de los fondos de asroba fecha de 23-02-2017.
Queda por entregar el dinero perteneciente al apartado piggy.

ACK

**Comment by jgvictores** [comment]
@Rodriwp El comentario de @David-Estevez se refiere a los interrogantes en la wiki referente al contenido actual de Piggy. Por favor documéntalo con una cifra exacta.

**Comment by David-Estevez** [comment]
> Como ya ha sido comunicado a @jgvictores hay 80 euros asignados a ROBOTDEVASTATION en #21, no asignados todavia.

Esa frase es una contradicción lógica A = ¬A no se cumple para ningún valor de A.

> @Rodriwp El comentario de @David-Estevez se refiere a los interrogantes en la wiki referente al contenido actual de Piggy. Por favor documéntalo con una cifra exacta.

Exacto.

**Comment by jgvictores** [comment]
> Esa frase es una contradicción lógica. A = ¬A no se cumple para ningún valor de A.

:joy::+1:

**Comment by Rodriwp** [comment]
@David-Estevez corrijo commentario, es "entregados" no "asignados"

En piggy hay 9,02 a las 12:07 del dia 23-02-2017, procedo ha actualizar la wiki

**Comment by David-Estevez** [comment]
Thanks :smile:

**Comment by Rodriwp** [comment]
Se ha actualizado el dinero de piggy puesto que hubo un fallo en el primer recuento de monedas. El dinero real de piggy es 8,03

**Comment by David-Estevez** [comment]
:man_facepalming:

**Comment by Rodriwp** [comment]
Se procede a la entrega a @jgvictores nuevo tesorero votado democraticamente en #57 de la cantidad ##8,03##ocho euros con tres centimos ## correspondiente al dinero en el interio de piggy el dia 23-02-2017 a las 12:26

**Comment by jgvictores** [comment]
Recibida la entrega por parte de @jgvictores votado democraticamente en #57 de la cantidad ##8,01##ocho euros con un centimo ## correspondiente al dinero en el interior de piggy más ##0,02## dos céntimos## el dia 23-02-2017 a las 12:26

**Comment by Rodriwp** [comment]
> Recibida la entrega por parte de @jgvictores votado democraticamente en #57 de la cantidad ##8,01##ocho euros con un centimo ## correspondiente al dinero en el interior de piggy más ##0,02## dos céntimos## el dia 23-02-2017 a las 12:26

ACK

**Comment by jgvictores** [comment]
@Rodriwp Ok transacción 27 EUR restantes el jueves Marzo 9 2017 a las 11h ?

**Comment by Rodriwp** [comment]
Se procede a la entrega a @jgvictores nuevo tesorero votado democraticamente en #57 de la cantidad ##27##veintisiete euros## correspondientes al dinero piggy fuera de piggy el dia 9-03-2017 a las 11:10

**Comment by jgvictores** [comment]
ACK recibido re: "Se procede a la entrega a @jgvictores nuevo tesorero votado democraticamente en #57 de la cantidad ##27##veintisiete euros## correspondientes al dinero piggy fuera de piggy el dia 9-03-2017 a las 11:10"

**Comment by Rodriwp** [comment]
`ACK recibido re: "Se procede a la entrega a @jgvictores nuevo tesorero votado democraticamente en #57 de la cantidad ##27##veintisiete euros## correspondientes al dinero piggy fuera de piggy el dia 9-03-2017 a las 11:10"`
ACK

**Comment by Rodriwp** [comment]
En cuanto @jgvictores  confirme que no queda ninguna duda respecto al traspaso de tesoreria, se procedera a cerrar la issue

**Comment by David-Estevez** [comment]
Estáis en un bucle ACK xD

**Comment by jgvictores** [comment]
Issue abierta a espera de la devolución de la impresora.

**Comment by Rodriwp** [comment]
No estoy de acuerdo en dejar la issue abierta, puesto que la impresora no forma parte del traspaso de tesoreria. Sugeriria poner otra issue acerca de la impresora. Para documentar el trabajo hecho en ella.

**Comment by Rodriwp** [comment]
La impresora esta ya en el armario de asrob. En el armario 2, procedo a cerrar issue.

![img_20170316_110812](https://cloud.githubusercontent.com/assets/9463837/23993455/ea71aebc-0a40-11e7-9969-e0c78fc9588d.jpg)
