### ISSUE TITLE
Camisetas ASROB

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#6]
En la reunión del 24/02/2016 se propuso la realización de camisetas ASROB.

Tareas:
- [x] Diseño de la camiseta
- [x] Buscar fabricante
- [x] Fabricar camisetas

@Rodriwp cuál era la web esa que tenía buenos precios?

**Comment by Rodriwp** [comment]
Donde pedi las camiseta la vez que hice se llama publilocura.es
El pedido minimo son 50 unidades, y tienen bastante flexibilidad (probablemente podamos pedir dos colores de camiseta en el mismo pedido)

Yo pedi dogo premium, que sale a 3,25 euros la camiseta serigrafia incluida. Abria que vectorizar la mascota.

Tambien hay oferta sudadera+camiseta por 13 euros, apartir de 15 unidades(serigrafia a un solo color en este caso, pero si necesitamos mas colores el precio no sube mucho)

Dejare una camiseta loft16 en el armario para que podais ver la calidad de la tela y la serigrafia. Esta tiene 2 años y mucho mucho uso.

**Comment by David-Estevez** [comment]
Pongo en copia a @JorFru, en representación de UC3Music, que también queremos camisetas.

La mascota es vectorial ya, lo único sería ver cuántos colores tiene la paleta que se usa en las camisetas, porque los degradados habría que convertirlos.

Yo veo bien los precios esos, aunque haya que poner dinero de más (o llevarnos 5 camisetas cada uno xD) Al final seguro que lo recuperamos.

**Comment by JorFru** [comment]
HOYGAN!
Gracias por la información @Rodriwp

**Comment by David-Estevez** [comment]
Creamos un doodle para ver cuánta gente quiere camiseta? Si vemos que faltan muchas camisetas para el pedido mínimo pues vemos quién puede poner más money y las dejamos en stock para el futuro.

**Comment by KFRodicio** [comment]
Creo que mejor que un doodle, un google sheet en el drive de asrob, ahí va el link:
https://docs.google.com/spreadsheets/d/1fYBetExHGzEztZOXPuVPL5BqdAVaF89dmJYS-BKuk0E/edit#gid=0

**Comment by David-Estevez** [comment]
Visto que no llegamos a 50 (hay 23 apuntados).. ¿buscamos una empresa que haga menos camisetas? (p.ej http://www.camisetas.info/ )

**Comment by JorFru** [comment]
Para UC3Music, que tenemos apuntadas 15 camisetas, saldría cada una a 15€
(incluso más si se añaden extras) Si llegásemos a treinta, saldrían a menos
de 10€.
PUFFFFFFF lo veo negro.
[image: Imágenes integradas 2]

2016-04-04 18:58 GMT+02:00 David Estévez Fernández <notifications@github.com
>:

> Visto que no llegamos a 50 (hay 23 apuntados).. ¿buscamos una empresa que
> haga menos camisetas? (p.ej http://www.camisetas.info/ )
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/asrob-uc3m/actas/issues/6#issuecomment-205392120>
>



-- 
*Jorge Frutos de Mingo*

Ingeniería Electrónica Industrial y Automática.
Asociación de estudiantes UC3Music-e.
Universidad Carlos III de Madrid.

**Comment by David-Estevez** [comment]
Hola a todos!

Como algunos ya sabréis, el día 7 de Octubre se celebra la Feria de Asociaciones en el campus de Leganés. ASROB estará por allí dándolo todo, pero nos hacen falta camisetas para que se nos reconozca mejor.

Aprovechando esto, y dado que no llegamos a las 50 camisetas necesarias para el proveedor que teníamos pensado en un principio, hemos buscado un proveedor alternativo que nos las deja en 7,5€ / ud.

Como tienen que estar para el día 7, necesitamos que el pedido esté hecho como muy tarde el día **29 de Septiembre.** Así que por favor, los que sigáis interesados en las camisetas ASROB, confimad talla y número de camisetas en[ el siguiente documento](https://docs.google.com/spreadsheets/d/1GDelNDZVYJTarbkCxeW0eYm63VwEIYpNvqrP9L2gDLU/edit#gid=0). Una vez cerrado el plazo, se hará el pedido con los datos del documento.

Una vez listas os avisaremos para que paséis a recogerlas.

Un saludo!

**Comment by David-Estevez** [comment]
Las camisetas están ya pedidas y pendientes de que las hagan y nos avisen para recogerlas. Deberían estar para el próximo viernes, para poder usarlas en la Feria de Asociaciones.

Para evitar líos, las camisetas se pagarán cuando vengáis a recogerlas (8.5€ cada una).

**Comment by David-Estevez** [comment]
Todas las camisetas están entregadas, así que cierro la issue :smile:

**Comment by JorFru** [comment]
Ahora que hay muchos jóvenes padawan en ASROB podríamos revivir esta issue, junto a la de las camisetas.

**Comment by David-Estevez** [comment]
Iguales o distintas (para coleccionarlas :joy: ) ??

Si queréis camisetas abrid una issue nueva, que yo creo que si no se pierden las cosas entre tanto comentario...
