### ISSUE TITLE
Entrega de llaves de las impresoras 3D

### ISSUE THREAD

**Issue by jorgerc21** [asrob-uc3m/actas#60]
Quería dejar constancia de que el anterior encargado ha hecho entrega de una de las llaves de los candados de las impresoras 3D. 
Aprovecho para preguntar si el encargado de impresoras debe tener llaves de los recursos de la asociación, ya que antes el encargado las tenía por ser responsable de un grupo activo.

**Comment by David-Estevez** [comment]
Constancia recibida.

Sobre " llaves de los recursos de la asociación", que imagino se refiere a los armarios, cito #15:
> Cada rama activa tiene derecho a tener hasta 2 llaves que se solicitaran al tesorero y tendra el coste de 1,20 euros. No se podran hacer copias adicionales de esas llaves. Se guardara en el inventario una relación con las llaves y los guardianes de las mismas.

Si perteneces a City of Iotas, siendo rama activa, podrías tener copia de la llave, ya que se pueden tener hasta 2. No obstante, si crees que el desempeño del cargo de Responable de Impresoras requiere acceso al material, propón una enmienda [aquí](https://github.com/asrob-uc3m/estatutos/issues).
