### ISSUE TITLE
Petición de financiación para impresoras 3D

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/actas#62]
Para la reparación de las impresoras 3D y para tener repuestos en un futuro 
<table>
<thead>
<tr>
<th>Item</th>
<th>Cantidad</th>
<th>Coste unitario</th>
<th>Coste</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="http://www.3despana.com/electronica/16-resistencia-ceramica-12v-40w-para-extrusor-hot-end.html">Resistencia ceramica para extrusor</a></td>
<td>2</td>
<td>1,99 €</td>
<td>3,98 €</td>
</tr>
<tr>
<td><a href="http://www.3despana.com/cinta-poliamida-kapton/57-rollo-cinta-poliamida-kapton-20mm.html">Rollo Cinta Poliamida Kapton 20mm</a></td>
<td>1</td>
<td>3,49 €</td>
<td>3,49 €</td>
</tr>
<tr>
<td><a href="http://www.3despana.com/camas-calientes-heat-bed/314-plancha-cristal-borosilicato-213-x-200.html">Plancha cristal borosilicato 213 X 200</a></td>
<td>2</td>
<td>4,99 €</td>
<td>9,98€</td>
</tr>
<tr>
<td>Total:</td>
<td>-</td>
<td>-</td>
<td>17,45€</td>
</tr>
<tr>
</tr></tbody></table>

- El espejo de Blacky ha desaparecido asi que toca pedir otro y los espejos de Ikea que hasta ahora usabamos están descatalogados.

-  El calentador de Hija está dando problemas y necesitamos un repuesto. Se estudia la posibilidad de comprar un hotend nuevo para Hija.

-  Se aceptan propuestas si encontrais los productos más baratos o de material necesario para las impresoras 3D que no hayamos incluido.

 Queda a la espera del visto bueno del tesorero @jgvictores

Gracias a @Siotma por buscar los productos a comprar

**Comment by David-Estevez** [comment]
No sé si procede en este caso la petición de financiación, pues los repuestos de impresoras, hasta donde yo sé, se gestionan a través del Departamento de Sistemas y Automática (DISA).

Siendo así, lo mejor es que hagáis un listado de las partes que serían necesarias para la reparación y que @jgvictores o yo mismo se lo pasemos a quien corresponda en el DISA.

PD: me suena que Kapton había en el armario, antes de comprar más es mejor comprobarlo.

**Comment by Siotma** [comment]
Una de las cosas buenas de 3DEspana es que permite entrega en mano en Getafe, lo que ahorraría los gastos de envío. Además el tío que lleva la tienda es muy atento y responde rápido ante cualquier problema o defecto con sus piezas.

Por otra parte, quiero destacar mi preocupación por el **antiguo cristal de Blacky**, ya que, que sepamos:

- No se ha estropeado, como sí ha pasado con el calentador del extrusor.

- Ni es un material fungible, como lo es el Kapton por ejemplo.

De lo que deduzco que en algún momento **alguien ha debido cogerlo y llevarlo** a otro sitio (quiero pensar que para guardarlo), o tal vez sí se rompiera y yo no lo sepa...

Por otra parte, dado que Blacky pertenece al DISA, lanzo la **pregunta:** 

- ¿Esta y futuras reparaciones deberían sufragarse desde los fondos de ASROB?

**Comment by Siotma** [comment]
Vale, David, te me has adelantado por poco jajaja

Entonces, todos los gastos corren por el DISA, independientemente de la propiedad de la impresora?

**Comment by David-Estevez** [comment]
Es lo que nos tiene que confirmar @jgvictores, pero yo tengo entendido que sí, ya que el mantenimiento de ambas lo hacemos nosotros.

Respecto a lo del espejo, me suena haber visto uno de ellos (muy) roto, probablemente al despegar una pieza rebelde, por lo que se habrá tirado. No obstante, estaría bien que la persona a la que se le haya roto, ya sea de ASROB o del DISA, hubiese dado parte de ello para poder sustituirlo.

**Comment by jorgerc21** [comment]
Si dices que hay Kapton lo buscaremos esta semana, pero no lo vimos en la reunión pasada. Esperamos unos días a ver si alguien tiene noticia del espejo de Blacky o quiere hacer una aportación a la lista y si no, podeis pasarle la lista al departamento. 
Entiendo que para esto no hace falta votación.

Yo tambien vi el espejo rotisimo, pero me parece que Blacky aún tenía el suyo por entonces.

Edito el OP: Quito los gastos de envio y la votación

**Comment by jgvictores** [comment]
1. Resistencia ceramica para extrusor: @David-Estevez va a hacer un pedido, con lo cual nos ahorramos los gastos de envío, pero sale a 3.5€. Propongo un bote express para reponérselo.
2. Rollo Cinta Poliamida Kapton 20mm: Me comenta @David-Estevez que debe haber en el armario. Por favor busquen y/o consúltenle.
3. Plancha cristal borosilicato 213 X 200: Mi amigo @veimox en su día me regaló un cristal para la impresora, quedando el espejo (con Kapton por cierto) a la espera de un nuevo lugar. Se lo he puesto a Blacky, adjunto foto.

![imag1456](https://cloud.githubusercontent.com/assets/4448588/23143387/7a512946-f7c1-11e6-8cee-ff9af4085722.jpg)

**Comment by Siotma** [comment]
Estupendo todo!! Muchas gracias por la donación Juan!

Animo a los demás grupos de trabajo activos que revisen su parte del armario en busca del rollo de Kapton, nosotros revisaremos hoy las baldas comunes.

**Comment by Rodriwp** [comment]
Piggy nacio para resolver estos problemas de petición de material. Propongo que la resistencia ceramica se saque de ahi. Además Piggy seguro que hara todo lo posible por revivir a su creador.

**Comment by jgvictores** [comment]
> Piggy nacio para resolver estos problemas de petición de material. Propongo que la resistencia ceramica se saque de ahi.

@Rodriwp Puedes proponer una [votación en condiciones](https://github.com/asrob-uc3m/estatutos/blob/0a2200c14a7dbd527f8a38935ea1ab643af3df58/metodo_de_votacion.md) para este gasto particular.

**Comment by David-Estevez** [comment]
Dos cosillas:

1. La resistencia esa se ha pedido al departamento como fungible, dado su escaso coste económico. No hay necesidad de romper la hucha de momento.
2. Al parecer no hay Kapton, no soy capaz de encontrarlo por ningún lado.  Para eso sí que puede que haya que romper la hucha (o intentar pedírselo también al departamento, que al fin y al cabo se va a usar en su impresora también).

**Comment by jgvictores** [comment]
- [x] Resistencia.
- [x] Espejo.
- [ ] Kapton. Trataré de gestionarlo a través del Departamento.

**Comment by jgvictores** [comment]
He conseguido Kapton 2 cm de ancho.

¿Serviría para sacar del apuro hasta conseguir uno más ancho (tardará aprox. 2 semanas)?

**Comment by Siotma** [comment]
Perfecto, es el mismo que yo uso.

Ten en cuenta que no lo queremos para cubrir los espejos, sino para asegurar los montajes en las partes calientes.

**Comment by jgvictores** [comment]
Ahí os lo dejé:
![imag1588](https://cloud.githubusercontent.com/assets/4448588/23506314/eae93c1a-ff47-11e6-9178-fe4d49751122.jpg)

**Comment by jgvictores** [comment]
¿Ok cerrar issue?

**Comment by David-Estevez** [comment]
Falta calefactor de repuesto, ya está pedido. Cuando llegue cerramos issue.

**Comment by Siotma** [comment]
Cinta de Kapton fagocitada.

Está ahora en la caja de impresoras 3D, dentro del armario.

**Comment by David-Estevez** [comment]
Calentador recibido y guardado en el armario: 
![img_20170306_171533](https://cloud.githubusercontent.com/assets/1451819/23622075/757365ba-029d-11e7-98ab-4d8e72d683cd.jpg)

Cerrando issue...

**Comment by jorgercobo** [comment]
_Reabro la issue para hacer una nueva petición. Si es mejor abrir una issue aparte, decidmelo._
Para el uso de las impresoras 3D
<table>
<thead>
<tr>
<th>Item</th>
<th>Cantidad</th>
<th>Coste unitario</th>
<th>Coste</th>
</tr>
</thead>
<tbody>
<tr>
<td>Espatula</td>
<td>1</td>
<td>-</td>
<td>-</td>
</tr>
<tr>
<td>Rollo Cinta Poliamida Kapton</td>
<td>1</td>
<td>-</td>
<td>-</td>
</tr>
<tr>
<td>Acetona</td>
<td>1</td>
<td>-</td>
<td>-</td>
</tr>
</tr></tbody></table>


- No es necesario que la espatula sea especifica para impresoras 3D [(ejemplo)](https://www.3djake.es/buildtak/espatula), puede servirnos cualquier espatula mientras su hoja sea grande.
- Como el kapton que recibimos la vez anterior parece no hacer su función, repetimos la petición.

Rogamos se trasladen estas peticiones a quien corresponda, si es necesario financiar algún gasto por Piggy iniciaremos la votación

**Comment by jgvictores** [comment]
1. Da un poco igual, abrir nueva que reabrir en este caso. Sigamos por aquí.
1. Se trataría de especificar un coste y abrir una votación.

PD: Aunque Mardkdown (`.md`) admita `HTML` inline, dispone de [su propio mecanismo para tablas](https://help.github.com/articles/organizing-information-with-tables/) y hasta existen [generadores de tablas markdown](http://www.tablesgenerator.com/markdown_tables).

**Comment by jorgercobo** [comment]
| Item                         | Cantidad | Coste unitario | Coste |
|------------------------------|----------:|----------------:|-------:|
| [Espatula de pintor](https://www.amazon.es/gp/product/B00ITVVOLG/ref=as_li_ss_tl?ie=UTF8&camp=3626&creative=24822&creativeASIN=B00ITVVOLG&linkCode=as2&tag=carballo-21)                     | 1        | ~2,50€         | 2,50€ | 
| [Rollo Cinta Poliamida Kapton](http://www.3despana.com/cinta-poliamida-kapton/57-rollo-cinta-poliamida-kapton-20mm.html) | 1        | 3,49€          | 3,49€ |  
| [Acetona pura 1L](https://www.amazon.es/Acetona-especial-desmaquillado-esmaltado-permanente/dp/B01ND18G6V/)                   | 1        | ~11€         | 11€  |  
|**Total** |- |- |16,99€|

La espatula y la acetona pura se pueden conseguir en alguna ferretería cercana y rondarán los precios de la tabla. Podríamos pedir un presupuesto en El Iman para ajustar precios.
 
Como vamos a tratar con materiales corrosivos, sería necesario añadir material de protección -guantes, gafas y mascarilla- a la lista si no lo tenemos ya.

PD: Gracias por buscarme la info 😄

**Comment by David-Estevez** [comment]
Yo creo que no es necesario llegar a tales extremos. Con votar la petición con los precios aproximados y siempre que lo que finalmente se compre esté cerca de esos valores es suficiente (el precio no va a variar mucho de lo que has puesto en tu comentario).

**Comment by jorgercobo** [comment]
La votación: https://goo.gl/forms/em3CGL0yKztgbYtx2

**Comment by jorgercobo** [comment]
El resultado de la votación fue **favorable**. Se prodece a a la compra de dichos materiales.

**Comment by Siotma** [comment]
Se han comprado ya estos materiales? @jorgercobo

**Comment by jorgercobo** [comment]
Aún no he podido ir a por ello

**Comment by Siotma** [comment]
El Kapton es importante para resolver https://github.com/asrob-uc3m/impresoras-asrob/issues/23

**Comment by jorgercobo** [comment]
La acetona y la espatula ya se han comprado. 

| Item                      | Coste esperado | Coste total|
|--------------------|----------------:|-------:|
| Espatula de pintor | 2,50€         | 2,60€ |  
| Acetona pura 1L    |~11€         | 4,90€  |  
|**Total**  |~13,50 |7,50€|

Como han sobrado 6 euros de lo asignado y como se sugirió en https://github.com/asrob-uc3m/actas/issues/62#issuecomment-292024856 podríamos destinar ese dinero a material de protección -guantes, gafas y mascarilla- si no lo tenemos ya.

Reabro la issue para discutir el tema.

**Comment by David-Estevez** [comment]
Por mi guay! :+1:

**Comment by jgvictores** [comment]
@jorgercobo La votación de https://github.com/asrob-uc3m/estatutos/issues/16 ha determinado que es necesaria la realización de una nueva votación para esto. Como buena noticia, para acelerar nuestra burocracia y gracias a https://github.com/asrob-uc3m/estatutos/issues/15, podéis establecer de plazo de votación un mínimo de 24 h (antes eran 7 días recomendado, que sigue estando bien para cuando se busque una buena relevancia estadística a través de una elevada participación).

**Comment by David-Estevez** [comment]
Tareas pendientes: 
- @jgvictores : pagar lo gastado por @jorgercobo y que fue aprobado dentro de esta misma issue
- @jorgercobo : en caso de querer gastar el sobrante del presupuesto, y como se decidió en https://github.com/asrob-uc3m/estatutos/issues/16 , se ha de abrir una issue nueva con nueva votación

**Comment by jgvictores** [comment]
@jorgercobo Lo podemos hacer la tarde del miércoles 13?

**Comment by jorgercobo** [comment]
De acuerdo 👍

**Comment by David-Estevez** [comment]
Esto se está haciendo / se va a hacer / se hizo ya?

**Comment by jorgercobo** [comment]
Mañana en la reunión

**Comment by David-Estevez** [comment]
Eso lo saben / están de acuerdo ambas partes? (Miércoles 13 por la tarde es ahora)

**Comment by jgvictores** [comment]
Sí, me comentó vía Telegram. :+1:

**Comment by jorgercobo** [comment]
Pago recibido en la reunión de día 14 de Septiembre (referencia al acta pendiente)

**Comment by jgvictores** [comment]
Recibido a Sept 14 2017, página http://asrob.uc3m.es/index.php/Cuentas_ASROB actualizada.
