### ISSUE TITLE
Exposición actividades asociaciones estudiantes Acto clausura 25 aniversario EPS

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#63]
Nos han invitado a participar en este acto que tendrá lugar aquí en el auditorio de la universidad mañana día 21 a las 18h.

Se trata de darnos un poco de visibilidad, llevando nuestros robots allí y haciendo acto de presencia con las camisetas corporativas para que nos hagan fotos a nosotros y a los robots.

Yo estoy disponible para ir, pero molaría si hubiese alguien conmigo para no aburrirme allí solo :sweat_smile:  @jgvictores creo que tiene clase a esa hora, que nos confirme por aquí.

Apuntaos en este hilo si os apetece colaborar, y perdonad por avisar con tan poco márgen, pero nos lo han dicho prácticamente hoy.

**Comment by jgvictores** [comment]
Confirmo que tengo clase a esa hora :sweat:

**Comment by Siotma** [comment]
Yo también estaré en clase a esa hora.

Enviado desde Android

**Comment by David-Estevez** [comment]
Gracias vuestra colaboración @jgvictores @KFRodicio , vuestras ASROB-coins están en camino!! :joy:
