### ISSUE TITLE
Reunión con el RSS de la rama española de estudiantes del IEEE

### ISSUE THREAD

**Issue by KFRodicio** [asrob-uc3m/actas#64]
Buenas.

Se puso en contacto conmigo Josemi, el representante de las ramas de estudiantes de españa. Quiere tener una reunión corta (15 min o así) por Skype o Hangouts para redactar un informe sobre el estado de la rama. Básicamente quiere que le respondamos a una serie de preguntas. Me parece que para esto, lo adecuado sería que estuviera presente la junta directiva, podría ser?

**Comment by David-Estevez** [comment]
Por mi guay. ¿Tiene que ser presencial o nos puede pasar las preguntas para que se las respondamos por escrito?

**Comment by KFRodicio** [comment]
Creo que el prefiere hacerlo presencial

**Comment by David-Estevez** [comment]
¿Mañana después de comer, entonces?

**Comment by jgvictores** [comment]
Ok!

**Comment by David-Estevez** [comment]
Reunión finalizada con éxito. La conclusión más o menos fue que todo era  casta, pero que molaba colaborar para conocer gente y ver mundo.

En la reunión estuvimos @KFRodicio, @jgvictores y

**Comment by jgvictores** [comment]
Aquí anotaciones a modo acta:

## Gente importante en esto de los IEEE Student Branches
- jj (jjyubero) -> student activitiy chair (SAC) -> A él le enviamos el Report
- jose miguel -> section student representative (SSR)
- Por nuestra parte, alguien en la Comisión de Colaboración (@KFRodicio)

## Eventos chulos grandes
- IEEE Day (Octubre) (será sevilla?)
- SWYP (encuentro estudiantes españa,, entrega premis) (granada) (antes CNR) (marzo-abril)
- SYP (cada 2 años, internacional; europa, oriente medio, áfrica) (fue: alemania, regensburg)

## Eventos chulos más eventuales
- Incursiones (son invasiones/excursiones de unos IEEE Student Branch a otros, hay un vídeo donde unos van a ver a los drones de la UPM (?)).
- Competiciones: http://www.ieee.org/membership_services/membership/students/competitions/xtreme/index.html

## Even more
- Iniciativas para ir a conferencias técnicas (concurso o tal, solicitud poder ir 600->gratis; papers y cosas).
- Student paper contest (nivel master/doctorando). Tb la confe http://eurocon2017.org/
- Distinguished lecturer program, IEEE paga invitar viaje y alojamiento de un experto para dar una charla (sabemos que queréis a Rodney Brooks en El Evento (TM)). Se solicita con 5-6 meses antelación. https://www.ieee.org/about/volunteers/tab/distinguished_lecturer_program.html
- Hay grupo de Telegram sin spam y otro con spam. Dentro de los temas que están hablando, está el buscar una alternativa al [trello](https://trello.com/ieeestudentbranches) al que de vez en cuando pedimos acceso.
