### ISSUE TITLE
Juego de Llaves 

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#65]
En el ultimo cambio de candados se creo un juego de llaves que incluye:

- Llave armario principal

- Llave armario secundario

- Llave impresoras 

¿Quien deberia tener este juego de llaves? ¿El presidente @jgvictores ?

**Comment by David-Estevez** [comment]
¿Quién tiene ese juego de llaves actualmente?

**Comment by Rodriwp** [comment]
@Rodriwp tiene las llaves en este momento

**Comment by Rodriwp** [comment]
@David-Estevez en calidad de secretari, podria dar parte de las llaves de los armarios actualmente en uso?

**Comment by David-Estevez** [comment]
No podría dar parte en calidad de secretario porque no se me proporcionó dicha relación tras la issue #15. Se hicieron las copias, pero  no se me comunicó ni cuántas ni a quiénes (y no hay registro electrónico de ello tampoco).

Tampoco tenía constancia de la existencia de el *manojo único* ("Un manojo para gobernarlos a todos. Un manojo para encontrarlos, un manojo para atraerlos a todos y atarlos en las tinieblas" :ring: ) objeto de esta issue, ni de quién era el *gollum* que lo tenía.

**Comment by Rodriwp** [comment]
Esta todo documentado por escrito en el inventario de ASROB

**Comment by jgvictores** [comment]
Por favor, enlace cuando citas a algo.

[Haz click aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links).

:smile:

**Comment by Rodriwp** [comment]
No se donde se encuentra dicho inventario

**Comment by David-Estevez** [comment]
https://www.youtube.com/watch?v=pR1olDL5Vqo

**Comment by David-Estevez** [comment]
Se ruega al poseedor del *manojo único* (:ring:) que proceda a su entrega junto con el dinero restante este jueves a las 11h.

**Comment by Rodriwp** [comment]
Se procede a la entrega a @jgvictores presidente el manojo único (:ring:) ("Un manojo para gobernarlos a todos. Un manojo para encontrarlos, un manojo para atraerlos a todos y atarlos en las tinieblas" :ring: ) el dia 09-03-2017 a las 11:10. 

M.A.G.A

**Comment by jgvictores** [comment]
ACK recibido re: "Se procede a la entrega a @jgvictores presidente el manojo único (:ring:) ("Un manojo para gobernarlos a todos. Un manojo para encontrarlos, un manojo para atraerlos a todos y atarlos en las tinieblas" :ring: ) el dia 09-03-2017 a las 11:10."

![imag1619](https://cloud.githubusercontent.com/assets/4448588/23745797/e2b8d970-04b9-11e7-952e-fa32e6fa6b6c.jpg)

**Comment by Rodriwp** [comment]
ACK

Cierro Issue
