### ISSUE TITLE
Video asociaciones 2017

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#66]
[thanks @JorFru por esta descripción]:

Buenos días compañeros horizontales.
Pese a que no estaba issueado, hoy había una reunión de asociaciones en Getafe. Yo he asistido y os transmito las líneas generales.

Se va a hacer un vídeo de (todas) las asociaciones, y lo va a grabar y montar la asociación Modus que son de comunicación y estudian en Getafe.
El vídeo durará un máximo de 140 segundos para compatibilizar con todas las redes sociales. Se pretende que sea dinámico y divertido, huyendo de la dinámica del típico vídeo institucional, pero también se pretende que pase la criba de Comunicación Institucional y se ponga en la web de la uni.
En el vídeo no se va a explicar una por una todas las asociaciones, aunque sí se pretende que todas tengan visibilidad.
Yo he propuesto que nosotros aparezcamos como gente que hace cosas.

Para seguir apuntando ideas, coordinar la grabación y el montaje, se ha creado un grupo de WhatsApp (sí, esa temida app). Quien quiera entrar al grupo para ver o aportar, que me diga (yo estoy dentro: defenderé a la asociación pero no aportaré mucho).

**Comment by JorFru** [comment]
Gracias Juan!
Me has adelantado!

**Comment by David-Estevez** [comment]
Méteme a mi en nombre de Robot Devastation, guardianes del NECRO y sus secretos.

**Comment by David-Estevez** [comment]
Estuve el pasado lunes en la siguiente reunión, y se hablaron ideas de cómo sería el argumento. Se creó el grupo de Whatsapp, en el que estamos @JorFru y yo, y se quedó en hacer otra reunión para trabajar en el guión del corto.

**Comment by David-Estevez** [comment]
No hemos vuelto a tener noticias de los que estaban haciendo el vídeo, así que cerramos esto por inactividad.
