### ISSUE TITLE
El router se puede conectar cerca de las reuniones

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#67]
El router ya se puede conectar en la esquina de la nave más cercana a las reuniones, específicamente el conector etiquetado como 11-25l.

**Comment by Siotma** [comment]
Propongo que se documente este hecho con una pegatina explicativa sobre el router.

**Comment by jgvictores** [comment]
Gracias, donador anónimo de pegatina explicativa!

![photo_2017-03-15_17-28-32](https://cloud.githubusercontent.com/assets/4448588/23959313/22c92f0c-09a5-11e7-9fa9-67807fb02a69.jpg)

**Comment by Siotma** [comment]
Se me olvidó comentarlo, lo puse yo jajjaj
