### ISSUE TITLE
 Página Principal de la Wiki: Añadir Printer One: A Clone Wars Story

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#68]
Se ha recibido una solicitud de **Printer One: A Clone Wars story** de convertirse en Grupo Activo de ASROB. Dado que cumplen las condiciones requeridas en los [estatutos](https://asrob-uc3m.gitbooks.io/estatutos/content/chapter1.html), se ha procedido a la creación de una [página para el grupo](http://asrob.uc3m.es/index.php/Printer_One:_A_Clone_Wars_Story) en la wiki.

Quedamos pendientes de que **Printer One: A Clone Wars story** rellene su página de la wiki para enlazarla desde la página principal.

**Comment by Siotma** [comment]
Hemos estado comentando a este respecto en la reunión de hoy y valoraremos también la posibilidad de publicar nuestra wiki en github, que, por lo que dicen, resulta que es más amigable.

**Comment by David-Estevez** [comment]
Aunque finalmente decidáis documentar todo en una wiki de GitHub, es conveniente que haya algo puesto en la wiki, aunque sea un enlace a la otra wiki.

La wiki de ASROB actúa como nuestra web, y es donde suele buscarnos la gente, así que mola que estéis ahí aunque la chicha esté en GitHub.

**Comment by Siotma** [comment]
Correcto, tendremos, al menos, un enlace en la wiki de ASROB.

**Comment by jorgercobo** [comment]
Hecho
