### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#7]
En la reunión del 24/02/2016 se propuso la creación de una single-page web que sirviese como portada para la wiki de la asociación.

**Comment by Rodriwp** [comment]
En single page abria que añadir el proyecto city of robots, ya que es un rama activa de la asocación.

Aunque se reuna a la vez que robot devastation, convendria mantenerlo como dos ramas separadas, ya que el nivel para participa en ambas es radicalmente distinto

**Comment by David-Estevez** [comment]
Desde ayer mismo está funcionando el nuevo sistema para dar de alta a grupos de trabajo activos: http://goo.gl/forms/movrqVPe6k a través de google forms.

Rellenad los datos del formulario y os añadiremos a wiki & webpage lo antes posible.

**Comment by David-Estevez** [comment]
Doy por terminada la plantilla básica, faltaría por añadir el texto definitivo de cada grupo: [issue 2](https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/2)

Podéis cambiarlo vosotros mismos desde el repo (fork & pull request para no romper nada, por favor) o mandarme los textos y fotos y yo me encargo de añadirlos a la página principal.

cc:
 * **Rd**: @jgvictores
 * **MYOD**: @KFRodicio @JavierIH @RobertoHE
 * **UAVs**: @Rodriwp

**Comment by Siotma** [comment]
El botón de contacto por e-mail tiene asociada la dirección de correo de uc3music.

Esto está en el pie del website, en la sección de contacto, donde aparecen los botones de twitter, g+ etc...

**Comment by David-Estevez** [comment]
MYOD (@KFRodicio @JavierIH @RobertoHE @Siotma), si a día 24 de Abril no se ha recibido el texto e icono que queréis poner (o si no habéis puesto vosotros el que queráis), se ejecutará el siguiente script:

```python
from random import choice
print "Opcion elegida:"
print choice(["Borrar apartado MYOD en web", "Dejarlo como está"])
```

Y lo que salga, salió

**Comment by Rodriwp** [comment]
La rama ya tiene la wiki actualizada y aqui envio el texto para la pagina principal.

City of Robots es la rama activa donde se inician los más novatos  en la robótica, con una introducción a las bases de la programación en Arduino, asi como el diseño de pequeños proyectos para mejorar la [City|enlace The city en la wiki]. Nos reunimos todos los miércoles en dos sesiones de 11:00 a 13:00 y de 15:00 a 17:00 en la nave 1.0.B06. Se ruega que cada participante traiga su portátil o equipo, pero el acceso es libre. Para ponerte en contacto con nosotros manda un correo a asrobuc3m@gmail.com con el asunto “Info City of Robots”

Añadiremos una imagen icono de la rama basa en la imagen en grande que hay en la pagina principal

**Comment by Rodriwp** [comment]
Para seguir con el estilo de le resto de ramas 

¿Quieres iniciarte a la robotica?

City of Robots 

Aprende robotica basada en arduino

**Comment by asrobuc3m** [comment]
Cerrado por inactividad (> 1 mes).

**Comment by David-Estevez** [comment]
Reabro la issue porque creo que habría que terminar la web dado que la mayor parte del curro está ya hecho. 

Buscaré tiempo para echarle un ojo y ver qué cosas faltan por hacer / actualizar / arreglar.

**Comment by jgvictores** [comment]
Lo principal (aparte de info grupos) era el tema de los iconos que se deformaban en la versión móvil.

**Comment by jgvictores** [comment]
De momento, asrob.uc3m.es apunta a una wiki mediawiki. Alternativas:
- Seguir con mediawiki
- Mejorar y utilizar la singlepage propuesta en esta issue, actualmente alojada en http://asrob-uc3m.github.io/
- ¿Qué opináis de http://www.mdwiki.net/ ?

**Comment by David-Estevez** [comment]
Como ya presenté por el grupo de Telegram, yo propongo como web esto: http://asrob-uc3m.github.io/

Las cuestiones pendientes serían:

* ¿Falta algo en la web propuesta? ¿Echáis algo de menos?
* ¿Seguiríamos con la wiki en paralelo para documentar cosas más extensas?
* ¿Redireccionamos asrob.uc3m.es para que lleve a la web propuesta?

**Comment by David-Estevez** [comment]
Muchas de las cuestiones que pregunté en el anterior comentario quedaron resueltas en la reunión del 14/09/17. 

Por tanto doy por cerrada esta issue. Todas las mejoras / bugs que encontréis en la web, se notificarán via issue en [su correspodiente repositorio](https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues)
