### ISSUE TITLE
Página Principal de la Wiki: Añadir Group for Arcade Machine Experimentation (G.A.M.E)

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#70]
Se ha recibido una solicitud de **Group for Arcade Machine Experimentation (G.A.M.E)** de convertirse en Grupo Activo de ASROB. Dado que cumplen las condiciones requeridas en los [estatutos](https://asrob-uc3m.gitbooks.io/estatutos/content/chapter1.html), se ha procedido a la creación de una [página para el grupo](asrob.uc3m.es/index.php/GAME) en la wiki.

Quedamos pendientes de que **Group for Arcade Machine Experimentation (G.A.M.E)** rellene su página de la wiki para enlazarla desde la página principal.

**Comment by jorgercobo** [comment]
Hecho
