### ISSUE TITLE
Solicitud de espacio en el armario

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/actas#71]
El grupo de trabajo de Printer One necesitamos espacio en el armario de la nave.

Solicito redistribución de espacios para poder tener nuestro material ordenado, ya que actualmente contamos con dos cajas pero no con espacio en las baldas.

**Comment by David-Estevez** [comment]
Ciertamente estáis haciendo un gran trabajo y os merecéis tener vuestro propio espacio dentro del armario ASROB. Dada la gran afluencia de gente que tenéis en vuestra rama, y ya que hay mucho espacio vacío disponible en el armario (la 4ª balda tiene vacía el 70% del espacio), propongo que se os asigne el 50% de esa balda.

Como esta propuesta ha recibido mucho feedback favorable hoy en persona, adjunto directamente la votación para aprobar vuestra solicitud para que podáis disponer de este espacio cuanto antes. Como ya sabéis, el plazo para votar es de 7 días, hasta el próximo día 12/04/2017.

Votación: https://goo.gl/forms/R5Tei7z8VbBzXSxJ2

**Comment by David-Estevez** [comment]
Votación aprobada con 9 votos a favor y 0 en contra. 

@Siotma  Se os asigna la mitad de la 4ª  balda, que actualmente está vacía. Podéis proceder a usar el espacio asignado cuando queráis.
