### ISSUE TITLE
Semana de Asociaciones 2017: Participación de ASROB

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#72]
Resumen del correo de África:

* Este año la Semana de Asociaciones será la semana del 2 al 6 de octubre.
* Lunes-Jueves actividades, Jueves y/o Viernes Feria de Asociaciones
* Hay que proponer actividades para la Semana de Asociaciones, de 1.5 o 3 h de duración. 

**Fecha límite para la entrega de propuestas: 16 de Mayo**

Una muestra de las que propusimos el año pasado [aquí](https://github.com/asrob-uc3m/actas/issues/18) y [aquí](https://github.com/asrob-uc3m/actas/issues/19).

**Comment by Siotma** [comment]
Según lo que hablamos en el grupo horizontal, @KFRodicio y yo estaríamos dispuestos a dar un taller de Arduino.

Se podrían plantear dos ediciones del mismo, en diferentes horarios (uno mañana y otro tarde, por ejemplo), para que pueda venir más gente.

Mi idea es utilizar los protobots que hicimos para El Evento, ya que tenemos los servos trucados, las protoboard, las arduino y otros componentes y cables.

En 90 minutos no da tiempo a casi nada, así que yo los propondría de 3 horas y así vamos relajados y la gente tiene tiempo de divertirse.

El espacio ideal sería un aula con mesas móviles y con muchos enchufes. Creo que lo mejor es pedir a la gente que traiga sus propios equipos, aunque sé que alguna vez se han usado aulas informáticas. Si alguien tiene experiencia con esto que lo aporte.

¿Qué ficha habría que rellenar?

**Comment by David-Estevez** [comment]
El correo de África tenía el formulario a rellenar, lo he descargado y subido al drive de ASROB. Está en `papeleo/Semana de asociaciones/2017`. Sería hacer una copia de la plantilla y rellenarlo. Una vez todos estén rellenos se mandan a África por correo y listo.

A mi no me importa rellenarlos todos, pero si lo preferís podéis rellenar vosotros los de vuestros talleres y así no os ando preguntando por los detalles.

Id avisando por aquí cuando estén listos para enviarlos todos. Y recordad que sólo queda esta semana para entregarlos.

**Comment by David-Estevez** [comment]
Formularios enviados. 

Muchas gracias a @Siotma por rellenar el suyo :smile: :+1:
