### ISSUE TITLE
Página principal de la Wiki: añadir taller de Zowimanoides

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/actas#73]
Creo que el taller de Zowimanoides debería aparecer en la página principal de la Wiki... en qué parte creéis que es más procedente?

Creo que podría ponerse en el lugar que ahora mismo ocupa "El Evento", ya que creo que es un buen lugar para publicitar las actividades que se realicen en cada momento.. Y trasladar "El Evento 2016" a una sección menos privilegiada que aglutine las actividades pasadas.

**Comment by David-Estevez** [comment]
Como corre prisa darle publicidad, y de momento no ha habido objeciones al respecto en el grupo de Telegram, he actualizado la wiki para incluir el taller: 

![image](https://cloud.githubusercontent.com/assets/1451819/25253012/72b4ce4a-261f-11e7-8c2e-0ffae9f6c5ec.png)

¿Valdría con eso, o queremos algo más llamativo? ¿Con foto de los zowimanoides quizá?

**Comment by Siotma** [comment]
Me parece muy bien la posición y el color para resaltar. 

He cambiado el texto a "Participa en la " próxima actividad, para que sea más llamativo.

Respecto a la foto... si se pone, debería ser una foto pequeña y que resalte. Mañana busco algo.

**Comment by David-Estevez** [comment]
Esto ya está terminado y en marcha, cierro la issue.
