### ISSUE TITLE
Página principal de la Wiki: Actualizar Info para los nuevos

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/actas#74]
Esta parte de la [wiki](http://asrob.uc3m.es/index.php/Info_para_los_nuevos) ha quedado desactualizada, estan pendientes de añadir/actualizar su resumen los grupos Printer One: A Clone Wars Story, G.A.M.E (Group for Arcade Machine Experimentation) y Hacklab. Asigno a los responsables de cada grupo activo.

Tambien hay información desactualizada: *"No obstante estamos organizando un evento a finales de Octubre en el que daremos talleres explicando todo lo que necesitaréis saber para participar en cualquiera de las asociaciones de "cacharreo " de la uni."*

Como recomendación, esta pagina debería ser más sencilla o ser sustituida por https://asrob-uc3m.github.io/

**Comment by David-Estevez** [comment]
> Tambien hay información desactualizada: "No obstante estamos organizando un evento a finales de Octubre en el que daremos talleres explicando todo lo que necesitaréis saber para participar en cualquiera de las asociaciones de "cacharreo " de la uni."

Esa parte es cierta :rofl: 

Estamos trabajando en El Evento 2017 :smile:

**Comment by Siotma** [comment]
He estado trabajando en la página.

Primero le he dado un lavado de cara en cuanto a lo formal, he sustituido expresiones como:

- "Nuestra asociación" por "La asociación" o "ASROB"
- "Impartir" o "dar clase" por "explicar
- Primera persona del plural por impersonal.
- Segunda personal del plural por tercera persona del singular.
- Primera persona del singular por segunda persona del singular

Segundo, he añadido Printer One

**Comment by David-Estevez** [comment]
Gracias, @Siotma !

Las modificaciones están muy bien. El texto original era menos formal porque estaba pensado para ser más cercano al lector y fomentar su captación, pero igual era demasiado informal.

**Comment by David-Estevez** [comment]
Lo de GAME ya está editado (perdón por el retraso).

@Rodriwp podrías actualizar la información de Hacklab. Me consta que la actual no está al día.

**Comment by jgvictores** [comment]
@Rodriwp ¿Tienes alguna intención de actualizar la info de Hacklab antes del 10 de mayo 2017?

**Comment by Rodriwp** [comment]
He estado desconectado este ultimo mes, pero ya vuelvo a estar disponible y operativo.

Me he puesto a actualizar la información, pero no he sido capaz de loggearme en mi cuenta, tampoco me deja recuperar la contraseña. Algun idea de que puedo hacer @jgvictores

**Comment by jgvictores** [comment]
@Rodriwp Para que puedas crear una contraseña nueva, acabo de asociar tu usuario con el email de alumnos que va por nombre.

**Comment by Rodriwp** [comment]
HackLab ya tiene la información actualizada.

**Comment by David-Estevez** [comment]
Acabo de mirarlo y la información de HackLab no está actualizada. 

Por favor, actualizadla con información *actual y verídica*.

**Comment by Rodriwp** [comment]
Considero que la información de Hacklab,  esta actualizada y es verídica.

**Comment by jgvictores** [comment]
Ahora mismo en [portada](http://asrob.uc3m.es) y en [Info para los nuevos](http://asrob.uc3m.es/index.php/Info_para_los_nuevos) están exclusivamente los grupos que se están reuniendo asiduamente.

El día que otro grupo se empiece a reunir asiduamente (de forma presencial no remota, mínimo una vez por semana), que se vuelva a actualizar.

Por favor, no le demos más vueltas.
