### ISSUE TITLE
Comprar cargador de baterías

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/actas#75]
Creo que un cargador de baterías es algo básico y necesario para la asociación. Además no es caro, por lo que propongo romper la hucha y comprar uno.

Creo que algo como esto (http://www.ebay.es/itm/iMAX-B6AC-Professional-Intelligent-Balance-Charger-Discharger-US-Plug-ES-/222415645035) sería perfecto, ya que es compatible con todos los tipos de batería.

Votación hasta 29/04/2017: https://goo.gl/forms/AllUdqJh6d7tFz9g2

**Comment by Dani191995** [comment]
Buenas!! Creo que podríamos conseguir algo mejor por 30 y pico euros, depende de si queréis cargar descargar tener mas control entonces si el imax, pero si es solo para cargar podríamos pillar 3 cargadores de hobby que valen 10 euros cada uno un poco menos y una fuente de 12v 10A y montar un pseudo triple cargador yo le tengo para mis baterias saldría por unos 45 euros o un poco mas pero se podrían cargar 3 a la vez.

**Comment by Dani191995** [comment]
https://hobbyking.com/en_us/hobbykingr-dc-4s-balance-charger-cell-checker-30w-2s-4s.html?___store=en_us

Este es el enlace vale 8.26€ es decir unos 24'78 euros mas 15 de la fuente unos 40€

**Comment by Dani191995** [comment]
No puedo editar los mensajes perdón.
También tengo una carcasa para juntar los 3 cargadores impresa en 3D, si queréis puedo pasar fotos el grupo de asrob, como queráis.

**Comment by Siotma** [comment]
Por lo que he visto, los cargadores que propones son solo válidos para LiPo o LiIon. Una de las motivaciones que tengo al proponer la compra del cargador es poder cargar también pilas de NiMH por ejemplo, que las montaremos en los Zowis y son muy comunes en robótica. 

Además, el hecho de cargar una LiPo por el conector de equilibrado limita la velocidad a la que puede ser cargada. El Imax puede cargar a través de los cables de la batería y solamente utiliza el cargador de equilibrado al final, obteniendo una mayor velocidad.

Por último, tal y como yo lo veo, un cargador en la asociación debería ser entendido como una herramienta polivalente de uso general y fácil de usar. Me explico:
- El cargador debe ser útil independientemente del tipo de batería que se quiera cargar. El cargador Imax B6 es compatible con LiPo, LiIon, LiFe, NiMH, NiCd y Pb, lo que lo convierte en una herramienta mucho más versátil. Destacar que es compatible con LiPo y LiIon de 1 a 6 celdas.
- El cargador no debe ser concebido para cubrir necesidades de tipo intensivo como las que tienen los UAVs en los que existe la necesidad de cargar baterías de 3 en 3, en casos de una necesidad tan específica creo que lo más lógico es que el miembro activo que lo necesite lo adquiera por su cuenta.
- El cargador debe cubrir la necesidad de un miembro de cargar una batería cuando éste no disponga de cargador, o cuando por ejemplo se le haya olvidado en casa.
- Además, desconozco si el DC-4S es fácil porque no lo conozco, pero creo que el Imax, a la vez que completo, es muy fácil de usar.

**Comment by Dani191995** [comment]
El que he pasado solo carga lipo de 2-4S, en el caso de que se quiera para NiMH,.... Es mejor el imax.

**Comment by JorFru** [comment]
Si es necesario reducir el coste a un mínimo, se puede comprar la misma versión del cargador pero sin fuente de alimentación incluida. En este caso hay que alimentarlo con corriente continua. Por ejemplo, una fuente de ordenador, usando la salida de 12V.
Se ahorraría entre 5 y 10€.

Si se optase por este distribuidor, la jugada saldría por menos de 20€ [Bangood](https://www.banggood.com/es/Wholesale-IMAX-B6-Digital-RC-Lipo-NiMH-battery-Balance-Charger-p-46220.html?rmmds=search)

Yo tengo un iMAX sin fuente y estoy muy contento con su rendimiento y sus posibilidades.

**Comment by Siotma** [comment]
La votación se ha cerrado con 5 votos a favor y ninguno en contra.

Respecto a la opción de comprarlo sin fuente de alimentación, yo proponía la versión AC porque es más cómoda de usar, pero como dice @JorFru , ambas tienen las mismas funciones

Habría que habilitar una fuente de ordenador o similar.

Qué decís?

**Comment by JorFru** [comment]
Me ofrezco a tunear una de las fuentes disponibles para esta función. Estoy
seguro de que el dinero que se ahorre será bien empleado en otros
juguetitos para ASROB.

**Comment by David-Estevez** [comment]
Yo creo que por la comodidad que se gana frente al dinero ahorrado (5-10€) hace que merezca la pena comprar el modelo completo. 

No obstante, si os decidís a comprar la versión sin fuente, hay varias fuentes de PC actualmente en poder de Robot Devastation que se podrían donar a la causa.

**Comment by jgvictores** [comment]
Yo estoy con @David-Estevez, ya ni siquiera por comodidad sino por seguridad. La carga de baterías no deja de ser una tarea con un grado de peligrosidad, en general un equipo integrado va a ofrecer mayores garantías de robustez. Me gustaría minimizar la posibilidad de arcos eléctricos debido a conectores y partes móviles en un equipo que a la larga tocarán muchas manos.

**Comment by Siotma** [comment]
Yo también apuesto por el modelo con fuente integrada ya que, como dice Juan, muchas manos lo van a usar y es más robusto.

Parece que hemos llegado a una conclusión, por tanto solo falta buscar uno a buen precio y preguntar al tesorero: **¿de dónde va a salir la pasta?**

**Comment by Siotma** [comment]
Tesorero, manifiéstate!

**Comment by David-Estevez** [comment]
@jgvictores

**Comment by jgvictores** [comment]
@Siotma @David-Estevez La votación se realizó y salió favorable. La pasta saldrá de los Fondos Actuales.
1. ¿Cuánto es finalmente, contando con transportes, etc?
1. ¿Quién va a realizar la compra?

**Comment by Siotma** [comment]
Es un cargador muy extendido, lo tienen en todos lados.

He visto precios en dx y banggood desde los 30€, y en Aliexpress está por 23€, todo esto es con envío incluido; pero imagino que para algo tan pesado deberíamos evitar china por las aduanas.

En europa tenemos varios que rondan también los 30€ en eBay.

En españa lo hay en los 38 euros en eBay.

**Comment by David-Estevez** [comment]
Banggood y dx ya se inventan lo imposible para no pasar por aduanas, aunque tardará más en llegar que si lo compramos por eBay.

**Comment by Siotma** [comment]
Ya, eso también es verdad. Yo es que no tengo nada de experiencia por AliExpress, pero el precio es muy competitivo. Si alguien ha comprado antes que nos diga su recomendación, teniendo en cuenta que el paquete pesa 800 gramos.

https://es.aliexpress.com/store/product/80W-IMAX-B6AC-RC-Balance-Battery-Charger-B6-AC-Nimh-Nicd-lithium-Battery-Balance-Charger-Discharger/1952837_32751803832.html

>  tardará más en llegar que si lo compramos por eBay.

En principio no es algo que corra prisa de modo que en ese aspecto no habría problema.

**Comment by David-Estevez** [comment]
A mi nunca me han parado un paquete de aliexpress, por mucho que abultase.

**Comment by Siotma** [comment]
Pues yo lo veo claro. Aliexpress es la mejor baza.

Quién lo compra.

**Comment by David-Estevez** [comment]
Opciones: 
1. Lo compra @Siotma y @jgvictores le paga con dinero ASROB
2. Lo compra directamente @jgvictores con dinero ASROB

**Comment by jgvictores** [comment]
Ok opción 1 por mi parte!

**Comment by Dani191995** [comment]
Buenas al final que cargador vais a comprar porque han ahora mismo los isdt
están muy bien y cargan todo tipo de baterias porque los imax falsos además
d eser muy antiguos no van del todo finos

**Comment by Dani191995** [comment]
Y lo compraría en BG, ali según tengo entendido últimamente no se están
haciendo mucho cargo de las garantías...  y por BG doy fe que no paran
pedido si lo compras por el envió gratis gratis o priority.

**Comment by Siotma** [comment]
Por favor, Daniel, podrías incluir un modelo concreto, o un link?

**Comment by Dani191995** [comment]
A un precio asequible tenemos estos dos cargadores de la marca isdt que
tienen muy buenos comentarios

Por 30€ (en oferta):

iSDT SC-608 150W 8A MINI Smart LCD Cargador del Balance de la Batería
https://banggood.app.link/a2OCsLqkpG

Por 50:

ISDT Q6 Plus 300W 14A MINI Cargador del Equilibrio de Batería del Bolsillo
https://banggood.app.link/qycMeHskpG

**Comment by Siotma** [comment]
A los cargadores que propones les veo una pega fundamental: ambos vienen sin fuente de alimentación, por lo que sería un gasto adicional. Además tampoco traen cables para distintos tipos de conectores. Creo que es un modelo muy chulo para utilizarlo de forma portátil, sobre todo porque se puede alimentar con una batería para cargar otra.. pero sigo pensando que no es algo así lo que necesitamos en la asociación.

Hoy, he comprado el B6AC de AliExpress. Que es el modelo que se votó y salió que sí. Se estiman entre 2 y 3 semanas de envío. Una vez me llegue haré la entrega a la Asociación aportando factura, a cambio de su importe.

**Comment by JorFru** [comment]
Gracias por moverlo Manu

El B6AC es un buen cargador para un uso esporádico, y fácil de utilizar.

**Comment by Siotma** [comment]
Ayer llegó el cargador a mi casa, aunque no he podido abrirlo hasta hoy. Tiene muy buena pinta, adjunto imágenes:
![asrob_b6ac_charger_in_the_box](https://user-images.githubusercontent.com/6171234/31759745-b1ada8d4-b4b2-11e7-9c97-4b3b5a6c203d.jpg)

![asrob_b6ac_box_contents](https://user-images.githubusercontent.com/6171234/31759760-b9a0726a-b4b2-11e7-95ef-c08f9242eafb.jpg)

Viene con un manual de instrucciones muy bien detallado en inglés. Lo he encontrado también online. Este es el [enlace al manual](https://www.pololu.com/file/download/iMAXB6ACmanual.pdf?file_id=0J525). También dejo [el archivo](https://github.com/asrob-uc3m/actas/files/1397540/iMAXB6ACmanual.pdf) por si el enlace se rompiera.

Voy a hacer algunas pruebas con baterías que tengo en casa, y mañana lo llevaré a la nave para las reuniones de RoboFactory y Robot Devastation.

**Comment by Siotma** [comment]
**IMPORTANTE**: AliExpress me da 9 días para abrir una disputa antes de dar el pedido por satisfactorio. Animo a todos los miembros de ASROB a que a partir de mañana prueben a cargar las baterías de los robots de su Grupo de Trabajo Activo.

En caso de detectar alguna deficiencia en el funcionamiento del cargador, deberá ser comunicada por aquí explicando el problema y adjuntando pruebas (tales como fotos o vídeos) de que el cargador efectivamente está defectuoso.

**Comment by Siotma** [comment]
El cargador de baterías se encuentra desde las 16:00 horas de hoy en el armario de la nave.

Dado que el plazo de AliExpress finaliza el domingo día 29, únicamente se dispone de la próxima semana para comprobar el buen funcionamiento del cargador. Animo por tanto a todos los grupos de trabajo activos que utilicen baterías a realizar pruebas de carga de baterías durante sus próximas reuniones.

**Comment by jgvictores** [comment]
Durante la reunión de [Robot Devastation](https://github.com/asrob-uc3m/robotDevastation) de ayer, se utilizó el cargador de baterías para cargar la siguiente batería de 20C 7.4V 1000mAh (la menos hinchada):
![photo_2017-10-21_02-48-50](https://user-images.githubusercontent.com/4448588/31850638-920cb7c8-b60a-11e7-8125-9982d1697350.jpg)

La configuración se hizo en base a las instrucciones del manual que está en el sobre pegado a la caja en la parte interna superior, tomando algunas hipótesis.
- `LiPo FAST CHG`: No se aprecia en la foto, pero la batería pone LiPo, y queríamos carga rápida.
- `2.0A`: Da la impresión que el valor de corriente no es relevante para LiPo (dice que la corriente cambia dinámicamente para LiPo; y hay tablas en el manual para otros tipos de baterías), por lo que se utilizó este valor porque venía en los pantallazos del manual referidos a la `LiPo FAST CHG`.
- `7.4V(2S)`: La batería pone 7.4V. El conector de la batería se corresponde con el conector del cargador que pone 2S (o parecido). Hay unos valores nominales de tensiones/celdas en el manual (el manual especifica que el cargador sólo sirve para estos valores nominales de tensiones/celdas), uno de ellos es 3.7V/celda. Suponiendo que 2S significa 2 celdas, (2celda)*(3.7V/celda)=7.4V, con lo cual todo pareció encajar.

Aquí foto de esta configuración (creo que era `enter` durante 3 segundos para confirmar arranque carga, viene en el manual):
![photo_2017-10-21_02-48-47](https://user-images.githubusercontent.com/4448588/31850728-3d619eda-b60c-11e7-8564-8a37583dcc48.jpg)

Tras 33 min, la pantalla del cargador pasó a poner `FULL 0.0A 08.40V FST 033:08 00866`, aquí foto:
![photo_2017-10-21_02-48-45](https://user-images.githubusercontent.com/4448588/31850762-1b237ed2-b60d-11e7-9657-4f1b56385166.jpg)

Por último, también se comprobaron los 8.4V de tensión entre bornes gruesos de la batería, mediante polímetro.

**Comment by JorFru** [comment]
Buenos días

La corriente de carga se pued cambiar siempre, incluso en el modo Fast
Charge.


Las LiPos se cargan a corriente constante hasta que una de las celdas llega
a 4.2V. en ese momento, el cargador se pone en modo voltaje constante, y la
corriente de carga va bajando progresivamente hasta que las celdas se ponen
exactamente a 4.2V y la batería estaría cargada.
Aclaración, cuando se están cargando a corriente constante, aunque estés
midiendo 4.2V, a razón de la caída de tensión en la resistencia interna de
la batería, en realidad la lipo no está a 4.2V, ni totalmente cargada. Por
eso se cambia a modo voltaje constante y al disminuirse poco a poco (según
se carga la batería) la diferencia de voltaje disminuye y por la ley de Ohm
la corriente también disminuye hasta que se hace cero. En este momento
tenemos la batería cargada.

La diferencia entre los modos, Normal, Fast Charge y el modo Balance son.

Fast charge: solo hace el ciclo de carga a corriente constante: no carga al
100% la batería, aproximadamente a un 97%. No carga la batería de manera
balanceada.

Normal (sin balanceo): igual que el anterior pero sí aplica el segundo modo
de carga para llegar al 100%. No balancea la batería. Este proceso supone 5
minutos más que el anterior.

Modo balance: Hace una carga completa y, además, balancea la batería. Esto
es: pone todas las celdas a 4.2 cargado completo. Los dos modos anteriores
dan por concluida la carga cuando cualquiera de las celdas llega a 4.2V.
este proceso supone 5 minutos extra a parte cargado normal.


El único modo que yo considero compatible es el modo balance. Los otros dos
no.
Se pueden usar pero no más de dos veces seguidas. Ya que ninguna batería
tiene todas las celdas idénticas. Y si se abusa de esos modos, una celda
podrá con las otras a la larga.



Corriente de carga.
Para la parte principal de la carga, que consume el 90% del tiempo, es a
corriente constante. Está corriente se debe de ajustar según el siguiente
criterio:

1C: baterías LiPo normales
1-3C: baterías LiPo de alto rendimiento

C: número resultante de la siguiente operación: (corriente a través de la
batería)/(capacidad de la batería en Ah[amperios hora]).
Ejemplo: tú batería es de 1000mAh, cargada a 1A, significa que estás
cargándola a una tasa de 1C.
Misma batería a 2A, tasa de 2C.
Batería de 8000mAh, cargada a 4A, tasa de 0.5C.

La tasa típica de carga de las LiPos es 1C. Si la excedes estás recortando
la vida últil de la batería, si la disminuyes la batería se cargará más
feliz. Y si la batería es malucha o está en mal estado, estás incrementando
las posibilidades de incendiar la batería.





Esto es lo básico de lo básico en la carga de LiPos. Fuera de estos baremos
puede haber problemas, y creo que todos sabemos que este tipo de baterías
son propensas a incendios y explosiones, sólo hay que buscar en YouTube.

No he mencionado nada sobre que el conteo de celdas tiene que coincidir. Lo
consideraba demasiado obvio pero lo apunto, ya que es con diferencia lo más
peligroso que se puede hacer con un cargador.


Quedo disponible para cualquier duda sobre la carga de LiPos. Si no estoy
disponible, consultar a cualquier miembro de ASROB-UAVs.
Añado foto de mi arsenal de baterías, para que comprobéis mi experiencia. Y
faltan las 2S, las 3S, los Frankenstein y todas las que murieron en combate.


On Oct 21, 2017 12:09, "Juan G. Victores" <notifications@github.com> wrote:

Durante la reunión de Robot Devastation
<https://github.com/asrob-uc3m/robotDevastation> de ayer, se utilizó el
cargador de baterías para cargar la siguiente batería de 20C 7.4V 1000mAh
(la menos hinchada):
[image: photo_2017-10-21_02-48-50]
<https://user-images.githubusercontent.com/4448588/31850638-920cb7c8-b60a-11e7-8125-9982d1697350.jpg>

La configuración se hizo en base a las instrucciones del manual que está en
el sobre pegado a la caja en la parte interna superior, tomando algunas
hipótesis.

   - LiPo FAST CHG: No se aprecia en la foto, pero la batería pone LiPo, y
   queríamos carga rápida.
   - 2.0A: Da la impresión que el valor de corriente no es relevante para
   LiPo (dice que la corriente cambia dinámicamente para LiPo; y hay tablas en
   el manual para otros tipos de baterías), por lo que se utilizó este valor
   porque venía en los pantallazos del manual referidos a la LiPo FAST CHG.
   - 7.4V(2S): La batería pone 7.4V. El conector de la batería se
   corresponde con el conector del cargador que pone 2S (o parecido). Hay unos
   valores nominales de tensiones/celdas en el manual (el manual especifica
   que el cargador sólo sirve para estos valores nominales de
   tensiones/celdas), uno de ellos es 3.7V/celda. Suponiendo que 2S significa
   2 celdas, (2celda)*(3.7V/celda)=7.4V, con lo cual todo pareció encajar.

Aquí foto de esta configuración (creo que era enter durante 3 segundos para
confirmar arranque carga, viene en el manual):
[image: photo_2017-10-21_02-48-47]
<https://user-images.githubusercontent.com/4448588/31850728-3d619eda-b60c-11e7-8564-8a37583dcc48.jpg>

Tras 33 min, la pantalla del cargador pasó a poner FULL 0.0A 08.40V FST
033:08 00866, aquí foto:
[image: photo_2017-10-21_02-48-45]
<https://user-images.githubusercontent.com/4448588/31850762-1b237ed2-b60d-11e7-9657-4f1b56385166.jpg>

Por último, también se comprobaron los 8.4V de tensión entre bornes gruesos
de la batería, mediante polímetro.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/actas/issues/75#issuecomment-338380651>, or mute
the thread

**Comment by Siotma** [comment]
Gran explicación @JorFru . Creo que podría ser buena idea realizar un manual explicativo de uso rápido del cargador. Voy a ponerme a ver lo que tardo.

**Comment by Siotma** [comment]
# Guía rápida de uso del cargador IMAX B6AC
Disclaimer: esta guía está concebida como un resumen de uso rápido. Para una documentación completa sobre el cargador se debe consultar siempre el [manual de usuario](https://github.com/asrob-uc3m/actas/files/1397540/iMAXB6ACmanual.pdf).

## 1. Contenido de la caja
Cuando vayas a utilizar el cargador, comprueba la presencia de todos estos elementos:
- Cargador IMAX B6AC
- Cable negro para alimentación AC
- Cable con pinzas para alimentación DC
- Manual de instrucciones, dentro de un sobre pegado en el interior de la tapa
- Cables para la conexión de baterías

Asimismo, **cuando termines de usarlo, asegúrate de que vuelves a dejarlo todo dentro de la caja.**

## 2. Alimentación del cargador
Para poner en funcionamiento el cargador se pueden utilizar dos tipos de alimentación:
- Toma de corriente de 220V AC (corriente alterna) utilizando el cable negro (recomendada).
- Fuente de alimentación o batería de 11 a 18V DC (corriente continua) utilizando el cable con pinzas.

Una vez conectado, si la alimentación es correcta, el cargador emitirá un breve pitido y la pantalla se encenderá mostrando la última configuración utilizada. 

## 3. Conocer la batería que se quiere cargar
El cargador IMAX B6AC puede cargar los siguientes tipos de baterías:
- LiPo (tensión nominal 3,7V) hasta 6 celdas
- LiIon (tensión nominal 3,6V) hasta 6 celdas
- LiFe (tensión nominal 3,3V) hasta 6 celdas
- NiMH hasta 15 celdas
- NiCd hasta 15 celdas
- Pb hasta 20 V
**Precaución**: no recargar baterías dañadas o pilas no recargables, bajo riesgo de incendio.

Para conocer el tipo de batería que vas a cargar, debes observar su etiquetado. A continuación se exponen los casos de uso más comunes.

## 4. Carga de baterías LiPo
### a. Reconocimiento de características
Es preciso conocer las siguientes características, que se encuentran habitualmente en la etiqueta de la batería:
- Debe poner claramente que es una batería de tipo LiPo. 
- La capacidad, dada en miliamperios hora (mAh).
- La capacidad de descarga, dada en C.
- El número de celdas o la tensión nominal de la batería. Teniendo en cuenta que las celdas de LiPo tienen una tensión nominal de 3,7V, el número de celdas será el resultado de la siguiente cuenta: `número de celdas = tensión nominal de la batería / 3,7V`. El número de celdas también coincide con la siguiente cuenta: `número de celdas = número de cables del conector de equilibrado - 1`.

En la siguiente figura se muestra un ejemplo de dos baterías LiPo donde:
- El tipo de batería está señalado en amarillo.
- La capacidad está señalada en azul.
- La capacidad de descarga está señalada en naranja.
- El número de celdas, la tensión de la batería y los conectores de equilibrado están señalados en verde.

![lipo example](https://user-images.githubusercontent.com/6171234/31884020-1240a6a6-b7ec-11e7-91f2-f21bcd684afa.jpg)

### b. Conexión de la batería
Se deben conectar los bornes de la batería a los bornes marcados como OUTPUT en el cargador. Si la batería dispone de conector de equilibrado, se recomienda su conexión en el conector contiguo correspondiente. La conexión debe quedar tal y como muestra la siguiente figura:

![lipo connection](https://user-images.githubusercontent.com/6171234/31885067-8e0930c0-b7ef-11e7-8d2b-3e8946e7f6a1.PNG)

### c. Configuración del cargador
Al encenderse, el cargador mostrará la última configuración utilizada. 
1. Pulsar repetidamente el botón Stop hasta que aparezca esta pantalla:
![program select lipo batt](https://user-images.githubusercontent.com/6171234/31885092-a046e156-b7ef-11e7-89ee-b229a7e823eb.PNG)

2. Pulsar el botón Enter, se mostrarán las opciones de carga o descarga:
![lipo options](https://user-images.githubusercontent.com/6171234/31885133-c4e54282-b7ef-11e7-8169-627c724361f8.PNG)

3. Pulsar los botones izquierda o derecha para navegar entre las opciones:
- CHARGE: Carga completa, sin utilizar el conector de equilibrado.
- BALANCE: Carga completa y equilibrada, requiere conectar el conector de equilibrado.
- FAST CHG: Carga rápida, incompleta, sin utilizar el conector de equilibrado.
- STORAGE: Carga o descarga equilibrada hasta la tensión óptima de almacenamiento. Útil si se va a tener la batería mucho tiempo sin utilizar.
- DISCHARGE: Descarga completa de la batería.
**Atención**: Se recomienda utillizar únicamente las opciones BALANCE y STORAGE, por ser las más respetuosas con la batería. Las otras opciones pueden comprometer su vida útil y su seguridad. En esta guía se describe el proceso de carga mediante la opción BALANCE. Para otras opciones consultar el [manual de usuario](https://github.com/asrob-uc3m/actas/files/1397540/iMAXB6ACmanual.pdf).

4. Una vez se encuentre en la pantalla la opción BALANCE, pulsar Enter. Parpadeará la corriente.
5. Ajustar la corriente con los botones izquierda o derecha. Esta corriente será la máxima utilizada durante el proceso de carga; a mayor corriente, mayor velocidad.
**Precaución**: Para la carga, se recomienda utilizar como máximo un valor de corriente correspondiente a 1C. Un valor de 1C es un valor en corriente igual a la capacidad de la batería. Por ejemplo, para una batería de 2200mAh, un valor de 1C es una corriente de 2,2A. Si no se tiene mucha prisa, se recomienda utilizar valores alrededor de 0,5C.

6. Una vez seleccionada la corriente deseada, pulsar Enter. Parpadeará la tensión.
7. Ajustar la tensión con los botones izquierda o derecha. Esta debe ser la tensión nominal de la batería.
8. Mantener pulsado Enter durante 3 segundos. El cargador comprobará la batería conectada.
9. Se mostrará en pantalla una comparación entre la batería detectada y la batería indicada por el usuario. Si son distintas, pulsar Stop para comprobar la configuración, si son idénticas pulsar Enter y la carga comenzará.

### d. Proceso de carga
Durante el proceso de carga es importante mantener la atención sobre el cargador y la batería, siendo importante controlar periódicamente la temperatura de la misma. Se pueden realizar las siguientes operaciones:
1. Durante la primera parte de la carga, se puede modificar la corriente de carga. Presionando Enter la corriente parpadeará y se podrá modificar con los botones izquierda o derecha. Tras la selección se puede volver a fijar con Enter.
2. Durante la carga, pulsar los botones izquierda o derecha muestra los valores de tensión de cada celda. Esto permite comprobar el estado de la carga y el grado de equilibrio de la batería. Volviendo a pulsar los botones izquierda o derecha se regresa a la pantalla principal de la carga.
3. Si se desea, se puede cancelar la carga en cualquier momento presionando Stop.

**Atención**: Si se produce algún error durante la carga, el cargador emitirá una alarma sonora durante 10 segundos y aparecerá el mensaje de error en la pantalla.

Al finalizar la carga, el cargador emitirá una alarma sonora durante 10 segundos, y aparecerá la palabra FULL en la pantalla.

## 5. Carga de baterías NiMH
### a. Reconocimiento de características
Es preciso conocer las siguientes características, que se encuentran habitualmente en la etiqueta de la batería:
- Debe poner claramente que es una batería de tipo NiMH
- La capacidad, dada en miliamperios hora (mAh).

En la siguiente figura se muestra un ejemplo de baterías NiMH donde:
- El tipo de batería está señalado en amarillo.
- La capacidad está señalada en azul.

![nimh example](https://user-images.githubusercontent.com/6171234/31884292-e78d91ac-b7ec-11e7-83f3-2ea06a6bebdc.png)

### b. Conexión de la batería
Se deben conectar los bornes de la batería a los bornes marcados como OUTPUT en el cargador. Para baterías de este tipo, no es compatible el uso de conector de equilibrado.

### c. Configuración del cargador
Al encenderse, el cargador mostrará la última configuración utilizada. 
1. Pulsar repetidamente el botón Stop hasta que aparezca esta pantalla:
![program select nimh batt](https://user-images.githubusercontent.com/6171234/31885761-f517c8ce-b7f1-11e7-8c24-8d07e11401ab.PNG)

2. Pulsar el botón Enter, se mostrarán las opciones de carga o descarga:
![nimh options](https://user-images.githubusercontent.com/6171234/31885770-fa0b8730-b7f1-11e7-9b2f-93c2dbeaad23.PNG)

3. Pulsar los botones izquierda o derecha para navegar entre las opciones:
- CHARGE: Carga completa de la batería.
- DISCHARGE: Descarga completa de la batería.
- CYCLE: Ciclos de carga y descarga.
**Atención**: En esta guía se describe el proceso de carga mediante la opción CHARGE. Para otras opciones consultar el [manual de usuario](https://github.com/asrob-uc3m/actas/files/1397540/iMAXB6ACmanual.pdf).

4. Una vez se encuentre en la pantalla la opción CHARGE, pulsar Enter. Parpadeará el modo.
5. Ajustar el modo con los botones izquierda o derecha. El modo automático (Aut) permte seleccionar la máxima corriente de carga pero deja libertad al cargador para irla variando durante la carga, mientras que el modo manual (Man) utiliza una corriente de carga fija.
6. Una vez seleccionado el modo deseado, pulsar Enter. Parpadeará la corriente.
7. Ajustar la corriente con los botones izquierda o derecha.
**Precaución**: Para la carga, se recomienda utilizar como máximo un valor de corriente correspondiente a 0,5C. Un valor de 1C es un valor en corriente igual a la capacidad de la batería. Por ejemplo, para una batería de 2200mAh, un valor de 1C es una corriente de 2,2A; y un valor de 0,5C es una corriente de 1,1A. Si no se tiene mucha prisa, se recomienda utilizar valores alrededor de 0,25C.
**Atención**: Debido a la técnica que utiliza el cargador para reconocer la carga, no se recomienda utilizar corrientes inferiores a 0,2C, ya que el cargador tendrá problemas para reconocer cuándo la batería está completamente cargada. 
8. Mantener pulsado Enter durante 3 segundos. El cargador comprobará la batería conectada, y en caso afirmativo la carga comenzará.

### d. Proceso de carga
Durante el proceso de carga es importante mantener la atención sobre el cargador y la batería, siendo importante controlar periódicamente la temperatura de la misma. Se pueden realizar las siguientes operaciones:
1. Durante la primera parte de la carga, se puede modificar la corriente de carga. Presionando Enter la corriente parpadeará y se podrá modificar con los botones izquierda o derecha. Tras la selección se puede volver a fijar con Enter.
2. Si se desea, se puede cancelar la carga en cualquier momento presionando Stop.

**Atención**: Si se produce algún error durante la carga, el cargador emitirá una alarma sonora durante 10 segundos y aparecerá el mensaje de error en la pantalla.

Al finalizar la carga, el cargador emitirá una alarma sonora durante 10 segundos, y aparecerá la palabra FULL en la pantalla.

**Comment by Siotma** [comment]
La idea es que la guía anterior se pueda reutilizar y ampliar conforme a las necesidades, y quede como referencia de uso mientras exista el cargador. ¿Dónde creéis que podríamos ponerla?

**Comment by jgvictores** [comment]
>¿Dónde creéis que podríamos ponerla?

https://github.com/asrob-uc3m/tutoriales

**Comment by Siotma** [comment]
Conocía la página de la Wiki, pero no la de GitHub ni GitBook.

Voy a echar un ojo para aprender a usar GitBook y lo migro esta tarde.

**Comment by jgvictores** [comment]
PS: Incluso subiría el PDF del manual a https://github.com/asrob-uc3m/tutoriales/tree/master/assets, pero:
1. Antes quiero probar el mecanismo [git-lfs](https://git-lfs.github.com/).
1. También creo que es conveniente organizar assets en carpetas (ahora mismo el único fichero está en la raiz de assets).
1. Siempre me entran dudas con respecto a propiedad intelectual/industrial de los manuales.

**Comment by jgvictores** [comment]
> Voy a echar un ojo para aprender a usar GitBook y lo migro esta tarde.

Debería servier el la sintaxis tal cual, ya que usaste un markdown con sabor a GitHub, xD. Es crear el fichero con ese contenido, y actualizar manualmente `SUMMARY.md` a tu gusto.

**Comment by Siotma** [comment]
Hecho, se pude leer en https://asrob-uc3m.gitbooks.io/tutoriales/content/battery_charger_es.html

**Comment by Siotma** [comment]
El plazo de protección de AliExpress finalizó ayer. Dado que no se reportaron problemas no abrí ninguna disputa. Ya únicamente quedaría la parte en la que yo recupero el dinero del cargador.

**Comment by David-Estevez** [comment]
Quedaba presupuesto en el taller de zowimanoides?

**Comment by Siotma** [comment]
Sí, queda.

Pase lo que pase en #108 , se podría recuperar el importe del cargador, si no íntegro, casi.

Ya he solicitado la factura por el cargador. Espero recibirla próximamente.

**Comment by Siotma** [comment]
Ya tengo la factura del cargador de baterías.

El jueves la llevaré a la Universidad para cargarla en el taller de Zowimanoides.

**Comment by Siotma** [comment]
Ayer, entregué la factura del Cargador de Baterías en el Registro de la Universidad para que la carguen al Taller de Zowimanoides

**Comment by Siotma** [comment]
Hoy, he recibido el pago de la universidad de 21,48€ ([íntegro](https://github.com/asrob-uc3m/actas/issues/75#issuecomment-334935760)) por el Cargador de Baterías.

Issue cerrada.
