### ISSUE TITLE
Participación de ASROB en Feria de Asociaciones Benéfica

### ISSUE THREAD

**Issue by KFRodicio** [asrob-uc3m/actas#76]
Buenas.

La semana pasada recibimos un email avisando de que se quiere montar una nueva Feria de Asociaciones para recaudar fondos para construir un jardín con parque infantil en el hospital Gregorio Marañón. Creo que el plan es organizar actividades como las de la feria normal, pero donar lo que se les cobre a los participantes (o si la actividad es gratuita, aceptar donaciones). Abro esta issue para ver si nos interesa el tema o pasamos (de todas todas, no vendría mal tener un poco más de información al respecto, porque el email era poco preciso).

**Comment by David-Estevez** [comment]
Poner una recreativa y que la gente juegue a cambio de donativos se puede considerar "actividad"?

PD: el proyecto del que habla el mail es este: https://www.juegaterapia.org/el-jardin-de-mi-hospi/

**Comment by JorFru** [comment]
Mando capturas de lo que he hablado con el organizador.

Resumen: finales de mayo, después de exámenes. Es posible que se haga en
interior, no sé por qué...

**Comment by JorFru** [comment]
![imagen](https://cloud.githubusercontent.com/assets/11017088/25390469/e1772b04-29d3-11e7-94aa-e2e9ea986fa5.png)

**Comment by David-Estevez** [comment]
¿Alguien sabe qué pasó con esto? ¿Sigue en pie la feria esa?

**Comment by David-Estevez** [comment]
Como no se sabe nada de esto, voy a cerrar la issue por inactividad
