### ISSUE TITLE
Comprar cables micro USB

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#77]
Muchas de las placas arduino que tenemos funcionan con Micro USB, no obstante, la mayoría de cables que tenemos en el armario son de otros tipos.

Abro esta issue para consultar si otros grupos activos tienen también esta necesidad de cables micro USB y cuántos harían falta.

**Comment by Siotma** [comment]
Los Zowimanoides llevarán mini-usb, y son 6 robots, aunque no hace falta tener un cable para cada uno, con tener 2 hay de sobra porque solo se necesitan para programarlos, y eso es algo que se hace eventualmente.

De todas formas, de estos mini-usb que digo sí tenemos varios cables en el armario. Como bien dices los que faltarían son micro-usb.

Aquí una imagen ilustrativa para que todos hablemos de los mismo (creo que es necesaria porque yo siempre me lío): 

http://phandroid.s3.amazonaws.com/wp-content/uploads/2009/06/microusb-vs-miniusb.jpg

**Comment by Siotma** [comment]
Ayer hice pruebas con los zowimanoides y se pueden programar por bluetooth, de manera que no serán necesarios cables para ellos.

**Comment by David-Estevez** [comment]
Comprados cables USB con presupuesto de G.A.M.E, los que no se usen (seguro que habrá excedentes) se donarán al material común.
