### ISSUE TITLE
Convocatoria de ayuda a las ramas

### ISSUE THREAD

**Issue by KFRodicio** [asrob-uc3m/actas#79]
Buenas.

Me informan desde el IEEE que sigue abierto el plazo para pedir subvenciones (creo recordar que no dan mucha pasta, pero menos da una piedra). Igual nos interesa pedir algo, por lo pronto se me ocurre para El Evento 2017. Si se os ocurre algo que necesitemos financiar, me lo comentáis por aquí y yo me encargo del papeleo.

**Comment by jgvictores** [comment]
Creo que esto es un duplicado de #23.

**Comment by KFRodicio** [comment]
Cierto, fallo mío. En cualquier caso hay que plantear peticiones
