### ISSUE TITLE
Pagina principal de la wiki: añadir impresoras 3D

### ISSUE THREAD

**Issue by Rodriwp** [asrob-uc3m/actas#8]
Creo que seria conveniente que la información referente a las impresoras 3d, hoja de reservas, lista de operadores y documentación de uso, se puediera acceder desde la pagina principal.
No seria poner la rama tal cual, si no solo la información referente al uso actual de ellas

**Comment by jgvictores** [comment]
Sumaría el incorporar un formulario para incidencias (google forms funciona :smile:).

**Comment by David-Estevez** [comment]
+1

**Comment by David-Estevez** [comment]
@Rodriwp @jgvictores Definamos cuáles serían las preguntas más significativas que habría que incluir en el formulario.

**Comment by David-Estevez** [comment]
Up!

**Comment by jgvictores** [comment]
¿Qué tal...?
- Nombre de impresora
- Qué ocurre
- Subir foto

**Comment by David-Estevez** [comment]
* Qué se estaba imprimiendo
* Cuánto tiempo llevaba imprimiendo
* Hizo algo raro (la impresora) al imprimir 
* Se usó alguna configuración distinta a la por defecto

**Comment by jgvictores** [comment]
Recordemos que la página tiene partes incompletas: [LINK](http://asrob.uc3m.es/index.php/Gesti%C3%B3n_Impresoras)

**Comment by Rodriwp** [comment]
Actualizada la imformación que faltaba. Por ahora el contacto de incidencias se hace atraves de asrobuc3m@gmail.com con el asunto "Gestion de impresoras"

**Comment by jgvictores** [comment]
@Rodriwp Enlace?

**Comment by jgvictores** [comment]
@Rodriwp Ok,  [ENLACE](http://asrob.uc3m.es/index.php/Gesti%C3%B3n_Impresoras) :smiley:

**Comment by David-Estevez** [comment]
Guay, faltaría el formulario/procedimiento a seguir cuando una impresora se escacharre, que debería contar con una copia impresa colocada cerca de las impresoras. Si finalmente se usa un form, un QR con el link al form también quedaría chulo.

**Comment by asrobuc3m** [comment]
El nuevo Responsable de Impresoras (@jorgerc21) debería implementar lo discutido en esta issue.

**Comment by jorgerc21** [comment]
Tomo nota. Añado que podríamos usar el mismo método para las peticiones de impresión, ya que el formulario nos evita tener que actualizar la hoja de calculo y nos proporciona avisos a la lista de correo. He ocultado de manera temporal la hoja de reservas y agradecería que le echarais un vistazo a los cambios que he hecho ya que no controlo el lenguaje que usa la wiki y puedo haber dejado algo mal.

**Comment by David-Estevez** [comment]
En mi opinión, la ventaja de tener una hoja de cálculo es que es más intuitivo, porque de un vistazo ves qué huecos están libres y cuáles no.

Pero se puede abrir un debate sobre el tema. Qué opinas, @jgvictores ?

**Comment by jgvictores** [comment]
Yo estoy con @David-Estevez 

La hoja de cálculo es más intuitivo y fácil de gestionar. Si necesitas notificaciones de cambios en la hoja de cálculos, parece que existen opciones (véase [esto](https://support.google.com/docs/answer/91588?co=GENIE.Platform%3DDesktop&hl=en)), aunque no lo veo necesario. Una tabla de reservas haría falta en todo caso, aunque fuese de uso interno.

**Comment by jorgerc21** [comment]
La hoja de cálculo es un buen sistema si las impresoras tuvieran mucho uso -y ni siquiera, las casillas ocupadas podrían ser modificadas por cualquiera y dar problemas de suplantación-. Por lo que he visto en la que hay ahora mismo, hay una sola petición en la mayoría de hojas y cada vez que alguien hace una hay que crear una página o modificar la actual -cosa que supongo que las personas que no están familiarizadas con el sistema no hacen-. De igual forma si que veo interesante usarlo de manera interna para organizarnos entre nosotros, aunque por lo que he visto cada uno imprime cuando lo necesita y espera si hay alguien usándolas.
Propongo estas soluciones:

- **Mantenemos y mejoramos el sistema de hojas de calculo**: Añadimos notificaciones a la hoja, suprimimos el formato de pagina por semana (confuso), realizamos un mantenimiento mensual de la hoja, imprimimos semanalmente la hoja para que figure en los puestos de impresión, añadimos un sistema de seguridad para evitar modificaciones no autorizadas. _**Ideal para un uso casi continuo de las impresoras.**_


- **Creamos un formulario de petición y las gestionamos internamente**: Añadimos avisos del formulario al correo de la asociación y si la fecha y/o horario indicados no están disponibles sugerimos una alternativa. _**Pensado para un uso medio**_, digamos dos o tres veces por semana. Opcionalmente se podría crear un script que en el propio formulario ofreciese solo horarios no ocupados, como por ejemplo se hace en webs de cita previa en servicios sanitarios. _**También ideal para un uso casi continuo de las impresoras.**_

- **Gestionamos las peticiones mediante correos**: Indicamos en la página un formato para las peticiones y las manejamos desde la lista de correo. _**Para un uso mínimo**_, como creo que es el caso.

Aún con el sistema de hoja de calculo mejorado sigo prefiriendo el formulario, me parece más eficiente en uso/mantenimiento por nuestra parte para el uso actual y es más user-friendly.

**Comment by jgvictores** [comment]
Con el sistema de hojas de cálculo, el responsable tiene al máximo 1 cita semanal, o de una sentada podría crear las aproximadamente 52 hojas del año. Sí conservaría el sistema semanal para conservar un poco de histórico/trazabilidad en caso de avería no notificada.

Siempre hay que pensar en la escalabilidad. 13*7 = 91 franjas horarias por semana / impresora, significa en potencia **182 gestiones manuales de emails por semana** para dos impresoras.

**El único motivo por el que no estamos en el escenario de uso casi continuo de impresoras es porque no lo estamos gestionando bien** Poniendo carteles de impresión 3d gratuitas e implementando una gestión automatizada eficiente, se llena.

Por esto, **ruego encarecidamente que se siga con la tabla semanal, por lo menos hasta que no se desarrolle un script que gestione esto de forma automática**.

**Comment by David-Estevez** [comment]
Yo estoy de acuerdo con @jgvictores me parece que el sistema actual requiere un esfuerzo mínimo frente a un sistema manual mediante formulario.

Otra de las razones de que las impresoras estén infrautilizadas es que suele haber alguna rota (ahora mismo hay una que no funciona, de hecho).

**Comment by jgvictores** [comment]
Sí, con gestión eficiente me refiero a muuuchos factores. 
PD: Un dashboard con el estado de las impresoras no sería demasiado dificil de forma manual (otra hoja de cálculo). Automatizar tests sobre hardware es otra historia. :-)

**Comment by David-Estevez** [comment]
Ahí es cuando volvemos al tema de encontrar una forma de notificar de forma rápida y efectiva que una impresora no va. (ya era hora de volver al tema :joy: )

**Comment by jorgerc21** [comment]
Ok, por ahora dejo la hoja oculta y en cuanto pueda me pongo con todo lo que hemos dicho. 
De todos modos no sabía que queríais publicitar las impresoras, mientras haya operadores disponibles para todas las franjas me parece bien.

**Comment by jgvictores** [comment]
Empiezan a llegar peticiones manuales. @jorgerc21 ¿Puedes rehabilitar la hoja de cálculo y eliminar el mensaje "Actualmente la hoja de reservas no está disponible"?

**Comment by David-Estevez** [comment]
Dado que la gente manda muchos correos a la lista preguntando por las impresoras, deduzco que está pasando al menos una de estas cosas:

 * En la página de la wiki no está suficientemente bien explicado el proceso a seguir para imprimir en las impresoras (Ser operador, reservar, manual de la impresora), por lo que habría que mejorarla.
* La gente pasa de leerse la wiki.

**Comment by jgvictores** [comment]
Metí mejoras a http://asrob.uc3m.es/index.php/Gesti%C3%B3n_Impresoras

No cerramos issue porque aquí todavía hay muchas ideas muy buenas por implementar.

**Comment by jgvictores** [comment]
Cc: https://github.com/asrob-uc3m/impresoras-asrob/issues/7 y https://github.com/asrob-uc3m/impresoras-asrob/issues/8

**Comment by David-Estevez** [comment]
Creo que [printer-status-webpage](https://github.com/asrob-uc3m/printers-status-webpage) resuelve esta issue.
