### ISSUE TITLE
Patrocinios para El Evento 2017

### ISSUE THREAD

**Issue by KFRodicio** [asrob-uc3m/actas#80]
Buenas.
Para pedir patrocinios para el evento, y para la petición de ayuda a ramas del IEEE, necesito lo siguente:
Fechas de El Evento 2017
Coste estimado de cada taller (independientemente de que tengamos parte del material comprado ya) y del Hackaton.

Y ya por último, alguno sabe cuanto cuestan los carteles esos grandes (A0) sería la ostia

**Comment by David-Estevez** [comment]
Fechas:
> Lunes 23 a jueves 26 de octubre de 2017. Que sea el Evento

Coste de cada taller:

* Si hacemos uno de soldadura SMD, serían unos 250€ para 10 personas

Cartel:

* En el callejón nos hicieron un póster en paper fotográfico por 30€, pero no sé si eso es tamaño A0...

**Comment by David-Estevez** [comment]
Visto que El Evento 2017 ha muerto por falta de apoyo institucional, esta issue ha quedado invalidada.
