### ISSUE TITLE
Semana de Asociaciones 2017: Charla ¡Conoce ASROB!

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#83]
Este año tenemos la típica charla anual en la que contamos a la gente lo que hacemos. 

La info de la charla es la siguiente:
> Martes 3 de octubre de 2017
>
> Código 52. Charla: ¡Conoce ASROB!
>
>    15:00 - 16:30h
>    Biblioteca Rey Pastor. Sala de Video 3.1.S08
>
> ASROB es la Asociación de Robótica de la UC3M, y sus miembros activos se organizan en distintas ramas de trabajo activas. Cada rama se encarga de realizar un proyecto distinto. En esta charla presentaremos los principales proyectos de ASROB: G.A.M.E, Printer One, Robot Devastation y UAVs.
>
 >   Organiza: Asociación ASROB

Como vamos a hablar de todas las ramas, estaría bien que hubiese al menos un representante de cada grupo de trabajo para que pueda explicar en qué consiste ese grupo. Si no viene nadie de algún grupo, los demás tendremos que inventarnos la parte correspondiente, con las consiguientes potenciales burradas e incoherencias que esto pueda ocasionar.

**Comment by Siotma** [comment]
Yo puedo ir.

**Comment by jgvictores** [comment]
Anotado!

**Comment by Siotma** [comment]
Respecto a esta actividad, me surgen dos cuestiones ya que desconozco cómo está planteada:

1. ¿Se va a utilizar algún soporte visual como presentación durante la charla? ¿En caso afirmativo, tenemos alguna que podamos reutilizar? Sería importante ir confeccionándola/actualizándola.
2. ¿Se van a llevar chismes para enseñar?

**Comment by David-Estevez** [comment]
¿Cuándo preparamos esto? ¿10 minutos antes como siempre? :joy: :joy: :joy:

**Comment by JorFru** [comment]
Aprovechando que estuve en el acto "Bienvenida", dediqué quince minutos para presentar a ASROB y sus ramas.
https://twitter.com/jorgeelalto/status/914765984300507136
En la imagen, hablando de UAVs

**Comment by David-Estevez** [comment]
Gracias @JorFru :clap: :clap: :clap: :clap:

**Comment by Siotma** [comment]
Finalmente, sí que voy a poder ir a la charla, aunque no sé si desde el principio. 

Creo que puedo explicar el grupo Printer One utilizando la Wiki y la web de impresoras, calculo que me llevará unos 10 minutos así que no me pongáis el primero, pero contad conmigo :)

**Comment by David-Estevez** [comment]
Gran charla, gracias a todos los que habéis participado en ella!

@Siotma 
@jgvictores 
@KFRodicio 
@David-Estevez
