### ISSUE TITLE
Semana de Asociaciones 2017: Taller de arduino

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#84]
Este año en la Semana de Asociaciones haremos un taller de arduino (ver #72 ). Este taller tendrá dos sesiones.

La info del taller es la siguiente:
* Sesión 1 (Martes 3 de octubre de 2017):

> Código 47. Taller de arduino - 2 SELLOS
> 
>    9:00 - 12:00h
>    Edificio Torres Quevedo. Aula 4.0.E06
> 
> Decídete a dar el paso para iniciarte en el mundo de Arduino. En este taller te enseñaremos a utilizar la IDE para realizar tu primer programa en C con nosotros. Aprenderás a mover servos, leer sensores, o controlar LEDs. Pero este taller es solo un punto de partida: también conocerás las distintas placas que existen actualmente, así como los principales recursos de autoaprendizaje para seguir avanzando en este mundillo por tu cuenta.
> 
>    Organiza: Asociación ASROB

* Sesión 2 (Miércoles 4 de octubre de 2017):

> Código 57. Taller de arduino - 2 SELLOS
> 
>  15:00 - 18:00h
>    Edificio Torres Quevedo. Aula 4.0.E05
>
> Decídete a dar el paso para iniciarte en el mundo de Arduino. En este taller te enseñaremos a utilizar la IDE para realizar tu primer programa en C con nosotros. Aprenderás a mover servos, leer sensores, o controlar LEDs. Pero este taller es solo un punto de partida: también conocerás las distintas placas que existen actualmente, así como los principales recursos de autoaprendizaje para seguir avanzando en este mundillo por tu cuenta.

 >   Organiza: Asociación ASROB

Asigno a @KFRodicio y @Siotma que fueron los que propusieron la charla. Como siempre, si necesitáis que os echemos una mano, avisadnos.

**Comment by Siotma** [comment]
Por lo que veo nos han concedido hacer los dos talleres iguales. Genial!

**Comment by David-Estevez** [comment]
Sí, espero que la gente se de cuenta y no se apunten los mismos a los dos :joy:

**Comment by Siotma** [comment]
Dada esta situación, si se puede, yo pediría que se añadiera una línea más a la descripción que diga algo así como:

"Este es el mismo taller que se impartirá el día (inserte el día contrario), únicamente se computarán los sellos correspondientes a uno de ellos por lo que no está permitido apuntarse a ambos."

Tampoco sé cómo funciona esto, si acaso recibimos un listado con los apuntados o cómo.

**Comment by David-Estevez** [comment]
Se lo puedo comentar a África mañana a ver cómo lo haría ella para evitar confusiones.

La lista de los apuntados suele tenerla África justo antes de la semana por si hay que cancelar alguna actividad con poca gente o algo.

**Comment by Siotma** [comment]
Respecto a este taller, aun me surgen más dudas:

La más importante es si los asistentes saben que tienen que traer su ordenador portátil, porque en la [página oficial](https://www.uc3m.es/ss/Satellite/UC3MInstitucional/es/TextoDosColumnas/1371236588534/Semana_de_Asociaciones_-_Campus_de_Leganes) no lo pone.

La verdad es que no recuerdo de si al final propusimos pedir que cada uno traiga sus ordenadores, o si en cambio contamos con utilizar algún aula informática, como sé que ya se ha hecho alguna vez. Sea como sea, esto hay que aclararlo y moverlo cuanto antes:
- En caso de que los asistentes necesiten portátil, indicarlo en la descripción del taller.
- En caso de utilizar un aula informática, pedir que el aula se habilite con el IDE de Arduino, apertura de puertos y permisos para instalar drivers.

Otra cosa son los objetivos y materiales del taller, pero creo que urge más lo anterior, por lo que de esto podemos hablar la semana que viene con más calma.

**Comment by David-Estevez** [comment]
Eso queda como decisión vuestra, que sois los que vais a hacer el taller. Bajo mi punto de vista, el punto 2 es casi imposible de conseguir, yo optaría por el primero que propones.

Por lo demás:
* Para cambiar la descripción del taller hay que escribir un correo a África (alsanche@pa.uc3m.es)
* Los objetivos los decidís vosotros, podéis inspiraros en el taller que dísteis en El Evento.
* Materiales: 9 Freeduinos + 1 Arduino Uno chinorro. Más lo que tengamos en el armario. Si hay que comprar más cosas se pueden comprar. También se pueden pedir más Arduinos al GUL, que lo mismo nos los prestan (#91)

**Comment by KFRodicio** [comment]
Yo creo que lo mejor es justo eso, repetir el taller que se dió para el
evento, en teoría el material debería estar todo, no? Sobre lo del
ordenador, yo creo que lo mejor es avisar de que cada uno se traiga el suyo

El 25 sept. 2017 12:59 a. m., "David Estévez Fernández" <
notifications@github.com> escribió:

Eso queda como decisión vuestra, que sois los que vais a hacer el taller.
Bajo mi punto de vista, el punto 2 es casi imposible de conseguir, yo
optaría por el primero que propones.

Por lo demás:

   - Para cambiar la descripción del taller hay que escribir un correo a
   África (alsanche@pa.uc3m.es)
   - Los objetivos los decidís vosotros, podéis inspiraros en el taller que
   dísteis en El Evento.
   - Materiales: 9 Freeduinos + 1 Arduino Uno chinorro. Más lo que tengamos
   en el armario. Si hay que comprar más cosas se pueden comprar. También se
   pueden pedir más Arduinos al GUL, que lo mismo nos los prestan (#91
   <https://github.com/asrob-uc3m/actas/issues/91>)

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/actas/issues/84#issuecomment-331746227>, or mute
the thread

**Comment by Siotma** [comment]
De acuerdo, hay que escribir a África. Quién lo hace.

**Comment by KFRodicio** [comment]
Si alguien es tan amable de hacerme un resumen de lo que hay que decirle, me encargo yo mañana por la mañana

**Comment by Siotma** [comment]
Desde mi punto de vista, el correo debería incluir

- Una petición para que se avise a los inscritos en los talleres que deben traer sus propios ordenadores portátiles con Arduino IDE. También se puede pedir que se incluya esta condición en la descripción del taller. Los que vengan sin portátil podrán participar formando equipos con los que sí tengan (máximo 3 personas por equipo).
- Una aclaración de que ambos talleres serán iguales para que ella valore si debe gestionar que la gente no pueda repetir.
- Una pregunta sobre cuántos participantes hay apuntados en cada taller, para comenzar con la publicidad agresiva si es necesario.

**Comment by Siotma** [comment]
Por otra parte, hay que quedar para preparar un poco el taller: quedamos el lunes por la mañana?

**Comment by KFRodicio** [comment]
A ver que os parece esto:

Buenas tardes.

Escribo en nombre de la asociación de robótica de la uc3m (ASROB) para comentar algunas cosas acerca del taller que vamos a organizar durante la semana de asociaciones. En primer lugar, nos gustaría que se modificase la descripción del taller para añadir al final lo siguiente:

_"Es recomendable traer un portatil con el IDE de arduíno instalado (aquellos que vengan sin portatil tendrán que formar equipo con otros participantes que si lo tengan, hasta un máximo de tres personas por equipo)"_

Además, queremos que quede claro que los dos talleres que vamos a dar son el mismo, pero en dos horarios diferentes. Es importante que nadie se apunte a los dos. Por último, queríamos saber si es posible conocer la cantidad de personas apuntadas, para así empezar a hacer más difusión si hay muchas plazas vacías.

Un saludo

**Comment by KFRodicio** [comment]
Me parece bien lo de quedar el lunes

**Comment by Siotma** [comment]
Ya te lo dije por Telegram, pero lo reafirmo por aquí. Conforme con el correo.

A qué hora quedamos el lunes?

**Comment by Siotma** [comment]
Hoy hemos quedado @KFRodicio y yo para preparar el taller.

Utilizaremos material común de la asociación tal como:
- 9 Freeduinos con un cable USB cada una.
- 20 LDRs del armario.
- 10 LED azules del armario.
- 10 LED RGB del armario.
- 80 Resistencias de 470ohm y de 20 de 2k2ohm del armario.
- 11 Microservos cogidos prestados del taller de Zowimanoides.
- 9 placas protoboard del armario, de las cuales 5 corresponden a las pedidas para el Hackatón de El Evento.
- Un número indeterminado de cables macho-macho del armario.
- 2 kit de robot móvil con dos servos de rotación continua, del armario.
- 2 sensores de ultrasonidos, del armario.

También nos llevaremos regletas, alargadores y herramientas tales como destornilladores etc.

Además, @KFRodicio se ha ofrecido a traer una Arduino UNO suya, así como alguna protoboard más, y más cables.

Yo, por mi parte, llevaré dos protoboards.

He creado un repositorio donde guardar los archivos importantes que generemos durante las actividades de la Semana de Asociaciones, de manera que sea fácil recuperarlos en un futuro: https://github.com/asrob-uc3m/Semana_de_Asociaciones_2017

**Comment by Siotma** [comment]
La sesión de hoy ha sido todo un éxito de asistencia (30 personas) así como de realización. Creo que la clave ha sido colgar la presentación online para que todos pudieran tenerla como guía.

Toco madera para que el taller de mañana salga igual de bien, o mejor!!

**Comment by Siotma** [comment]
La sesión de ayer tambíen fue un éxito de asistencia: 29 personas. La realización fue mejor si cabe que la del martes pues hubo grupos que consiguieron completar los objetivos del taller (recogidos en [este pdf](https://github.com/asrob-uc3m/Semana_de_Asociaciones_2017/blob/master/Taller_de_Arduino/Curso%20de%20Arduino%20Semana%20de%20Asociaciones%202017%20completo.pdf)).

Las presentaciones utilizadas las he dejado en el [Repositorio de la Semana de Asociaciones 2017](https://github.com/asrob-uc3m/Semana_de_Asociaciones_2017) para que puedan consultarse y reutilizarse en un futuro. 

Respecto al material utilizado para los talleres:
- Las regletas y destornilladores las hemos dejado en su sitio en el armario de la izquierda.
- Los componentes listados [aquí](https://github.com/asrob-uc3m/actas/issues/84#issuecomment-333635352), están en una caja en el armario de la derecha. Dado que se va a hacer [limpieza](https://github.com/asrob-uc3m/actas/issues/93) la próxima semana, @KFRodicio y yo hemos pensado que será el mejor momento para encontrarles un sitio.

Sin más, doy la Issue por cerrada.

**Comment by Siotma** [comment]
Aquí dejo el material utilizado para dar los talleres.

[Taller_de_Arduino.zip](https://github.com/asrob-uc3m/actas/files/1501289/Taller_de_Arduino.zip)

**Comment by jgvictores** [comment]
Subido tambien a Drive, accessible via asrob-uc3m (gmail.com) y asrob (uc3m.es): `Charlas y talleres` > `2017 Semana de asociaciones`.
