### ISSUE TITLE
Semana de Asociaciones 2017: Feria de Asociaciones

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#85]
Como todos los años, la Semana de Asociaciones tiene un día de Feria de Asociaciones dedicado a la promoción de las distintas asociaciones de la universidad. 

Se suelen celebrar 2 (puede que 3 este año si Colmenarejo celebra la suya), un día en Leganés y otro en Getafe. Todavía no se sabe qué día se celebrará qué feria, mañana África nos dará más detalles.

Como siempre, es una gran oportunidad para promocionar la asociación que creo que deberíamos aprovechar para enseñar nuestros cacharros y reclutar gente nueva.

**Comment by KFRodicio** [comment]
Dejo esto por aquí:

1.- Las Ferias serán el Jueves 5 de octubre en Getefe (de 10.30 a 19.00 h. aproximadamente) y el viernes 6 de octubre (de 10.30 a 19.30 h) en Leganés. En Colmenarejo la Delegación de Estudiantes no me ha comunicado nada a día de hoy, por lo que no sé si finalmente habrá feria en ese campus.

2.- Os dejo un doodle para que podáis "inscribiros" para participar en la Feria y que así las Delegaciones conozcan el número de asociaciones participantes en cada campus. Por favor, necesito que contestéis antes del martes 26 de septiembre.

DOODLE PARTICIPACIÓN FERIA: https://doodle.com/poll/ycshq2fwxc66rq2g



3.- Como sabéis, también podéis participar hablando un poquito de vuestra asociación en la charla inaugural. Necesito que me rellenéis también otro doodle para que las diferentes delegaciones conozcan cuantas asociaciones están interesadas en participar en esta conferencia y poder así distribuir el tiempo y preparar su ponencia. Plazo: hasta el 26 de septiembre tb... 

Aquí tengo el mismo problema que con la Feria en el campus de Colmenarejo, nadie se ha puesto en contacto conmigo de Delegación, y si se va acercando la fecha, tendremos que valorar realizar esa charla nosotros (las asociaciones de Colmenarejo) por lo que os pido máxima colaboración si esto llegara a ocurrir... vamos a ir viendo!!!)😰

Las conferencias inaugurales son en Getafe y Leganés de 9.00 a 10.30 h el lunes 2 de octubre. En Colmenarejo es de 10.45 a 12.15 h.

DOODLE PARTICIPACIÓN CONFERENCIA INAUGURAL: 

https://doodle.com/poll/fcuqntuzt9veb4fi

ATENCIÓN: EN LOS DOODLES PONER EL NOMBRE DE LA ASOCIACIÓN NO EL VUESTRO!!!!

4.- Adjunto el informe de la inscripción a día de hoy en vuestras actividades. Estamos muy flojitos, por lo que como todos los años, os pido máximo esfuerzo esta semana y la que viene en difundir la Semana... No es difícil, es una Semana INCREIBLE, así que todos a una!!! 💪

5.- Como es una semana INCREIBLE 😍, nos han concedido también el reconocimiento de un crédito de humanidades para los participantes (para obtenerlo deben  realizar las actividades suficientes para obtener 6 sellos en el pasaporte de la Semana de Asociaciones). Recordad que ya teníamos concedido el optativo.

6.- Como sabéis, por la organización de dos o más actividades, vosotros podéis obtener un crédito optativo. Cuando acabe la semana os contaré en un correo cómo podéis solicitarlo.

7.- Por favor, aquellas asociaciones que ibais a cambiar actividades (cara sur, ALMUCAT, etc... ) comunicármelo cuanto antes!!!!! 

8.- Estoy dando vueltas a lo que os conté de poder hacer una pancarta... si me da tiempo a comprar las telas y demás, haré convocatoria de "taller de pancartas"...😉

**Comment by Siotma** [comment]
Yo puedo colaborar en la feria de asociaciones.

Además, creo que dado que la conferencia inaugural únicamente se nos pide una intervención de 5 minutos, seguro que podemos encontrar la manera de que alguien vaya en representación de ASROB, aunque a día de hoy yo no puedo comprometerme a ir a esta conferencia.

Podemos ir diciendo nuestra disponibilidad para una u otra cosa po aquí, de manera que podamos votar el Doodle antes de que acabe el plazo.

**Comment by KFRodicio** [comment]
Mandó africa un correo para pintar una pancarta que quieren colgar en la semana de asociaciones. No me queda claro si lo que quiere es que cada asociación ponga su nombre o algo, o si quieren pintar algo genérico. En cualquier caso, si tenemos algún miembro que tenga algo de talento artístico, y quiere meterse en esto, hay que pasarse por delegación

**Comment by KFRodicio** [comment]
Respecto a la feria, contesté por correo, pero no lo puse por aquí, así que lo repito. Yo echo una mano en la feria sin problema. Respecto a la conferencia inaugural, la verdad es que me da bastante pereza, pero si nadie más va a ir, y lo vemos muy necesario, pues hago un esfuerzo

**Comment by David-Estevez** [comment]
Sobre la pancarta; no es algo que requiera de talento artístico o específico de ASROB. Lo que se busca es voluntarios que puedan ayudar a pintar una pancarta genérica para la semana de asociaciones.

**Comment by KFRodicio** [comment]
Bueno, pues si alguien se quiere meter en eso, ya sabe a donde ir

**Comment by JorFru** [comment]
![imagen](https://user-images.githubusercontent.com/11017088/31119913-ef0e9aee-a832-11e7-9a51-86605c3bd555.png)
Alguien está al tanto de esto?
Os habéis apuntado vosotros a la gymkhana?

Desde luego UC3Music no se ha apuntado, al menos conscientemente.

**Comment by Siotma** [comment]
Dado que hemos propuesto como actividad de la Gymkhana la pelea de Zowimanoides, he cargado 5 paquetes de pilas para que haya durante todo el día.

Creo que sería buena idea llevar algún móvil android viejo, o alguna tablet a la que no tengamos mucho cariño para que la gente los use como mando a distancia de los robots. Alguien puede ofrecer alguno?

**Comment by David-Estevez** [comment]
Puede que tenga algo por casa, voy a mirar. ¿Cuál es la app que hay que instalar para controlarlos?

**Comment by David-Estevez** [comment]
He encontrado uno de [estos](https://en.wikipedia.org/wiki/Samsung_Galaxy_Ace) por casa. ¿serviría?

![picture](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Samsung_Galaxy_Ace.png/250px-Samsung_Galaxy_Ace.png)

**Comment by Siotma** [comment]
Probablemente. Si enciende tráetelo porfa, con un cargador a ser posible.

**Comment by David-Estevez** [comment]
Enciende y está borrado de fábrica, por lo que habrá que instalarle todo lo que necesites.

Para cargarlo vale con cualquier cable micro USB.

**Comment by David-Estevez** [comment]
Muchas gracias a todos los que os pasásteis por el stand y contribuísteis a una gran feria de asociaciones!!

@KFRodicio 
@Siotma 
@jorgercobo 
@JorFru 
@David-Estevez
