### ISSUE TITLE
Redirección del dominio de ASROB a la web

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#87]
En la reunión del 14/09/2017 se decidió usar la web como página web principal de ASROB, enlazando a la wiki (y viceversa). Por tanto se ha de redirigir el dominio de ASROB (asrob.uc3m.es) a la web (asrob-uc3m.github.io).

**Comment by jgvictores** [comment]
https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by David-Estevez** [comment]
@jgvictores sugiere la migración total de los contenidos de la wiki desde el servidor de ASROB a la web en formato Markdown, por lo que se llevará a cabo una redirección DNS del nombre de dominio.

Me encargo de hablar con el servicio de informática.

**Comment by Siotma** [comment]
Hoy, @David-Estevez y yo hemos hablado de las dificultades que tendría apuntar la url asrob.uc3m.es a la web de GitHub, al estilo de music.uc3m.es .

La principal dificultad es que en GitHub no podríamos tener nuestras propias aplicaciones como asrob.uc3m.es/printers/ , http://asrob.uc3m.es/printers/operators.html , la futura página de reservas (https://github.com/asrob-uc3m/printers-status-webpage/issues/4) etc...

Estas aplicaciones tendrían que estar en un dominio con nuestro nombre, pero el de asrob.uc3m.es, debería apuntar directamente a nuestra web ya que ambos son nuestra carta de presentación. Se nos ha ocurrido que si solicitamos un nuevo subdominio como por ejemplo:

- api.asrob.uc3m.es
- apps.asrob.uc3m.es
- api_asrob.uc3m.es
- apps_asrob.uc3m.es

Podríamos alojar nuestras aplicaciones ahí, y dejar el actual dominio para la web, desde donde podríamos enlazar las aplicaciones que queramos. En el caso de que la web, además, soporte javascript, se podría reducir el papel de nuestro servidor a dar servicio de api contra bases de datos que tengamos (ejemplo: estado de impresoras, operadores, reservas, inventario, y más..).

**Comment by David-Estevez** [comment]
Voy a intentar expandir el comentario de @Siotma con otros conceptos o ideas sobre las que hemos estado debatiendo esta tarde. 

Básicamente, y como bien dice @Siotma , nos hemos dado cuenta de que una migración completa de nuestro sistema a servidores externos no es posible, porque pese a que la mayor parte de nuestras necesidades las tenemos cubiertas con gitbooks, la web y demás páginas estáticas, tenemos la necesidad de tener ciertas páginas dinámicas que necesitan de un servidor para correr. Estas aplicaciones son las que ha mencionado @Siotma 

La propuesta entonces sería hacer que asrob.uc3m.es lleve a la web, y que sea esta web la que redirija a las páginas externas dinámicas que sean necesarias. Esto es posible, y se ha implementado con éxito para disponer de enlaces que siempre apuntan al doodle más reciente (Ver  https://tinyurl.com/asrob-doodle-game). El esquema de esta solución sería el siguiente:

![image](https://user-images.githubusercontent.com/1451819/33912026-98daba60-df94-11e7-9c36-a696610271ad.png)

Otra opción que se me ocurre, pero que tengo que validar si es factible es implementar las webs que tengan que ser dinámicas usando un framework de javascript, de forma que sea la propia web la que pida la información necesaria a un backend. La webapp en sí la serviría GitHub, pero haría peticiones a nuestro servidor para obtener la información necesaria. El esquema de esta solución sería el siguiente:

![image](https://user-images.githubusercontent.com/1451819/33912021-95c83546-df94-11e7-8aef-2cf486450681.png)

Tanto las redirecciones, como la alternativa de usar javascript con un backend emplearían el servidor de asrob, el cual tendría que tener un nuevo nombre de dominio como los que sugiere @Siotma .

**Comment by PeterBowman** [comment]
Necesitarás JSONP o CORS para sortear la same-origin policy que imponen los navegadores cuando lanzas una request con JS entre diferentes dominios. En el segundo caso, debería bastar con que el backend devuelva una cabecera `Access-Control-Allow-Origin` con el filtro adecuado.

**Comment by David-Estevez** [comment]
Ya he averiguado cómo se hace esto, y procederé al cambio (junto con #88 ) tan pronto como sea posible. Lo único que me hace falta saber es cómo solucionar que se pueda acceder a la wiki una vez este cambio y el de #88 se hagan efectivos. 

Mi propuesta es tener un dominio wiki.asrob.uc3m.es que resuelva al server de ASROB, y para el que podamos pedir un certificado independiente del de asrob.uc3m.es. La otra alternativa es un asrob.uc3m.es/wiki , pero ahí seguramente tengamos problemas de certificado con el https. 

@jgvictores ok solicitar wiki.asrob.uc3m.es, apuntar a wiki y migrar dominio a la web?

**Comment by jgvictores** [comment]
> @jgvictores ok solicitar wiki.asrob.uc3m.es, apuntar a wiki y migrar dominio a la web?

Me parece perfecto. En el peor de los casos tendríamos que tocar algún parámetro del apache del server, nada grave. Adelante y muchas gracias!

**Comment by David-Estevez** [comment]
Dominio redirigido. 

El resultado de esta issue es:
* asrob.uc3m.es ahora apunta a la web, alojada en github pages.
* wiki.asrob.uc3m.es ahora apunta a la wiki, alojada en el servidor de siempre.
* Todas las páginas especiales (printers, contributors, etc) ahora son parte de wiki.asrob.uc3m.es (aunque printers tiene un redirect y funciona también desde asrob.uc3m.es/printers.html).
* Todos los links de la web que apuntaban a la wiki están actualizados.
* Las configuraciones nuevas de apache están respaldadas en wikirobots.
