### ISSUE TITLE
Usar https en las webs de la asociación

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#88]
Actualmente las comunicaciones con la wiki son en http plano. En la reunión del 14/09/17 se decidió pedir un certificado a la universidad para usar https en las páginas de la asociación.

Acciones a tomar: 
 * [x] Pedir un certificado a la universidad
 * [x] Configurar el servidor para usar https

**Comment by jgvictores** [comment]
Véase #87

**Comment by Siotma** [comment]
Tal vez en vez de solamente pedir el certificado a la universidad, dado que el servidor de asrob es un dominio uc3m se podría pedir ayuda al servicio de informática para simplificar el proceso. Seguro que para ellos es una tarea sencilla de hacer.

**Comment by jgvictores** [comment]
Véase https://github.com/asrob-uc3m/actas/issues/87#issuecomment-331735981

**Comment by jgvictores** [comment]
> Véase https://github.com/asrob-uc3m/actas/issues/87#issuecomment-331735981

Ok, acabo de ver que esto es para otro caso de uso, el #4. No aplica el comentario porque es para otro context (wiki vs web).

**Comment by David-Estevez** [comment]
La dificultad de esto no radica en la dificultad de obtener el certificado / configurarlo, sino en que queremos mover los servicios críticos a proveedores externos (#87) pero a su vez tenemos todavía cosas alojadas en nuestro servidor (wiki) y cosas que nos interesaría tener en nuestro servidor en un futuro (aplicación de reserva de impresoras, por ejemplo). 

Decidir cómo tendrá lugar esa convivencia de ambas cosas es la parte en la que radica la dificultad, y había quedado un poco abandonada por mi parte por las deadlines de las subvenciones. De hecho, tenía conversaciones pendientes con Nuria, que se ofreció para echarnos una mano con esto de los certificados y las redirecciones.

**Comment by jgvictores** [comment]
Me gusta la idea de outsourcing porque no tenemos redundancia en servidores ni en servicio de atención al servidor. Pero sí, de momento hay muchos servicios que tenemos en nuestro servidor, y no tenemos una agenda ni manera clara de migración. En conclusión, de acuerdo con lo que comentas, además de [esto otro tuyo acerca de la importancia de https](https://github.com/asrob-uc3m/printers-status-webpage/issues/4#issuecomment-351008631).

**Comment by David-Estevez** [comment]
Posiblemente esto nos sea útil: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by David-Estevez** [comment]
Estado actual: Pidiendo certificados a través de @VentressAsajj , y documentándonos sobre cómo los gestiona GitHub cuando hay un dominio externo.

**Comment by David-Estevez** [comment]
Recibidos los certificados, comenzaremos la configuración tan pronto como nos sea posible.

**Comment by VentressAsajj** [comment]
Sin la clave no puedes. Has estado aquí y no te he dado la clave para descomprimir

**Comment by David-Estevez** [comment]
Trabajando en esto tras #87. Metí la pata al decirle a @VentressAsajj cómo había que configurar el DNS para esto, pero la semana que viene lo solucionaremos.

**Comment by David-Estevez** [comment]
Ya está todo configurado, y la web funciona con https. 

Hacer que la wiki funcione con https es un poco más complejo, ya que involucra jugar con configuraciones y certificados. Dado que nos ha costado más de 1 año dar el soporte únicamente a la web, voy a dar la issue por cerrada, y en el momento en que veamos una ferviente necesidad de poner https en la wiki, que actualmente se mantiene por motivos históricos, abrimos otra issue para ello.
