### ISSUE TITLE
Página Principal de la Wiki: Añadir City of Robots

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#9]
Se ha recibido una solicitud de City of Robots de convertirse en Grupo Activo de ASROB. Dado que cumplen las condiciones requeridas en los [estatutos](https://asrob-uc3m.gitbooks.io/estatutos/content/chapter1.html), se ha procedido a la creación de una [página para el grupo](http://asrob.uc3m.es/index.php/City_of_Robots) en la wiki.

Quedamos pendientes de que City of Robots rellene su página de la wiki para enlazarla desde la página principal.

cc @Rodriwp

**Comment by Rodriwp** [comment]
La wiki esta actualizada en su versión uno

**Comment by jgvictores** [comment]
Enlace?

**Comment by Rodriwp** [comment]
http://asrob.uc3m.es/index.php/City_of_Robots

**Comment by David-Estevez** [comment]
Estoooo... y el logo de Robot Devastation?? :sweat:

**Comment by Rodriwp** [comment]
El logo grande es del city of robots, en el logo pequeño iran los dos, el de robot devastation y el de city of robots, ya que la ciudad esta pensada para robot devastation.

**Comment by Rodriwp** [comment]
La documentación de city of robots ha sido actualizada a su ultima versión. Ya esta lista para ser incluida en la pagina principal de asrob

**Comment by Rodriwp** [comment]
City of Robots ya esta en la pagina principal de la wiki
