### ISSUE TITLE
Crear calendario comprartido para actividades ASROB

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#90]
En la reunión del 14/09/17  se propuso el crear un calendario compartido desde la cuenta de ASROB en el que podamos poner todos los eventos y compartirlo, publicarlo en la web, etc.

Tareas:
* [ ] Crear el calendario compartido, compartirlo y publicarlo.

**Comment by David-Estevez** [comment]
Aquí está el calendario creado: https://calendar.google.com/calendar/embed?src=e97mebpnhjcq8pbl28plc8l3is%40group.calendar.google.com&ctz=Europe/Madrid

Deberíamos enlazarlo en algún lado?

**Comment by Siotma** [comment]
Yo apostaría por incrustar el calendario en la web.

Quién y cómo puede editar ahora mismo el calendario? Lo suyo sería que los responsables de grupos de trabajo pudiéramos crear los eventos de reunión...

**Comment by David-Estevez** [comment]
Te has suscrito ya al calendario? Te aparece alguna opción de pedir permisos de admin? 

Una vez puedas editarlo es como un calendario más de google, sólo que los eventos son públicos (cualquiera puede consultarlos).

**Comment by Siotma** [comment]
Creo que sí que me he suscrito, pero no veo ninguna opción de pedir privilegios. Le he cambiado el color, no sé si habrá repercutido en los demás o es un cambio local.

Hay que ver cómo se puede compartir también la administración.

**Comment by jgvictores** [comment]
> Deberíamos enlazarlo en algún lado?

Sí, además sería bonito que se pudiese descargar el `.ics` (pese a que se utilice aun menos que los QR 😂 ).

**Comment by David-Estevez** [comment]
Descargar el `.ics` no tiene mucho sentido, porque los eventos no están añadidos para todo el año, sino que se van añadiendo semana tras semana. 

Pese a ello, creo que puedes descargarte el `.ics` desde las opciones.

**Comment by jgvictores** [comment]
Oks!

**Comment by jgvictores** [comment]
> Deberíamos enlazarlo en algún lado?

1. Me suena haber visto un widget pero no encuentro. ¿Os suena haberlo puesto?
1. ¿Quizás enlazarlo desde http://asrob-uc3m.github.io/ ?
