### ISSUE TITLE
Contactar con el GUL para negociar la cesión de placas Arduino

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#91]
En la reunión del 14/09/2017 se habló de la posibilidad de llegar a un acuerdo con el GUL para que nos cedan Arduinos para el [taller de la Semana de Asociaciones](https://github.com/asrob-uc3m/actas/issues/84).

Dado que @Morgloz tiene contacto con ellos, creo que es un buen candidato para resolver esta issue. :wink:

**Comment by Siotma** [comment]
A la vista de https://github.com/asrob-uc3m/actas/issues/84#issuecomment-333817004, esto finalmente no va a ser necesario. Cierro.
