### ISSUE TITLE
Organizar el III Hackaton UC3Music-ASROB

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#92]
Tras la muerte de El Evento en la reunión del 14/09/17, se manifestó nuestro interés por salvar al menos el hackaton, dado el alto nivel de demanda que suele tener todos los años.

Esta issue ha sido creada para organizar dicho hackaton. Todo el que esté interesado en la organización, que se asigne / comente.

**Comment by JorFru** [comment]
Según
![imagen](https://user-images.githubusercontent.com/11017088/36939617-2c58d78e-1f34-11e8-83ee-fe55754c737d.png)
A UC3Music le han subvencionado la actividad Hackatón.
Por afinidad electrónica con ASROB, es posible que UC3Music se anime a organizarlo con vosotros si, por ejemplo, ofrecéis vuestra herramienta para tal actividad.

¿Votación para definir si es de interés para ASROB?

**Comment by David-Estevez** [comment]
No se suponía que era conjunto? No se pidió con esa intención?

**Comment by JorFru** [comment]
No se pidió en conjunto.
Esto es una propuesta a posteriori.

**Comment by David-Estevez** [comment]
Entonces sí, votación sería lo suyo.

**Comment by JorFru** [comment]
Skynet en línea y procesando a 100TFlops/s

https://docs.google.com/forms/d/1Db4JYi8Bo1_Z05usq0_lvMnZtWAN1MF0A8eR5N6P5cU/edit

Voten!

**Comment by JorFru** [comment]
El resultado de la votación ha sido cinco síes, cero nóes, cero "haced lo que queráis, pesaos"

La etiqueta "Y después cervezas" de esta issue no es una sugerencia, es una obligación!.


Resumen: ASROB ayudará a UC3Music en el hackatón aportando herramientas variadas.

**Comment by jgvictores** [comment]
Guai! Hay fecha aprox?

**Comment by JorFru** [comment]
Por ahora nada, ni si quiera aproximada.
Pero cuando empiece el movimiento te aseguro que se hará sonar.

**Comment by JorFru** [comment]
Fecha provisional, 19 de octubre, antes de las ferias maker, después del puente del 12 de octubre, que la uni cierra.
Y en viernes, para intentar conseguir la máxima asistencia (buena excusa para saltarse clase)

**Comment by GioSunrider** [comment]
Yo me apunto!

**Comment by David-Estevez** [comment]
Plis, usa el botoncito de github para mover esa issue a este repo:

![image](https://user-images.githubusercontent.com/1451819/51091610-11532500-178d-11e9-889d-75b6d63f036b.png)

**Comment by JorFru** [comment]
Ya está en el repo actas.


¿Es esto lo que querías?

**Comment by David-Estevez** [comment]
Ferpecto :+1:

**Comment by JorFru** [comment]
Gracias compañeros sois unos organizadores excelentes.
la próxima vez nos inventamos las reglas por lo menos media hora antes del evento.
