### ISSUE TITLE
Limpieza y orden del espacio de trabajo ASROB

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#93]
En la reunión del 14/09/2017 se comentó que el departamento nos había dado un toque de atención por el aspecto desordenado y descuidado de nuestro espacio de trabajo. También se habló de los armarios y su caos interno y de la necesidad de un inventario usable.

Para solucionarlo, se propusieron dos quedadas:
  *  [X] Quedada para tirar basura y limpiar (+ cervezas)
  *  [x] Quedada para ordenar las cosas restantes (+ cervezas)

**Comment by David-Estevez** [comment]
Aprovechando que la semana que viene tenemos un puente gigante en Leganés, y que puede que muchos no os vayáis a ningún lado durante el puente, he creado un doodle para quedar un día y comenzar la limpieza del espacio de trabajo (y finallizarla, con un poco de suerte).

El doodle es este: https://doodle.com/poll/hwue3nawyqfhn6fr y estará abierto hasta el domingo.

**Comment by Siotma** [comment]
He votado el Doodle. Me sorprende ser el primero. Hay que dar publicidad a esto por los grupos de trabajo.

**Comment by David-Estevez** [comment]
Limpiar nunca ha sido una actividad muy popular... :joy: Compartiendo!

**Comment by David-Estevez** [comment]
Parece que el día más popular es el próximo **Martes 10 por la tarde**, así que haremos la limpieza ese día. 

Además, creo que había negociaciones con otras asos para continuar las cervezas del viernes pasado este Martes, así que podemos empalmar la limpieza con las birras :beers:  :beers:  :beers:

**Comment by JorFru** [comment]
Muchas gracias a todos los participantes del día de hoy en la limpieza tediosa que nadie quería hacer! Sin vuestra ayuda no hubiese sido posible.
Reconocimiento de mérito excepcional a @David-Estevez @Siotma @juanfdelarco @jorgercobo @jorfru @kfrodicio

Además, me autoproclamo cerrador oficial de esta issue de manera horizontal tras la conclusión del trabajo de hoy.

**Comment by David-Estevez** [comment]
Gracias, señor @JorFru, y gracias a todos los que os pasásteis a echar una mano, pero esta issue todavía no se puede cerrar. Ayer se hizo la parte de limpieza, pero falta una parte muy importante que es la del orden del espacio de trabajo. 

Para ello, @jorgercobo y yo hemos hecho un brainstorming con propuestas de mejora del orden que nos gustaría comentar con vosotros por aquí.

Las propuestas son:
- **~Tirar a la basura~ Reciclar el escenario verde**. No se usa desde hace años, ocupa mucho espacio y aunque volviésemos a competir no nos serviría para ninguna competición.
- **Creación de un rack de impresoras (autónomas)**. De esta forma, liberaremos mesas que actualmente están ocupadas con ordenadores dedicados a la impresión. Otras posibles mejoras en el rack sería cerrar el rack y poner extracción de humos / detección de incendios y pasar el GCODE por WiFi  / instalar octoprint.
- **Creación de nuevos escenarios de competición portables**. Esto se podría hacer en RoboFactory.
- **Cambiar la distribución de mesas**. Una vez creado el rack de impresoras, mover las mesas que estaban ocupadas con los ordenadores para poder usarlas. Se ha pensado también en dedicar una de ellas a guardar / trabajar con la mesa de Air Hockey.
- **Pensar en un protocolo fijo de ferias/exposiciones**. Pensar qué cosas sacar y si hace falta preparar algo más para sacar (cosas que falten para demos, etc).
- **Espacio de trabajo hardware**. Comprar un taladro / dremel y una escoba y habilitar un espacio para hacer "bricolaje".
- **Espacio de trabajo de electrónica**. Habiiltar una mesa para el trabajo con electrónica, incluyendo fuentes de alimentación, instrumentación (osciloscopio, aunque sea cutre) y cosas para soldar.
- **Organización de herramientas**. Buscar una más óptima de guardar y clasificar las herramientas.
- **Decoración del armario**. Actualmente en el armario hay mucho cartel anticuado. Evaluar si alguno se puede retirar e instalar magnéticamente el nuevo cartel ASROB.

**Comment by Siotma** [comment]
Creo que todo son buenas ideas.

-Yo utilizaría la idea de crear escenarios portables para tratar de mejorar el escenario verde. Si lo desmontamos, las planchas de madera no ocupan mucho y se pueden reutilizar. Incluso, con un poco de paciencia se pueden poner clavijas para que las paredes sean de quita y pon, de manera que pueda estar guardado pegado a una pared y en el momento que se necesite, se monte rápidamente. Incluso se puede partir el escenario en cuatro sub escenarios (véase cortar el suelo en cuatro y las paredes por la mitad) de forma que se puedan utilizar para construir escenarios con diferentes tamaños y formas utilizando las clavijas para montar el puzzle resultante. Tirar a la basura tanta madera no me parece muy buena idea.

-El rack de impresoras autónomas me convence mucho. Creo que sería muy buena idea instalar un gestor en la nube (véase octoprint, Repetier-Server, o el que sea), y utilizar uno de los dos ordenadores nuevos que tenemos ahora como usuario y el otro como servidor conectado a todas las impresoras. El hecho de poner tarjetas SD o pantallas a las impresoras quedaría en un segundo plano pues la interfaz del servidor haría la misma función, si no me equivoco.

-Resto de puntos a favor, sin niguna aportación adicional.

**Comment by David-Estevez** [comment]
Comentando a tus comentarios:

- La principal razón de tirar el escenario es que no veíamos que hubiese sido útil en los últimos años ni que fuera a serlo en el futuro cercano. Por otro lado, y como dijo también @jorgercobo durante el brainstorming, tirar toda esa madera es un desperdicio, por lo que estaría guay buscarle alguna utilidad a esa madera y reciclarla, ya sea con la idea que propones o con otra.

- Lo de tener el controlador en la nube mola, pero yo pensaría en una primera implementación con pantallas y SDs. Las pantallas y SDs son fáciles de usar y tienen un workflow sencillo. Sin embargo, el instalar un sistema en la nube, además del trabajo de mantenimiento del servidor, implica documentar su uso y que la gente aprenda a manejar este sistema, que me parece bastante complejo . No obstante, yo lo mantendría como un objetivo a largo plazo.

**Comment by Siotma** [comment]
Según he leído, el uso de octoprint se limita a seleccionar la impresora (caso de tener varias) y subirle un g-code, que se puede generar con cualquiera de los programas actualmente conocidos. Me gustaría investigar más esto antes de posicionarme definitivamente, pero obviamente no va a ser trivial hacer la transición a ninguna de las dos alternativas...

**Comment by David-Estevez** [comment]
Creo que @jcarolinares tiene experiencia con octoprint, quizá nos pueda echar una mano para entenderlo mejor.

**Comment by jcarolinares** [comment]
¡Hola!

Os cuento mi experiencia personal desde hace unos 4 meses con Octoprint.

Obviamente lo he usado a nivel personal por lo que desconozco hasta que punto funciona con un rack de impresoras 3D. Siendo Octoprint seguro que bien. La persona que si puede que lo sepa es Jokin Lacalle que si no me equivoco ha aplicado Octoprint a las impresoras 3D de su aula.

En mi caso uso octopi, la versión para raspberry pi del OS. Octoprint tiene opciones interesantes. Permite tal como comenta @Siotma subir gcodes, pero también permite cargar pérfiles de impresora como los de Cura y que se el propio Octoprint el que reciba el stl, lo lamine e imprima.

NO soy nada fan de esa segunda opción ya que se hace, hasta donde yo he probado prácticamente a ciegas lo cual es una chapuza, mejor laminar en el software y subirlo luego a octoprint el .gcode

También se puede observar como va la impresión a través de Webcam e incluso tiene los típicos controles de motores, ventiladores y temperatura en cada eje. Es muy completo y hay plugins que lo pueden mejorar.

Creo que tanto Cura como Slic3r permiten comunicarse a través de la API con Octoprint. En el caso de Cura lo utilizo muy a menudo y francamente es increíblemente cómodo. También recomiendo el plugin de Telegram con Octoprint. Desconozco que tal funcionará con varias personas, pero es una forma de conocer como va una impresión (manda capturas de pantalla de la webcam, se puede imprimir, subir un archivo, parar la impresión, etc) desde fuera de la red a la que esté conectado octroprint y por tanto sin riesgo para abrir puertos.

Respecto a la configuración de Octoprint, está literamente "chupao", yo seguí el vídeo de Thomas Salandeer del que os sobra la mitad, pero muy útil: https://youtu.be/MwsxO3ksxm4

Cosas a tener en cuenta:

* Tenéis que probarlo pero en mi casa a veces el navegador no consigue con la interfaz de Octoprint, por  lo que no lo considero absolutamente estable.

Por lo demás, de verdad, es una auténtica pasada, os recomiendo que hagáis pruebas individuales poco a poco antes de sustituir el sistema, pero es una buena opción.

**Comment by Siotma** [comment]
En la asociación disponemos de Raspis, aunque ninguna está actualmente dedicada a impresoras. Por eso yo había pensado en utilizar una torre de PC para instalar octoprint aunque sea de forma más manual. En la torre de PC de Hija Resurrection que estamos a punto de quitar se podrían hacer algunas pruebas y valorar la idoneidad de estas ideas...

**Comment by jorgercobo** [comment]
Avances en #139

**Comment by JorFru** [comment]
Qué falta por hacer aquí?
Esto se ve bastante bien.

**Comment by David-Estevez** [comment]
Ver si queda alguna cosa de la lista de features por documentar (via nueva issue) y cerrar
