### ISSUE TITLE
Participación de ASROB en la OSHWDem 2017

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#94]
Issue para gestionar nuestra participación en la feria [OSHWDem 2017](https://oshwdem.org).

Datos de interés:
> 11 Noviembre
> Museo Domus
> A Coruña

**Comment by JorFru** [comment]
Para participar se tiene que rellenar el siguiente formulario:
https://oshwdem.org/call4makers/

**Comment by JavierIH** [comment]
Hola, 

¿Quien se apunta a ir? Yo voy a las competiciones y charlas. Puedo aportar unos pocos robots al stand y estar allí  un mínimo del  33% del tiempo.

**Comment by JavierIH** [comment]
Por temas logísticos retiro el ofrecimiento (la organización me ha pedido que esté en otro stand de competiciones/charlas)

**Comment by Morgloz** [comment]
Yo me apunto

**Comment by KFRodicio** [comment]
Yo me apunto tambien

**Comment by JorFru** [comment]
Plazas llenas
Kike y Alejandro serán los representantes de ASROB en la OSHWDem 2017

**Comment by JorFru** [comment]
Oficialmente inscritos
Kike y Álex están dentro

**Comment by Siotma** [comment]
Dicho por @JorFru en https://github.com/asrob-uc3m/actas/issues/99#issuecomment-338072601 : 

> En la OSHWDem pretendemos llevar los Zowis. Son lo más vistoso que tenemos. En cierta manera los Zowis tendrán que "cederse" para la feria, me imagino. 

Desde mi punto de vista, salvo que se malogre el tema de la subvención (que todavía no he visto el dinero), los Zowimanoides son robots de la Asociación, y como tales su uso está contemplado para eventos como este, en el que participa ASROB formalmente. 

Si en algo se puede incidir en un caso como este es que se vele por que los robots vuelvan en un estado igual o mejor al que se fueron. Es decir, los asistentes al evento se responsabilizarán de mantenerlos en funcionamiento, principalmente cambiar servos si se rompen, y trimarlos. También propongo que a la vuelta se redacte un breve resumen de lo ocurrido con ellos (rotura de piezas, reparaciones, cantidad de peleas realizadas, vídeos), ya que esta información será útil a la hora de endurecerlos para que en un evento futuro funcionen aún mejor.

Recordad que actualmente contamos con un teléfono móvil en la caja de Zowimanoides, donado por @David-Estevez . Este teléfono tiene [la aplicación](https://github.com/Siotma/Android-BT-Controller/tree/master/apk) para conectarse por Bluetooth a los Zowis y controlarlos, de manera que podéis prestarlo durante el evento para que la gente maneje los robots.

**Comment by David-Estevez** [comment]
Sí, yo creo que si es un evento al que asiste ASROB entonces no hay cesión, porque como dice @Siotma , los robots son de ASROB (A menos que no le paguen a Manu su pasta, en cuyo caso serán de @Siotma :see_no_evil: ).

**Comment by Siotma** [comment]
He comprobado que ya me han devuelto la gran mayoría del dinero, por lo que los robots ya son oficialmente propiedad de ASROB 🎉

**Comment by jgvictores** [comment]
Un par de anotaciones para el gran día:
- La wiki va a estar caída, server down due to cortes eléctricos a nivel UC3M (probable hasta 16:00), os recomiendo http://asrob-uc3m.github.io/ y todo lo que está en github como portada.
- Faltaban cosas hoy, como el alargador de muchas tomas... Sabemos que es un lío lo del inventario y documentar. Lo que os pediría sería una foto con todo lo que se llevó, para utilizarlo de documentación y que todo venga de regreso sano y salvo. ;-)

**Comment by David-Estevez** [comment]
> Faltaban cosas hoy, como el alargador de muchas tomas... Sabemos que es un lío lo del inventario y documentar. Lo que os pediría sería una foto con todo lo que se llevó, para utilizarlo de documentación y que todo venga de regreso sano y salvo. ;-)

Todo lo que dices es cierto. Salimos con prisa e improvisamos sobre la marcha, y una vez allí no hubo un momento de tranquilidad para hacer la lista de cosas que llevábamos. Además nos llevamos cosas de otros proyectos y deberíamos haber avisado antes (y pedido permiso :sweat_smile: ). Mis disculpas en nombre de todos los que fuimos allí. Para la próxima feria / evento incluiremos una lista de cosas que llevamos en la misma issue de dicha feria.

Por otro lado, me gustaría agradecer a todos los que fuísteis a la feria por aguantar como unos campeones en el stand, pese a la gran cantidad de gente (y niños) que pasó por allí. Yo creo que supimos transmitir a los visitantes y al resto de expositores el buen rollo que hay en ASROB y los proyectos molones que hacemos.

**Comment by David-Estevez** [comment]
PD: Por alguna razón no me deja asignar a @Morgloz a la issue, por lo que me dejo constancia por aquí de que fue uno de los que participamos en la feria.

**Comment by jgvictores** [comment]
> Todo lo que dices es cierto. Salimos con prisa e improvisamos sobre la marcha, y una vez allí no hubo un momento de tranquilidad para hacer la lista de cosas que llevábamos. Además nos llevamos cosas de otros proyectos y deberíamos haber avisado antes (y pedido permiso :sweat_smile: ). Mis disculpas en nombre de todos los que fuimos allí. Para la próxima feria / evento incluiremos una lista de cosas que llevamos en la misma issue de dicha feria.

No problem!

> Por otro lado, me gustaría agradecer a todos los que fuísteis a la feria por aguantar como unos campeones en el stand, pese a la gran cantidad de gente (y niños) que pasó por allí. Yo creo que supimos transmitir a los visitantes y al resto de expositores el buen rollo que hay en ASROB y los proyectos molones que hacemos.

¡Enhorabuena y muchas gracias a los que os habéis currado esto!
