### ISSUE TITLE
Baja como responsable de Robot Devastation

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#95]
Con esta issue presento mi baja como responsable de Robot Devastation. Quedo a disposicion para colaborar en el traspaso de responsabilidad y para resolver todas las dudas que el nuevo responsable tenga.

Pese a no seguir trabajando por el momento en Robot Devastation, seguiremos en contacto, ya que uno de los principales objetivos de RoboFactory es fabricar robots que sean compatibles con Robot Devastation :smile:

**Comment by David-Estevez** [comment]
Han pasado más de 3 semanas desde que se puso el aviso, así que entiendo que todo el mundo está al tanto ya y se puede cerrar la issue.

Por mi parte sólo me queda recordar al nuevo responsable que se debe actualizar la información en la página de responsables en la web de ASROB si no se ha hecho todavía.

**Comment by David-Estevez** [comment]
> Por mi parte sólo me queda recordar al nuevo responsable que se debe actualizar la información en la página de responsables en la web de ASROB si no se ha hecho todavía.

Reitero, esta información debe estar actualizada.

**Comment by jgvictores** [comment]
He actualizado http://asrob.uc3m.es/index.php/Lista_de_socios
De momento no hay responsable en Robot Devastation.
