### ISSUE TITLE
Colocar cartel en [la puerta del despacho oficial] apuntando a asrob.uc3m.es y 1.0.B06

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#97]
Colocar cartel en [la puerta del despacho oficial] apuntando a asrob.uc3m.es y a `1.0.B06`

Esto podría ser:
- `2.3.B08`, porque es nuestro despacho según [fuentes oficiales](https://www.uc3m.es/ss/Satellite/UC3MInstitucional/es/TextoMixta/1371234098964/#leganes).
- `2.3.D02b`, porque ahí hay muchos carteles

**Comment by jgvictores** [comment]
Nota: Según el directorio de [entes](https://aplicaciones.uc3m.es/directorio/ente/list?lang=en) figura otro email que no revisamos, y el despacho 2.1.04 con extensión 5880.

**Comment by Siotma** [comment]
Madre mía, la verdad es que si alguien nos quisiera encontrar a través de los datos de la Universidad lo tendría verdaderamente difícil... Menos mal que nuestra wiki y nuestra web se localizan fácil en Google...

**Comment by jgvictores** [comment]
Lo más reciente de África:
> ASOCIACIONES QUE HACEN MUDANZA "PROVISIONAL" HASTA LA MUDANZA DEFINITIVA EN MARZO-ABRIL
> 1.- ASROB. Van del despacho 2.3.A11 al 2.3. B08 hasta su ubicación definitiva,  prevista para marzo/abril 2018.

**Comment by jgvictores** [comment]
Y esto me gusta:
> ASOCIACIONES QUE REALIZARÁN MUDANZA EN MARZO/ABRIL DESDE SUS DESPACHOS DE ORIGEN AL DESPACHO  1.3.D19:
> 1.- PHOTOFOLKS
> 2.- ASROB 
> 3.- GUL

**Comment by jgvictores** [comment]
#offtopic logística para mudanza: legasun [at] pa [dot] uc3m [dot] es

**Comment by David-Estevez** [comment]
Hombre, reciente, reciente... https://github.com/asrob-uc3m/actas/issues/114#issue-275538068 😅

**Comment by jgvictores** [comment]
:joy:

**Comment by David-Estevez** [comment]
😜

**Comment by madelgj** [comment]
Sí, yo iba a pasarme por la reprografía a imprimir el cartel, pero no he tenido tiempo. Cuando pueda me paso y lo llevo. Necesitaríamos uno o dos?(puerta de la nave y el despacho)

**Comment by jorgercobo** [comment]
Imprimiría cuatro: para el armario, para la puerta de la nave, para el despacho que nos iban a asignar y otro para la puerta del despacho del resto de asociaciones, que sería una buena forma de darnos más visibilidad.
Podríamos aprovechar y retomar #137

**Comment by David-Estevez** [comment]
Contestación rápida (estoy en una charla del IROS currando):
- Armario: ya hay en la nave un cartel con la web, creo que sería redundante
- Puerta de la nave: Si nos dejan, me parece muy buena idea tener un cartel ahí
- Nuevo despacho: es el objetivo de esta issue, y sólo falta imprimir el cartel y pegarlo
- Despacho general: no creo que nos dejen, y tampoco lo veo muy necesario, no creo que nadie nos busque allí si no pone en ningún lado que estamos allí...

**Comment by madelgj** [comment]
Bueno imprimo 4 y si sobran que se guarden, tamaño A4?

**Comment by GioSunrider** [comment]
la web?

**Comment by JorFru** [comment]
El grupo de Telegram? Por poner método de contacto rápido. O podemos poner el correo y nos contacten allí.

**Comment by JorFru** [comment]
@madelgj por mí qu esea en tamaño A3 como poco. Sí, son más caros. Si lo necesitas los pago yo.

**Comment by madelgj** [comment]
No, está bien, es que David me dijo A4 en un principio. Entonces el logo, la web, la dirección de la nave y el correo? Y en vertical u horizontal?

**Comment by GioSunrider** [comment]
Pero en mi opinión, no pondría la antigua web, pondría ya la nueva, que muchos se siguen liando.

**Comment by David-Estevez** [comment]
La web (nueva, antigua y única) es asrob.uc3m.es

**Comment by GioSunrider** [comment]
y esta que es? http://asrob-uc3m.github.io/

**Comment by David-Estevez** [comment]
Nuestra web.

Si te refieres a la url "asrob-uc3m.github.io", entonces es:

1. Bastante fea
2. Dificil de recordar
3. Un producto temporal hasta que se cierre #87

En todo caso, web sólo hay una y debe estar en asrob.uc3m.es, que es a donde hay que apuntar todo.

**Comment by GioSunrider** [comment]
Vale vale, entonces perfecto.

**Comment by jgvictores** [comment]
Bloqueado por #114

**Comment by JorFru** [comment]
@L4g0 hará los carteles
1. Cartel para poner en el Sabatini: logo ASROB mandando a 1.0.B06
2. Cartel para poner en la puerta de la Nave: Logo de ASROB y minimapa para que entren hasta el fondo a la izquierda

**Comment by jgvictores** [comment]
![photo_2019-10-16_15-16-51](https://user-images.githubusercontent.com/4448588/66922763-041edb80-f028-11e9-8a8f-a72901627828.jpg)

:top: visto en `2.3.D02b`. :smile:

**Comment by L4g0** [comment]
Aquí el .svg creado con Inkscape por si alguien quiere mejorarlo
[CartelesASROB.zip](https://github.com/asrob-uc3m/actas/files/3859017/CartelesASROB.zip)

**Comment by JorFru** [comment]
![photo_2019-12-05_17-30-38](https://user-images.githubusercontent.com/11017088/70254209-01697880-1785-11ea-8cb9-8afd0fd23734.jpg)

**Comment by JorFru** [comment]
Falta poner la web en el cartel de la puerta de La Nave

**Comment by JorFru** [comment]
[EntradaNave-conweb.svg.zip](https://github.com/asrob-uc3m/actas/files/3928080/EntradaNave-conweb.svg.zip)

**Comment by jgvictores** [comment]
> * `2.3.B08`, porque es nuestro despacho según [fuentes oficiales](https://www.uc3m.es/ss/Satellite/UC3MInstitucional/es/TextoMixta/1371234098964/#leganes).

Colocado en tablón de `2.3.B08` versión que @L4g0 subió [aquí](https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/31#issuecomment-555036901). Adjunto foto, donde el logo de la puerta y el otro tablón es de `Photofolks` (esto cuadra con lo comentado en "Mudanza a nuevo despacho" https://github.com/asrob-uc3m/actas/issues/114).

Subidos a Google Drive de ASROB:
- `Multimedia/2019/CartelesASROB/Edificio2.pdf`
- `Multimedia/2019/CartelesASROB/editable/Edificio2.svg`

PD: En principio, el cartel mencionado [arriba](https://github.com/asrob-uc3m/actas/issues/97#issuecomment-542695782) permanece.

![photo_2020-01-09_15-33-13](https://user-images.githubusercontent.com/4448588/72076297-9bc55a80-32f5-11ea-8779-e5a9901564a4.jpg)

**Comment by JorFru** [comment]
Hurra! 
Muchas gracias!
